### ISSUE TITLE
Upgrade GPflow to work without a fork of TensorFlow

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#10]
There have been several improvements to TensorFlow which mean that we need fewer UserOps. Where possible we should switch over to using the official versions of Ops.

**Comment by alexggmatthews** [comment]
As far as I am aware:

A) Now in tensorflow main branch:
matrix triangular solve 
digamma
log gamma

B) Not yet in tensorflow main branch
reverse mode cholesky backpropagation (pull request on the way)
np.triu . Does anyone have any ideas how to do this sensibly with existing tensorflow? @jameshensman ?

getting diagonal of a square matrix. Does anyone have any ideas how to do this sensibly with existing tensorflow? @jameshensman ?

C) Not actually used anyway
gamma

**Comment by alexggmatthews** [comment]
Update: getting diagonal of a square matrix is implemented in HEAD as diag_part

**Comment by jameshensman** [comment]
Our use of triu is actually a bit of a hack. We're optimizing a lower
triangular matrix by giving the upper half a gradient of zero.

What we really want is a function that takes a vector and reshapes it into
a triangular matrix. I think there's a BLAS function for that, perhaps
there's an eigen equivalent that we could wrap?

**Comment by alexggmatthews** [comment]
I'm going to punt the triu question for the time being. There's still a few of our custom ops we need anyway.

I'm almost there. I'm working on fork branch tf_0.7.1 and on GPflow branch tf_0.7.1 . I get one new test failure with the new tensorflow diag_part operator which replaces our own user_ops.get_diag .  The message is:

MESSAGE STARTS 

Traceback (most recent call last):
  File "test_variational.py", line 80, in test_prior_KL
    prior_KL_function = model.build_prior_KL()
  File "/homes/mlghomes/am554/cloud_src/external/GPflow/GPflow/svgp.py", line 55, in build_prior_KL
    KL = kullback_leiblers.gauss_kl_diag(self.q_mu, self.q_sqrt, K, self.num_latent)
  File "/homes/mlghomes/am554/cloud_src/external/GPflow/GPflow/kullback_leiblers.py", line 82, in gauss_kl_diag
    KL += num_latent * 0.5*tf.reduce_sum(tf.log(tf.square(tf.diag_part(L) ))) #Prior log determinant term.
  File "/scratch/am554/miniconda/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 294, in diag_part
    return _op_def_lib.apply_op("DiagPart", input=input, name=name)
  File "/scratch/am554/miniconda/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)
  File "/scratch/am554/miniconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2062, in create_op
    set_shapes_for_outputs(ret)
  File "/scratch/am554/miniconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1545, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/scratch/am554/miniconda/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 875, in _DiagPartShape
    " do not match ")
ValueError: Invalid shape, shape[:mid] (?,) and shape[mid:] (?,) do not match 

MESSAGE ENDS

Initially I thought this was a bug in the new diag_part op but I'm now thinking that it comes from the previous line 81 of [this file](https://github.com/GPflow/GPflow/blob/master/GPflow/kullback_leiblers.py) . @jameshensman Is it possible that this line won't work correctly in the multifunction case and that TensorFlow is correctly warning us?

**Comment by jameshensman** [comment]
Hmm, I don't think so. Line 81 is

`KL = 0.5*tf.reduce_sum(tf.square(alpha)) #Mahalanobis term.`

reduce_sum (without any axis specified) should return a scalar (i.e. summed
over the latent dimensions), and the next line is also a reduce_sum, so
should also be a scalar!

`KL += num_latent * 0.5*tf.reduce_sum(tf.log(tf.square(tf.diag_part(L) )))`

I don't understand why it shouldn't work, sorry.

**Comment by alexggmatthews** [comment]
OK. Not sure the juice is worth the squeeze on that one. It is supposed to be a very simple op. I'm going back to our version of the op  for the time being and expect it will come out in the wash with our next merge of the TensorFlow main branch.

**Comment by jameshensman** [comment]
Looks like we're up to date on this one. PErhaps we can reopen when the cholesky-grad code is accepted into tensorflow

**Comment by alexggmatthews** [comment]
I've reopened an old issue and renamed it. We are pretty close to getting to the point where we don't need a fork of TensorFlow. 

Outstanding issues that I am aware of:

1) The lack of various triangular matrix operations in TensorFlow: see this feature request https://github.com/tensorflow/tensorflow/issues/1825

2) The lack of a gradient for matrix_triangular_solve . I am working on a PR for this with @jameshensman here: https://github.com/alexggmatthews/tensorflow/tree/matrix_triangular_solve_grad

3) A difficult with shape inference for the new diag_part op in TensorFlow which I have asked about here as I'm not sure the behavious is deliberate or not yet: 

https://groups.google.com/a/tensorflow.org/forum/#!topic/discuss/qQKrS10Aops

**Comment by alexggmatthews** [comment]
Update: Google are implementing triangular parts of matrices which is sufficient (but not perfect ) for 1

**Comment by alexggmatthews** [comment]
Update: Gradient for matrix_triangular_solve now at pull request stage:

https://github.com/tensorflow/tensorflow/pull/1891

**Comment by alexggmatthews** [comment]
Update: Matrix_triangular solve is now in, though in the end the tf team did their own version. 

We only have one issue left namely this one:

https://github.com/tensorflow/tensorflow/issues/1893
