### ISSUE TITLE
Prediction is slower than I would expect

### ISSUE THREAD

**Issue by PeterMitrano** [GPflow/GPflow#1003]
System information:

* Python version: 3.7.3
* TensorFlow installed from (source or binary): binary
* TensorFlow version (use command below): 1.13.1
* GPflow installed from (source or binary): binary
* GPflow version: 1.3.0

It takes 10ms to call `predict_y` on my SGPR model. There are 30 inducing points, the input dimensionality is 8, and the output dimensionality is 6. 

Given the simplicity of the operation (basically just a cholesky decomposition and some algebra) I would expect this to be an order of magnitude faster, <=1ms. Is that expectation unreasonable? Is there any way to speed up this model? I cannot batch inputs unfortunately. Sorry for not having a very actionable issue, I'm just looking for some information on performance and what I can expect and how I can improve things.

**Comment by st--** [comment]
Hi @PeterMitrano, does your timing include the tensorflow set-up overhead (i.e., is it 10ms in every call)?
When I run the following example in ipython, each call to `predict_y` takes about 1.5ms:
```python
import gpflow
m = gpflow.models.SGPR(X=randn(100,8), Y=randn(100,6), kern=gpflow.kernels.SquaredExponential(8), Z=randn(30,8))
m.predict_y(randn(1,8))  # constructs tensorflow graph on the first call; run once so timing won't be affected
%timeit m.predict_y(randn(1,8))
>>> 1.48 ms ± 20.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

**Comment by PeterMitrano** [comment]
Ah, my mistake I'm actually using an SVGP. Here's a rough paste of my model. But yes, I am measuring only the time it takes to call `predict_y`.

https://pastebin.com/5K70dMLE

**Comment by st--** [comment]
As you use separate not shared kernel/features, Cholesky decomposition & everything needs to be done independently for each output, so your performance of 10ms is comparable to 6 * 1.5ms from my simple example. One thing to note is that tensorflow doesn't make it easy to cache things like the Cholesky of Kuu, which remains the same for independent calls to `predict_y`, yet is recomputed each time. Fixing this should give a significant performance improvement, but is unlikely to happen in gpflow-1.

**Comment by PeterMitrano** [comment]
Thanks for the explanation, maybe I'll try to implement that. What would you think of this:
 - add a method to the model that computes the Cholesky of Kuu and any other values we can cache and store them as numpy arrays in the class
 - on future calls to predict, if nothing has changed that would invalidate the cache (not sure exactly what that would be) it feeds that as a an additional placeholder?

**Comment by tadejkrivec** [comment]
I have a similar example where I gave to call predict sequentially @st--. Why would SVGP predictions be faster then SGPR in that case? Isn't the time complexity with prediction the same for all sparse models? This is the code I ran for testing it:
```python 
from numpy.random import randn
import gpflow

sgpr = gpflow.models.SGPR(X=randn(70000,8), Y=randn(70000,1), kern=gpflow.kernels.SquaredExponential(8), Z=randn(200,8))
sgpr.predict_y(randn(1,8))
%timeit -n 100 -r 7 sgpr.predict_y(randn(1,8))
>>> 128 ms ± 696 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

svgp = gpflow.models.SVGP(X=randn(70000,8), Y=randn(70000,1), kern=gpflow.kernels.SquaredExponential(8), likelihood=gpflow.likelihoods.Gaussian(), Z=randn(200,8))
svgp.predict_y(randn(1,8))
%timeit -n 100 -r 7 svgp.predict_y(randn(1,8))
>>> 6.61 ms ± 913 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

**Comment by st--** [comment]
@tadejkrivec answered in #1030.
@PeterMitrano we've also been thinking about separating out the posterior as an object that stores all precomputable quantities to make prediction as fast as possible. Would be great to get it into gpflow-2!
