### ISSUE TITLE
v1.4.1 does not work with TF2

### ISSUE THREAD

**Issue by fonnesbeck** [GPflow/GPflow#1007]
I've installed the latest release (1.4.1) on Linux against TensorFlow 2 ('2.0.0-beta1'). However, importing GPFlow generates an error that appears to be an incompatibility issue with TF2. The release notes seem to indicate that it should be compatible. 

```python
AttributeError                            Traceback (most recent call last)
<ipython-input-1-f6755039abc9> in <module>
     19 tfd = tfp.distributions
     20 psd_kernels = tfp.positive_semidefinite_kernels
---> 21 import gpflow as gf
     22 
     23 sns.set(style="whitegrid")

~/.local/lib/python3.5/site-packages/gpflow/__init__.py in <module>
     19 from ._settings import SETTINGS as settings
     20 
---> 21 from .session_manager import get_session
     22 from .session_manager import get_default_session
     23 from .session_manager import reset_default_session

~/.local/lib/python3.5/site-packages/gpflow/session_manager.py in <module>
     29 
     30 
---> 31 class TracerSession(tf.Session):
     32     def __init__(self, output_file_name=None, output_directory=None,
     33                  each_time=None, **kwargs):

AttributeError: module 'tensorflow' has no attribute 'Session'
```

**Comment by vdutor** [comment]
Hi, @fonnesbeck 

You're right - the latest release of GPflow on PyPI does not support `TensorFlow>=2.0`.

If you need GPflow to work with TF2, have a look here: https://github.com/GPflow/GPflow/tree/awav/gpflow-2.0.
This branch is currently in alpha, but should be ready for prototyping.
Installing it can be done 
```
git clone --single-branch --branch awav/gpflow-2.0 https://github.com/GPflow/GPflow.git && cd GPflow
```

The current GPflow `develop` is compatible with the latest TensorFlow version below 2.0 (i.e. TF1.14).
My preferred way of installing this version is by manually cloning and installing it.
```
git clone git@github.com:GPflow/GPflow.git
cd GPflow
python setup.py develop
```

**Comment by vdutor** [comment]
Hi, @fonnesbeck

You're right - the latest release of GPflow on PyPI does not support TensorFlow>=2.0.

If you need GPflow to work with TF2, have a look here: https://github.com/GPflow/GPflow/tree/awav/gpflow-2.0. This branch is currently in alpha, but should be ready for prototyping.
To install this branch:
```
git clone --single-branch --branch awav/gpflow-2.0 https://github.com/GPflow/GPflow.git && cd GPflow
python setup.py develop
```

You can also use GPflow's `develop` branch, which is compatible with the latest TensorFlow version below 2.0 (i.e. `tensorflow==1.14`).
```
git clone https://github.com/GPflow/GPflow.git && cd GPflow
python setup.py develop
```

**Comment by fonnesbeck** [comment]
Thanks. Are there updated API docs or examples anywhere? The API for fitting models seems to have changed a fair bit.

**Comment by st--** [comment]
We've started updating the notebooks ! Have a look at the recently created PRs (e.g. #1048 for minibatch optimisation with Adam, or #1044 for examples using scipy optimizer)
