### ISSUE TITLE
Installation from source fails

### ISSUE THREAD

**Issue by fonnesbeck** [GPflow/GPflow#1008]
I'm trying to install from master, but this fails either via pip or using the setup script locally. See the error message below.
___

System information:

* Python version: 3.5.3
* TensorFlow installed from (source or binary): source
* TensorFlow version (use command below): 2.0.0-beta
* GPflow installed from (source or binary): source
* GPflow version: current master

![image](https://user-images.githubusercontent.com/81476/61644081-a9b0f180-ac69-11e9-8c86-0959e1ded1d6.png)

**Comment by fonnesbeck** [comment]
I guess this is related to #1007 which is an incompatibility with TF2.

**Comment by vdutor** [comment]
At the moment of writing GPflow develop is not compatible with TF>=2.0. See answer #1007 .
