### ISSUE TITLE
Some wrong behaviours with code coverage and integration with GitHub

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#101]
A couple of incorrect behaviours of code coverage that I have observed:

1) The code coverage shown on the front page of the repo is currently dispayed as the coverage of the last build even if that build is not master. So for example the coverage on the front page reads 95% when in fact master has 98% coverage because the last build was on the GPLVM pull request. In this case the code coverage is misleadingly low for new visitors to our front page. 

2) A similar problem. The merge criterion that the coverage on a branch should not be less than master is currently that the coverage should not be less than the last autobuild. Thus if you build a branch with 50% test coverage and the next build has coverage of 75% then it will pass even if master has coverage of 98% which is very wrong behaviour that could damage the coverage we have worked so hard to obtain over time.

**Comment by alexggmatthews** [comment]
I also mention 1) in #98

**Comment by jameshensman** [comment]
calling @coveralls, could you guys give us any input on why this might be happening?

**Comment by alexggmatthews** [comment]
@jameshensman I think I can close this one, no?

**Comment by jameshensman** [comment]
yeah, I think codecov/codeship meet 99% of our needs for the moment, and have pretty good service, apart from the occasional hang.
