### ISSUE TITLE
"How to contribute" page

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#102]
As per suggestion of @jameshensman it might be a good idea to start a page explaining how to contribute to GPflow .

**Comment by alexggmatthews** [comment]
Maybe we should both read the Google style guide.

https://google.github.io/styleguide/pyguide.html

**Comment by alexggmatthews** [comment]
OK so the Google style guide seems to partly contradict pep8 which is used in TensorFlow. pep8 seems to be mostly text style (apart from a few programming recommendations see below) whereas the Google style guide has rather a lot of recommendation. At the moment we're not doing a lot of the stuff in the Google style guide e.g we have relative imports and we aren't using pylint. I don't really agree with the Google style guide suggestion to use implicit false under "True/False evaluations" as I think this is confusing.

https://www.python.org/dev/peps/pep-0008/#programming-recommendations

**Comment by markvdw** [comment]
I usually find PEP8 to be fine. And even then, things like variable name casing conventions don't really fit that well with GPflow, I find. For example, pep8 doesn't allow uppercase variable names. We like using uppercase variables for matrices, as this fits with our maths notes.

**Comment by st--** [comment]
There is https://github.com/GPflow/GPflow/blob/develop/contributing.md now; if that's not sufficient please re-open...
