### ISSUE TITLE
Minor documentation issue: unclear docstring in Scipy's minimize

### ISSUE THREAD

**Issue by vdutor** [GPflow/GPflow#1036]
Docstring of scipy_optimizer's `minimize` method is unclear: parameters `initialize` and `initialize_optimizer` have identical explanations.
See: https://github.com/GPflow/GPflow/blob/develop/gpflow/training/scipy_optimizer.py#L75
```
        :param initialize: If `True` model parameters will be re-initialized even if they were
            initialized before for gotten session.
        :param initialize_optimizer: If `True` model parameters will be re-initialized even if they were
            initialized before for gotten session.
```

Happy to fix it, once I understand their correct usage.

**Comment by st--** [comment]
I propose we close this issue as in gpflow2/tf2 the whole thing is a lot easier... objections?
