### ISSUE TITLE
Sphinx documentation does not include `__init__` docstring

### ISSUE THREAD

**Issue by st--** [GPflow/GPflow#1039]
Particularly evident for the Coregion kernel: https://gpflow.readthedocs.io/en/develop/gpflow/kernels/index.html#gpflow-kernels-coregion does not contain anything, even though the code is well-documented.

**Comment by joelberkeley-pio** [comment]
worth mentioning here that most of the `Coregion.__init__` docstring looks like it should be in the class docstring not the `__init__` docstring
