### ISSUE TITLE
GPy and GPflow 2.0 prediction mismatch

### ISSUE THREAD

**Issue by a-z-e-r-i-l-a** [GPflow/GPflow#1053]
System information:

* Python version: 3.6
* TensorFlow installed from (source or binary): source
* TensorFlow version (use command below): 2.0.0b1
* GPflow installed from (source or binary): source
* GPflow version: 1.9.999

There is a difference between the variance calculated by GPy and GPflow 2.0 by an order of magnitude. 
```

kernel                        = gpflow.kernels.RBF(lengthscale=10.1)
kernel.variance               = tf.Variable([1], name='signal_variance', dtype=tf.float32)
m                      = gpflow.models.GPR(X, y, kernel=kernel)
m.likelihood.variance  = tf.Variable([1e-9], name='noise_variance', dtype=tf.float32) 

m.predict_y(x)
(<tf.Tensor: id=15215, shape=(1, 1), dtype=float32, numpy=array([[-4.99999998]])>,
 <tf.Tensor: id=15217, shape=(1, 1), dtype=float32,  numpy=array([[1.00000008e-09]])>)
```
Gpy's prediction:
```
(array([[-4.99999982]]), array([[1.19999996e-08]]))
```

Finally, I wanted to also ask about the difference between predict_f and predict_y in gpflow.

**Comment by awav** [comment]
Hello @a-z-e-r-i-l-a ,

The GPy uses fp64 by default, in your example you work with fp32. You opened another issue regarding fp64, check the answer there https://github.com/GPflow/GPflow/issues/1051.
