### ISSUE TITLE
SyntaxError when importing GPflow

### ISSUE THREAD

**Issue by miquelmassot** [GPflow/GPflow#1056]
### Please fill out the template below.
___

System information:

* Python version:  3.5
* TensorFlow installed from (source or binary):  binary (pip3)
* TensorFlow version (use command below):  1.14
* GPflow installed from (source or binary):  source
* GPflow version:  1.15

> You can collect some of this information using our environment capture script You can also obtain the TensorFlow version with python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

... _Describe the current behavior_
Import gpflow gives an error and exits the program.

... _Describe the expected behavior_
No error expected.

... _Code to reproduce the issue Provide a reproducible test case that is the bare minimum necessary to generate the problem._
    import gpflow

.. _Other info / logs, include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached._

    File "/home/miquel/git/pybpslam/gaussian_process.py", line 1, in <module>
        import gpflow
    File "/usr/local/lib/python3.5/dist-packages/gpflow-1.5.0-py3.5.egg/gpflow/__init__.py", line 36, in <module>
        from . import training as train
    File "/usr/local/lib/python3.5/dist-packages/gpflow-1.5.0-py3.5.egg/gpflow/training/__init__.py", line 3, in <module>
        from .scipy_optimizer import ScipyOptimizer
    File "/usr/local/lib/python3.5/dist-packages/gpflow-1.5.0-py3.5.egg/gpflow/training/scipy_optimizer.py", line 117
        msg = f"Original error message: \n\t{error}\nOptimiser message: {msg}."
                                                                              ^
    SyntaxError: invalid syntax

**Comment by st--** [comment]
Hi @miquelmassot, thanks for bringing this to our attention. This is due to the f"" string introduced in #1011, which is a syntax feature introduced in python 3.6 (and hence backwards-incompatible with python 3.5). I've fixed this on the st/fix_python35 branch (PR #1057).
