### ISSUE TITLE
Optional Verbose Compilation

### ISSUE THREAD

**Issue by PabloLeon** [GPflow/GPflow#106]
I am creating lots of Models in a loop and would like to suppress the "compiling tensorflow function..." output it generates. I've modified _compile in model.py to contain a verbosity parameter that defaults to false, however in most instances the output is quite useful and I would like to have both options.

I am a bit lost in the autoflow decorator/param specifications...Where exactly is _compile called so that I can add an optional verbosity parameter?

**Comment by jameshensman** [comment]
I don't think AutoFlow uses _compile, at least not in its current incarnation. I don't think it outputs anything either?

I just invited you to be a 'contributor' (sorry, should have done this ages ago when you were working on mean functions). You should be able to push your changes to a GPflow branch, where it will get automatically tested and coveraged. From there you can create a PR and we can look at this together -- I'd also like to suppress that message!

**Comment by jameshensman** [comment]
Did you get anywhere with this, @PabloLeon ?

I'd like to be able to suppress GPflow's messages, or better, have them sent to a logging module in some way. It's annoying to see constant 'compiling tensorflow function' messages: that was useful when the project was very young, but now I feel like that part is pretty stable, so the messages less useful.

**Comment by PabloLeon** [comment]
I haven't had a chance to look at this - I think a logging module would be very nice in general. I've used https://docs.python.org/2/library/logging.html in the past and found it very flexible and easy to use, maybe we could integrate a logger and allow the user to set different levels of logs (debug/verbose/silent) and allow to store these logs locally. 
I will probably not be able to look at this until the end of the month though (have a few deadlines coming)...

**Comment by markvdw** [comment]
Currently it's only `_compile()` that sends messages. As a quick fix, could we add a module-level `verbosity` variable in `GPflow.model` to control the compilation verbosity? Would be super easy to do, and it would make my notebooks a lot cleaner :)

**Comment by jameshensman** [comment]
This is fixed: models now only print stuff if the verbose flag is set in gpflowrc
