### ISSUE TITLE
print summary fails for sum kernel

### ISSUE THREAD

**Issue by jameshensman** [GPflow/GPflow#1066]
System information:

* Python version: 3.7
* TensorFlow installed from pip tf2 nightly
* TensorFlow version (use command below):'2.0.0-dev20190930'
* GPflow installed from (source or binary): python setup.py develop
* GPflow version: awav/gpflow-2.0

... _Describe the current behavior_
MWE:
```
k = gpflow.kernels.SquaredExponential() + gpflow.kernels.SquaredExponential()
print_summary(k)

Output:
name    class    transform    trainable    shape    dtype    value
------  -------  -----------  -----------  -------  -------  -------
```
... _Describe the expected behavior_
should print the values of the summed kernel's parameters.

**Comment by st--** [comment]
Closed by #1071
