### ISSUE TITLE
GPflow2: stationary kernels have `ard` flag but does not work

### ISSUE THREAD

**Issue by st--** [GPflow/GPflow#1077]
This flag should be removed as it is misleading, and without `input_dim` I don't see how it is possible to initialize the lengthscale correctly.
Moreover, there should be a check that if the lengthscale is NOT a scalar, that it matches up with the effective input dimensions.
Also, the K_r / K_r2 framework that is useful e.g. for the generalised Periodic kernel (#1052) seems to only be partially supported (e.g. SquaredExponential falls out of it), this needs fixing to be able to port #1052 to develop-2.0

**Comment by st--** [comment]
@jahall do you reckon this issue is now solved and can be closed?

**Comment by jahall** [comment]
> @jahall do you reckon this issue is now solved and can be closed?

Yes - all resolved

**Comment by st--** [comment]
Thanks!
