### ISSUE TITLE
Bayesian GPLVM runs out of memory when using quadrature_expectation.

### ISSUE THREAD

**Issue by raven38** [GPflow/GPflow#1084]
I tried to run Bayesian GPLVM. In a series of my experiments, I notice that I can't use some kernels. I can use RBF kernel. But I can't use White and Convolutional kernels. 
We can calculate analytic expectations of RBF kernel.
But we can only calculate quadrature expectations of  White and Convolutional kernels.

Can I use these kernels with Bayesian GPLVM?
___

System information:

* Python version: 3.7.4
* TensorFlow installed from (source or binary): pip install tensorflow<2
* TensorFlow version (use command below):  1.14.0
* GPflow installed from (source or binary):pip install gpflow
* GPflow version: 1.5.0     

> You can collect some of this information using our environment capture script You can also obtain the TensorFlow version with python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
v1.14.0-rc1-22-gaf24dc91b5 1.14.0

I put my code.

```python
import tensorflow as tf
import numpy as np

import gpflow
from gpflow  import kernels

import pods

data = pods.datasets.oil_100()
Y = data['X']
labels = data['Y'].argmax(axis=1)

latent_dim = 4  # number of latent dimensions
num_inducing = 40  # number of inducing pts
num_data = Y.shape[0]  # number of data points
X_mean_init = gpflow.models.PCA_reduce(Y, latent_dim)  # Initialise via PCA
X_var_init = np.ones((num_data, latent_dim))
Z_inducing_inputs_init = np.random.permutation(X_mean_init.copy())[:num_inducing]  # Pick inducing inputs randomly from dataset initialisation

kernel = kernels.White(latent_dim)

m = gpflow.models.BayesianGPLVM(
    X_mean=X_mean_init,
    X_var=X_var_init,
    Y=Y,
    kern=kernel,
    M=num_inducing,
    Z=Z_inducing_inputs_init
)
```

In `m = gpflow.models.BayesianGPLVM(X_mean=X_mean_init, X_var=X_var_init,  Y=Y, kern=kernel,  M=num_inducing,Z=Z_inducing_inputs_init)`, The code spent long time and raise error `ValueError: Tried to convert 'input' to a tensor and failed. Error: Cannot create a tensor proto whose content is larger than 2GB.`

Please give me your support.

**Comment by st--** [comment]
Hi @raven38 , I've now looked into this - it's not a bug in GPflow, it's just how you use it. The default number of points to use for the Gauss-Hermite numerical quadrature (when analytic kernel expectations haven't been defined) is H=100, which works fine for D=2, but produces too many points in the D=4 that you chose (`latent_dim`), as the overall number of support points that need to be generated is O(H^D)! You can make it work in D=4 by reducing the number of points, e.g. to 30. You can achieve this by adding the keyword argument `num_gauss_hermite_points=30` to the calls of `expectation(pX, ...)` in the gplvm.py code. (Ideally, this would be more easily configurable - please do help out and make a pull request to GPflow if you can think of how to make this happen!)

It would be great if you could re-state your question on stackoverflow.com on the gpflow tag: https://stackoverflow.com/questions/tagged/gpflow - I would then post my answer over there again, which will be much more helpful to other users in the future than a closed issue!

**Comment by st--** [comment]
(You might want to reduce the number of latent dimensions, 4 is probably too large - definitely for this dataset - and I don't see how a White kernel would let you learn anything useful here! though obviously the same is true for any other kernel for which analytic expectations haven't been added, such as Matern32)
