### ISSUE TITLE
Continuous integration for GPflow 

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#11]
It would be good to have continuous integration rather than checking the tests manually. It would also be good to run coverage at the same time. Actually at the time of writing the code coverage of the unit tests is very high.

**Comment by jameshensman** [comment]
This is ready to go in this PR: https://github.com/GPflow/GPflow/pull/18

**Comment by jameshensman** [comment]
Is there any other CI required @alexggmatthews , or do we have sufficient to s=close this for the moment?

**Comment by alexggmatthews** [comment]
I think it is already very good. Do you know if travis do mac as well as linux? That would be very useful.

**Comment by jameshensman** [comment]
It does do osx too, yes. But I'm having some difficulty getting it working.
See the travis_osx branch.

**Comment by jameshensman** [comment]
So I gave codeship a try, and they don't have the same time-out problem as travis. The build completed in just under an hour (free version). 

I'll try to link codeship with the coverage and we could consider abandoning travis.

**Comment by alexggmatthews** [comment]
@jameshensman can I close this for now?

**Comment by alexggmatthews** [comment]
Before doing so we should consider #101 and #103

**Comment by jameshensman** [comment]
I'm not very happy with coveralls. I think the service provided by codecov.io is better. Have been meaning to switch back, but didn't want to bring the repo down for everyone.

**Comment by alexggmatthews** [comment]
We have switched back to codecov now so I'm closing.
