### ISSUE TITLE
How to copy sets of parameter values across models

### ISSUE THREAD

**Issue by st--** [GPflow/GPflow#1119]
I would like to be able to copy values of hyperparameters between models, e.g. get a list "all parameters contained within model `m1`", be able to remove some of these (e.g. filter out inducing point locations), then collectively set the corresponding parameters in a different model `m2` to the values gathered from `m1`. There is no such feature at the moment, and e.g. the `understanding/upper_bound.ipynb` notebook contains a rather hacky workaround to achieve this behaviour. It would be neat to have a generally usable utility function for this. This may involve actually naming and name-scoping all our parameters...

**Comment by condnsdmatters** [comment]
Worth checking out:

`gpflow.utilities.multiple_assign(input: tf.Module, vars_dict: Dict[str, tf.Tensor])`

Usage:
```
# model_1 copied to model_2

param_dict = gpflow.utilities.leaf_components(model_1)
gpflow.utilities.multiple_assign(model_2, param_dict)
```

I think the misleading thing is the function name `leaf_components`, which should be called something like: `get_params_dict` or smth.

**Comment by awav** [comment]
It can be done with,

```python
params = gpflow.utilities.parameter_dict(m1)
gpflow.utilities.multiple_assign(m2, params)
```

**Comment by st--** [comment]
Is this in the documentation? Would be need to have this in one of the notebooks!

**Comment by awav** [comment]
This https://github.com/GPflow/GPflow/issues/1113 and https://github.com/GPflow/GPflow/issues/1217 will cover this. So, I think we can close it, as it duplicates the request.
