### ISSUE TITLE
[Discussion] Contributing

### ISSUE THREAD

**Issue by jahall** [GPflow/GPflow#1144]
# Contributing
I would be keen to contribute more regularly to this project as I think it is awesome. Just wondering what the most useful way to go about this would be? Do you have a backlog of bugs/enhancements/documentation for which you would welcome additional help? Or maybe you have sufficient support, which is also fine...

**Comment by awav** [comment]
Hello @jahall.

Thanks for your interest in the GPflow! We don't have a board where share our plans or intentions (yet). Github projects is a good place for planning and organizing work in the future. As for now, we have a couple of things in the todo list: 1. gpflow 1.0 positive transform had shift term equal 1e-6, this https://github.com/GPflow/GPflow/pull/1110 is returning it back, but some tests are failing and we need to figure out what's wrong with it. 2. Current positive transform uses softplus, but in some cases it is "preferable" to use exp instead; it would be nice to have an option in the gpflow.config, such that the user could choose global positive transformation.

**Comment by jahall** [comment]
Great stuff. Thanks for this! Feel free to close the "issue". Wasn't sure the best way to reach out :)

**Comment by jahall** [comment]
Both points should now be addressed in #1148
