### ISSUE TITLE
Parameter logging during optimisation / sampling

### ISSUE THREAD

**Issue by markvdw** [GPflow/GPflow#115]
@jameshensman mentioned that logging parameters during sampling/optimisation could be a useful feature to have. One suggestion was for the code to keep track of a list of dicts and return it after sampling.

What I've been using in my own code is an external logging class with a callback that is to be called by the optimiser. One class does more than just logging. I meant it to be a class that helps logging, storing and quitting long parallel optimisation runs, that are necessary for running lots of experiments for papers. I think it's nice, since it handles:
- Printing progress at intervals that can be adjusted by the user
- Logging parameters at intervals that can be adjusted by the user
- Storing the logged parameters to disk at intervals that can be adjusted by the user
- A timeout that kills optimisation if it takes too long

You can take a look at the current code here: https://gist.github.com/markvdw/216f6d4cfd040251e3b7e8c7551f559c. I'm happy to adapt it to fit into GPflow, if there's interest in more control over optimisation. It shouldn't be hard to get this to work with logging sampling as well.

**Comment by alexggmatthews** [comment]
Hi @jameshensman @markvdw we should be aware of what TensorFlow already has built in for this area as it may well be faster.

https://www.tensorflow.org/versions/r0.9/how_tos/summaries_and_tensorboard/index.html#serializing-the-data

**Comment by alexisboukouvalas** [comment]
Great point @alexggmatthews 
Maybe it is worth considering more extensive support for tensorboard in GPflow in general. I have opened issue #116 to foster discussion.

**Comment by st--** [comment]
Superseded by gpflow-monitor (to be merged by #705)
