### ISSUE TITLE
Incorrect GPFlow version listed by pip for develop branch

### ISSUE THREAD

**Issue by malharjajoo** [GPflow/GPflow#1154]
I am currently trying to use GPFlow 2.0 but have a query:

On checking out the **develop** branch from the github repo and running 
`pip install -e .` (as per the README.md), after the installation is complete, 
the version (listed by pip) for GPFlow is "1.9.999" and not "2.0".

In this case, are both versions the same or am I missing something?

**Comment by awav** [comment]
Everything is correct. 1.9.999 is pre-release status. I'll make a release candidate soon.
