### ISSUE TITLE
Tensorboard support

### ISSUE THREAD

**Issue by alexisboukouvalas** [GPflow/GPflow#116]
1. Implement extensive scoping in the code. This will make the job of looking at the computational graph in tensorboard much easier. For example each kernel could define its own scope. We would need to agree on a systematic way of how to add scoping to the code. 

2. Logging statements. To debug issues I have extensively been using the print commmand, for example to print the first 10 entries of a  tensor and its shape:
```lik = tf.Print(lik,[pointToUpdate, tf.shape(lik), lik],message='point - lik=',name='likeddebug',summarize=10) ``` In my code, I add Print nodes under a debug flag. Perhaps something similar would be useful for GPflow.

3. Use the summary statistics to log information. I have been playing with histogram_summary but tensorflow offers storing scalars and images as well. To keep a log of the value of a tensor simply do:
```tf.histogram_summary('probvector', tf.squeeze(probVector))```
Then collect all the summaries and write to file
```
tf.merge_all_summaries()
tf.train.SummaryWriter("logs",  self._session.graph)
```

**Comment by alexggmatthews** [comment]
@alexisboukouvalas just had another look at this one. We now have #183 merged which deals with 1). Do you think we want 2) and 3) to be in the code all the time?

**Comment by alexisboukouvalas** [comment]
Thanks @alexggmatthews , I  like the new scoping support.
It is worth thinking about more support for debugging including the work you've done on identifying performance problems. 
However the most important change was to include scoping to make the tensorboard graphs readable.
So I am happy to close this.

**Comment by alexggmatthews** [comment]
Ok thanks @alexisboukouvalas , closing now.

**Comment by icouckuy** [comment]
> However I did not get anything particularly nice and useful out of this and would welcome ideas for better support.
At least tracking the optimization progress seems useful to me (likelihood and hyperparameters). I was also thinking about keeping the distributions and histograms for the MCMC methods (like Model.sample()).

Of course adding compute speed and memory metadata is very useful for debugging and profiling (slows the code down a lot), though generating chrome trace files might be better for that.

I'll add a pull request for my branch.
