### ISSUE TITLE
"Independent" coregionalization model?

### ISSUE THREAD

**Issue by fonnesbeck** [GPflow/GPflow#1160]
I'm looking to implement what appears to be a sort of special case of the coregionalization model, whereby the inputs are not at the same points across outputs, but there isnt necessarily a high degree of correlation between them. However, I would like to have them share hyperparameters. Is there a straighforward way of doing this? Heavily constraining W with strong priors, perhaps? I was hoping I could use something like the `SeparateIndependent` kernel with `SwitchedLikelihood`, and then setting the lengthscales to be the same across kernels.

Is anything like this possible? I don't see an example that does something like this.

**Comment by st--** [comment]
@fonnesbeck this is a question much more suitable for discussion on stackoverflow.com, as it's not about any specific bugs or feature requests to gpflow core, and questions/answers posted there will have higher visibility and will be more useful to future users. Please tag it `gpflow`: https://stackoverflow.com/questions/tagged/gpflow - thank you!

**Comment by st--** [comment]
(We'd also appreciate pull requests that improve the documentation, add further example notebooks, etc.!)
