### ISSUE TITLE
static shapes vs dynamic shapes

### ISSUE THREAD

**Issue by marcoadurno** [GPflow/GPflow#1179]
Hi,

The codebase heavily relieson static shapes (eg t.shape) as opposed to dynamic shapes (eg tf.shape(t)). 

## Bug case:
Using static shapes makes it impossible to use unknown batch size:
```
import tensorflow as tf
import gpflow

@tf.function
def K_diag_dynamic(X):
    variance = 1.0
    return tf.fill(tf.shape(X)[:-1],tf.squeeze(variance))

@tf.function
def K_diag_static(X):
    variance = 1.0
    return tf.fill(X.shape[:-1],tf.squeeze(variance))

if __name__=='__main__':
    K_diag_dynamic.get_concrete_function(X=tf.TensorSpec([None,2], tf.float64))
    K_diag_static.get_concrete_function(X=tf.TensorSpec([None,2], tf.float64))
```
Getting the concrete function for ```K_diag``` succeeds when using dynamic shapes and throws when using static shapes. At the moment we often rely on static shapes, like [here](https://github.com/GPflow/GPflow/blob/develop/gpflow/kernels/stationaries.py#L61). Wouldn't be better to use dynamic shapes?

## System information:

Python version: 3.7
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): 'v2.0.0-rc2-26-g64c3d382ca', '2.0.0'
GPflow installed from (source or binary): source
GPflow version: develop, 24b5733

Best Regards,

Marco

**Comment by st--** [comment]
I completely agree, and I had even changed some of them already because I needed it to get something else to work... let me dig up where that was and start a PR -- would be great if you wanted to help out with that!

**Comment by awav** [comment]
@marcoadurno, I do agree about dynamic shapes. But, it is not obvious for me what is the relation between the dynamic shape and a saver here. Could you remove mentioning about saver? It echoes the #1127 issue.

**Comment by marcoadurno** [comment]
@awav: done. I only really use dynamic shapes when saving models but I do agree that there might be other scenarios.

**Comment by marcoadurno** [comment]
@st-- Happy to help but I'm traveling to neurips tomorrow, I'll try and do what I can.

Thanks,

Marco

**Comment by marcoadurno** [comment]
@st-- I might have something to share. Ho do you want me to proceed?

**Comment by st--** [comment]
@marcoadurno could you make a new pull request into the `st/dynamic_shapes` branch (see #1181), i.e. after clicking "New pull request", set "base:" to `st/dynamic_shapes` ("compare:" should be the branch you've worked on in your fork)?

**Comment by marcoadurno** [comment]
@st-- yes, I worked on st/dynamic_shapes and I have the changes into a fork. Overall it's quite a lot of changes (always moving from static to dynamic shapes). Tests still run, are we happy to start like that? If so I can open PR.

**Comment by st--** [comment]
Yes, please do open a PR! One thing that I think would be good to add before merging into gpflow-develop would be some test making use of tf.function that demonstrates why we need this PR (i.e., test fails without proposed changes, test passes with proposed changes).

**Comment by st--** [comment]
@marcoadurno thanks for your help! we would appreciate any further improvements you would like to contribute to GPflow. :)

**Comment by st--** [comment]
@marcoadurno I hope this solves all your issues! please re-open (or make a PR...) if you encounter any further issues.
