### ISSUE TITLE
Accessing different models with different graphs is particularly slow

### ISSUE THREAD

**Issue by JPelamatti** [GPflow/GPflow#1189]
EDIT: A runnable code is provided

Hello,

I am currently dealing with a slow running code issue  when iterating over different GPFlow models assigned to different graphs. The brief description of my problem is the following:

I receive as an input the training values (x and f(x)) of different GP models as well as their optimal hyperparameters. I  then define the models on a different graph each in order to avoid having a single very large and very slow graph.
Finally, I iterate over the models in order in order to perform predictions , and it is this task which results particularly slow. Please note that it is only a matter of a few seconds, however for my application it adds up to several days of computation.  Do you have any idea whether it is normal, and if there is a way to speed it up?

A very synthetic representation of my problem in code would be the following:

```
import numpy as np
import tensorflow as tf
import gpflow
import pickle

import numpy as np
import tensorflow as tf
import gpflow
from pyDOE import lhs
import time

def f(X):
    y = (X[0] + 2*X[1] - 7)**2 + (2*X[0]+X[1]-5)**2
    return y

number_of_models = 10
model_dimension = 2

X,Y,HP = [],[],[]

for i in range(number_of_models):
    x = lhs(2,10)
    y = np.empty((0,1))
    for i in range(10):
        y = np.vstack([y,f(x[i])])
    k = gpflow.kernels.RBF(model_dimension)*gpflow.kernels.Matern32(model_dimension) + gpflow.kernels.Matern52(model_dimension)
    meanf = gpflow.mean_functions.Constant(0.)
    m = gpflow.models.GPR(x, y,k,meanf)
    gpflow.train.ScipyOptimizer(method='L-BFGS-B',tol = 1e-7, options = {'ftol' : 1e-7}).minimize(m, maxiter = 10000)
    hp = m.read_trainables()   
    
    X.append(x)
    Y.append(y)
    HP.append(hp)
    
    tf.reset_default_graph()
    graph = tf.get_default_graph()
    gpflow.reset_default_session(graph=graph)     


M = []

for i in range(number_of_models):
    with tf.Graph().as_default() as graph:
        with tf.Session(graph=graph).as_default():
            k = gpflow.kernels.RBF(model_dimension)*gpflow.kernels.Matern32(model_dimension) + gpflow.kernels.Matern52(model_dimension)
            meanf = gpflow.mean_functions.Constant(0.)
            m = gpflow.models.GPR(X[i], Y[i],k,meanf)
            m.assign(HP[i])
            M.append([m,graph])   


for i in range(100):
    print('\n i', i)
    x_pred = np.random.rand(20,model_dimension)
    for i in range(number_of_models):
        gr = M[i][1]
        mp = M[i][0]
        t1 = time.time()
        with tf.Session(graph = gr).as_default():
            p,s = mp.predict_y(x_pred)        
            t2 = time.time()
        print(t2-t1)
        
   ```

If I run this code, it takes roughly .2s to predict the value over 20 points, and it doesn't increase that much if i perform the same prediction but over 1000 points. Would someone know how to reduce this overhead?

I am working on Windows with Python 3.6, GPflow 1.2.0 and Tensorflow 1.12.0.
Thanks in advance!

**Comment by st--** [comment]
Hi @JPelamatti , I'm afraid I can't think of an obvious answer to your question. We have also moved development efforts towards gpflow2 / tensorflow-2.0, which gets rid of a lot of the issues that were common with graphs and sessions in tensorflow 1.x, so we are unlikely to spend much time on v1-issues that aren't obviously bugs in our code. In any case, your question seems more appropriate for stackoverflow - there's a gpflow tag: https://stackoverflow.com/questions/tagged/gpflow where you might get more visibility. I'll leave this issue open for a while, but if no-one else has added any thoughts by the end of the year I'll close it - hope you understand.

**Comment by JPelamatti** [comment]
Hello again,
I totally understand. I was just hoping to be missing something silly, as I am still wrapping my mind around tensorflow graphs. 
Thank you anyway

**Comment by st--** [comment]
@JPelamatti - I don't know if this directly applies to your specific use-case, but one thing to be aware of is that gpflow's GPR model does not cache the computation of Kuu^{-1} from the training. You could speed up prediction time by editing the predict function to make use of tf.placeholders (or non-trainable gpflow Parameters if you find those easier to use), computing the relevant quantities once after training and storing them for prediction. (This is a feature we were thinking of for a while now, but when we find the time to implement it it will be in gpflow 2 only.)

**Comment by awav** [comment]
@JPelamatti could you mirror your question in StackOverflow?

**Comment by JPelamatti** [comment]
@st-- what surprises me is that the the computation time for each iteration varies considerably little if I consider a prediction over a vector of 1000 elements rather than 20 (it goes from 1 to 2 seconds approximately). So  I guess that the Kuu inversion does not factor in that much.
@awav I just did, thanks for the advice!

**Comment by st--** [comment]
Closed in favour of https://stackoverflow.com/questions/59378927/accessing-different-gpflow-models-with-different-graphs-results-particularly-slo

**Comment by st--** [comment]
@JPelamatti the size of the matrix that needs inverting is related to the number of training points, not prediction points
