### ISSUE TITLE
broadcasting of coordinates is not consistent

### ISSUE THREAD

**Issue by Joshuaalbert** [GPflow/GPflow#1192]
In the docstring of `scaled_squard_dist` in gpflow 1.5.1 it was stated:

>         This function can deal with leading dimensions in X and X2. 
>         In the sample case, where X and X2 are both 2 dimensional, 
>         for example, X is [N, D] and X2 is [M, D], then a tensor of shape 
>         [N, M] is returned. If X is [N1, S1, D] and X2 is [N2, S2, D] 
>         then the  output will be [N1, S1, N2, S2].

Now it does not, but I assume the same behaviour is expected, since the function has not been changed (only refactored). The above behaviour is not what you get if `X2 is None`.
``` python
kern = gp.kernels.RBF(1)
K = kern.K(np.ones((2,5,1)))
# shape(2, 5, 5)
K = kern.K(np.ones((2,5,1)), np.ones((2,5,1)))
# shape (2, 5, 2, 5)
```
For consistency both should give (2,5,2,5).
## Request
I think it would actually make more sense to enable computing batches of covariance matrices, which is useful in computing the covariance for a batch of independent measurements.
I.e. I think rather than the pattern `[a b c] [d e c] -> [a b d e]` it makes more sense to do `[a b c] [d e c] -> [a b e] if a==d else raise Error`. I currently need this batch form and need to rewrite all the kernels in order to use them for my purposes.

**Comment by st--** [comment]
@Joshuaalbert the difference between k(X, X) and k(X, None) is awkward but was intentional to support some of the multi-output code. This means it's not a bug, and I'm afraid we won't maintain gpflow 1.x beyond actual bug fixes.

In as much as your question still applies to gpflow2(rc1) (which I would strongly suggest you start using - and please do open more issues for anything you find wrong with it, including features/behaviour change requests/other things that aren't bugs per se!):

You can obtain what you need without rewriting kernels using `tf.map_fn`:
```python
import gpflow
kernel = gpflow.kernels.SquaredExponential()
X = np.random.randn(4, 3, 2)
X2 = np.random.randn(4, 5, 2)
K = tf.map_fn(lambda inputs: kernel(inputs[0], inputs[1]), (X, X2), dtype=gpflow.default_float())
assert K.shape == (4, 3, 5)
```

**Comment by Joshuaalbert** [comment]
Thanks @st-- . I do plan to move to gpflow 2 as soon as I'm done a current project. I'll also rewrite the heterogp package.

Also, for others interested, I solve the above problem in 1.5.1 with:
``` python 
def fix_kernel(kern: Kernel):

    @params_as_tensors
    def _scaled_square_dist(cls, X, X2):
        """
        Rewrite of gpflow version with broadcasting.

        :param X: tf.Tensor [B1, N, D]
        :param X2: [B1, M, D]
        :return: tf.Tensor [B1, N, M] if B1=B2 else raises error at run time.
        """
        # B1, N, D
        X = X / cls.lengthscales

        if X2 is None:
            # B1, N
            Xs = tf.reduce_sum(tf.square(X), axis=-1)
            # B1, N, N
            dist = -2 * tf.matmul(X, X, transpose_b=True)
            # B1, N, N
            dist += Xs[...,:,None] + Xs[..., None, :]
            return dist
        # B1, N
        Xs = tf.reduce_sum(tf.square(X), axis=-1)
        # B2, M, D
        X2 = X2 / cls.lengthscales
        # B2, M
        X2s = tf.reduce_sum(tf.square(X2), axis=-1)
        #B, N, M
        dist = -2 * tf.linalg.matmul(X, X2, transpose_b=True)
        dist += Xs[..., :, None] + X2s[..., None, :]
        return dist

    setattr(kern,'_scaled_square_dist', _scaled_square_dist)
    return kern
```
