### ISSUE TITLE
AdaGrad

### ISSUE THREAD

**Issue by RansML** [GPflow/GPflow#121]
I'm wondering if I can use adagrad with svgp. 

`
mdl = GPflow.svgp.SVGP()
mdl.optimize(method=??)
`

Although a "non-string" can be passed into optimize(method=??) which eventually is passed into _optimize_tf() in model.py, I'm not sure what it should be. `tf.optimize.AdaGrad` seems to be an incorrect choice. Thanks.

**Comment by fujiisoup** [comment]
I think
`mdl.optimize(tf.train.AdagradOptimizer(learning_rate=0.01))`
works.

**Comment by markvdw** [comment]
True, I'm making an addition to `svi_test.ipynb` now to illustrate. I thought this was in there.

**Comment by markvdw** [comment]
See https://github.com/GPflow/GPflow/pull/122 for an example.
