### ISSUE TITLE
Fix broadcasting of conditionals etc. in gpflow2

### ISSUE THREAD

**Issue by st--** [GPflow/GPflow#1218]
GPflow 2 does not implement broadcasting on conditionals & co properly. Check #895 and take code into gpflow2.

**Comment by st--** [comment]
Note that this PR is about making gpflow2 feature-equivalent to gpflow1, which is distinct from #1204 that addresses broadcasting *more generally* than in GPflow 1

**Comment by awav** [comment]
Sounds like a duplication of the #1209. If it is not the case, then it requires a better description of the problem.

**Comment by st--** [comment]
@awav this issue is about the multi-output framework itself (regardless of the model in which you want to use it, but with an eye towards SVGP). #1209 is about making the `GPR` model class be able to work with MultiOutputKernel subclasses.

**Comment by awav** [comment]
@st--, What I'm trying to say is that from the current description it is not clear what is wrong with multi-output framework. The https://github.com/GPflow/GPflow/pull/895 was merged ages ago and gpflow 2.0 works with broadcasting in the same way it worked for gpflow 1.0.

**Comment by st--** [comment]
Agreed, we should clarify the various open issues. 
@vdutor this was brought up by you I believe - could you clarify?

**Comment by st--** [comment]
Closed by #1308
