### ISSUE TITLE
log_likelihood() missing 1 required positional argument: 'Y'

### ISSUE THREAD

**Issue by jt2718** [GPflow/GPflow#1224]
Hi, I've never asked a question here, but will give it a try.

I am not able to run the multiclass_classification notebook after cloning the repo. When trying to run inference I get the following error:

"log_likelihood() missing 1 required positional argument: 'Y'"

Full error message:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-89209ae44c24> in <module>
      7 opt_logs = opt.minimize(objective_closure,
      8                         m.trainable_variables,
----> 9                         options=dict(maxiter=ci_niter(1000)))
     10 print_summary(m, fmt='notebook')

~/anaconda3/envs/gpflow/lib/python3.7/site-packages/gpflow/optimizers/scipy.py in minimize(self, closure, variables, method, step_callback, **scipy_kwargs)
     58 
     59         return scipy.optimize.minimize(func, initial_params, jac=True, method=method,
---> 60                                        **scipy_kwargs)
     61 
     62     @classmethod

~/anaconda3/envs/gpflow/lib/python3.7/site-packages/scipy/optimize/_minimize.py in minimize(fun, x0, args, method, jac, hess, hessp, bounds, constraints, tol, callback, options)
    598     elif meth == 'l-bfgs-b':
    599         return _minimize_lbfgsb(fun, x0, args, jac, bounds,
--> 600                                 callback=callback, **options)
    601     elif meth == 'tnc':
    602         return _minimize_tnc(fun, x0, args, jac, bounds, callback=callback,

~/anaconda3/envs/gpflow/lib/python3.7/site-packages/scipy/optimize/lbfgsb.py in _minimize_lbfgsb(fun, x0, args, jac, bounds, disp, maxcor, ftol, gtol, eps, maxfun, maxiter, iprint, callback, maxls, **unknown_options)
    333             # until the completion of the current minimization iteration.
    334             # Overwrite f and g:
--> 335             f, g = func_and_grad(x)
    336         elif task_str.startswith(b'NEW_X'):
    337             # new iteration

~/anaconda3/envs/gpflow/lib/python3.7/site-packages/scipy/optimize/lbfgsb.py in func_and_grad(x)
    283     else:
    284         def func_and_grad(x):
--> 285             f = fun(x, *args)
    286             g = jac(x, *args)
    287             return f, g

~/anaconda3/envs/gpflow/lib/python3.7/site-packages/scipy/optimize/optimize.py in function_wrapper(*wrapper_args)
    324     def function_wrapper(*wrapper_args):
    325         ncalls[0] += 1
--> 326         return function(*(wrapper_args + args))
    327 
    328     return ncalls, function_wrapper

~/anaconda3/envs/gpflow/lib/python3.7/site-packages/scipy/optimize/optimize.py in __call__(self, x, *args)
     62     def __call__(self, x, *args):
     63         self.x = numpy.asarray(x).copy()
---> 64         fg = self.fun(x, *args)
     65         self.jac = fg[1]
     66         return fg[0]

~/anaconda3/envs/gpflow/lib/python3.7/site-packages/gpflow/optimizers/scipy.py in _eval(x)
     70             cls.assign_tensors(variables, values)
     71 
---> 72             loss, grads = _compute_loss_and_gradients(closure, variables)
     73             return loss.numpy().astype(np.float64), cls.pack_tensors(grads).astype(np.float64)
     74 

~/anaconda3/envs/gpflow/lib/python3.7/site-packages/gpflow/optimizers/scipy.py in _compute_loss_and_gradients(loss_cb, variables)
    114 def _compute_loss_and_gradients(loss_cb: LossClosure, variables: Variables):
    115     with tf.GradientTape() as tape:
--> 116         loss = loss_cb()
    117     grads = tape.gradient(loss, variables)
    118     return loss, grads

~/anaconda3/envs/gpflow/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py in __call__(self, *args, **kwds)
    455 
    456     tracing_count = self._get_tracing_count()
--> 457     result = self._call(*args, **kwds)
    458     if tracing_count == self._get_tracing_count():
    459       self._call_counter.called_without_tracing()

~/anaconda3/envs/gpflow/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py in _call(self, *args, **kwds)
    501       # This is the first call of __call__, so we have to initialize.
    502       initializer_map = object_identity.ObjectIdentityDictionary()
--> 503       self._initialize(args, kwds, add_initializers_to=initializer_map)
    504     finally:
    505       # At this point we know that the initialization is complete (or less

~/anaconda3/envs/gpflow/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py in _initialize(self, args, kwds, add_initializers_to)
    406     self._concrete_stateful_fn = (
    407         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
--> 408             *args, **kwds))
    409 
    410     def invalid_creator_scope(*unused_args, **unused_kwds):

~/anaconda3/envs/gpflow/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
   1846     if self.input_signature:
   1847       args, kwargs = None, None
-> 1848     graph_function, _, _ = self._maybe_define_function(args, kwargs)
   1849     return graph_function
   1850 

~/anaconda3/envs/gpflow/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   2148         graph_function = self._function_cache.primary.get(cache_key, None)
   2149         if graph_function is None:
-> 2150           graph_function = self._create_graph_function(args, kwargs)
   2151           self._function_cache.primary[cache_key] = graph_function
   2152         return graph_function, args, kwargs

~/anaconda3/envs/gpflow/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   2039             arg_names=arg_names,
   2040             override_flat_arg_shapes=override_flat_arg_shapes,
-> 2041             capture_by_value=self._capture_by_value),
   2042         self._function_attributes,
   2043         # Tell the ConcreteFunction to clean up its graph once it goes out of

~/anaconda3/envs/gpflow/lib/python3.7/site-packages/tensorflow_core/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    913                                           converted_func)
    914 
--> 915       func_outputs = python_func(*func_args, **func_kwargs)
    916 
    917       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

~/anaconda3/envs/gpflow/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py in wrapped_fn(*args, **kwds)
    356         # __wrapped__ allows AutoGraph to swap in a converted function. We give
    357         # the function a weak reference to itself to avoid a reference cycle.
--> 358         return weak_wrapped_fn().__wrapped__(*args, **kwds)
    359     weak_wrapped_fn = weakref.ref(wrapped_fn)
    360 

<ipython-input-6-89209ae44c24> in objective_closure()
      3 @tf.function(autograph=False)
      4 def objective_closure():
----> 5     return - m.log_marginal_likelihood(data)
      6 
      7 opt_logs = opt.minimize(objective_closure,

~/anaconda3/envs/gpflow/lib/python3.7/site-packages/gpflow/models/model.py in log_marginal_likelihood(self, *args, **kwargs)
     43 
     44     def log_marginal_likelihood(self, *args, **kwargs) -> tf.Tensor:
---> 45         return self.log_likelihood(*args, **kwargs) + self.log_prior()
     46 
     47     def log_prior(self) -> tf.Tensor:

TypeError: log_likelihood() missing 1 required positional argument: 'Y'

**Comment by condnsdmatters** [comment]
hey there @jt2718, thanks for opening the issue. May I ask what version of gpflow you are running?

**Comment by condnsdmatters** [comment]
I am struggling to reproduce the problem here:

_in a new virtual environment_ 
`git clone https://github.com/gpflow/gpflow.git gpflow && cd gpflow && pip install -e . && pip install matplotlib jupyter && jupyter notebook`

All seems to work. Can you run `pip freeze` and check your installed version is the same as the cloned version.

**Comment by jt2718** [comment]
Hi! @condnsdmatters, I initially tried this using 2.0.0-rc1 installed using conda/pip (not entirely sure). When this didn’t work I tried cloning all of the master branch of the repo and running the notebook within that folder. This gave the same error so I tried the develop branch, but still no luck.

**Comment by jt2718** [comment]
Ok I’ll try what you just sent, maybe I have messed something up during the installation. Will update when I’ve tried, thank you!

**Comment by condnsdmatters** [comment]
for what its worth, in develop i we recently changed the interface for the likelihood because we wanted to homogenise some api's before the 2.0 proper release. Its possible that installing from pip and trying to run develop may have caused some problems in this particular instance!

**Comment by jt2718** [comment]
I see, it works now at least! Thank you so much.

**Comment by condnsdmatters** [comment]
no problem, good luck!
