### ISSUE TITLE
Dimension error

### ISSUE THREAD

**Issue by irum** [GPflow/GPflow#1226]
Hi,
I am using intro to gpflow2 file from doc in gpflow 2 version and i have used my  images as data but I am getting the following error. I want to do multiclass classification

ValueError: Dimensions must be equal, but are 1 and 3 for 'Tensordot/MatMul' (op: 'MatMul') with input shapes: [10,1], [3,1605632].

I do not understand why I am getting this error

the code is as follows

Dir = "/media/irum/DATA/Dataset/train"

warnings.filterwarnings('ignore')

gpflow.config.set_default_float(np.float64)

num_features=10
C=10

#sum kernel: Matern32 + White
kernel = gpflow.kernels.Matern32() + gpflow.kernels.White(variance=0.01)

# Robustmax Multiclass Likelihood
invlink = gpflow.likelihoods.RobustMax(C)  # Robustmax inverse link function
likelihood = gpflow.likelihoods.MultiClass(C, invlink=invlink)  # Multiclass likelihood

inducing_variable = np.linspace(0, 10, num_features).reshape(-1, 1)

model = gpflow.models.SVGP(kernel=kernel, likelihood=likelihood,
    inducing_variable=inducing_variable, num_latent=C, whiten=True, q_diag=True)

# Only train the variational parameters
set_trainable(model.kernel.kernels[1].variance, False)
set_trainable(model.inducing_variable, False)

optimizer=gpflow.optimizers.Scipy()

@tf.function()
def optimization_step(model: gpflow.models.SVGP, batch_x,batch_y):
    with tf.GradientTape(watch_accessed_variables=False) as tape:
        tape.watch(model.trainable_variables)
        obj = - model.elbo(batch_x,batch_y)
        grads = tape.gradient(obj, model.trainable_variables)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))

def simple_training_loop(model: gpflow.models.SVGP, epochs: int = 2, logging_epoch_freq: int = 10):
    data_loader = utils.Data_loader(32, Dir)

    tf_optimization_step = tf.function(optimization_step, autograph=False)
    for epoch in range(epochs):
        data_loader.shuffle_data()
        for _ in range(data_loader.n_batches):
            batch_x, batch_y = data_loader.next_batch(32)
            batch_x=tf.convert_to_tensor(batch_x)
            batch_y=tf.convert_to_tensor(batch_y)
            tf.squeeze(batch_x)

            print(batch_x.shape)
            print(batch_y.shape)

            tf_optimization_step(model, batch_x,batch_y)

        epoch_id = epoch + 1
        if epoch_id % logging_epoch_freq == 0:
            tf.print(f"Epoch {epoch_id}: ELBO (train) {model.elbo(batch_x, batch_y)}")

if __name__ =="__main__" :
    simple_training_loop(model, epochs=10, logging_epoch_freq=2)

**Comment by awav** [comment]
Hello @irum! Thanks for the question. Could you re-post it in StackOverflow with `gpflow` tag? It doesn't look like a GPflow bug :) https://github.com/GPflow/GPflow#getting-help

Thanks!

**Comment by irum** [comment]
Ok, Thank you. Yes,its some logical issue
