### ISSUE TITLE
Syntax for setting active_dims on Periodic kernel is unclear

### ISSUE THREAD

**Issue by doccosmos** [GPflow/GPflow#1230]
It is unclear from the documentation what the correct syntax is for creating a periodic Matern kernel, say:

k1 = gpflow.kernels.Matern12(1, active_dims = [0])
k = gpflow.kernels.Periodic(base = k1)

or 

k1 = gpflow.kernels.Matern12(1, active_dims = [0])
k2 = gpflow.kernels.Periodic(1, active_dims = [0])
k = k1 * k2

**Comment by st--** [comment]
Hi @doccosmos, thanks for your feedback! You are right, the Periodic kernel's interface wasn't quite right. I've tried to address it in this PR: #1231. Please have a look and if you think it's not actually answering your issue, please leave a comment!
