### ISSUE TITLE
Cholesky decomposition issue with subtractive kernel

### ISSUE THREAD

**Issue by doccosmos** [GPflow/GPflow#1232]
I'm trying the following kernel:

class AperiodicMatern12(gpflow.kernels.Kernel):
  def __init__(self, input_dim = None, period = 1.0, variance = 1.0, lengthscales = 1.0, active_dims = None, name = None):
    super().__init__(input_dim, active_dims = active_dims)
    k0 = gpflow.kernels.Matern12(input_dim, active_dims = active_dims)
    k1 = gpflow.kernels.Matern12(input_dim, active_dims = active_dims)
    k = gpflow.kernels.Periodic(base = k1, period = period)
    self.base = k0
    self.per = k

  @gpflow.params_as_tensors
  def K(self, X, X2 = None):
    res = self.base.K(X, X2) - self.per.K(X, X2)
    return res

  def Kdiag(self, X):
    return np.diag(self.K(X))

--

When I run it with:

lik = gpflow.likelihoods.Gaussian()
k = AperiodicMatern12(1, active_dims = [0])
m = gpflow.models.GPR(X, Y, kern = k) 
gpflow.train.ScipyOptimizer().minimize(m)

I get:

InvalidArgumentError (see above for traceback): Cholesky decomposition was not successful. The input might not be valid.
	 [[node GPR-0b2840db-15/likelihood_1/Cholesky (defined at /Users/mjg/anaconda3/lib/python3.6/site-packages/gpflow/models/gpr.py:72) ]]

When I try with the kernel defined as additive:

  @gpflow.params_as_tensors
  def K(self, X, X2 = None):
    res = self.base.K(X, X2) + self.per.K(X, X2)
    return res

everything works fine. X and Y are standardized in both cases. So what is the issue with the subtractive kernel?

**Comment by st--** [comment]
@doccosmos thanks for your interest in using GPflow! As your question is a "how to use" question about code on top of what is implemented in GPflow, and not about anything that affects GPflow code itself, it would be more appropriate for stackoverflow ([tagged [gpflow]](https://stackoverflow.com/tags/gpflow)); then other people can more readily benefit from your question and answers in the future. Could you please ask it over there and post the link to the question in here?

**Comment by doccosmos** [comment]
I would argue that lack of support for subtractive kernels (which work in GPy) is actually about GPflow code itself but have asked on stackoverflow as suggested.

**Comment by st--** [comment]
https://stackoverflow.com/questions/59919814/cholesky-decomposition-issue-with-subtractive-kernel-in-gpflow/59923511#59923511

As far as I was aware, "Subtractive kernels" aren't a thing - taking the difference between two kernels doesn't necessarily result in a valid kernel. I also couldn't find any mention of "subtractive kernel" in the GPy documentation - could you point to what you meant?
