### ISSUE TITLE
Using Softmax for multi-class prediction

### ISSUE THREAD

**Issue by margiki** [GPflow/GPflow#1234]
I see that multi-class classification uses RobustMax squashing function.

How can I use the Softmax squashing function?

**Comment by awav** [comment]
Hello @margiki. We would appreciate if you could post questions not related to GPflow bugs/issues on StackOverflow with `gpflow` tag. Thanks!

**Comment by margiki** [comment]
Thank you!

https://stackoverflow.com/questions/59955150/gpflow-multi-class-how-to-squeeze-many-gp-predict-f-samples-to-obtain-their-pro
