### ISSUE TITLE
The constructor of SGPR is confusing

### ISSUE THREAD

**Issue by yiwei-prowler** [GPflow/GPflow#1248]
In the constructor of SGPR class, the parameter inducing_variable: Optional[InducingPoints] = None, which means if not provided, a None value is used. But a None value will cause crash.

Also, the header comment of this __init__ method is out-dated. The comments mentions X and Y, But X and Y are not defined. There is no explanation of inducing_variable, num_latent and noise_variance.

**Comment by awav** [comment]
Thanks, @yiwei-prowler! Could you make a PR to fix it?
