### ISSUE TITLE
Documentation of GPModel.predict_f_samples incomplete

### ISSUE THREAD

**Issue by yiwei-prowler** [GPflow/GPflow#1249]
In GPModel.predict_f_samples, the header comment is incomplete. explanation for the parameters are missing. In the implementation, shape indications such as [S, N, P] needs to be explained better. Also consider writing shape assertions too.

**Comment by awav** [comment]
Thanks, @yiwei-prowler. If you have already looked at it and you know what you would like to change, can you create a PR?
