### ISSUE TITLE
SVGP.predict_f has inconsistent argument names

### ISSUE THREAD

**Issue by yiwei-prowler** [GPflow/GPflow#1250]
SVGP.predict_f has a parameter named Xnew, but the inherited method GPModel.predict_f has the parameter named predict_at. We should keep using predict_at. Some other models have the same issue.

Also, in GPModel.predict_f, header comments are missing.

**Comment by st--** [comment]
Thanks for pointing out this inconsistency! I agree we should be consistent with argument names - in fact I think we should use `X` everywhere (and retire `predict_at`), as that notation is standard across GP papers, and `predict_f(predict_at=<...>)` seems rather redundant.

What do you mean by header comments?

**Comment by yiwei-prowler** [comment]
Header comments:
"""
:param 
:param 
"""
