### ISSUE TITLE
Coregionalisation mismatch GPFlow 2, GPFlow 1.5.1

### ISSUE THREAD

**Issue by dblanm** [GPflow/GPflow#1279]
Basically **comparing** **GPFlow 2** result on **coregionalisation** with the same kernel has a huge difference compared to **GPFlow 1.5.1**, both on the prediciton and coregionalisation matrix.
The model of GPFlow 2 predictions compared to 1.5.1 seems as the lengthscales optimization did not converge, possibly the issue is on the optimiser. Could it instead be an issue of GPFlow 2 coregionalisation definition? (I haven't looked at the new implementation)

[GPFlow 2 Coregionalisation](https://gpflow.readthedocs.io/en/master/notebooks/advanced/coregionalisation.html)
[GPFlow 1.1.5 Coregionalisation](https://github.com/GPflow/GPflow/blob/v1.5.1/doc/source/notebooks/advanced/coregionalisation.ipynb)

As an example of what the result with a Matern32 kernel would produce in [GPy coregionalisation](https://nbviewer.jupyter.org/github/SheffieldML/notebook/blob/master/GPy/coregionalized_regression_tutorial.ipynb).

**Comment by alexisboukouvalas** [comment]
hi @dblanm 
Thank you for your question regarding multi-output GPs in GPflow. I think the documentation at <> is out of data. If you pick up the latest version of the notebook (after this commit 
 https://github.com/GPflow/GPflow/commit/22edd92d06c201b1f40a656e5bbca84a5f483f2d ) you should see an improved fit for the Coreg kernel. @st-- can comment further. Please let us know if you are still hitting issues.

**Comment by st--** [comment]
@dblanm this has already been resolved in the `develop` branch, see https://gpflow.readthedocs.io/en/develop/notebooks/advanced/coregionalisation.html (note the `develop` instead of `master` in your link).
