### ISSUE TITLE
Docs not building

### ISSUE THREAD

**Issue by st--** [GPflow/GPflow#1300]
#1270 got merged into develop 4 days ago, yet the gpflow/docs repo says last commit was 11 days ago, and the readthedocs haven't updated to reflect the changes to the notebook.

**Comment by awav** [comment]
The `gpflow` project never triggered the documentation generation. It requires investigation, and there is no need for CircleCI access.

**Comment by awav** [comment]
Command `make -C GPflow/doc/source/notebooks -j 4` fails for some reason. https://app.circleci.com/jobs/github/GPflow/docs/75

**Comment by st--** [comment]
Tried it out locally but can't reproduce the dead kernel. It looks like it may be some kind of time-out issue? We could make an exception for the convolutional.ipynb (which takes significantly longer to run than any of the other notebooks) and store the compiled version in the repo, so that it won't have to actually run?
