### ISSUE TITLE
No module named 'gpflow.utilities'

### ISSUE THREAD

**Issue by chennanli** [GPflow/GPflow#1301]
Run examples from GPFlow in GCP tensorflow 2.0 instance

Original code from GPFlow example is

from gpflow.utilities import print_summary

Received error messages

ImportError: No module named 'gpflow.utilities'

**Comment by st--** [comment]
Hi @chennanli, thanks for your interest in GPflow. Could you please specify which version of GPflow you are using (e.g. `import gpflow; print(gpflow.__version__)`)?

**Comment by st--** [comment]
Hi @chennanli - I believe you may be using an old version of GPflow; if you want to use GPflow with tensorflow 2 I would suggest to install the `develop` branch from github, we're also working hard towards making a public gpflow-2.0 release (aiming for early April). Please let us know if there's anything we can help with in the meanwhile.
