### ISSUE TITLE
A higher order likelihood expectation? 

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#131]
We currently support the following likelihood functionality

If:

q(f) = N(Fmu, Fvar)

then _predict_density_ computes

\int p(y=Y|f)q(f) df

I've come across a need for 

\int p(y=Y|f)q(f) f df

whilst implementing a mean field method. Do we think this is generally useful?

**Comment by alexggmatthews** [comment]
I think that GPML has this functionality for its likelihoods.

**Comment by jameshensman** [comment]
I guess that's the mean of the tilted distribution? what about a more
general tilted-moments function?
