### ISSUE TITLE
A pre-computed kernel

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#132]
In my previous work I've encountered the case where you want to pre-compute a gram matrix (which has fixed hypers) and load it into some GP software without implementing all the code you used in that software. The solution I came to was to store the gram matrix and make the data inputs integer indeces into that matrix. then K(i,j) = K_{i,j} . Do we think this is of general interest?  Is the integer index trick the best way to do it?

**Comment by jameshensman** [comment]
In GPy, there's a 'Fixed' kernel, which just returns a designated matrix (times a scalar parameter). 

The problem is, what to do at predict time? Presumably you just want to ignore this kernel when predicting? 

I think GPy's fixed kernel is confusing for users.

**Comment by alexggmatthews** [comment]
I guess you would upload those elements of the matrix too :) . Consider a case I've come across where the data inputs are _actually_ a large set of graphs. We may not want to have to deal with that sort of complex data structure in GPflow. I can always implement it myself but its just a question of whether we think it is core and more of use to others than a hindrance.

**Comment by jameshensman** [comment]
Ah. Now I have had a think about this sort of thing. What I would suggest, is that the 'X' in GPflow becomes some integer values, and the kernel stores a big lookup table. so the kernel would look like

```python
class LookupKern(GPflow.kernels.Kern):
    def __init__(self, K):
        self._K = K
    def K(X, X2):
            return self._K[X, X2]

big_K = np.load(...)
k = LookUpKern(big_K)

X = np.random.randint(0, big_K.shape[0], (10, 1))
Y = np.foo
```

Then, if you wanted to combine this kernel with other kernels, you'd use separate columns of X, and the active_dims feature of the kernels.

In this case, I think it's core, and a definite upgrade on GPy.kern.Fixed.

**Comment by alexisboukouvalas** [comment]
Just some feedback which may be of use - models such as the PANAMA model use fixed kernels so this enhancement would be useful when trying to implement such models.
[PANAMA](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1002330) is a GPLVM model that includes known confounding factors

**Comment by alexggmatthews** [comment]
OK. I'm now thesis writing so I will open this one up if someone fancies it.

**Comment by jameshensman** [comment]
Note: This is already pretty-much implemented in the Coregion kernel. The difference in that in the Coregion kernel the positive-definite matrix can be optimized (sampled), whereas this proposal is for a fixed matrix.
