### ISSUE TITLE
cosine kernel returns indefinite covariance matrices

### ISSUE THREAD

**Issue by ilia-kats** [GPflow/GPflow#1328]
Consider the following minimal example:
```python
tf.random.set_seed(42)
X = tf.random.uniform((10,2), minval=-10, maxval=10, dtype=tf.float64)

kern = gpflow.kernels.Cosine()
print(tf.linalg.eigvalsh(kern(X)))
```
This gives me
```python
tf.Tensor(
[-2.27306374 -1.58787397 -0.2847927   0.19340605  1.18589017  1.33897599
  1.6473351   2.37452162  2.89101446  4.51458702], shape=(10,), dtype=float64)
```
Because of this, the cosine kernel in GPR or SGPR is unusable, as optimization aborts due to failed cholesky decomposition (I haven't tried other models, yet, but I assume that this is a general issue). As far as I can tell, the cosine kernel was first derived in [1] for the univariate case. There, the cosine kernel is defined as $\sigma^2\cos\left(\frac{2\pi(x - x')}{p}\right)$. Note that it is a function of $x - x'$, not $|x - x'|$, as in the gpflow implementation. Transitioning to the multivariate case and defining $k(x, x') = \sigma^2\cos\left(\frac{2\pi\sum_k (x_k - x'_k)}{p}\right)$, positive semidefinite covariance matrices are obtained up to numerical imprecision:
```python
dist = X[:, tf.newaxis, :] - X[tf.newaxis, :, :]
dist = tf.reduce_sum(dist, axis=-1)
print(tf.linalg.eigvalsh(tf.math.cos(dist)))
```
This gives
```python
tf.Tensor(
[-1.79943150e-15 -6.15775238e-16 -4.15847122e-16 -3.93820396e-17
  9.50847803e-17  2.43329656e-16  6.85377761e-16  1.38407146e-15
  3.22740434e+00  6.77259566e+00], shape=(10,), dtype=float64)
```
The above kernel can be derived from eq. 4.7 in [2] as the limiting case of $v_q^{(p)} = 0 \forall p$

[1] https://dspace.mit.edu/bitstream/handle/1721.1/92869/Tenenbaum_Automatic%20Construction.pdf?sequence=1&isAllowed=y
[2] https://www.cs.cmu.edu/~andrewgw/andrewgwthesis.pdf

sorry for the bad math, I have no idea how to make GitHub render equations...

**Comment by st--** [comment]
Hi @ilia-kats, thanks for spotting this bug! Would you be up for making a pull request with the corresponding changes to the Cosine kernel? (I hope I understood correctly - in the univariate case, the behaviour should be exactly the same?)

**Comment by ilia-kats** [comment]
Yes, univariate results are identical.
