### ISSUE TITLE
Access to SVGP.inducing_variable gives object of a different type

### ISSUE THREAD

**Issue by yiwei-prowler** [GPflow/GPflow#1336]
Creating a SVGP object requires to passing in an inducing_variable object. Since there is no type hinting and no documentation for this passed-in argument, we've seen people passing in object of type `tf.Tensor`. When they do so, when they access the `inducing_variable` field from SVGP, they get an object of a different type `InducingPoints'. 

This creates surprise for using the API of SVGP because people would expect the field `SVGP.inducing_variable` to point to the object passed in through the `inducing_variable` argument.

Also, when setting the prior of the inducing variables, people will create code:
```
model = SVGP(inducing_variable)
model.inducing_variable.Z.prior = ...
```

This is a bit awkward because you first construct the whole model object and then being able to set part of it.

My suggestion is to require SVGP.__init__ to accept `InducingPoints` or some of its ancestor type, add type hinting, and add documentation (by the way, the current documentation for __init__ does not follow the same format at other methods in the same class) to tell people how to create InducingPoints object.

**Comment by st--** [comment]
I agree this is a bit awkward. On the other hand, most of the time we do use inducing *points* and it is very convenient for users not to always have to wrap the Z array/tensor in an `InducingPoints` class...

**Comment by st--** [comment]
@yiwei-prowler I would suggest to leave the behaviour as is for now, I do think we could make the behaviour much clearer by improving the docstring - perhaps adding a type hint `inducing_variable: Union[Tensor, InducingVariable]`. It'd be great if you could contribute this directly as a pull request - happy to chat on the gpflow slack to hash out details and answer questions you may have in the process!

**Comment by st--** [comment]
Adding the correct type hint is already covered by #1368.
