### ISSUE TITLE
InducingPointsBase.Z may benefit from a more informative name

### ISSUE THREAD

**Issue by yiwei-prowler** [GPflow/GPflow#1337]
- The field `Z` in `InducingPointsBase` needs a more informative name, maybe `location`.  

- Its type hinting is missing,

**Comment by st--** [comment]
Z is standard nomenclature in the Gaussian process literature for the location of the inducing inputs, so we won't be changing that. I'd be happy to review&merge a PR that adds the type hint, if you want to do that!

**Comment by yiwei-prowler** [comment]
ok, then why in SVGP, we have `SVGP.inducing_variable.Z`, instead of just `SVGP.Z`?

**Comment by yiwei-prowler** [comment]
From the SVGP paper: "additional input-output pairs Z, u, known as ‘inducing inputs’ and ‘inducing
variables’.". What is the decision procedure to use Z instead of "inducing inputs", but use "inducing_variable" but not "u"?
