### ISSUE TITLE
Full type hint coverage

### ISSUE THREAD

**Issue by joelberkeley-secondmind** [GPflow/GPflow#1368]
**What?**

Full type hint coverage. That is, types should be specified everywhere they can't be inferred by a type checker.

@joelberkeley-pio would like mypy to be part of the CI run so that we have some visibility of degradation. We need to discuss whether it makes sense to require mypy passes for merge.

**Why?**

As a user (or GPflow maintainer), I want full type hint coverage so that I know what types I'm expected to provide and which I should expect to receive back.

As a production user, I want full type hint coverage so that I can gain confidence my code is integrated correctly with the library.

As a GPflow maintainer, I want full type hint coverage so that I can be confident my changes are sound.

**Comment by joelberkeley-pio** [comment]
**How?**

I propose we apply this a sub-package at a time.

**Comment by joelberkeley-pio** [comment]
Before we do this, I recommend we reconsider the current approach of aliasing types. I find type aliases can be problematic for the following reasons:

  * they hide the actual meaning behind library-local names and therefore
    * are potentially less clear or accurate
    * require an indirection to find out what type I'm actually looking at
  * they give the user the unwarranted impression of type safety for different aliases of the same type. For example a user seeing `InputData` and `OutputData` may interpret these as different types, and thus feel that the type system (in the form of IDE highlighting/mypy) will warn them when there's a mistake. However, they are both aliases for `tf.Tensor` so they are actually the same type

There are cases where aliases make sense, for example when shortening lengthy types which are used repeatedly in a module

**Comment by st--** [comment]
I'd be happy to go with a submodule-at-a-time approach and see how comfortable we all end up being with it. How about you & others who are keen to add types make a start with a couple PRs so we can see what that would look like?

**Comment by joelberkeley-pio** [comment]
Things learnt from adding types to gpflow/base.py

  - it's looking promising that we can leave nothing without a type or suitable comment/pragma
  - use `# type unknown` where a type is unknown
  - use `if TYPE_CHECKING:` to avoid importing optional dependencies at runtime
  - use `# type: ignore` where the correct solution would require too much boilerplate

**Comment by joelberkeley-pio** [comment]
I'd like to clarify that I think it's really important that we don't consider casually choose that omitting a type is a good final state, simply because we then don't know what's been looked at and what hasn't. Alternatives include comments or an alias of `Any`

**Comment by st--** [comment]
Before we spend more effort on this, can we try adding mypy to the build and ask it to only check the submodules we've typified so far ?
