### ISSUE TITLE
Rename jit

### ISSUE THREAD

**Issue by joelberkeley-pio** [GPflow/GPflow#1373]
GPflow uses the word 'jit' to describe compiling operations with [`tf.function`](https://www.tensorflow.org/api_docs/python/tf/function). However, TensorFlow use the word 'jit' to mean compilation with/for XLA, see the top 4 google searches for "tensorflow jit"

https://www.tensorflow.org/xla
https://docs.w3cub.com/tensorflow~guide/performance/xla/jit/
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/compiler/jit
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/compiler/xla/jit.py

These are distinct in general, but coincide when the argument `experimental_compile` to `tf.function` is `True`.

I propose we remove usages of the word 'jit' where we mean compilation with `tf.function`, so as to be more aligned TensorFlow nomenclature, so that users are clear on what the name means. Candidate replacements:

  - `eager`
  - `eagerly`
  - `execute_eagerly` (as per the function [`tf.executing_eagerly`](https://www.tensorflow.org/api_docs/python/tf/executing_eagerly))
  - `compile(d)` (note [`tf.keras.Model.compile`](https://www.tensorflow.org/api_docs/python/tf/keras/Model#compile) means "Configures the model for training.")
  - `graph_compile(d)`
  - `compile_graph`
  - `trace_compile(d)`
  - `as_graph`

**Comment by st--** [comment]
I'd be happy to change it to `compile`. (`trace_compile` doesn't seem any clearer to me, if anything I find it more confusing what it's supposed to mean. `eager[ly]` also seems less clear than `compile` as to what a flag changes, and `execute_eagerly` is a fair amount more verbose than `compile`.)

If no-one else has any objections, would you be up for making a pull request that changes all occurrences? (Note that this affects the currently-in-review #1276). Happy to review it.

**Comment by joelberkeley-pio** [comment]
We can't do this before 2.0, so there's no rush

**Comment by st--** [comment]
> We can't do this before 2.0, so there's no rush

it's a very small change, so in fact I'd be much happier to change this before rolling out the 2.0 release

**Comment by joelberkeley-pio** [comment]
wasn't the plan that all names changes were to be submitted by the deadline a couple of weeks ago?

**Comment by st--** [comment]
If you think it would be cleaner to not call it `jit`, I think we'd be making our lives easier in the longer run if we change it now rather than later. I believe the main motivation had been to limit how much reviewing was needed so that we'd be able to handle it. I would be happy to review a PR that renames all `jit` to `compile`, though.

**Comment by joelberkeley-pio** [comment]
completed by #1392
