### ISSUE TITLE
Import error: cannot import name 'variadic_signature_matches'

### ISSUE THREAD

**Issue by fonnesbeck** [GPflow/GPflow#1381]
Following the instructions on installing GPflow by cloning the repository and using pip, I am unable to run GPflow. I get the following ImportError:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-0dccf67cb4c8> in <module>()
----> 1 import gpflow

~/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/gpflow/__init__.py in <module>()
     17 from .base import Module, Parameter
     18 from .config import default_int, default_float, default_jitter
---> 19 from .utilities import set_trainable
     20 from . import (
     21     conditionals,

~/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/gpflow/utilities/__init__.py in <module>()
      1 from .bijectors import *
----> 2 from .multipledispatch import Dispatcher
      3 from .utilities import *

~/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/gpflow/utilities/multipledispatch.py in <module>()
      1 from multipledispatch import Dispatcher as GeneratorDispatcher
----> 2 from multipledispatch.dispatcher import variadic_signature_matches
      3 from multipledispatch.variadic import isvariadic
      4 
      5 __all__ = ["Dispatcher"]

ImportError: cannot import name 'variadic_signature_matches'
```

Additional information:
    * GPflow version: current master (0d97bc0)
    * Tensorflow version: 2.2.0-dev20200325
    * Does your tensorflow use GPU or not: yes
    * Python version: 3.6
    * OS: Linux (AWS)

**Comment by st--** [comment]
Hi @fonnesbeck, thanks for bringing this issue to our attention. Could you please clarify what version of the `multipledispatch` package you've got installed? (`pip freeze | grep multipledispatch` should work)

**Comment by st--** [comment]
Furthermore, if you are not using the latest version (0.6.0) could you try installing that (`pip install -U multipledispatch`) and check whether you still get the same error?

**Comment by fonnesbeck** [comment]
Right, I was on 0.5.0. Updating via pip did the trick. Thanks.
