### ISSUE TITLE
Monitor doesn't update when using multiple tasks

### ISSUE THREAD

**Issue by markvdw** [GPflow/GPflow#1385]
If I have multiple tasks in the monitor (e.g. `ModelToTensorBoard` and `ScalarToTensorBoard`), then one of them will stop to update in TensorBoard, even though the data is still being written to the file.

I believe the problem is that each task uses its own `FileWriter`, which gives each task a different events file. TensorBoard gives the error
```E0329 00:03:23.523564 123145515630592 directory_watcher.py:244] File ./adam_SqExp_Points_M1000/events.out.tfevents.1585439824.mv310.53594.189.v2 updated even though the current file is ./adam_SqExp_Points_M1000/events.out.tfevents.1585439824.mv310.53594.205.v2```

Could this make sense? Any suggestions on how to fix it?

**Comment by markvdw** [comment]
A workaround is to use `tensorboard --logdir . --reload_multifile=true`, as suggested in https://github.com/tensorflow/tensorboard/issues/1063.

**Comment by st--** [comment]
Workaround merged in #1389
