### ISSUE TITLE
multiclass notebook does not fit as expected.

### ISSUE THREAD

**Issue by jameshensman** [GPflow/GPflow#1403]
## Bug case
The notebook that does multi-class classification does not fit correctly: the posterior does not capture the patterns in the generated data `https://gpflow.readthedocs.io/en/master/notebooks/advanced/multiclass_classification.html`

**Comment by st--** [comment]
This is an issue with automatically generating the documentation (which currently does not happen for `master` - see #1404). Everything is working fine in the `develop` version of the notebook: https://gpflow.readthedocs.io/en/develop/notebooks/advanced/multiclass_classification.html

**Comment by st--** [comment]
The `master` documentation has just been re-started manually, so even https://gpflow.readthedocs.io/en/master/notebooks/advanced/multiclass_classification.html works fine now.
