### ISSUE TITLE
`master` documentation is not building automatically

### ISSUE THREAD

**Issue by st--** [GPflow/GPflow#1404]
While the documentation for the `develop` branch is now building freshly on each merged pull request, the `master` documentation is out of date. This was evidenced by #1403, which pointed out that the [multiclass classification notebook (master)](https://gpflow.readthedocs.io/en/master/notebooks/advanced/multiclass_classification.html) had a bug, whereas everything was working fine as expected in the [develop version](https://gpflow.readthedocs.io/en/develop/notebooks/advanced/multiclass_classification.html). *(Note that the master docs have been re-started manually to fix this for now.)*

**Comment by st--** [comment]
Thanks to @vdutor for manually kick-starting the documentation build for `master` as a one-off - this brings the documentation up to date with the 2.0 release from yesterday. We should automate this in the long run, but has lower priority for now.

**Comment by condnsdmatters** [comment]
my mistake sorry
