### ISSUE TITLE
Proposal: reorganize likelihoods directory/submodule structure

### ISSUE THREAD

**Issue by st--** [GPflow/GPflow#1405]
Currently, there are two files in the likelihoods/ directory, `likelihoods.py` for almost all of them (almost 1000 lines) and `robustmax.py` (80 lines, only the RobustMax helper class for the MultiClass likelihood). I think re-grouping likelihood classes and splitting up the big `likelihoods.py` file would make it more maintainable and easier to add new likelihoods (e.g. we're already thinking about adding built-in support for heteroskedastic likelihoods).

This is the proposal I've come up with, I would appreciate further input and discussion before actually going and shuffling code around!

### Base classes: `base.py`
- `Likelihood`
- `ScalarLikelihood`
- `MonteCarloLikelihood`
- Q: should `SwitchedLikelihood` also go in here, as it only wraps other likelihoods?

#### Option 1: Subclasses of `ScalarLikelihood`: these could all go in one file `scalar_likelihoods.py`:
- `Gaussian`
- `Exponential`
- `StudentT`
- `Gamma`
- `Beta`
- `Poisson`
- Q: `Bernoulli` - here or into `classification.py` (see below)? It is classification but in terms of code logic/structure it is much more similar to the other ScalarLikelihoods (it is only parametrized by a single GP per observation dim and can easily broadcast over multiple outputs)

#### Option 2: Group by "type of likelihood", e.g.
`regression.py`:
- `Gaussian`
- `Exponential`
- `StudentT`
- `Gamma`
- `Beta`

Q: should `Poisson` and `Ordinal` go in here or into a different module `counts.py` / `discrete.py` ?

### Multi-class classification
`classification.py`? or be explicit and call it `multiclass_classification.py` (and definitely keep `Bernoulli` in another file)?
- `MultiClass` as well as the `RobustMax` helper
- `Softmax`
- Q: should `Bernoulli` go in here? this would make sense in terms of "classification", but in terms of code logic/structure it is much more similar to the other ScalarLikelihood subclasses (see above, Option 1)

### Discussion:
What other ways of structuring / grouping the different likelihoods can you think of?
What would be the advantages / disadvantages of the different options?
What (if anything) do you personally prefer (and how much do you care)?

**Comment by jameshensman** [comment]
Yes! This has needed sorting for a while. Happy to help.

I definite agree that we should have the base-classes separately. I’m not sure how to organise the rest but I kind of like the idea of regression/classification/count. I think it might help new users understand what the likelihood’s are for.

**Comment by markvdw** [comment]
I just noticed the added `ScalarLikelihood` class. Could I think of these as likelihoods that factorise over the dimensions of the output? I.e. they do allow vector outputs, but the likelihood just factorises?

**Comment by st--** [comment]
> I just noticed the added ScalarLikelihood class. Could I think of these as likelihoods that factorise over the dimensions of the output? I.e. they do allow vector outputs, but the likelihood just factorises?

Yes, that's exactly what a `ScalarLikelihood` is!

I guess we could combine both your and @jameshensman's points by having **Option 3**:
* `base.py`: Likelihood, MonteCarloLikelihood, SwitchedLikelihood
* `multiclass_classification.py`: MultiClass + RobustMax, Softmax
* `scalar_likelihoods/` subsubmodule...
  - `scalar_likelihoods/base.py`: ScalarLikelihood base class
  - `scalar_likelihoods/continuous.py`: Gaussian, StudentT, Exponential, Beta, Gamma
  - `scalar_likelihoods/discrete.py`: Bernoulli, Poisson, Ordinal

What do you think of that? or is that splitting things up too finely?
We could also have a flat directory structure, **Option 4**:
* `base.py`: Likelihood, MonteCarloLikelihood, SwitchedLikelihood, *ScalarLikelihood*
* `multiclass_classification.py`: MultiClass + RobustMax, Softmax (as before0
* `scalar_continuous.py`: Gaussian, StudentT, Exponential, Beta, Gamma
* `scalar_discrete.py`: Bernoulli, Poisson, Ordinal

Or `factorizing_continuous.py` and `factorizing_discrete.py` ...

**Comment by markvdw** [comment]
I'm happy with either. I don't see the need to split things up very finely, especially not into nested directories. So I'm for option 4.
