### ISSUE TITLE
Small noise_variance value leads to weird InvalidArgumentError exception

### ISSUE THREAD

**Issue by jjramsey** [GPflow/GPflow#1407]
Here's what should be a minimal, reproducible example:

```python
import numpy as np
import gpflow

x = np.linspace(0.0, 0.5)
y = np.sin(x) + 1e-2*np.random.standard_normal(x.shape)

# var_val = 1e-2
var_val = 1e-7

model = gpflow.models.GPR(data = (x,y),
                          kernel = gpflow.kernels.RBF(),
                          noise_variance = var_val)

gpflow.utilities.print_summary(model)
```

If the `noise_variance` argument in the above code is set to 1e-2, things work as expected, and I get the following result:

```
╒═════════════════════════╤═══════════╤══════════════════╤═════════╤═════════════╤═════════╤═════════╤═════════╕
│ name                    │ class     │ transform        │ prior   │ trainable   │ shape   │ dtype   │   value │
╞═════════════════════════╪═══════════╪══════════════════╪═════════╪═════════════╪═════════╪═════════╪═════════╡
│ GPR.kernel.variance     │ Parameter │ Softplus         │         │ True        │ ()      │ float64 │    1    │
├─────────────────────────┼───────────┼──────────────────┼─────────┼─────────────┼─────────┼─────────┼─────────┤
│ GPR.kernel.lengthscales │ Parameter │ Softplus         │         │ True        │ ()      │ float64 │    1    │
├─────────────────────────┼───────────┼──────────────────┼─────────┼─────────────┼─────────┼─────────┼─────────┤
│ GPR.likelihood.variance │ Parameter │ Softplus + Shift │         │ True        │ ()      │ float64 │    0.01 │
╘═════════════════════════╧═══════════╧══════════════════╧═════════╧═════════════╧═════════╧═════════╧═════════╛
```

However, if it is set to 1e-7, then I get the following traceback:

```
Traceback (most recent call last):
  File "./test.py", line 14, in <module>
    noise_variance = var_val)
  File "/Users/jjramsey/venvs/gpflow2/lib/python3.7/site-packages/gpflow/models/gpr.py", line 49, in __init__
    likelihood = gpflow.likelihoods.Gaussian(noise_variance)
  File "/Users/jjramsey/venvs/gpflow2/lib/python3.7/site-packages/gpflow/likelihoods/likelihoods.py", line 404, in __init__
    self.variance = Parameter(variance, transform=positive(lower=variance_lower_bound))
  File "/Users/jjramsey/venvs/gpflow2/lib/python3.7/site-packages/gpflow/base.py", line 82, in __init__
    unconstrained_value = self.validate_unconstrained_value(value, dtype)
  File "/Users/jjramsey/venvs/gpflow2/lib/python3.7/site-packages/gpflow/base.py", line 165, in validate_unconstrained_value
    return tf.debugging.assert_all_finite(unconstrained_value, message=message)
  File "/Users/jjramsey/venvs/gpflow2/lib/python3.7/site-packages/tensorflow_core/python/ops/numerics.py", line 67, in verify_tensor_all_finite_v2
    verify_input = array_ops.check_numerics(x, message=message)
  File "/Users/jjramsey/venvs/gpflow2/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 902, in check_numerics
    _ops.raise_from_not_ok_status(e, name)
  File "/Users/jjramsey/venvs/gpflow2/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: gpflow.Parameter: unconstrained value of passed value has NaN or Inf and cannot be assigned. : Tensor had NaN values [Op:CheckNumerics]
```

My software and hardware configuration are as follows:

* GPflow version: 2.0.0, from PyPI
* Tensorflow version: 2.1.0, from PyPI
* Tensorflow Probability version: 0.9.0, from PyPI
* Does your tensorflow use GPU: No
* Python version: 3.7.7
* OS: macOS 10.13.6 
* Macbook configuration: MacBook Pro (15-inch, 2017), Processor: 2.9 GHz Intel Core i7, Memory: 16 GB 2133 MHz LPDDR3, Graphics: Radeon Pro 560 4096 MB, Intel HD Graphics 630 1536 MB

**Comment by joelberkeley-pio** [comment]
I was also seeing this with variance `1e-6`

**Comment by st--** [comment]
I believe this may be due to the lower bound on the positive constraint in the likelihood. From the source:
```python
class Gaussian(ScalarLikelihood):
    r"""
    The Gaussian likelihood is appropriate where uncertainties associated with the data are
    believed to follow a normal distribution, with constant variance.
    Very small uncertainties can lead to numerical instability during the
    optimization process. A lower bound of 1e-6 is therefore imposed on the likelihood variance
    by default.
    """

    def __init__(self, variance=1.0, variance_lower_bound=1e-6, **kwargs):
        super().__init__(**kwargs)
        self.variance = Parameter(variance, transform=positive(lower=variance_lower_bound))
```
This ensures that the likelihood (noise) variance can only take values strictly larger than `variance_lower_bound`. This lower bound exists because if the noise variance is optimized to arbitrarily small numbers, the numerics become unstable. GPflow 1 had an implicit lower bound on the noise variance, i.e. you could *set* it to 1e-20, but it would still be 1e-6. In GPflow 2 we decided to explicitly error.

How could we improve documentation/behaviour to make this more obvious & self-explanatory?

**Comment by joelberkeley-pio** [comment]
> How could we improve documentation/behaviour to make this more obvious & self-explanatory?

I suggest we document it where it's possible to specify the `variance` but not the `variance_lower_bound`, e.g. in `GPR`. There's a bit explaining it in the docs for `Gaussian` which is good, perhaps it could be explicit in the `__init__`, sth like
```
        """
        :param variance: The variance of this Gaussian. Must be greater than
            ``variance_lower_bound``. 
        :param variance_lower_bound: The lower (exclusive) bound of ``variance``.
        :param kwargs: Keyword arguments forwarded to :class:`ScalarLikelihood`.
        :raise InvalidArgumentError: If ``variance`` is not greater than ``variance_lower_bound``.
        """
```

**Comment by jjramsey** [comment]
That may be a workaround, but it looks like something is wrong in the `Parameter` constructor. Take this code for example:

```python
import gpflow
import tensorflow_probability as tfp

tfb = tfp.bijectors
lower_bound = 1e-6

# Should be Softplus + Shift
bijector = tfb.Chain([tfb.Shift(gpflow.utilities.to_default_float(lower_bound)), tfb.Softplus()])

x_in = 1e-7
x_out = bijector.forward(x_in)

print("x_in = {}".format(x_in))
print("x_out = {}".format(x_out))
print("bijector.inverse(x_out) = {}".format(bijector.inverse(x_out)))
```

The output of this is as one would expect, with the bijector apparently successfully doing its job:
```
x_in = 1e-07
x_out = 0.6931482305599465
bijector.inverse(x_out) = 1e-07
```

However, if I try to make a GPFlow parameter from `x_in` and the bijector, then I get about the same traceback as before:

```python
Traceback (most recent call last):
  File "test2.py", line 18, in <module>
    x_param = gpflow.base.Parameter(x_in, transform = bijector)
  File "/Users/jjramsey/venvs/gpflow2/lib/python3.7/site-packages/gpflow/base.py", line 82, in __init__
    unconstrained_value = self.validate_unconstrained_value(value, dtype)
  File "/Users/jjramsey/venvs/gpflow2/lib/python3.7/site-packages/gpflow/base.py", line 165, in validate_unconstrained_value
    return tf.debugging.assert_all_finite(unconstrained_value, message=message)
  File "/Users/jjramsey/venvs/gpflow2/lib/python3.7/site-packages/tensorflow_core/python/ops/numerics.py", line 67, in verify_tensor_all_finite_v2
    verify_input = array_ops.check_numerics(x, message=message)
  File "/Users/jjramsey/venvs/gpflow2/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 902, in check_numerics
    _ops.raise_from_not_ok_status(e, name)
  File "/Users/jjramsey/venvs/gpflow2/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: gpflow.Parameter: unconstrained value of passed value has NaN or Inf and cannot be assigned. : Tensor had NaN values [Op:CheckNumerics]
```

It looks like there's something in `Parameter`'s `validate_unconstrained_value` that leads to a false positive in the NaN check.

**Comment by joelberkeley-pio** [comment]
@jjramsey you've used `.forward` in your test, but the code uses `.inverse`, as the hidden unconstrained value on the `Parameter` will be the inverse of the bijector (I think)

**Comment by jjramsey** [comment]
Ah, you're right. The forward output of Softplus + Shift is constrained to be a value greater than Shift, so it corresponds to the constrained value. I got it backwards. Never mind.

**Comment by jjramsey** [comment]
> How could we improve documentation/behaviour to make this more obvious & self-explanatory?

At the very least, a bad value for the variance (or any other argument) should be filtered out at the earliest level. As a negative example, here's the current constructor for the Gaussian likelihood:

```python
    def __init__(self, variance=1.0, variance_lower_bound=1e-6, **kwargs):
        super().__init__(**kwargs)
        self.variance = Parameter(variance, transform=positive(lower=variance_lower_bound))
```

Even though `variance` is supposed to be greater than `variance_lower_bound`, there's no check that this is the case. Instead, the constructor should be something like this:

```python
    def __init__(self, variance=1.0, variance_lower_bound=1e-6, **kwargs):
        if variance <= variance_lower_bound:
            raise ValueError("Likelihood variance must be strictly greater than {}".format(variance_lower_bound))

        super().__init__(**kwargs)
        self.variance = Parameter(variance, transform=positive(lower=variance_lower_bound))
```

With this exception message, it's more obvious what the problem is and how to fix it.

Furthermore, the *value* of this lower bound should be documented. Ideally, it should be some constant in GPFlow that a user can query, maybe something like `gpflow.config.default_noise_variance_lower_bound()`.

**Comment by st--** [comment]
> Furthermore, the _value_ of this lower bound should be documented. Ideally, it should be some constant in GPFlow that a user can query, maybe something like `gpflow.config.default_noise_variance_lower_bound()`.

There is actually `gpflow.config.default_positive_lower_bound()` (which by default is 0, and explicitly overridden by the `variance_lower_bound` in `Gaussian()`). I'm a bit hesitant to add more specific configurables - should this be default_gaussian_likelihood_noise_variance? or should it apply to e.g. StudentT as well (but in what way - it's not _exactly_ comparable)? What's the value of making this lower bound configurable - if you are thinking about the lower bound, you can also set it manually on the concrete parameters?

**Comment by st--** [comment]
I think the Parameter.assign() check is important, as TFP has quite subtle behaviour around invalid values passed through bijectors. Note the difference between
```python
import gpflow
pos = gpflow.utilities.positive(lower=1e-6)
print(pos.forward(pos.inverse(1e-10)).numpy())  # -> "1e-10"
print(pos.forward(pos.inverse(1e-10) + 0.0).numpy())  # -> "nan"
```
because the bijectors do caching on tensor identity. It's easy to accidentally end up with `nan` or `-inf` in the unconstrained_variable representation, at which point your optimizer is either going to behave weirdly or at the very least not optimize your parameter even though it is set trainable (as inf or nan minus any finite gradient is still inf or nan!).

I think it's better to fail earlier - which is why I clarified the error message on this check (see [#1408](https://github.com/GPflow/GPflow/pull/1408/files#diff-e2281e00a6a807545fc8c393630c5c36R162)); please let me know if that error message would have made it easier for you to debug yourself or how we could phrase it even better. I've also included your suggestion of explicitly checking in the `Gaussian` constructor.

**Comment by jjramsey** [comment]
> What's the value of making this lower bound configurable - if you are thinking about the lower bound, you can also set it manually on the concrete parameters?

It's less about making it configurable and more about guarding against changes in the lower bound on *your* end, a way of avoiding ["magic numbers"](https://en.wikipedia.org/wiki/Magic_number_(programming)). The lower bound doesn't *need* to be in `gpflow.config` per se; that was just for the sake of having a concrete example. I don't really care much if it's configurable; I only care about being agnostic as to the lower bound's exact value.

If I have a script that reads
```python
noise_variance = (noise_var_init_est if noise_var_init_est > 1.1e-6 else 1.1e-6)
```
in order to ensure that my initial value for the noise variance doesn't encroach on the lower bound that GPFlow has set for that variance, then I've essentially hardcoded the assumption that GPFlow will always have a lower bound less than 1.1e-6, an assumption that may change in the future. Such code would be brittle if later editions of GPFlow were to *increase* that lower bound.

However, if I can have code roughly like this,
```python
noise_variance = (noise_var_init_est 
                  if noise_var_init_est > 1.1*gpflow.NOISE_VAR_LB
                  else 1.1*gpflow.NOISE_VAR_LB)
```
then I'm no longer hardcoding an assumption about the value of the lower bound of the noise variance in GPFlow. There's also a bit of self-documentation there as well; it's more obvious that this code is hedging against a lower bound set by GPFlow itself, rather than user's own guestimate of what a good lower bound should be.

Note that I don't care that much if the constant in question is called `gpflow.NOISE_VAR_LB`. It could even be a class constant like, say, `gpflow.likelihoods.Gaussian.default_variance_lower_bound`.

> I think the `Parameter.assign()` check is important

Of course, there's no reason for it to go away. It's certainly useful as a guard against bugs. However, it is no substitute for a check at a higher level that indicates the reason for a problem. The following error message, which would be from the `Parameter.assign()` check, still leaves me guessing as to the reason for a problem:

> "`gpflow.Parameter`: the value to be assigned is incompatible with this parameter's transform (the corresponding unconstrained value has NaN or Inf) and hence cannot be assigned."

At this point, I don't know *why* the value is incompatible with this parameter's transform. I might not even be sure what this "transform" even *means* at this point. It's an error message that suggests a weird bug that involves getting into the weeds of GPFlow's internals, not something that's trivially solvable. 

On the other hand, if I see an error message like, "Argument `noise_variance` must be strictly greater than `gpflow.NOISE_VAR_LB (= 1e-6)`", then I have a *far* clearer idea of where the problem lies.

**Comment by st--** [comment]
> It could even be a class constant like, say, gpflow.likelihoods.Gaussian.default_variance_lower_bound.

Great idea! Hadn't thought of that :+1: 

> I'd say that as a general rule, invalid user input to a constructor should be rejected directly by that constructor, rather than passing it along to other constructors. That way, when the constructor sees invalid input, it can report an intelligible error message that explains why the input is invalid and how to fix it.

Yes, I agree, where we don't do that already and can easily do it, we definitely should! (If you're already aware of more places in our codebase where that might apply, it'd be great if you could contribute a pull request to improve it!)

I've tried to incorporate all your feedback in #1408 , could you check the changes there please and see if there's anything I missed, or whether you can think of better ways of phrasing messages etc.?

**Comment by jjramsey** [comment]
I think that looks like it's on about the right track.

**Comment by st--** [comment]
Hi @jjramsey, I hope you are satisfied with the resolution of your issue - please let us know if not, or if you've got any further feedback! Thanks for helping us improve GPflow :+1:
