### ISSUE TITLE
GPflow.org is out of date (suggests gpflow would work with python 3.5)

### ISSUE THREAD

**Issue by fonnesbeck** [GPflow/GPflow#1409]
When installing GPflow from master on Python 3.5 (Windows), I get a syntax error as shown here:

![image](https://user-images.githubusercontent.com/81476/78284294-ceda4d00-74e4-11ea-81ab-f294d3a8abd8.png)

I assume this is an f-string issue?

## Relevant information:
    * GPflow version: current master
    * Tensorflow version: 2.1.0
    * Does your tensorflow use GPU or not: no
    * Python version: 3.5
    * OS: Windows

**Comment by st--** [comment]
As noted in the intro (https://github.com/GPflow/GPflow/#what-does-gpflow-do), GPflow no longer supports python 3.5. The minimum required version is 3.6. Would it be helpful to make this clearer? How else should we point this out?

**Comment by fonnesbeck** [comment]
Ah, right. Perhaps update gpflow.org, which is where I checked first. It still says 3.5.

**Comment by st--** [comment]
Oh, I was completely unaware of that! Many thanks for bringing that to our attention!

**Comment by st--** [comment]
I've just updated gpflow.org - it should all be up to date for now.

**Comment by st--** [comment]
Thanks for bringing this to our attention! (personally I think most developers only ever look straight at github so it's easy to fall out of our minds...)
