### ISSUE TITLE
Feature request: a consistent way to get the number of model parameters for model selection, such as BIC

### ISSUE THREAD

**Issue by yiwei-prowler** [GPflow/GPflow#1415]
Given a model, it would be nice if there is a consistent way to get the number of model parameters that should be entered into the BIC formula.

For now, what needs to be done is:
1. for GPR, VGP, this is the number of trainable parameters.
2. for SGPR, SVGP, this is the number of trainable parameters - number of inducing points. And there is no common parent for these two classes either, the `inducing_variable` field are introduced twice, once in SGPR, onces in SVGP.

The client code needs to rely on object test to decide how to compute the number of parameters used for BIC. 

We should not see object test in a good OO software.

**Comment by awav** [comment]
GPflow provides granular enough interfaces for tackling this task (BIC formula). You can get trainable parameters and variables; you can count how many of them for a specific model (with inducing points) using type information.

> And there is no common parent for these two classes either

Could you clarify this point? GPR, VGP, SGPR and SVGP are different type of models, and they all have a parent class. What kind of common parent would you expect for SGPR and SVGP to have? If they had the same parent, it would not address your question anyway.

**Comment by yiwei-prowler** [comment]
I would like to compute the number of parameters for BIC without using object type test. So this is not what I want to do:
```
if isinstance(model, GPR):
   ...
elif isinstance(model, SVGP):
   ...
```
I don't want to use object type test because is is not good OO design. Sometimes we have to, but I will be very concerned every time we have to use object type test to implement something.

If you can show me how to implement BIC parameter counting without object type test, that would be super.

**Comment by yiwei-prowler** [comment]
To clarify, I meant that if `inducing_variable` is in GPModel, and it returns an empty list for sparse models, such as GRP, and returns the actual inducing variables for sparse models. 

This way, we can solve the problem described here -- we let the inheritance and  polymorphism work for us, instead of us using object type test.

**Comment by st--** [comment]
`inducing_variable` should not be part of `GPModel`. GPflow does not yet do as good a job as it could with respect to decoupling model and posterior approximation, but moving `inducing_variable` into the `GPModel` base class is not the right thing to do. In any case, just considering `inducing_variable` parameters is not actually giving you the answer you want - for BIC, you should also exclude the other variational parameters (e.g. q_mu, q_sqrt for VGP, and q_mu, q_sqrt, inducing_variable for SVGP). I would not be opposed to including some kind of `num_hyperparameters` property or some other way of distinguishing non-variational from variational parameters. Perhaps we should hear other people's thoughts on the best design.

I would then encourage you to contribute to the code, too, and to prepare a pull request with the required changes. GPflow is a community project - the GPflow maintainers do not have enough capacity to add all requested features ourselves!

**Comment by awav** [comment]
@yiwei-prowler following OOP for the sake of it doesn't look right here. Same request could be made for TensorFlow or PyTorch asking them to provide a number of parameters for Module structure.

You have all ingredients in place to implement an extendable approach for counting parameters for BIC. You could simulate functional pattern matching using dispatch or factories from OOP patterns.

Injecting this feature in GPflow (or TF, or Pytorch) because of the single use-case is the wrong action, and, in my opinion, it should be the other way around.

I don't think that this feature is implementable or will be implemented in the future in GPflow. I suggest closing it and if @yiwei-prowler has ideas on how to implement it, he always can open a PR with a prototype.
