### ISSUE TITLE
Gast Problem appears to have resurfaced

### ISSUE THREAD

**Issue by lordfiftyfive** [GPflow/GPflow#1422]
I first pip installed tensorflow 2.1 before pip installing gplflow 2.0

When I try to import gpflow i get this error

\ContextualVersionConflict: (gast 0.3.3 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('gast<0.3,>=0.2.2'), {'gpflow'})

It seems that the version of gast that tensorflow uses and the version gpflow uses are different. I noticed that it was said that this problem only surfaces if tensorflow is not already installed so I am a bit confused as to why it is giving me this error given that I had installed tensorflow 2.1 before trying to install gpflow.

**Comment by st--** [comment]
Hi @lordfiftyfive, the requirements for gast given by gpflow are correct - tensorflow 2.1 requires gast 0.2.2 and won't work with gast 0.3.3. This appears to be an issue with your python environment, not gpflow; as such, could you please post it on stackoverflow and tag it python / tensorflow? Thanks!

**Comment by st--** [comment]
Hi @lordfiftyfive, if you've got any further system information that would allow us to help you, please feel free to re-open this issue. (As it stands, I'm afraid I can't see anything that we could do about it!)
