### ISSUE TITLE
Matplotlib import problem with simple coregionalization notebook

### ISSUE THREAD

**Issue by jjramsey** [GPflow/GPflow#1423]
In the notebook ["A simple demonstration of coregionalization"](https://github.com/GPflow/GPflow/blob/develop/doc/source/notebooks/advanced/coregionalisation.pct.py), Matplotlib is imported in a way that *looks* like it should work, but doesn't:

```python
import matplotlib
plt = matplotlib.pyplot
```
In version 3.1.3 of Matplotlib, that second line, `plt = matplotlib.pyplot`, leads to an error with the message "`AttributeError: module 'matplotlib' has no attribute 'pyplot'`."

However, changing the import statement to the following (and of course, getting rid of the assignment to `plt`) does work:

```python
import matplotlib.pyplot as plt
```
However, for the notebook in question, `matplotlib.rcParams["figure.figsize"] = (12, 6)` has to be changed to `plt.rcParams["figure.figsize"] = (12, 6)`.

After the notebook is tweaked with the changes described above, it runs just fine.

**Comment by st--** [comment]
Thanks for bringing this to our attention! Sounds like you found not just the bug, but already the solution - so I'd encourage you to simply make these changes in your own fork of GPflow, and then to open a pull request into the GPflow develop branch - it's quite simple (easier than writing up an issue report, I find...), happy to help you out if you want:)
