### ISSUE TITLE
conditionals.util.sample_mvn should use a boolean to specify a full covariance matrix

### ISSUE THREAD

**Issue by johnamcleod** [GPflow/GPflow#1447]
# Feature request

There are many places in GPFlow which need to specify whether to use a "full" covariance matrix or just a diagonal covariance matrix. This is handled in most places with a `bool`; where `True` we want a "full" covariance matrix, and where 'False` we want a diagonal covariance matrix.

There appears to be one function which expects the same dichotomy to be expressed with strings: `conditionals.util.sample_mvn`. This function accepts a string argument which must take one of two values: "full" or "diag". 

## Motivation

I like consistency. 

## Proposal

**Describe the solution you would like**
I propose that this function should also use the established convention of a boolean "full_cov" to choose whether to return a full covariance matrix or a diagonal covariance matrix.

**Are you willing to open a pull request?** (We really appreciate contributions!)
Yes

**Comment by st--** [comment]
Resolved by #1448
