### ISSUE TITLE
Tracking model parameters during optimisation using Scipy

### ISSUE THREAD

**Issue by vr308** [GPflow/GPflow#1449]
# Documentation/tutorial notebooks

*Is there anything missing in the docs?* Yes 

*Are there any mistakes in the docs?* - No 

*Is there a feature that needs some example code in a notebook?* - Yes

There should be an example of how to track the evolution of variational parameters by utilizing the callback argument in  scipy minimize. It is not clear how to extract the state of the variables from the gplvm object. 

Using the snippets below in the GPLVM notebook just prints the gplvm object which is an numpy.ndarray which has the state of the trainable variables concatenated together ...ideally I want to be able to extract the trainable variable by name ...as I dont know the order in which they are stored.

```
def tracker(gplvm):
    print (gplvm)
    
opt = gpflow.optimizers.Scipy()
maxiter = ci_niter(10)
_ = opt.minimize(
    gplvm.training_loss,
    method="BFGS",
    variables=gplvm.trainable_variables,
    options=dict(maxiter=maxiter, disp=True),
    callback= tracker
)

```

*Do you know how to fix the docs?* If so, it'd be amazing if you'd be willing to directly contribute a pull request :)

Once I work out how to do, will be happy to do so.

Links:
* [latest GPflow documentation](https://gpflow.readthedocs.io/en/develop/)
* [latest GPflow tutorial notebooks](https://gpflow.readthedocs.io/en/develop/notebooks_file.html)

**Comment by awav** [comment]
Hello @vr308! Thanks for the reported issue with documentation.

We have a docstring for the scipy's minimize method [here](https://github.com/GPflow/GPflow/blob/develop/gpflow/optimizers/scipy.py#L36) and we have a usage example in notebook [here](https://github.com/GPflow/GPflow/blob/develop/doc/source/notebooks/theory/FITCvsVFE.py#L158). I do agree that the notebook is hard to find and the scipy docstring could be better.

The simplest example of using `step_callback`:

```python
def step_callback(step, variables, values):
    print(f"Step {step}: variables{[v.numpy() for v in variables]}")

model = ...  # Create a GPR model
Scipy().minimize(model.training_loss, model.training_parameters, step_callback=step_callback)
```

Do you think the example above in the docstring will help in the future to understand how progress tracking works in scipy? The alternative would be a dedicated notebook. That will require bigger effort and you can help with it by initiating a PR, collecting use cases for scipy optimisation in a notebook file.

**Comment by vr308** [comment]
Thanks! This is helpful..

I am doing the following for preserve the trace of kernel lenghtscales ...turns out it is much easier to extract from the model than from the variables/values or am I missing something...
```
ls = []

# Extracting from values vs. from model
def step_callback(step, variables, values):
    print( 'Legthscales: ' + str(gplvm.kernel.lengthscales.numpy()))
    print( 'Legthscales: ' + str(values[3].numpy()))
    ls.append(gplvm.kernel.lengthscales.numpy())
    
    
opt = gpflow.optimizers.Scipy()
maxiter = ci_niter(10)
_ = opt.minimize(
    gplvm.training_loss,
    method='BFGS',
    variables=gplvm.trainable_variables,
    options=dict(maxiter=maxiter, disp=True), 
    step_callback = step_callback
)
```
I think amending the docstring in the notebook will be sufficient to get the idea.

**Comment by awav** [comment]
> I am doing the following for preserve the trace of kernel lenghtscales ...turns out it is much easier to extract from the model than from the variables/values or am I missing something...

That's a good point. You can do that. I will add it to the docstring as well. Thanks!

**Comment by st--** [comment]
Ideally the gpflow.monitor tools (such as the ModelToTensorBoard) would cooperate with the Scipy optimizer. That worked in GPflow 1, but we may have to put a bit more work into it to get it to work again!

**Comment by st--** [comment]
@vr308 thanks to @vatsalaggarwal 's contribution in #1642 you can now use the gpflow monitoring tools just as easily with the Scipy optimizer as with custom optimization loops using TensorFlow optimizers. Simply pass the `monitor` object as the `step_callback` argument to the Scipy().minimize() method. Let us know if you've got any further questions/issues around this!
