### ISSUE TITLE
`_kill_autoflow()` fails in Python 3

### ISSUE THREAD

**Issue by markvdw** [GPflow/GPflow#148]
When using Python 3, `_kill_autoflow()` fails with the following error:
```
Traceback (most recent call last):
  File "gpf.py", line 10, in <module>
    m._needs_recompile = True
  File "/Users/markvdw/Documents/projects/GPflow/GPflow/param.py", line 599, in __setattr__
    self._kill_autoflow()
  File "/Users/markvdw/Documents/projects/GPflow/GPflow/param.py", line 608, in _kill_autoflow
    for key in self.__dict__.keys():
RuntimeError: dictionary changed size during iteration
```

Code to generate.
```
m = GPflow.gpr.GPR(d.X[:100, :], d.Y[:100, :], GPflow.kernels.RBF(d.X.shape[1]))
m._compile()
m.predict_f(d.X[100:200, :]);
m._needs_recompile = True
```

It looks like something has changed regarding how `self.__dict__` handles the deletion of objects during a loop. Probably something like `keys()` returning an iterator instead of a static list or something...

The fix is super easy. Just create a list with the keys, copied from the dict `keys()` iterator.

I.e. `for key in list(self.__dict__.keys()):` instead of `for key in self.__dict__.keys():`

I'll submit a pull request.

**Comment by markvdw** [comment]
Oh wow, I just saw @jameshensman 's pull request, which already does this.

**Comment by jameshensman** [comment]
fixed in #137 I think. Have assigned you, please have a look and click 'merge', perhaps with a squash commit, available from the drop-down)

**Comment by jameshensman** [comment]
Ha. Simultaneous commenting. If you don't have permissions to merge (I think you should) let me know and I'll fix.

**Comment by markvdw** [comment]
Done!

**Comment by jameshensman** [comment]
Marvellous, thanks.
