### ISSUE TITLE
Coregionalization with heteroscedastic errors

### ISSUE THREAD

**Issue by doccosmos** [GPflow/GPflow#1484]
Under GPflow 1.5.1, I was able to construct a coregionalized kernel with HeteroskedasticGaussian likelihoods by following the two tutorials on this. However, now upgrading to GPflow 2.0.4, the code no longer works. I have followed the upgrade guidelines but it appears that I can no longer use SwitchedLikelihood with HeteroskedasticGaussian that just extends Likelihood but rather needs to extend ScalarLikelihood. 

If I then set num_latent_gps = 1 in VGP (as per the HG tutorial):

m = gpflow.models.VGP((X_augmented, Y_augmented), kernel=kern, likelihood=lik, num_latent_gps = 1)

I get:

super().__init__(latent_dim = 1, observation_dim = 2, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/gpflow/likelihoods/base.py", line 310, in __init__
    super().__init__(latent_dim=None, observation_dim=None, **kwargs)
TypeError: __init__() got multiple values for keyword argument 'latent_dim'

Correcting for this gives other issues so I'm wondering what the best advice now is for combining HeteroskedasticGaussian with Coregion?

**Comment by st--** [comment]
Hi @doccosmos, thanks for your interest in GPflow and reporting your issues! To help us investigate what's going on, could you please complete your minimal example so that it is self-contained and we can run it (and reproduce your bug) by copy&pasting (see https://stackoverflow.com/help/minimal-reproducible-example for more details)? Thanks!

**Comment by st--** [comment]
@doccosmos if this is indeed a bug in GPflow we'd be happy to look into fixing this - however, without a reproducible example of your issue this isn't feasible for us. Please do re-open this if you're able to provide more details! Thanks:)
