### ISSUE TITLE
pickle and active_dims

### ISSUE THREAD

**Issue by mauinz** [GPflow/GPflow#149]
Hi All,

Thanks for implementing the getters and setters for pickle, makes saving experiments much easier! However I noticed a small bug, if you have active_dims set in the kernel it stops pickle from working since the active dimensions are stored as tf.constants.

example code to reproduce bug:

```python
X = np.random.randn(100).reshape((10,10))
y = np.random.randn(10)

k = GPflow.kernels.RBF(len(X[0]), active_dims=[0])
m = GPflow.gpr.GPR(X, y[:, np.newaxis], k)
```

Best,
Matt

**Comment by jameshensman** [comment]
Thanks for the report @mauinz, we're glad you're using GPflow. 

I fixed this in #151 . You can use that branch for the moment, until one of the other GPflowers admits the changes. I wrote a test that covers that case, so it shouldn't happen again, but it would be great if you could check that it works for you.
