### ISSUE TITLE
Parameter with (e.g. positive) transform has unintuitive behaviour at edge of domain

### ISSUE THREAD

**Issue by elvijs** [GPflow/GPflow#1497]
# Models can predict despite invalid parameter values

It is possible for the optimiser to take a model's parameters to a pathological region. When that happens, the user is not protected against making predictions using known pathological values. 

Moreover, the learned parameters can lead to an exception when attempting to use in a new model.

## To reproduce, run the following

```python
import gpflow
import numpy as np


def kaboom():
    effective_zero = 1e-6

    x = np.arange(10.).reshape(-1, 1)
    y = np.arange(10.).reshape(-1, 1)
    model = gpflow.models.GPR(data=(x, y), kernel=gpflow.kernels.RBF())
    # model.likelihood.variance.assign(effective_zero) explodes with the following error
    # 'gpflow.Parameter: the value to be assigned is incompatible with this parameter's transform
    # (the corresponding unconstrained value has NaN or Inf) and hence cannot be assigned.'
    # That's a good thing!
    # 1e-6 is the "effective zero" in GPflow for the Gaussian likelihood variance,
    # so users should not be allowed to assign it to params.

    # CG happily takes us to a "severely overfit" region as can be seen by the model summary
    # Interestingly, it seems to even take the variance to 1e-6, which should be invalid!
    optimiser = gpflow.optimizers.Scipy()
    optimiser.minimize(
        closure=model.maximum_log_likelihood_objective,
        variables=model.trainable_variables,
        method="CG",
        options=dict(maxiter=100),
        tol=effective_zero/100,  # Key! No blowup without this line.
        # We need to ensure we get sufficiently close to the effective zero.
    )
    assert model.likelihood.variance.numpy() == effective_zero

    # Despite the pathological value of the likelihood variance,
    # I can still use the model to predict y (badly!!)
    prediction = model.predict_y(x)
    print(f"Mean predictions for x: {prediction[0].numpy().T}")
    print(f"Variance predictions for x: {prediction[1].numpy().T}")

    # A side-effect of the naughtiness: if I extract parameters from the trained model,
    # they are actually invalid for a new model.
    learned_parameters = gpflow.utilities.read_values(model)
    new_model = gpflow.models.GPR(data=(x, y), kernel=gpflow.kernels.RBF())
    print("Let's assign the values that the old model is happily providing to us to a new model")
    gpflow.utilities.multiple_assign(new_model, learned_parameters)  # KABOOM!


if __name__ == '__main__':
    kaboom()
```

**Stack trace:**
```
Mean predictions for x: [[0.00000000e+00 2.82804157e-43 5.65608314e-43 8.48412471e-43
  1.13121663e-42 1.41402079e-42 1.69682494e-42 1.97962910e-42
  2.26243326e-42 2.54523741e-42]]
Variance predictions for x: [[1.e-06 1.e-06 1.e-06 1.e-06 1.e-06 1.e-06 1.e-06 1.e-06 1.e-06 1.e-06]]
Let's assign the values that the old model is happily providing to us to a new model
Traceback (most recent call last):
  File "/home/elvijs/.PyCharmCE2019.2/config/scratches/scratch_9.py", line 46, in <module>
    kaboom()
  File "/home/elvijs/.PyCharmCE2019.2/config/scratches/scratch_9.py", line 42, in kaboom
    gpflow.utilities.multiple_assign(new_model, learned_parameters)  # KABOOM!
  File "/home/elvijs/.virtualenvs/automl_res/lib/python3.7/site-packages/gpflow/utilities/utilities.py", line 67, in multiple_assign
    reference_var_dict[path].assign(value)
  File "/home/elvijs/.virtualenvs/automl_res/lib/python3.7/site-packages/gpflow/base.py", line 191, in assign
    unconstrained_value = self.validate_unconstrained_value(value, self.dtype)
  File "/home/elvijs/.virtualenvs/automl_res/lib/python3.7/site-packages/gpflow/base.py", line 166, in validate_unconstrained_value
    return tf.debugging.assert_all_finite(unconstrained_value, message=message)
  File "/home/elvijs/.virtualenvs/automl_res/lib/python3.7/site-packages/tensorflow_core/python/ops/numerics.py", line 67, in verify_tensor_all_finite_v2
    verify_input = array_ops.check_numerics(x, message=message)
  File "/home/elvijs/.virtualenvs/automl_res/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 902, in check_numerics
    _ops.raise_from_not_ok_status(e, name)
  File "/home/elvijs/.virtualenvs/automl_res/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: gpflow.Parameter: the value to be assigned is incompatible with this parameter's transform (the corresponding unconstrained value has NaN or Inf) and hence cannot be assigned. : Tensor had Inf values [Op:CheckNumerics]
```

## Expected behavior

I expected the model to explode at predict-time after the parameters had been optimized to a pathological region.

I'd also like `gpflow.utilities.read_values` to explode when the contained values are actually invalid - that way I cannot accidentally assign the invalid values to a new model. This use-case is actually where I first noticed the issue.

## System information

* GPflow version: 2.0.4
* GPflow installed from: `pip install gpflow==2.0.4`
* TensorFlow version: 2.1.0
* Python version: 3.7.5
* Operating system: Ubuntu

**Comment by st--** [comment]
Why (or perhaps how) would you expect the model to "explode" at predict-time? I don't think it'll be at all possible to avoid a situation where after optimisation the unconstrained value is highly negative, corresponding to (effectively) the lower bound in the constrained space, such that it is indistinguishable from the invalid constrained value of exactly the lower bound. If you've got suggestions for how to improve the situation I'd love to hear. Just be aware that this is a more fundamental problem than just a bug in gpflow, and we won't be able to guard against *all* errors - in the end you'll still need some understanding of what's actually going on to make use of GPflow..

**Comment by elvijs** [comment]
> Why (or perhaps how) would you expect the model to "explode" at predict-time? 

To me that seems closer to the principle of ensuring that errors don't pass silently. The model admits itself to be mutated in a way that makes it invalid (0 variance makes no sense), so it should tell the users that as early as possible. In this case, my model exploded somewhere in a backtest loop way after the invalid model's training and it took me a while to reproduce.

Some ideas for improvement:
* Really, I'd love to address the root cause and disallow the model mutation to make models invalid. Is there any way of telling Scipy/TF optimisers to respect the constraints when the constraints define an open interval? Maybe `gpflow.Parameter` can intercept value assignment from the optimisers and ensure they're checked?
* Alternatively, accept that optimisers render model parameters effectively invalid and add some checks to be run before users can interact with the public methods?
* If neither of the above is workable, let the users know that this may happen and tell them what exception they can expect, so they know what they should be catching and handling?

**Comment by st--** [comment]
```python
def check_model_makes_sense(m):
    try:
        gpflow.utilities.multiple_assign(k, gpflow.utilities.read_values(k))
    except tf.InvalidArgumentError:
        return False
    return True
```
