### ISSUE TITLE
'SVGP' object has no attribute 'training_loss_closure'

### ISSUE THREAD

**Issue by DennisReddyhoff** [GPflow/GPflow#1499]
I am trying to follow a tutorial in the readthedocs guide, but I am getting an error that SVGP has no attribute training_loss_closure. From what I have read it is supposed to inherit it from ExternalDataTrainingLossMixin

```
from gpflow.optimizers import NaturalGradient
from gpflow.models import SVGP
import numpy as np

Z = np.linspace(0,0.2,3)

svgp = SVGP(
    kernel=gpflow.kernels.Matern52(),
    likelihood=gpflow.likelihoods.Gaussian(),
    inducing_variable=Z,
)

svgp.training_loss_closure(data)
```

**Stack trace, or error message**
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-131-c51e957fc265> in <module>
     11 )
     12 
---> 13 svgp.training_loss_closure(data)

AttributeError: 'SVGP' object has no attribute 'training_loss_closure'
```

## System information

Running GPFlow 2.0.0rc1 in Python 3.

**Comment by st--** [comment]
You are using an outdated version of GPflow - please check with the latest release, which is 2.0.4 at the time of writing, which should be consistent with the documentation. If you are using `pip` for installation, you can upgrade using `pip install -U gpflow`.
