### ISSUE TITLE
documentation regarding training_loss() is confusing

### ISSUE THREAD

**Issue by irum** [GPflow/GPflow#1502]
I am using training_loss() inside tape.gradient but I am confused that whether we need to use closure inside tape.gradient or not.

**Comment by st--** [comment]
Without knowing more about what you mean by "weird behaviour" it's pretty much impossible to help you. We've added the issue templates for a reason - please provide a [minimal example](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces your issues.

Note that the SVGP model behaves slightly differently from the others - it doesn't store data inside, so its training_loss does take data. (This is documented in the training_loss docstring.)

**Comment by irum** [comment]
Hi, Thank you for your reply. I solved my problem but I should mention one thing that in the beginning of the documentation closure() is used with training_loss() function . Then in tape.gradient section it should be clearly mention that here we use this function without closure. As I was thinking how to use closure () inside  tape.gradient.

**Comment by st--** [comment]
It'd be great if you would contribute your suggested improvements directly as a pull request :) it's only people new to the code base who can point out where the documentation and tutorials are lacking clarity or depth!
