### ISSUE TITLE
Initial guesses for hyperparameters 

### ISSUE THREAD

**Issue by jwangjie** [GPflow/GPflow#1517]
Hi,

I found the initial guesses for hyperparameters by using `m.likelihood.variance.assign(0.01)` and `m.kernel.lengthscales.assign(0.3)` affects significantly to the final optimized hyperparameters. I was wondering if there is a method to get a good initial guess? For example, estimating using the dataset. Thanks.

**Comment by markvdw** [comment]
This is a common, and not completely trivial problem. [This distill article](https://drafts.distill.pub/gp/) has some pointers.

**Comment by jwangjie** [comment]
Thank you @markvdw for your quick reply, very much appreciate it.

**Comment by Atulsingh92** [comment]
Could someone please update the link to the distill article?
