### ISSUE TITLE
Hi, how could I access the value  the marginal likelihood or even better the log marginal likelihood of the a model, that I've allready traiend/optimized?

### ISSUE THREAD

**Issue by vadimus5** [GPflow/GPflow#1519]
Hi, how could I access the value of the marginal likelihood or even better of the log marginal likelihood of a trained/optimized model? I need it to evalute the models with BIC (bayesian information criterion)? The end goal is to evaluate a model with BIC. Thank you in advance!

**Comment by vadimus5** [comment]
Hi, how could I access the value  the marginal likelihood or even better the log marginal likelihood of the a trained model? I need it to evalute the models with BIC (bayesian information criterion)? The end goal is to evaluate a model with BIC. Thank you in advance!

**Comment by st--** [comment]
Hi @vadimus5, only the GPR model has an exact marginal likelihood. You can easily evaluate it using
`model.log_marginal_likelihood()`, where `model` is an instance of the `GPR` class. Note that we are aiming GPflow at people who are happy to skim the source code of a library - this should answer most questions. For "how do I ..." questions such as this one, please use stackoverflow.
