### ISSUE TITLE
How can I use GPflow 2.0 to implement spectral mixture (SM) kernel for multidimensional input?

### ISSUE THREAD

**Issue by Xiaodonghai** [GPflow/GPflow#1525]
Recently, I want to use GPflow2.0 to implement SM kernel and other custom kernel functions. The implementation of Brownian motion kernel function given in the official document seems simpler. Can you give me a better demo? Thank you for your help.

**Comment by vdutor** [comment]
Hi @Xiaodonghai, thanks for checking out GPflow! Given that your question is more a HOW-TO question, could you please repost it on [stackoverflow, using the GPflow tag](https://stackoverflow.com/tags/gpflow). We actively monitor questions asked on stackoverflow and will promptly answer it. Using stackoverflow for this type of questions is better as it makes it easier for other people to find the question/answers when they have similar problems.
