### ISSUE TITLE
GPflow on conda-forge

### ISSUE THREAD

**Issue by GuillemGSubies** [GPflow/GPflow#1534]
Right now the newest version is  1.3.0. Are there any plans of uploading newer versions to conda-forge? I would really appreciate it.

**Comment by st--** [comment]
Hi @GuillemGSubies, I didn't even know we had a package on conda-forge!
Could you explain the value you see in a conda-forge package? We are already maintaining the pip package - you can simply do `pip install gpflow` (and this should work just fine in a conda environment, too). What added value does the conda forge bring? (It's a trade-off against the cost of maintaining it!)

**Comment by GuillemGSubies** [comment]
In my company we use conda as a standard and we have a package that uses gpflow. So when trying to distribute it, not having a dependency available in conda, becomes a pain sometimes.

I did not know that you were not the maintainers of that conda-forge feedstock so I would understand if you cannot solve this issue.

Thanks you for the fast response

**Comment by st--** [comment]
Hi @GuillemGSubies, it looks like the gpflow conda-forge https://github.com/conda-forge/gpflow-feedstock actually has auto-generated PRs for updating to current GPflow versions: unfortunately, it looks like no-one of the maintainers is addressing them. You might want to get in touch with the conda-forge admins to sort this out - I'm afraid there's nothing we can do about it as GPflow maintainers! Happy to chat further on gpflow.slack.com (invite link in README.md) if you want to discuss what you might need to do to get the conda-forge package updated.
