### ISSUE TITLE
Make deepcopy functionality available to copy.deepcopy

### ISSUE THREAD

**Issue by joelberkeley-pio** [GPflow/GPflow#1538]
I am deep-copying models using `gpflow.utilities.deepcopy`. I'm also deep-copying other objects using `copy.deepcopy`. For simplicity, I'd like to be able to do both with `copy.deepcopy`. This may be possible by migrating the functionality in `gpflow.utilities.deepcopy` to a `__deepcopy__` implementation on `gpflow.base.Module`. I reckon the change can be backwards compatible by then aliasing `gpflow.utilities.deepcopy` to `copy.deepcopy`

**Are you willing to open a pull request?**

Yes, but I don't know when as I'm pretty busy

**Comment by st--** [comment]
This will be handled by tensorflow-probability's 0.12 release, which enables native deepcopy of bijectors. (See https://github.com/tensorflow/probability/pull/947#issuecomment-702403437). I just successfully tested it on tf[p]-nightly.
