### ISSUE TITLE
The v1.15 documentation link is broken

### ISSUE THREAD

**Issue by adamhall** [GPflow/GPflow#1546]
The v1.15 documentation link seems to be broken :(. It leads me to this page 

https://gpflow.readthedocs.io/en/v1.5.1-docs/ which does not exist.

**Comment by joelberkeley-pio** [comment]
Thanks for letting us know. By the way, we highly recommend using GPflow 2 rather than GPflow 1 if you can

**Comment by joelberkeley-pio** [comment]
Where did you find the broken link?

**Comment by adamhall** [comment]
It's on the GPflow main page in section [Install the last GPflow version compatible with TensorFlow 1:](https://github.com/GPflow/GPflow#install-the-last-gpflow-version-compatible-with-tensorflow-1).

I'm trying to use someone else's code and they use an older version of GPFlow (version 0.4.0!!!!) and am just trying to understand a couple things. Any chance you have a link to documentation for that version?

**Comment by joelberkeley-pio** [comment]
re 0.4.0, your best bet would be to checkout that version in the repository and look at/build the docs yourself from there. It's unlikely we have that version hosted anywhere

**Comment by st--** [comment]
@adamhall thanks again for reporting this! The v1.5.1-docs had disappeared when we improved our workflow and started using a separate repository to host the compiled notebooks. I've just fixed that, so https://gpflow.readthedocs.io/en/v1.5.1-docs/ is working again :+1: 
Re 0.4.0, as Joel already pointed out, best to see if you can build the docs from that version in the git history.
