### ISSUE TITLE
Multi-output GPR

### ISSUE THREAD

**Issue by shannon63** [GPflow/GPflow#1555]
Hi!

I was wondering if it is possible to do exact inference in GP regression with multiple output dimensions in GPflow.

Specifically, I would like to use a [shared independent multi-output kernel (MOK)](https://gpflow.readthedocs.io/en/master/notebooks/advanced/multioutput.html#1.-Shared-independent-multi-output-kernel-(MOK)-and-shared-independent-inducing-variables) but not with SVGP (and inducing variables) but with GPR.

Is this possible?

Thank you!

**Comment by st--** [comment]
Hi @shannon63, unfortunately the multi-output kernel framework doesn't work out of the box (as described in #1175), but you can get the same *effect* with the plain `GPR` model: just use a normal kernel, but provide a `Y` that has several columns, one for each output.
```python
import gpflow
k = gpflow.kernels.Matern52()
N, input_dim, output_dim = 13, 2, 5
X = np.random.randn(N, input_dim)
Y = np.random.randn(N, output_dim)
m = gpflow.models.GPR((X, Y), k)
```

**Comment by st--** [comment]
If you'd like a more detailed response please open a question on [StackOverflow (tag gpflow)](https://stackoverflow.com/tags/gpflow) and post the link here!
