### ISSUE TITLE
Heteroscedastic errors

### ISSUE THREAD

**Issue by Joshuaalbert** [GPflow/GPflow#1584]
Hey GPFlow folks,

I would like to address the feature of heteroscedastic errors.
I created the extension repo https://github.com/Joshuaalbert/heterogp some time ago back during GPFlow-1. 
I didn't really have time to maintain it, because I was finishing up a PhD.
I'm looking at it now and it seems rather trivial to implement heteroscedasticity in GPFlow without the need for an external repo.
There is just a small amount of logic that needs to be implemented, which I'll explain below.

# Feature request

Heteroscedastic errors is all to do with replacing the homogeneous `variance` parameter with a `DataHolder` that maps a vector of variances to the `X` that are being used (for either computing the marginal likelihood, or at inference time). This case is useful when measurement error uncertainties are known a priori. In principle, this just means that the prior for the measurement uncertainty is singular. Now, the logistical problem that needs to be overcome is the fact that the `Likelihood` owns the homogeneous variance parameter which is stored as a `Variable`. For heteroscedastic errors of known measurement uncertainty you want to forget about the `Likelihood`-owned `variance` and use in-place a `DataHolder` that is sychronised with the `X` `DataHolder`. 

So, what needs to be done?

- [ ] Enable passing extra `DataHolders` to all methods of the `Likelihood`.

- [ ] Have a flag in `Likelihood`'s constructor that says if it is using heteroscedastic errors, call it `heteroscedastic_errors:bool`.

- [ ] In the case `heteroscedastic_errors=True`, then expect another `DataHolder` in all `Likelihood` methods that contains the variances of the `X`. Call these `Y_var`. These are used as `diag(Y_var)` in place of the scalar `variance`. If this is unclear just consult RW, or ask here. 

- [ ] In the case `heteroscedastic_errors=False`, use the homoscedastic `variance` (times eye(X.shape[0])) parameter as is currently done.

- [ ] Add `heteroscedastic_errors:bool` to the `GPModel`. Just like the `Likehood`, each model method should expect a variable `*arg` list of `DataHolders` or numpy arrays if using `AutoFlow`.

- [ ] Just like the `Likelihood` methods, if `heteroscedastic_errors=True` then interpret the extra passed-in array as the diagonal of the observational variance that map to the `X_new`. 

# What's not covered by this implementation?

This will not address the case where the errors are not known. In this case the log-errors can be represented by another GP, but that would be something beyond the capacity of this addition to GPFlow. However, if you implement the above additions for singular observations errors then another repo (like mine if I update it) can come along and use the `DataHolder` and `heteroscedastic_errors=True` interface to inject a tensor of errors, which can be created by a higher up GP in the chain.

WDYT?

**Comment by st--** [comment]
Hi @Joshuaalbert , great to have you back! We've got two notebooks for heteroskedastic noise so far: https://gpflow.readthedocs.io/en/develop/notebooks/advanced/varying_noise.html and https://gpflow.readthedocs.io/en/develop/notebooks/advanced/heteroskedastic.html - could you clarify what your proposal would involve on top of this? (Btw- no more DataHolder in gpflow2! have you looked through the [upgrade guide](https://gpflow.readthedocs.io/en/develop/notebooks/gpflow2_upgrade_guide.html)?)

**Comment by Joshuaalbert** [comment]
Hi @st-- thanks. Those resources really highlight how much gpflow has grown in the past year or so. 
You've already implemented the functionality that I proposed about, in a better way.
I'll close this issue then. Also, there is one project I'm working on that would be interesting. Bayesian hyper parameter marginalisation using nested sampling. I've written a package in JAX which compiles the whole algorithm down to XLA and which can be exported to TF2 (experimental). I have very good results with it so far in combination with GPs.

**Comment by markvdw** [comment]
Hi @Joshuaalbert, that nested sampling sounds super interesting, I would love to hear about it. If you're interested to chat, send me an e-mail or find us on the GPflow Slack channel.

**Comment by Joshuaalbert** [comment]
Hey @markvdw I sent you an email.

**Comment by st--** [comment]
Pinging @frgsimpson who's also worked on using nested sampling for GPs.

@Joshuaalbert : the sign-up link is in the [GPflow readme](https://github.com/GPflow/GPflow/#slack-workspace)
