### ISSUE TITLE
Prettier Visualization in notebooks

### ISSUE THREAD

**Issue by mathDR** [GPflow/GPflow#160]
I want to tag this as "enhancement", but generically, I would replace the line:
```python
plt.plot(xx, mean + 2*np.sqrt(var), 'b--', xx, mean - 2*np.sqrt(var), 'b--', lw=1.2)
```
with a shaded version:
```python
plt.fill_between(xx[:,0], mean[:,0] - 2*np.sqrt(var[:,0]), mean[:,0] + 2*np.sqrt(var[:,0]), facecolor='blue', alpha=0.2)
```
I could submit a PR (as it is only a few lines of code to change), unless otherwise objected

**Comment by jameshensman** [comment]
Sure. We have a design decision not to 'support' plotting in GPflow. Plotting code gets messy and is hard to maintain. But plotting in the notebooks is fair game. 

Whilst you're there, might be worth making all the plotting consistent: I like to use `plt.style.use('ggplot')`. 

Oh, and the about-to-be-merged sphinx branch has changed the locations of the notebooks. might be worth starting from there, else there are going to be hellish merge conflicts inside ipynb files.

**Comment by mathDR** [comment]
Great!  I will start from the sphinx branch.  Hopefully a PR is
forthcoming...

**Comment by mathDR** [comment]
Okay this is all done.  I tried to submit a PR regarding the new plots, but (of course) I am denied.  Do you have a process of allowing for PR from non-core users?

**Comment by jameshensman** [comment]
Hi Dan, 

Our somewhat-unofficial process is to ask for PRs from remote repos first. If your first PR is all nice and tidy and you want to contribute more, we can give you permissions to push to branches in GPflow. 

Hope that sounds reasonable! We should probably document such a process somewhere, but we're playing it a little bit by-ear. 

To submit remotely, fork the project on github, commit to your fork and use github's PR button to ping it over to us.

**Comment by mathDR** [comment]
Okay, submitted a PR.  I don;t know what the merge conflict is (I think it has to to with the multiclass bug, but if that is the case, there were no changes against the sphinx multiclass.ipynb, so that one can be used)
