### ISSUE TITLE
Remove custom cast once we require TensorFlow >= 2.2

### ISSUE THREAD

**Issue by vdutor** [GPflow/GPflow#1601]
Hi @awav,
I stumbled upon this [TODO](https://github.com/GPflow/GPflow/blob/dda4adf361dbf54c3ca74808daec93d1de064463/gpflow/utilities/ops.py#L29) that is referencing your name. As we now have TF 2.3, do you reckon we can remove our custom cast method? Thanks

https://github.com/GPflow/GPflow/blob/dda4adf361dbf54c3ca74808daec93d1de064463/gpflow/utilities/ops.py#L29

**Comment by vdutor** [comment]
Hi @awav, can you have a look at this, please?

**Comment by st--** [comment]
Following discussion: we can remove cast() when we bump the minimum TensorFlow requirement of GPflow (currently 2.1).
