### ISSUE TITLE
Extend SVGP predict_f() and predict_y() to support predictions with samples from the inducing point distribution

### ISSUE THREAD

**Issue by aidanscannell** [GPflow/GPflow#1608]
# Feature request

It would be useful for me (and I assume others) if the functionality of `SVGP.predict_f` and `SVGP.predict_y `could be extended to draw samples from the inducing point variational distribution and call the standard GP conditional with these samples. Currently the methods analytically marginalise the inducing points (Gaussian convolution). 

## Motivation

When using the SVGP class in a Mixture of Experts lower bound (and probably other models) it is required to sample the inducing point variational distribution when calling `predict_f` and `predict_y` as they cannot be marginalised analytically. I can provide an example variational lower bound that requires this if the motivation is not clear.

## Proposal
I propose to add an extra argument (`num_inducing_samples`) to `predict_f` and `predict_y` that allows the behaviour to be switched.
1. If `num_inducing_samples=None` then the original behaviour is achieved (inducing points are analytically marginalised),
2. If `num_inducing_samples=N` then N samples are drawn from N(q_mu, q_sqrt q_sqrt.T) and the standard GP conditional is called for each sample (with `q_sqrt=None`). The predictions for each sample could then be stacked on the leading dimension of the returned mean and covariance.

**What alternatives have you considered?**

I have implemented this as a class that inherits SVGP which is what I am currently using and I have also extended GPflows SVGP class; I have opened a pull request  (#1609) and linked this issue. Below are the changes I propose.

- Add 1 new method to efficiently sample the inducing points variational distribution,
```python
def sample_inducing_points(self, num_samples: int = None) -> tf.Tensor:
    """Returns samples from the inducing point distribution.

    The distribution is given by,

    .. math::
        q \sim \mathcal{N}(q\_mu, q\_sqrt q\_sqrt^T)

    :param num_samples: the number of samples to draw
    :returns: samples with shape [num_samples, num_data, output_dim]
    """
    mu = tf.transpose(self.q_mu, [1, 0])
    q_dist = tfp.distributions.MultivariateNormalTriL(
        loc=mu,
        scale_tril=self.q_sqrt,
        validate_args=False,
        allow_nan_stats=True,
        name='InducingOutputMultivariateNormalQ')
    inducing_samples = q_dist.sample(num_samples)
    return tf.transpose(inducing_samples, [0, 2, 1])
```

- Edit the `predict_f` method - pass it an extra parameter (`num_inducing_samples`) that controls switching between analytically marginalising the inducing points and sampling them,
```python
def predict_f(self,
                Xnew: InputData,
                num_inducing_samples: int = None,
                full_cov: bool = False,
                full_output_cov: bool = False) -> MeanAndVariance:
    """"Compute mean and (co)variance of latent function at Xnew.

    If num_inducing_samples is not None then sample inducing points instead
    of analytically integrating them.

    :param Xnew: inputs with shape [num_test, input_dim]
    :param num_inducing_samples:
        number of samples to draw from inducing points distribution.
    :param full_cov:
        If True, draw correlated samples over Xnew. Computes the Cholesky over the
        dense covariance matrix of size [num_data, num_data].
        If False, draw samples that are uncorrelated over the inputs.
    :param full_output_cov:
        If True, draw correlated samples over the outputs.
        If False, draw samples that are uncorrelated over the outputs.
    :returns: tuple of Tensors (mean, variance),
        If num_inducing_samples=None,
            means.shape == [num_test, output_dim],
            If full_cov=True and full_output_cov=False,
                var.shape == [output_dim, num_test, num_test]
            If full_cov=False,
                var.shape == [num_test, output_dim]
        If num_inducing_samples is not None,
            means.shape == [num_inducing_samples, num_test, output_dim],
            If full_cov=True and full_output_cov=False,
                var.shape == [num_inducing_samples, output_dim, num_test, num_test]
            If full_cov=False and full_output_cov=False,
                var.shape == [num_inducing_samples, num_test, output_dim]
    """
    if num_inducing_samples is None:
        q_mu = self.q_mu
        q_sqrt = self.q_sqrt
        mu, var = conditional(Xnew,
                                self.inducing_variable,
                                self.kernel,
                                q_mu,
                                q_sqrt=q_sqrt,
                                full_cov=full_cov,
                                white=self.whiten,
                                full_output_cov=full_output_cov)
    else:
        q_mu = self.sample_inducing_points(num_inducing_samples)
        q_sqrt = None

        @tf.function
        def single_sample_conditional(q_mu):
            return conditional(Xnew,
                                self.inducing_variable,
                                self.kernel,
                                q_mu,
                                q_sqrt=q_sqrt,
                                full_cov=full_cov,
                                white=self.whiten,
                                full_output_cov=full_output_cov)

        # map each inducing point sample through the standard GP conditional
        mu, var = tf.map_fn(single_sample_conditional,
                            q_mu,
                            dtype=(default_float(), default_float()))
    return mu + self.mean_function(Xnew), var
```

The only change to `predict_y` is to accept `num_inducing_samples` as an argument and pass it to `predict_f`,
```python
def predict_y(self,
                Xnew: InputData,
                num_inducing_samples: int = None,
                full_cov: bool = False,
                full_output_cov: bool = False) -> MeanAndVariance:
    """Compute mean and variance at Xnew."""
    f_mean, f_var = self.predict_f(
        Xnew,
        num_inducing_samples=num_inducing_samples,
        full_cov=full_cov,
        full_output_cov=full_output_cov)
    return self.likelihood.predict_mean_and_var(f_mean, f_var)
```

**Comment by markvdw** [comment]
It certainly looks like you're doing interesting work!

For changes to GPflow, I'm generally of the opinion that we should keep the package as simple as possible, while enabling as much as possible. This is a trade-off, but essentially I believe that any enlargement of the codebase should be justified with enabling important new usecases.

In this case, I don't yet see
- new possibilities that are widely needed,
- why `SVGP` in particular needs to be modified, rather than (like you say) defining a child class.

For example, in a project I'm working on, I need to draw samples from the function posterior, and I chose to implement it through inheritance. Can you elaborate why this change in the GPflow core codebase is needed to enable you to do what you want?

**Comment by aidanscannell** [comment]
Hi Mark, thanks for the speedy response! 

Thinking about this in a bit more detail, I might have been a bit hasty opening a PR. I added this functionality to get extra stochasticity into my optimisation a while ago (and then forgot why it's there, woops) 😆 I do analytically marginalise the inducing points and like you say, needing to sample the latent function posterior is much more common. With this in my mind, I do not really think this functionality should be added to `SVGP`, so I will close the Issue/PR.

I am planning to opensource my project and it would be great if you link to it! A little bit of work is still needed though so maybe I'll get in touch when it's done. Cheers.

**Comment by st--** [comment]
@aidanscannell just make a PR to edit GPflow's README.md to add your project once it's ready!
