### ISSUE TITLE
RBF Kernel to perform even better in high dimensions

### ISSUE THREAD

**Issue by fabrang** [GPflow/GPflow#1610]
# Feature request

Optimizing in high dimensional input spaces requires well suited models. It seems that RBF kernels are the key to stack dimensions. 

## Motivation

I'm a researcher optimizing for high dimensional black-box problems and searching for a solid library for GP models. Yours look very good and I would like to integrate it in my work.

## Proposal

I would love to implement together with you guys the possibility to use RBF kernels for the GP-models. Looking forward to hearing from you

**Comment by vdutor** [comment]
Hi @fabrang, thanks for the kind words. In GPflow we already have an implementation for the RBF kernel. It is called the [Squared Exponential kernel](https://gpflow.readthedocs.io/en/master/gpflow/kernels/index.html#gpflow-kernels-squaredexponential). If you are interested in Bayesian Optimisation with GPflow, I would recommend having a look at [Trieste](https://github.com/secondmind-labs/trieste) - a very recent GPflow based Bayes Opt library. 

For now, I will close this issue as I don't think there is anything for us to implement. Feel free to re-open if that is not the case. Looking forward to see what you are going to build with GPflow :)
