### ISSUE TITLE
Perform distributed and GPU experiments

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#162]
I'm going to put together some experiments exhibiting the distributed and GPU abilities of GPflow.

**Comment by alexisboukouvalas** [comment]
@alexggmatthews would this cover performance? I am a bit concerned that we may be regressing performance (see recent issue you found with batch_mul) - is there a way to have an ongoing performance check similar to the code coverage check?

**Comment by alexggmatthews** [comment]
Hi @alexisboukouvalas yes I would like this too. See #170 . The problem with doing it as part of continuous integration is that a top end GPU can cost £900 so we don't have many lying around. The plan at the moment is to monitor it on a regular (say daily) test and that there is a script we can run when do anything that is likely to change speed. We would then submit the results with the relevant PR .
