### ISSUE TITLE
This version of TensorFlow Probability requires TensorFlow version >= 2.4; Detected an installation of version 2.3.0. Please upgrade TensorFlow to proceed

### ISSUE THREAD

**Issue by danielfllaneza** [GPflow/GPflow#1623]
`
<ipython-input-5-08466fb6b3b7> in <module>
----> 1 import gpflow
      2 import numpy as np
      3 import matplotlib.pyplot as plt
      4 
      5 import tensorflow as tf

~/miniconda3/lib/python3.7/site-packages/gpflow/__init__.py in <module>
     15 # flake8: noqa
     16 
---> 17 from . import (
     18     conditionals,
     19     config,

~/miniconda3/lib/python3.7/site-packages/gpflow/conditionals/__init__.py in <module>
      1 # noqa: F401
      2 
----> 3 from . import conditionals, multioutput, sample_conditionals
      4 from .dispatch import conditional, sample_conditional
      5 from .uncertain_conditionals import uncertain_conditional

~/miniconda3/lib/python3.7/site-packages/gpflow/conditionals/conditionals.py in <module>
     15 import tensorflow as tf
     16 
---> 17 from ..config import default_jitter
     18 from ..covariances import Kuf, Kuu
     19 from ..inducing_variables import InducingVariables

~/miniconda3/lib/python3.7/site-packages/gpflow/config/__init__.py in <module>
----> 1 from .__config__ import *

~/miniconda3/lib/python3.7/site-packages/gpflow/config/__config__.py in <module>
     58 import tabulate
     59 import tensorflow as tf
---> 60 import tensorflow_probability as tfp
     61 
     62 __all__ = [

~/miniconda3/lib/python3.7/site-packages/tensorflow_probability/__init__.py in <module>
     21 # from tensorflow_probability.google import staging  # DisableOnExport
     22 # from tensorflow_probability.google import tfp_google  # DisableOnExport
---> 23 from tensorflow_probability.python import *  # pylint: disable=wildcard-import
     24 from tensorflow_probability.python.version import __version__
     25 

~/miniconda3/lib/python3.7/site-packages/tensorflow_probability/python/__init__.py in <module>
    140   # Non-lazy load of packages that register with tensorflow or keras.
    141   for pkg_name in _maybe_nonlazy_load:
--> 142     dir(globals()[pkg_name])  # Forces loading the package from its lazy loader.
    143 
    144 

~/miniconda3/lib/python3.7/site-packages/tensorflow_probability/python/internal/lazy_loader.py in __dir__(self)
     59 
     60   def __dir__(self):
---> 61     module = self._load()
     62     return dir(module)
     63 

~/miniconda3/lib/python3.7/site-packages/tensorflow_probability/python/internal/lazy_loader.py in _load(self)
     39     """Load the module and insert it into the parent's globals."""
     40     if callable(self._on_first_access):
---> 41       self._on_first_access()
     42       self._on_first_access = None
     43     # Import the target module and insert it into the parent's namespace

~/miniconda3/lib/python3.7/site-packages/tensorflow_probability/python/__init__.py in _validate_tf_environment(package)
     66         'Please upgrade TensorFlow to proceed.'.format(
     67             required=required_tensorflow_version,
---> 68             present=tf.__version__))
     69 
     70   if (package == 'mcmc' and

ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.4; Detected an installation of version 2.3.0. Please upgrade TensorFlow to proceed.
`

## System information

* GPflow version: 2.1.4 (by runing `conda list | grep gpflow`)
* GPflow installed from: `!pip install git+https://github.com/GPflow/GPflow.git@develop`#egg=gpflow
* TensorFlow version:  2.3.0 (running `import tensorflow; print(tensorflow.__version__)`) and 2.4.0 (running `conda list | grep tensorflow`)
* Python version 3.7.6
* Operating system Windows

**Comment by MBasalla** [comment]
I came across the same issue,

here's how I could solve it (in case anyone else runs into the same problem)

run 'pip uninstall tensorflow' twice 
first to uninstall the current version, then to uninstall version 2.3.
Afterward, reinstall tensorflow in the correct version.

**Comment by susuhu** [comment]
I have the same issue, but the introduction says it only requires tensorflow>=2.1. ?

**Comment by st--** [comment]
@susuhu GPflow itself would work with TensorFlow 2.1. This is an issue with the tight coupling between TensorFlow and tensorflow_probability, even though tensorflow_probability does not specify any version pinning of tensorflow in their requirements - instead, they have a runtime check. I'm afraid there's nothing we can do about this in GPflow. I'll add a note to the README though.
