### ISSUE TITLE
GPflow 2 using conda

### ISSUE THREAD

**Issue by azinoma** [GPflow/GPflow#1632]
# Feature request
It would be great if an installation of GPflow 2 would be available through conda.

## Motivation
The reason is that the pip installation will install dependencies already installed in the conda environment. The different installations of the same libraries will then be messy to handle.
Being able to install through conda would facilitate the use of GPflow on HPC clusters.

Many greetings and many thanks for consideration.
Marlon

**Comment by st--** [comment]
Hi @azinoma, can you give some more details on what you mean by "pip installation will install dependencies already installed in the conda environment"? I'm usually using GPflow in a Conda environment, and if the dependencies are already available, `pip install gpflow` solely installs the gpflow package itself, so I'm not quite sure what your issue is. (Unfortunately https://github.com/conda-forge/gpflow-feedstock is both out of date and our control - ultimately it'd need to be the admins on _that_ repo to merge a pull request to bring it up to date, and that's none of the people currently contributing to GPflow.)

**Comment by azinoma** [comment]
Hi @st-- , thank you very much for your comment.
On my local computer I also did not face any issues.
However, when running on an HPC cluster the following happens:
1.) In my conda environment I install tensorflow-gpu. `tf.__version__` then shows 2.2.0 and the gpu is visible.
2.) Then I pip install GPflow. Now `tf.__version__` then shows 2.4 and the gpu is not visible anymore.
I contacted the support of the HPC cluster and they suggested the problem comes from the (via GPflow) pip installed tensorflow version.
I thought having a conda installation of GPflow would probably help, but maybe there is a better way?
Thanks a lot for your help and the great library.

**Comment by st--** [comment]
Hm, so that seems like the Pip call doesn't recognise the conda environment properly. What output do you get for the following shell commands (on the shell command line):
`which python`
`which conda`
`which pip`
?
What output do you get for the following python lines _before_ you pip-install GPflow (tf 2.2.0)?
```python
import tensorflow as tf
print(tf.__file__)
```
What output do you get for the following python lines after you pip-install GPflow (tf 2.4)?
```python
import tensorflow as tf
print(tf.__file__)
import gpflow
print(gpflow.__file__)
```

**Comment by azinoma** [comment]
Thank you very much for your help!
I tried what you said in a new environment and now get:
`which python`
/sapps/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/anaconda3-2020.02-ppgtwazm6cq2m6yivjpnat4qs4k3qrii/bin/python

`which conda`
/sapps/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/anaconda3-2020.02-ppgtwazm6cq2m6yivjpnat4qs4k3qrii/bin/conda

`which pip`
/sapps/opt/spack/linux-ubuntu16.04-x86_64/gcc-5.4.0/anaconda3-2020.02-ppgtwazm6cq2m6yivjpnat4qs4k3qrii/bin/pip

Before pip installing GPflow:
`import tensorflow as tf
print(tf.__file__)`
/home/cluster/mazino/.conda/envs/CK/lib/python3.8/site-packages/tensorflow/__init__.py

Before pip installing GPflow:
`import tensorflow as tf
print(tf.__file__)`
/home/cluster/mazino/.conda/envs/CK/lib/python3.8/site-packages/tensorflow/__init__.py

 `import gpflow
print(gpflow.__file__)` now returns an error:
ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.4; Detected an installation of version 2.2.0. Please upgrade TensorFlow to proceed.

Thanks a lot and many greetings,
Marlon

**Comment by azinoma** [comment]
Maybe I should add:
`pip install gpflow` showed:
Collecting gpflow
  Using cached gpflow-2.1.4-py3-none-any.whl (255 kB)
Requirement already satisfied: setuptools>=41.0.0 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from gpflow) (49.6.0.post20210108)
Requirement already satisfied: typing-extensions in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from gpflow) (3.7.4.3)
Requirement already satisfied: numpy in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from gpflow) (1.19.5)
Requirement already satisfied: scipy in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from gpflow) (1.6.0)
Requirement already satisfied: tensorflow>=2.1.0 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from gpflow) (2.2.0)
Collecting multipledispatch>=0.6
  Downloading multipledispatch-0.6.0-py3-none-any.whl (11 kB)
Requirement already satisfied: six in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from multipledispatch>=0.6->gpflow) (1.15.0)
Requirement already satisfied: keras-preprocessing>=1.1.0 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from tensorflow>=2.1.0->gpflow) (1.1.2)
Requirement already satisfied: google-pasta>=0.1.8 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from tensorflow>=2.1.0->gpflow) (0.2.0)
Requirement already satisfied: wheel>=0.26 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from tensorflow>=2.1.0->gpflow) (0.36.2)
Requirement already satisfied: h5py<2.11.0,>=2.10.0 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from tensorflow>=2.1.0->gpflow) (2.10.0)
Requirement already satisfied: grpcio>=1.8.6 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from tensorflow>=2.1.0->gpflow) (1.34.1)
Requirement already satisfied: protobuf>=3.8.0 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from tensorflow>=2.1.0->gpflow) (3.14.0)
Requirement already satisfied: absl-py>=0.7.0 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from tensorflow>=2.1.0->gpflow) (0.11.0)
Requirement already satisfied: termcolor>=1.1.0 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from tensorflow>=2.1.0->gpflow) (1.1.0)
Requirement already satisfied: wrapt>=1.11.1 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from tensorflow>=2.1.0->gpflow) (1.12.1)
Requirement already satisfied: gast==0.3.3 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from tensorflow>=2.1.0->gpflow) (0.3.3)
Requirement already satisfied: astunparse==1.6.3 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from tensorflow>=2.1.0->gpflow) (1.6.3)
Collecting scipy
  Downloading scipy-1.4.1-cp38-cp38-manylinux1_x86_64.whl (26.0 MB)
     |████████████████████████████████| 26.0 MB 159 kB/s 
Collecting opt-einsum>=2.3.2
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting tensorboard<2.3.0,>=2.2.0
  Downloading tensorboard-2.2.2-py3-none-any.whl (3.0 MB)
     |████████████████████████████████| 3.0 MB 65.0 MB/s 
Requirement already satisfied: markdown>=2.6.8 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow>=2.1.0->gpflow) (3.3.3)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow>=2.1.0->gpflow) (1.8.0)
Requirement already satisfied: werkzeug>=0.11.15 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow>=2.1.0->gpflow) (1.0.1)
Requirement already satisfied: requests<3,>=2.21.0 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow>=2.1.0->gpflow) (2.25.1)
Requirement already satisfied: google-auth<2,>=1.6.3 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow>=2.1.0->gpflow) (1.24.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from tensorboard<2.3.0,>=2.2.0->tensorflow>=2.1.0->gpflow) (0.4.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow>=2.1.0->gpflow) (4.7)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow>=2.1.0->gpflow) (4.1.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow>=2.1.0->gpflow) (0.2.7)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.3.0,>=2.2.0->tensorflow>=2.1.0->gpflow) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard<2.3.0,>=2.2.0->tensorflow>=2.1.0->gpflow) (0.4.8)
Requirement already satisfied: chardet<5,>=3.0.2 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow>=2.1.0->gpflow) (3.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow>=2.1.0->gpflow) (1.26.2)
Requirement already satisfied: certifi>=2017.4.17 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow>=2.1.0->gpflow) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard<2.3.0,>=2.2.0->tensorflow>=2.1.0->gpflow) (2.10)
Requirement already satisfied: oauthlib>=3.0.0 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.3.0,>=2.2.0->tensorflow>=2.1.0->gpflow) (3.0.1)
Collecting tensorflow-estimator<2.3.0,>=2.2.0
  Downloading tensorflow_estimator-2.2.0-py2.py3-none-any.whl (454 kB)
     |████████████████████████████████| 454 kB 14.6 MB/s 
Collecting tensorflow-probability>0.10.0
  Using cached tensorflow_probability-0.12.1-py2.py3-none-any.whl (4.8 MB)
Requirement already satisfied: decorator in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from tensorflow-probability>0.10.0->gpflow) (4.4.2)
Collecting cloudpickle>=1.3
  Downloading cloudpickle-1.6.0-py3-none-any.whl (23 kB)
Collecting dataclasses
  Using cached dataclasses-0.6-py3-none-any.whl (14 kB)
Collecting dm-tree
  Downloading dm_tree-0.1.5-cp38-cp38-manylinux2014_x86_64.whl (91 kB)
     |████████████████████████████████| 91 kB 3.6 MB/s 
Collecting packaging
  Downloading packaging-20.8-py2.py3-none-any.whl (39 kB)
Requirement already satisfied: pyparsing>=2.0.2 in /net/cephfs/data/mazino/.conda/envs/CK/lib/python3.8/site-packages (from packaging->gpflow) (2.4.7)
Collecting tabulate
  Using cached tabulate-0.8.7-py3-none-any.whl (24 kB)
Installing collected packages: tensorflow-estimator, tensorboard, scipy, opt-einsum, dm-tree, cloudpickle, tensorflow-probability, tabulate, packaging, multipledispatch, dataclasses, gpflow
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.4.0
    Uninstalling tensorflow-estimator-2.4.0:
      Successfully uninstalled tensorflow-estimator-2.4.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.4.1
    Uninstalling tensorboard-2.4.1:
      Successfully uninstalled tensorboard-2.4.1
  Attempting uninstall: scipy
    Found existing installation: scipy 1.6.0
    Uninstalling scipy-1.6.0:
      Successfully uninstalled scipy-1.6.0
  Attempting uninstall: opt-einsum
    Found existing installation: opt-einsum 0+untagged.61.gd905544.dirty
    Uninstalling opt-einsum-0+untagged.61.gd905544.dirty:
      Successfully uninstalled opt-einsum-0+untagged.61.gd905544.dirty
Successfully installed cloudpickle-1.6.0 dataclasses-0.6 dm-tree-0.1.5 gpflow-2.1.4 multipledispatch-0.6.0 opt-einsum-3.3.0 packaging-20.8 scipy-1.4.1 tabulate-0.8.7 tensorboard-2.2.2 tensorflow-estimator-2.2.0 tensorflow-probability-0.12.1

**Comment by st--** [comment]
Ahhh.... that looks like it's actually a different issue, not GPflow nor pip/conda.
GPflow relies on tensorflow_probability, which in turn relies on tensorflow, and a given version of tensorflow_probability only works with given version of tensorflow. But it doesn't specify in the setup.py!
If you do `pip install tensorflow_probability` without specifying a version, you'll get the latest (0.12.1) which requires tensorflow 2.4. In GPflow, we can't _pin_ the tensorflow_probability version because that would also restrict the tensorflow version. In your case, you already have tensorflow pre-installed, but not tensorflow_probability. You then end up with incompatible versions.
Can you try
`pip install tensorflow_probability==0.10.1 gpflow` (and using your HPC's base conda with tensorflow 2.2)?

**Comment by azinoma** [comment]
This worked!
Perfect!
Thank you very, very much!
You helped me a lot =)
