### ISSUE TITLE
Install instructions for IBM power 9 architecture

### ISSUE THREAD

**Issue by wolfiex** [GPflow/GPflow#1635]
# Feature request

Instructions/ ideas on how to install the gpflow package on the IBM power architecture would be greatly appreciated. I'm not quite sure where to start on the compilation. 

## Motivation

**Is your feature request related to a problem?**
The conda install does not have an entry for the `linux-ppc64le` environment. 

## Proposal

**Describe the solution you would like**
A pre compiled conda version for  the power 9 architecture, or instructions on how to set this up.

**Comment by wolfiex** [comment]
My process was a slightly obscure one: 

```
conda install -c conda-forge bazel
conda install tensorflow-probability
conda install tensorflow-gpu
conda install tensorflow-estimator --no-deps
pip install gpflow - use-deprecated=legacy-resolver
```

**Comment by st--** [comment]
Hi @wolfiex, GPflow itself doesn't require any compilation. Its Tensorflow dependency does, but that's an issue for github.com/tensorflow/tensorflow. I'm afraid this is out of scope for our project! If you're after `conda install gpflow`, this is related to #1632 - we're not currently admins of the conda-forge package but are looking into getting that working again.
