### ISSUE TITLE
Add parameter to GPR to specify if likelihood is trainable

### ISSUE THREAD

**Issue by joelberkeley** [GPflow/GPflow#1646]
# Feature request

An argument to `GPR` to specify whether the noise variance should be trainable.

## Motivation

I'm writing a function that makes a GPR. Currently I do ...
```python
gpr = GPR(...)
set_trainable(gpr.likelihood, False)
return gpr
```
This could be one line if there was an argument to specify whether I want the likelihood to be trainable. It also has the standard advantages of immutability.

**Are you willing to open a pull request?** Don't have the time right now. Might have later.

**Comment by johnamcleod** [comment]
There have been some internal changes in GPFlow which appear to address this issue, which are on `develop` but as of today have not yet been released. `Parameter`s can be passed into the constructor of `Parameters` to set the value, but also properties as well. We have not yet updated the type annotations to advertise this behaviour. 

`model = gpflow.models.GPR(
    data,
    kernel,
    noise_variance=gpflow.Parameter(1.0, trainable=False)
)
gpflow.utilities.print_summary(model)`

`╒═════════════════════════╤═══════════╤═════════════╤═════════╤═════════════╤═════════╤═════════╤═════════╕
│ name                    │ class     │ transform   │ prior   │ trainable   │ shape   │ dtype   │   value │
╞═════════════════════════╪═══════════╪═════════════╪═════════╪═════════════╪═════════╪═════════╪═════════╡
│ GPR.kernel.variance     │ Parameter │ Softplus    │         │ True        │ ()      │ float64 │       1 │
├─────────────────────────┼───────────┼─────────────┼─────────┼─────────────┼─────────┼─────────┼─────────┤
│ GPR.kernel.lengthscales │ Parameter │ Softplus    │         │ True        │ ()      │ float64 │       1 │
├─────────────────────────┼───────────┼─────────────┼─────────┼─────────────┼─────────┼─────────┼─────────┤
│ GPR.likelihood.variance │ Parameter │ Identity    │         │ False       │ ()      │ float64 │       1 │
╘═════════════════════════╧═══════════╧═════════════╧═════════╧═════════════╧═════════╧═════════╧═════════╛`
