### ISSUE TITLE
Enforce all user ops have GPU versions?

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#171]
We have some nice user ops and more coming through. There is the potential that they will improve performance on CPU but make it worse on GPU. We need to think about how to deal with this. One option is to only depend on user ops where we have both CPU and GPU implementations.

**Comment by alexggmatthews** [comment]
Related to #170

**Comment by markvdw** [comment]
So the performance hit is more that data would have to be loaded off GPU memory into CPU memory, right? This would be an issue even considering @jameshensman's point that the current ops are mostly reshapes and are fast.

I don't think it's unreasonable to require a GPU implementation. Especially for simple ops, it doesn't look too hard.

**Comment by jameshensman** [comment]
@markvdw , if you could make a GPU edition of the tri2vec/vec2tri ops, that would be amazing.

If you have a look at my RemoveRowElements op, it's completely based on yours. I reckon I could plagarize a GPU op similarly :)

**Comment by alexggmatthews** [comment]
Fixed in #430 we don't have any user ops any more.
