### ISSUE TITLE
Coregionalization with more than 2 outcomes generates an InvalidArgumentError error

### ISSUE THREAD

**Issue by essicolo** [GPflow/GPflow#1712]
Hi,

I had a similar issue to #985 while trying to a high-dimensional coregionalization, with multiple features and multiple outputs, but got errors trying to fit a single feature to more than 2 outcomes. Here is a case for 3 outcomes.

```
import gpflow
import numpy as np
np.random.seed(1)

X1 = np.random.rand(100, 1)
X2 = np.random.rand(50, 1) * 0.5
X3 = np.random.rand(50, 1) * 1.5

Y1 = np.sin(6 * X1) + np.random.randn(*X1.shape) * 0.03
Y2 = np.sin(6 * X2 + 0.7) + np.random.randn(*X2.shape) * 0.1
Y3 = np.sin(3 * X3 + 1.2) + np.random.randn(*X3.shape) * 0.08

X_augmented = np.vstack((
    np.hstack((X1, np.zeros_like(X1))),
    np.hstack((X2, np.ones_like(X2))),
    np.hstack((X3, 2 * np.ones_like(X3)))
))

Y_augmented = np.vstack((
    np.hstack((Y1, np.zeros_like(Y1))),
    np.hstack((Y2, np.ones_like(Y2))),
    np.hstack((Y3, 2 * np.ones_like(Y3)))
))
```

I'm not sure if the rank is ok. From the math, my guess is that the rank of $W$ (as defined in the [documentation](https://gpflow.readthedocs.io/en/master/gpflow/kernels/#gpflow-kernels-coregion)) should be the number of unique indexes in the augmented matrices.

```
n_idx = len(np.unique(Y_augmented[:, 1]))
k1 = gpflow.kernels.Matern32(active_dims = [0])
coreg = gpflow.kernels.Coregion(
    output_dim = 2,
    rank = n_idx,
    active_dims = [1]
)
kern = k1 * coreg
```

I should have the same number of likelihoods than the number of indexes, which allows me to create the model.

```
lik = gpflow.likelihoods.SwitchedLikelihood([
    gpflow.likelihoods.Gaussian(),
    gpflow.likelihoods.Gaussian(),
    gpflow.likelihoods.Gaussian()
])

m = gpflow.models.VGP(
    (X_augmented, Y_augmented),
    kernel = kern,
    likelihood = lik
)
```

However, the fitting returns an error.

```
gpflow.optimizers.Scipy().minimize(
    m.training_loss,
    m.trainable_variables,
    method = "L-BFGS-B"
)
```

```
InvalidArgumentError:  indices[150] = 2 is not in [0, 2)
	 [[node GatherV2_2 (defined at /Users/username/opt/miniconda3/envs/tf/lib/python3.6/site-packages/gpflow/kernels/misc.py:203) ]] [Op:__inference__tf_eval_20562]

Errors may have originated from an input operation.
Input Source operations connected to node GatherV2_2:
```

Note that I'm trying to use coregionalization as a way to consider patient effects on longitudinal data, where the active dimension of the coregionalization is the ID of the patient. I first thought adding a random intercept to each patient, but it ended up causing a lot of errors with PyMC3, and couldn't get support for gpflow on [stackoverflow](https://stackoverflow.com/questions/68501224/adding-probabilistic-random-effects-to-gaussian-processes-with-gpflow). If you have an idea how to resolve the problem of both coregionalization and random intercept, I would greatly appreciate the advice!

**Comment by st--** [comment]
Hi @essicolo, you define the coregionalisation kernel as follows:
```python
coreg = gpflow.kernels.Coregion(
    output_dim = 2,
    rank = n_idx,
    active_dims = [1]
)
```
with `output_dim=2` - but then you use it with _three_ outputs. Does changing this line to `output_dim=3` resolve your issue?

(NB- the number of likelihoods is orthogonal to the number of outputs. You could have three outputs and two likelihoods, or indeed just one and do away with the SwitchedLikelihoods. It's just a question of for which observations [data rows - not making any statement on which output this is!] you want to learn separate noise levels.)

**Comment by essicolo** [comment]
Hi @st-- ,

Changing to `output_dim=3` worked! I really thought this was the number of columns to the `Y` matrix. I'll have to investigate the `SwitchedLikelihoods` to better understand, but indeed it works with `lik = gpflow.likelihoods.Gaussian()`.

Thanks! 🙏
