### ISSUE TITLE
Duplication of computation

### ISSUE THREAD

**Issue by markvdw** [GPflow/GPflow#172]
Does TensorFlow recognise when parts of the computational graph are duplicated, and does it automatically merge them? I haven't done a comprehensive review of the code, but this could result in a slowdown if, for example, the `kern.K()` was called twice in a different location in the code, while calculating the objective. Since a different TensorFlow variable would be used, TensorFlow would (unless something smart is going on) have to compute the kernel matrix twice.

Is this something you thought about when writing TensorFlow?

**Comment by alexggmatthews** [comment]
Hi Mark it is maybe not exactly what you want but we there is some related discussion of partial_run 
https://github.com/tensorflow/tensorflow/issues/672

**Comment by alexggmatthews** [comment]
@markvdw  @jameshensman Althought obvious it is good if this stuff can be made automatic I also wonder if this makes a point about how we are structuring the code. I.e maybe we shouldn't be calculating the same thing twice in two different parts of the code when we know it is the same.

**Comment by markvdw** [comment]
The way I understand it, that tensorflow issue relates to getting results out of the graph, by running. What I meant is essentially your second point. Where the graph essentially duplicates computation because of the way the code is structured.

I found a concrete example in `SVGP`. Here K_zz is computed twice, once in `conditional()` through `build_predict()`, and once in `build_prior_KL()`. If TensorFlow will make the result of these two calls to `kern.K` different variables, while their graphs and inputs are the same, the computation will be doubled.

**Comment by markvdw** [comment]
If this is a problem, one way to solve it would be to memoize the inputs, and return an earlier calculated TensorFlow node, so that the computation would be re-used.

**Comment by jameshensman** [comment]
I'm quite sure this is not an issue: tf is supposed to do common subexpression elimination. see section 5.1 of the whitepaper.

http://download.tensorflow.org/paper/whitepaper2015.pdf

**Comment by alexggmatthews** [comment]
@jameshensman is correct. Code is here:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/graph/optimizer_cse.cc

**Comment by markvdw** [comment]
Phew, great!
