### ISSUE TITLE
Incorrect equations in SGPR_notes

### ISSUE THREAD

**Issue by joacorapela** [GPflow/GPflow#1753]
# Bug / performance issue / build issue

I believe there is an error in the next-to-last equation in the documentation page at https://gpflow.readthedocs.io/en/master/notebooks/theory/SGPR_notes.html, which makes the last prediction equation invalid. I provide details at http://www.gatsby.ucl.ac.uk/~rapela/gpflow/wrongPredictionEq.pdf. Can this be right?

**Comment by joacorapela** [comment]
The next-to-the-last equation in the [documentation page](https://gpflow.readthedocs.io/en/master/notebooks/theory/SGPR_notes.html) is correct, as shown [here](http://www.gatsby.ucl.ac.uk/~rapela/gpflow/proofPredictionMean.pdf).

**Comment by joacorapela** [comment]
Thanks @st-- . The third to the last equation in the [GPflow documentation page](https://gpflow.readthedocs.io/en/master/notebooks/theory/SGPR_notes.html) correctly states Kuu⁻¹ Λ Kuu⁻¹ = L⁻ᵀ and  as proved [here](http://www.gatsby.ucl.ac.uk/~rapela/gpflow/proofPredictionMean.pdf) the GPflow documentation is correct. What do you think?

**Comment by st--** [comment]
In other words, `Kuu⁻¹ Λ Kuu⁻¹` isn't consistent, it should be `Kuu⁻¹ Λ⁻¹ Kuu⁻¹` based on the "units".

**Comment by joacorapela** [comment]
Thanks for your comment @st--. I believe there is a typo in the third to the last equation of this [GPflow note](https://gpflow.readthedocs.io/en/master/notebooks/theory/SGPR_notes.html). The right hand side of this equation should contain <img src="https://render.githubusercontent.com/render/math?math=\Lambda^{-1}"> instead of <img src="https://render.githubusercontent.com/render/math?math=\Lambda">, as proven [here](http://www.gatsby.ucl.ac.uk/~rapela/gpflow/proofPredictionCov.pdf). With this correction, the proof of the predictive mean (second to the last equation of this [GPflow note](https://gpflow.readthedocs.io/en/master/notebooks/theory/SGPR_notes.html)) becomes simple, as shown [here](https://www.gatsby.ucl.ac.uk/~rapela/gpflow/proofPredictionMean2.pdf). I will create a pull request about this.

**Comment by st--** [comment]
I think we'd resolved this now ? If anyone disagrees please shout and we can reopen it:)
