### ISSUE TITLE
Future of LVM support

### ISSUE THREAD

**Issue by markvdw** [GPflow/GPflow#177]
What is the overall idea of the future of the GPLVM? The readme states that "GPflow does not do latent variable models". Is this going to change soon, or is the plan to maintain the GPLVM branch separately? Personally, I like the idea of having latent variable models in GPflow, or at least GPflow providing some provisions to do so.

I think the only provision needed in GPflow to make it easy to implement LVM's, is to have the kernel expectations defined in `kernels.py`, instead of some external file. I don't like the current solution of having the function `build_phi_stats()`, as it removes so much of what is nice about the object oriented structure. Extending the kernel classes to include the kernel expectations would make things a lot neater, and I don't think it would clutter up the code much.

Alternatively, if we only want to implement kernel expectations in a set of use cases that are more limited than all the use cases provided by `GPflow.kernels`, we could have a separate file `GPflow.kernels_exp`, that provide a subset of the kernels, but with expectations. These kernels could inherit from the normal `GPflow.kernels`.

If we decide not to put kernel expectations in GPflow, I would propose to create a separate project GPflowExtras or something, that provides the file mentioned above. This could provide extras to GPflow that are perhaps outside the scope of GPflow. Then anyone wanting to implement LVMs can rely on both GPflow and GPflowExtras, while committing common components to GPflowExtras.

Anyway, it would be nice to have some clarity on this. I've got some nice code for kernel expectations in the pipeline, and it would be nice to share it and get feedback from others too. However, right now I need some clarity as to whether this is desired to do in GPflow.

**Comment by alexisboukouvalas** [comment]
The GPLVM code right now is closely following the gpy architecture. With James we have also put in a quadrature solution for single parameter kernels. This catches the kernel cases where the expectations have not been derived. 
I would be happy to see more cases covered. I don't find the current implementation difficult to understand but perhaps if we add more cases we may want to separate out the kernel cases. 
The GPLVM branch currently has a working version of the code as well as some initial tests.
However the latter should be extended which is what I am looking at as well as adding some notebooks.

**Comment by jameshensman** [comment]
Hi @markvdw ,

I hope you agree that GPflow is a good platform for building all kinds of models, including LVMs. To start with, Alex and I wanted to get our six models up and running, and build the foundation of GPflow. 

Some things that I'd like to see in GPflow in future are 
 - GPLVM (this is almost done)
 - Kronecker structured GPs (with Gaussian likelihoods, and VB and MCMC)
 - Deep GPs (there is some preliminary work on this)
 - GP dynamical systems

How these things fit into GPflow is up for discussion I think. Certainly, we're not going to drop any standards for the sake of including new code: we want 100% tested (okay, >99% tested) code with a systematic API. 

Alex and I have thought about a 'contrib' section for GPflow, but decided against it for the moment. 

I agree that it would be nice to have `build_psi_stats` more elegantly incorporated into the kernel. It's be nice to follow the same pattern as we use in the likelihoods for quadrature. for 1D kernels, we can compute the psi-statistics using Gauss-hermite: we should build this into the base class, and then override when we can. The add and prod kernels will take some work.

**Comment by markvdw** [comment]
I totally agree that GPflow is a great foundation to build LVMs. Maybe a better phrasing of the question is "do we want to acknowledge that people may use GPflow for LVMs by adding support for that in kernels?".

Essentially I'm implementing the variational GP dynamical system (i.e. with a GP transition function, rather than a correlated GP prior in the latent space) now, and I'm wondering what the best way to go about this is, also with regard to merging improvements back into GPflow.

Currently, both my VGPSSM implementation and the GPLVM rely on computing the psi statistics. I just didn't like the current monolithic solution to computing the psi statistics*. Also I require a bit more functionality than what is required for the GPLVM, like expectations w.r.t. correlated Gaussians.

Essentially, I want to see if anyone agrees that the psi statistics should be implemented in the kernel classes, and whether anybody wants to work together to get this into GPflow now rather than later. But all this does require some thought about how to do it right :)

* This was the only thing I didn't like about the GPLVM implementation btw, the rest looks nice :)

**Comment by jameshensman** [comment]
I think we should support kernel expectations in the most elegant way possible, and I'm very happy to be involved in conversations about how this could be done.

**Comment by ilm** [comment]
We are working on implementing deep GPs. Can someone tell me the status of deep GPs at the moment, I see there is a 'deep' branch (5 months old)?

**Comment by jameshensman** [comment]
hi @ilm, 

What you see is what there is: there's some preliminary work on implementing deep GPs, but nothing ready to release into the wild yet. 

If you wanted to continue that implementation I think it would be a welcome part of GPflow.

**Comment by ilm** [comment]
Great, we will take a look at the deep branch and start working on it the coming months. I just don't want to be doing duplicate work, if someone is working on it behind the scenes for example.

**Comment by alexggmatthews** [comment]
Very old discussion. Please open a new issue if we feel there are still relevant things here.
