### ISSUE TITLE
A lot of our docstrings don't appear in the generated documentation.

### ISSUE THREAD

**Issue by jesnie** [GPflow/GPflow#1781]
# Bug

A lot of our docstrings don't appear in the generated documentation.

## To reproduce

For example; compare the fine docstrings in this file:
https://github.com/GPflow/GPflow/blob/develop/gpflow/models/gpr.py
With the generated HTML:
https://gpflow.readthedocs.io/en/develop/gpflow/models/gpr/index.html

## Expected behavior

All the hard work we put into docstrings should result in beautiful and informative HTML documentation.

**Comment by st--** [comment]
Ouff, that's really frustrating. Thanks for spotting this! Any ideas yet how to fix it ? (The docs generation as a whole is a bit of a mess unfortunately ... :S)

**Comment by jesnie** [comment]
Testing locally this "just" seems to be caused by everything that has to do with documentation using ancient versions of libraries, while our code is a lot newer. Does anybody know who owns this project on `readthedocs` and how to log in a check what's going?
