### ISSUE TITLE
Is it better to write GPFlow or GPflow?

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#180]
Someone asked me this today and I think it is a fair question.

We write TensorFlow  for example. 

You could also argue that writing GPFlow is more consistent as it gives a capital letter to each word.

**Comment by jameshensman** [comment]
I vote for GPFlow. 

I also vote for someone else to do the refactoring :p

**Comment by markvdw** [comment]
To me, GPflow feels more balanced and places a more distinct separation between GP and flow. I'd worry about it looking like GPF-low, rather than GP-flow.

**Comment by jameshensman** [comment]
cannot unsee GPF-low, changing my vote.

**Comment by alexggmatthews** [comment]
Me too. So let's leave as is.
