### ISSUE TITLE
Master branch on readthedocs not up to date

### ISSUE THREAD

**Issue by st--** [GPflow/GPflow#1801]
As noted in #1790

**Comment by joacorapela** [comment]
@st--  a related problem may be that there is a problem building the Sphynx documentation locally. A few months ago I was able to build Sphynx documentation.

1. modified source/notebooks/theory/SGPR_notes.md
2. entered `make html` in doc and got two warnings:
`WARNING: toctree contains reference to nonexisting document 'notebooks/intro_to_gpflow2'`
`WARNING: toctree contains reference to nonexisting document 'gpflow/index'`
but the build was reported as `succeded.`
3. opened `notebooks/theory/SGPR_notes.html` with browser and the changes do not appear.
