### ISSUE TITLE
Make sure all reasonable and supported combinations of Python and numpy (and tensorflow?) works.

### ISSUE THREAD

**Issue by jesnie** [GPflow/GPflow#1848]
Right now Python3.9 + numpy 1.20 refuses to load.

The problem comes from:

1. `numpy < 1.20.0` has no types.
2. For `1.20.0 <= numpy < 1.22.0` arrays has type `np.ndarray`.
3. For `1.22.0 <= numpy` arrays has type `np.ndarray[Any, Any]`.

We need a setup that works both for `mypy` and when actually running the code.

**Comment by jesnie** [comment]
Maybe we need to set up CircleCI to check more different versions of stuff, though I worry about budget?

**Comment by jesnie** [comment]
Maybe we can ban numpy 1.20 and 1.21 - that would make many things easier?

**Comment by st--** [comment]
> Maybe we can ban numpy 1.20 and 1.21 - that would make many things easier?

I'd be happy to not have a build for numpy 1.20/1.21, but I think if it's just for the types, then I'd rather see an (even clunky) workaround than to drop support entirely...
