### ISSUE TITLE
Allow dependency on tensorflow-macos instead of tensorflow

### ISSUE THREAD

**Issue by aterenin** [GPflow/GPflow#1850]
Right now, gpflow does not install correctly on Mac because it depends on `tensorflow` but the pip package has been changed to `tensorflow-macos`.

Seems to work perfectly fine once installed with `--no-dependencies`. This is with brew/pip - no Conda.

**Comment by jesnie** [comment]
We probably want to use this: https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#platform-specific-dependencies

**Comment by jesnie** [comment]
Done.
