### ISSUE TITLE
How exactly does predict_f function work?

### ISSUE THREAD

**Issue by Pranav110500** [GPflow/GPflow#1932]
How exactly does predict_f function work? I am trying to train a gpflow model with matern52 kernel, on a training set of X_train size (10x2) and y_train as (10x1), however using predict_f on testing data of (3600x2) is actually giving an output of (3600x11), how exactly is it giving this dimension can someone explain?

**Comment by jesnie** [comment]
That does sound wrong. Would it be possible for you to post a running code example, so I can debug it?

**Comment by Pranav110500** [comment]
[GPflow_model.pdf](https://github.com/GPflow/GPflow/files/9070144/GPflow_model.pdf)

Yeah sure sir, I'm attaching a PDF version of my notebook with its outputs for your reference. Kindly go through it and let me know how exactly is the model predict_f working and if there's a way for me to implement the code in a better way. 
(I'm still really new to using gpflow, and though I was able to understand this code with scikit learn, it's causing problems here.)

**Comment by jesnie** [comment]
It appears your `Y_train` has shape `[11]`, and not `[11, 1]`. Gpflow then broadcasts your `Y_train` to shape `[11, 11]` to be compatible with your `X_train`, and that is where you get your 11-dimensional output from.

Good news is that I'm currently working on implementing much stricter shapes-checks throughout GPflow, and in future versions these kind of mistakes should become a lot more obvious.

**Comment by Pranav110500** [comment]
Thank you Sir for pointing that out! I completely missed the fact regarding the shape of Y_train and broadcasting. The code is running fine now. If anything else comes up I'll mention it here or in a different issue, but for now thanks a lot for resolving this really quickly.

**Comment by jesnie** [comment]
No problem.
