### ISSUE TITLE
Can someone explain to me how to edit my code to implement a mean_function/ mean value along with my gpr model?

### ISSUE THREAD

**Issue by Pranav110500** [GPflow/GPflow#1938]
I am having some queries with regards to my gpr model. So initially I ran my model on some testing data where input was 10x2 data containing latitude and longitude values, and output was soil moisture for those values of lat and long. I hadn't used any mean function or mean value before, and for output data (a 60x60 grid of different similar lats,longs) I am not getting desired results. Hence I thought of updating the mean function in the model but it seems to give some error. Can anyone help out with regards to this so that I can help implement the mean, or in general suggest something to get better results in output predictions
[GPflowErrors.pdf](https://github.com/GPflow/GPflow/files/9104596/GPflowErrors.pdf)
?

**Comment by jesnie** [comment]
I haven't tested this, but I think I see two issues:

1. You're calling `predict_f(Y_test)` - that's probably wrong. We normally call `predict_f` with X values.
2. You'll probably need to initialise the weights  (the `A` parameter) of the `Linear` mean function. By default the `Linear` function assumes 1D input and 1D output. If that's not the case you'll need to do something like `Linear(A=np.ones((D, Q)))`, where `D` is the number of inputs and `Q` is the number of outputs.
