### ISSUE TITLE
link to readthedocs page

### ISSUE THREAD

**Issue by davharris** [GPflow/GPflow#194]
[The readthedocs page](https://gpflow.readthedocs.io/en/latest/guts.html) is very nice, but it isn't very discoverable from the README (I only found it because I knew GPy used readthedocs and searched there).  I think that adding it to the README would make GPflow much more accessible to new users.

**Comment by alexggmatthews** [comment]
@davharris well found! There no link because we haven't officially released it yet. We have to run it past some people here in Cambridge before we can. See #140

**Comment by davharris** [comment]
Ah, okay. Feel free to close this issue if it's redundant. Thanks for clarifying.

**Comment by alexggmatthews** [comment]
@davharris there is now a link on our GitHub front page. I've merged #140 so will now close this issue. Thanks,
Alex
