### ISSUE TITLE
gpflow.github.io

### ISSUE THREAD

**Issue by st--** [GPflow/GPflow#1969]
Currently https://gpflow.github.io/ gives a 404 not found error. Would be great if it could forward to gpflow.org or the docs underneath https://gpflow.github.io/GPflow/.

(In the longer run, it might be good to have the gpflow.org website through github.io as well - might make it easier to maintain? I don't even remember anymore how I would update the gpflow.org site)

**Comment by jesnie** [comment]
Done.
