### ISSUE TITLE
Text duplication in intro.rst and readme.md

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#197]
At the moment intro.rst in the docs and readme.md have duplicate text . We don't want to have to change everything twice so we should think about how to avoid this.

**Comment by jameshensman** [comment]
Personally I'm happy for the two to diverge, I needed something for the intro to the documentation and so I grabbed the text from the readme. 

We could probably remove quite a few things from the readme, like install instructions, which should really live in the docs.

**Comment by alexggmatthews** [comment]
I need to think about that. I think it is quite good to have something friendly on the GitHub front page.

**Comment by st--** [comment]
@alexggmatthews I'm assuming this is no longer relevant -please reopen if you disagree!
