### ISSUE TITLE
Different predictions when comparing GPflow with GPy

### ISSUE THREAD

**Issue by beckdaniel** [GPflow/GPflow#2]
Greetings,

First of all, nice work on this library! =)
I tried to replace some GPy models with GPflow ones in some stuff I am doing but I noticed I was getting worse results (in terms of MSE and other metrics). So I did a small test to check if GPy and GPflow were outputting the same values:

https://gist.github.com/beckdaniel/ac44ae59d223fde3e5c7

I expected the code above to give the same predict values but this is not happening. The model is supposed to be a standard GP regression with RBF kernel and zero mean function. No optimization is performed: all hyperparameters have their values kept at 1.0.

Did I miss something when I instantiated my GPflow model above? Is this behaviour expected?

**Comment by jameshensman** [comment]
Hi Daniel, thanks for your interest in GPflow.

There's a small mistake in your code. The following produces the same
result as GPy.

m_gpflow = GPflow.gpr.GPR(X, Y, GPflow.kernels.RBF(2))

In the same way as GPy, setting the input dimension to 1 will make the
kernel only work on the first column of the X matrix.

Best wishes,

James.

**Comment by beckdaniel** [comment]
Oh, geez, of course! Thanks for your prompt reply, James. Setting the dimensionality properly solved my issue in my experiments as well.

**Comment by beckdaniel** [comment]
Hi, sorry to reopen this but I have an additional question. I get small differences in the hyperparameters between GPy and GPflow models after optimization. Here's a modified version of the above gist that replicates this:

https://gist.github.com/beckdaniel/6a526a67714fe93331db

Is this expected behaviour?

The reason why I ask is because I ported the WarpedGP code in GPy to GPflow and, as in the example above, I am getting similar differences in the resulting hyperparameter values. I wanted to check if these are actually expected or if there might a bug in my implementation.

**Comment by alexggmatthews** [comment]
Hi Daniel,
Thanks for your interest in GPflow. Yes this behaviour is within expected variation. The percentage change in the parameters from GPy in this example is:
Noise variance 0.00014 %
Length scale 0.022 %
rbf variance 0.01 %
Although the interface is deliberately similar to GPy, the algorithmic code intentionally works very differently and we would not expect identical floating point results. If you are interested in how we check GPflow works then have a look at our unit test directory https://github.com/GPflow/GPflow/tree/master/testing . 
I hope that helps,
Alex
