### ISSUE TITLE
Update CI to test against Python 3.11

### ISSUE THREAD

**Issue by jesnie** [GPflow/GPflow#2007]
There's a new release of Python. We should make sure GPflow works with it.

**Comment by sc336** [comment]
[TensorFlow doesn't support 3.11 yet](https://github.com/tensorflow/tensorflow/issues/58032) - they're aiming to add support in the next release, TF2.12 - we can revisit this issue then.

**Comment by micmicpx** [comment]
TensorFlow now supports python 3.11, but check_shapes>=1.0.0 does not. Any chance we can up this requirement?

**Comment by NicolasDurrande** [comment]
What is the current status of this? I'm happy to have a look into it but I'm not sure what the blockers are...

**Comment by jesnie** [comment]
I'm looking into this. Most of the work is happening on `check_shapes`.
