### ISSUE TITLE
Ability to specify verbosity of optimization and compilation in config file. 

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#201]
As suggested by @markvdw .

**Comment by jameshensman** [comment]
@markvdw 

some simple things that you can do with the config file:

 - verbosity as described
 - jitter level: `ack-grep cholesky` to find where jitter is added
 - hmc verbosity
 - I will add float32/float64 types in another PR. 

I vote that verbose=False by default, but with the option to call functions with verbose=True (or False) at run time, for examples `Model.sample(verbose=True)`

**Comment by alexggmatthews** [comment]
To be clear though as @markvdw points out we are doing these things yet.

**Comment by markvdw** [comment]
First two are fixed in #202.
