### ISSUE TITLE
Tests failing on develop

### ISSUE THREAD

**Issue by sc336** [GPflow/GPflow#2015]
# Build issue

Sometime since the last merge on develop (2022-11-02), something has changed in our CI tests that they are now failing on develop (they passed on the PR at the time).  An excerpt from the [CircleCI log](https://app.circleci.com/pipelines/github/GPflow/GPflow/4678/workflows/5dd356ee-d7c4-429f-8162-cab5957c5fb0/jobs/19030) is pasted below.

I assume either mypy or some other dependency has changed over the last week.

*Update:* Indeed, [mypy is the culprit here](https://mypy-lang.blogspot.com/2022/11/mypy-0990-released.html).

## To reproduce

Run build_test_and_deploy in CircleCI on develop.

**Stack trace, or error message**
```
#!/bin/bash -eo pipefail
source /tmp/max_venv/bin/activate
# Test without flags, as that is what our users are likely to do:
mypy gpflow tests benchmark doc/*.py setup.py
# Test with flags improves coverage:
mypy $(python -m gpflow.mypy_flags) gpflow tests benchmark doc/*.py setup.py

tests/gpflow/models/test_model_predict.py:82: error: Only concrete class can be given where "Type[GPModel]" is expected  [type-abstract]
tests/gpflow/models/test_model_predict.py:82: note: Error code "type-abstract" not covered by "type: ignore" comment
benchmark/benchmark_api.py:185: error: "object" has no attribute "key_cost"  [attr-defined]
benchmark/benchmark_api.py:185: error: Returning Any from function declared to return "Union[SupportsDunderLT[Any], SupportsDunderGT[Any]]"  [no-any-return]
benchmark/benchmark_api.py:186: error: Argument 1 to "GroupingSpec" has incompatible type "List[object]"; expected "Sequence[GroupingKey]"  [arg-type]
Found 4 errors in 2 files (checked 220 source files)

Exited with code exit status 1

CircleCI received exit code 1
```

## Expected behavior

It's already passed this test suite to get merged in, so it should pass again.

## System information

* GPflow version: develop (but may extend to other branches
* GPflow installed from: CircleCI pipeline (HEAD is at 26a27a4c12e128a318e5b0f20800c12ab72caf74)

**Comment by Corwinpro** [comment]
Would you like a second pair of eyes to have a look at this?

**Comment by sc336** [comment]
Thanks for the offer @Corwinpro, this is fixed already.  If there are any further related issues I'll make sure to tag you in.
