### ISSUE TITLE
Missing Reference to Manipulating Kernels Page

### ISSUE THREAD

**Issue by UgurKap** [GPflow/GPflow#2046]
# Documentation/tutorial notebooks

In the [Kernel Design page](https://gpflow.github.io/GPflow/2.7.0/notebooks/tailor/kernel_design.html), there is a missing reference to the "Manipulating Kernels" notebook at the end. This notebook seems accessible from the old documentations, up to [2.6.4](https://gpflow.github.io/GPflow/2.6.4/notebooks/advanced/kernels.html).

It seems for some reason, this page was removed. Maybe it was considered unnecessary, as some information is given in the getting started page but I disagree. I believe it gives a more comprehensive review of the available kernel implementations, so it would be nice to have it back.

As a side note, for some reason 2.6.4 documentation insist on having dark theme for me, but I like the light theme better. Is there an option to change this? I am forced to clean the cookies to get a light background.

**Comment by st--** [comment]
Hi, the kernel notebook still exists, though it has been moved to https://gpflow.github.io/GPflow/2.7.0/notebooks/getting_started/kernels.html and updated somewhat. Thank you for noticing that this broke the link in the kernel design notebook though!
