### ISSUE TITLE
Missing documentation for SquaredExponential kernel

### ISSUE THREAD

**Issue by rowlesmr** [GPflow/GPflow#2056]
# Documentation

*Is there anything missing in the docs?*

Documentation of gpflow.kernels.stationaries.SquaredExponential went missing sometime after 2.4.0

It is there in [2.4.0](https://gpflow.github.io/GPflow/2.4.0/api/gpflow/kernels/index.html#gpflow-kernels-squaredexponential).

In [2.5.0](https://gpflow.github.io/GPflow/2.5.0/api/gpflow/kernels/index.html#gpflow-kernels-rbf) (and [currently](https://gpflow.github.io/GPflow/develop/api/gpflow/kernels/index.html#gpflow-kernels-rbf)), the entry was replaced by the RBF "as an alias of `gpflow.kernels.stationaries.SquaredExponential`", but there is no `SquaredExponential` entry.

**Comment by st--** [comment]
Good catch! Thank you for reporting it. I hope @khurram-ghani might be able to look into this and fix it:)

**Comment by khurram-ghani** [comment]
`Constant` kernel also had the same issue. Both fixed on `develop`. Will be in the next release.

**Comment by khurram-ghani** [comment]
Fixed doc [example](https://gpflow.github.io/GPflow/develop/api/gpflow/kernels/index.html#gpflow.kernels.SquaredExponential).
