### ISSUE TITLE
Keep getting bug when trying to optimize the model.

### ISSUE THREAD

**Issue by fiona-turner** [GPflow/GPflow#2059]
I am trying to do a basic GP regression, but keep getting a bug when optimizing parameters.

The code I'm running is:

kernel = gpflow.kernels.RBF(lengthscales=[1.0])

model = gpflow.models.GPR((input,output),kernel=kernel, mean_function=None)

model.likelihood.variance.assign(0.1)

optimizer = gpflow.optimizers.Scipy()

optimizer.minimize(model.training_loss, model.trainable_variables)

This results in the error:
ValueError: Shape must be rank 2 but is rank 1 for '{{node MatMul}} = MatMul[T=DT_DOUBLE, transpose_a=false, transpose_b=true](truediv, truediv)' with input shapes: [800], [800].

I haven't been able to find any solutions elsewhere so thought I'd ask here

**Comment by vdutor** [comment]
Hi @fiona-turner,

I would suspect this has something to do with the shape of your input and output data. Assuming you are dealing with one-dimensional outputs, make sure the input has shape `[num_data, input_dim]` and the output is of shape `[num_data, 1]`. Hope this helps.

**Comment by fiona-turner** [comment]
Hi, that was it! Using train_test_split meant my inputs were now one-dimensional without my noticing. Could this also be causing an error I occasionally get, where I get the message that my input matrix for optimizer.minimize isn't invertible?

**Comment by vdutor** [comment]
Great! The non-invertible matrix means that there is an issue with the gram matrix k(X,X). This typically happens when you have duplicate data in your inputs or very high lengthscales relative to the range of the data.
