### ISSUE TITLE
Having issues including a mean function in GPR

### ISSUE THREAD

**Issue by fiona-turner** [GPflow/GPflow#2079]
I'm trying to do a simple GP regression, but get an error message when I try to add in a linear mean function. Line I'm running is:

## To reproduce

**Minimal, reproducible example**
model = gpflow.models.GPR((inputs,U),kernel=gpflow.kernels.Matern52(), mean_function=gpflow.functions.Linear())
```python
# This is the place for your code that reproduces the bug.
# Please make sure it does not depend on external libraries (beyond GPflow's own requirements) or specific datasets, and the smaller, the better :)
# For help on how to write a good bug report, see https://stackoverflow.com/help/minimal-reproducible-example
```
where inputs is a 160x2 dataframe, U is a 160x4 matrix. The error message I'm getting is:
**Stack trace, or error message**
```
NoShapeError: 
Unable to determine shape of object.
  Function: GPR_deprecated.__init__
    Declared: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gpflow/models/gpr.py:57
    Argument: data
      Index: [0]
        Object type: pandas.core.frame.DataFrame
```

## System information

* GPflow version: 2.6.5
* TensorFlow version: 2.13.0
* Python version 3.11.0
* MacOS operating system

**Comment by jesnie** [comment]
It looks like your `inputs` or `U` is a pandas data frame. Try using a numpy array or TensorFlow tensor instead.
