### ISSUE TITLE
Error importing reduce_in_tests

### ISSUE THREAD

**Issue by Fontanapink** [GPflow/GPflow#2085]
# Bug / performance issue / build issue

Error while importing reduce_in_tests

I have a script that imported reduce_in_tests from gpflow.ci_utils, `from gpflow.ci_utils import reduce_in_tests`, which used to work 3 weeks ago. Now I am getting the following error:

```
GPFitScript.py 41 <module>
from gpflow.ci_utils import reduce_in_tests

ImportError:
cannot import name 'reduce_in_tests' from 'gpflow.ci_utils' (C:\ProgramData\anaconda3\envs\gpfitting\lib\site-packages\gpflow\ci_utils.py)
```
These are my packages versions: 
- Python: 3.10.12
- GPFlow: 2.5.2
- Tensorflow: 2.10.0

## To reproduce

**Minimal, reproducible example**

```python
import gpflow as gpf
from gpflow.utilities import print_summary
from gpflow.utilities import parameter_dict
from gpflow.ci_utils import reduce_in_tests
```

**Stack trace, or error message**
```
Traceback (most recent call last):
  File "c:\Users\User\Dropbox\UCL\GPs\testMWE.py", line 4, in <module>
    from gpflow.ci_utils import reduce_in_tests
ImportError: cannot import name 'reduce_in_tests' from 'gpflow.ci_utils' (C:\ProgramData\anaconda3\envs\GPfitting\lib\site-packages\gpflow\ci_utils.py)
```

## Expected behavior

This used to work fine 3 weeks ago for:

```python
MAXITER = reduce_in_tests(args['maxiter'])
```

## System information

* GPflow version: 2.5.2
* GPflow installed from: conda
* TensorFlow version: 2.10.0
* Python version: 3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:09:20) [MSC v.1916 64 bit (AMD64)]
* Operating system: Windows 11

**Comment by jesnie** [comment]
GPFlow `2.5.2` is *really* old, and does not seem to have the `ci_utils.reduce_in_tests` function. That was added in `2.6.0`. Did you downgrade to an older version of GPflow?

**Comment by Fontanapink** [comment]
I see what happened now, I installed it through `conda` and not `pip`
