### ISSUE TITLE
How to use gpflow in parallel computation

### ISSUE THREAD

**Issue by BinglinW** [GPflow/GPflow#2087]
Hi guys, when I try to do parallel computing with joblib, I usually get a hint that gpflow does not support parallel computing, regardless of backend. My code and warning are as follows. May I know what is a possible solution.

'''
for n_values in n_values_list:
        results = Parallel(n_jobs=20, backend='multiprocessing')(delayed(main)(n_values, seed=j+1) for j in range(n_repeat))
        all_results.append({'n_values': n_values, 'results': results})

'''
The warning is /home/dell/anaconda3/envs/wbl_gpflow_py39_2/lib/python3.9/site-packages/joblib/parallel.py:1332: UserWarning: Multiprocessing-backed parallel loops cannot be nested, setting n_jobs=1
  n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,

**Comment by uri-granta** [comment]
Apologies for not getting back to you. Is this still an issue? If so, could you please include some more details (what is `main` doing?). The best would be to include a short self-contained example that can be run by anyone to demonstrate the bug. (Also FYI [here is](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks) how to format a code block.)

**Comment by BinglinW** [comment]
Hello, I have solved this problem. This is due to memory conflicts and parallelism, I changed the parallelism to solve this problem. Thank you for your attention.
