### ISSUE TITLE
Ability to pass through tf config proto to Session 

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#209]
It would be useful to be able to use the following tf functionality for timed experiments.

```
config = tf.ConfigProto(intra_op_parallelism_threads=1,inter_op_parallelism_threads=1)
self._session = tf.Session(config=config)
```

This limits the number of cpu threads for testing. Overwriting the model._session at a later point doesn't seem to work.

**Comment by jameshensman** [comment]
Does it if work if you run _compile after replacing the session?

**Comment by alexggmatthews** [comment]
Oddly no it doesn't. I've tried a couple of times. I'm not quite sure why tbh.

**Comment by alexggmatthews** [comment]
I wondered if it might be some additional state that we aren't getting to when we recompile.

I notice for instance that AutoFlow creates a different session in param.py

`storage['session'] = tf.Session()`

**Comment by jameshensman** [comment]
Ok, that's strange. 

I wonder if we should also be separating out our graphs in tensorflow? Then we could ensure that the autoflow and _compile session are working with different graphs. At the moment, I think everything gets done on the default graph, which is maybe why we have issues.

Tensorflow graphs are a nuance that I didn't understand when writing GPflow to start with, and I'm still not sure I understand them.

**Comment by alexggmatthews** [comment]
A fair observation. I don't personally think the aspect is very well documented.

**Comment by alexggmatthews** [comment]
This branch has a config proto passed through SVGP, GPmodel and Model to allow us to control the number of CPU threads when doing profiling experiments. Obviously we would need to do it for the other model daughter classes to be a full solution. It isn't actually that intrusive and allows the ability to do things like logging device placements.

https://github.com/GPflow/GPflow/tree/profiling_mods

**Comment by alexggmatthews** [comment]
Actually there is also some suggestion that it might be possible to set tracing level for the whole session rather than individual run calls:

https://github.com/tensorflow/tensorflow/blob/r0.10/tensorflow/core/protobuf/config.proto

Might be worth looking into as it might make profiling less intrusive in our code base than the current plan for #174

**Comment by alexggmatthews** [comment]
Unfortunately I don't think this will help with the profiling aspect after all.

**Comment by kiudee** [comment]
I would like to add that setting the number of threads is also mandatory in a cluster computing setting where resource limits are enforced.

**Comment by markvdw** [comment]
@kiudee This is something I would very much like as well, and would make for a great option in `gpflowrc`. Do you know about any options that need to be passed, or caveats? I haven't had the time to look into this.

**Comment by kiudee** [comment]
In my tests I needed to change both:
https://github.com/GPflow/GPflow/blob/20a3f495691b621165cc7fcce1bca917516edf9a/GPflow/param.py#L525-L530
and
https://github.com/GPflow/GPflow/blob/master/GPflow/model.py#L124-L127

```python
config = tf.ConfigProto(intra_op_parallelism_threads=1,
                        inter_op_parallelism_threads=1)
self._session = session.get_session(graph=self._graph,
                                    output_file_name=settings.profiling.output_file_name + "_objective",
                                    output_directory=settings.profiling.output_directory,
                                    each_time=settings.profiling.each_time,
                                    config=config)
```
-----------
In the `profiling_mods` branch the session in the model is created as follows:
https://github.com/GPflow/GPflow/blob/profiling_mods/GPflow/model.py#L96
```python
self._session = tf.Session(config=session_config)
```
Thus the user is able to provide the complete session configuration in the init method. But in the `AutoFlow` class the session is not receiving any configuration:
https://github.com/GPflow/GPflow/blob/profiling_mods/GPflow/param.py#L516
```python
storage['session'] = tf.Session()
```

We need to provide the thread specification to both.

**Comment by markvdw** [comment]
@kiudee: Does @alexisboukouvalas' latest PR fix the issue that you have? I think it probably does, I just want to confirm before closing this issue.

**Comment by alexggmatthews** [comment]
Closed due to inactivity
