### ISSUE TITLE
Standardize whitening of matrices

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#21]
It would be a good idea to think about how we whiten matrices to stop the cholesky failing. 

We often use something like:

A) chol( K + 1e-6 eye )

Is this actually what we want? We might for instance instead do

B) chol( K + 1e-6 eye \* lambda)

where lambda takes into account the scale of K e.g lambda = mean(K) or somesuch like. 

In any case even if we do want A) then we should consider pulling it out into a utlity function in my opinion. Thoughts?

**Comment by jameshensman** [comment]
This seems like a  good plan. 

Actually, I often use a `White(1)` kernel added to my intended kernel which also helps, and it allows the optimizer to reduce the variance of this nugget as much as required.
