### ISSUE TITLE
tensorflow version 0.10 breaks things

### ISSUE THREAD

**Issue by hughsalimbeni** [GPflow/GPflow#211]
e.g. running the multiclass demo notebook works fine with v0.9, but upgrading to v0.10 I get this error at the first optimize line:

> ValueError: Shape () must have rank 1

**Comment by markvdw** [comment]
Could you give some more information on your setup? It works for me, running off the latest commit of master. Usually re-running `python setup.py develop` is necessary and solves problems after upgrading tensorflow.

**Comment by hughsalimbeni** [comment]
My mistake: I thought I was using the latest version, but an older version of GPflow was still on the path...
