### ISSUE TITLE
Prediction with a single thread

### ISSUE THREAD

**Issue by markvdw** [GPflow/GPflow#225]
I'm trying to do prediction with a single thread. To hack something together, I've modified `AutoFlow` to take an extra input argument `session_config` in the constructor. The session is then created using:

`storage['session'] = tf.Session(config=tf.ConfigProto(**self.session_config))`

Now I've changed the `@AutoFlow` decorator of `predict_f` to be:

```
@AutoFlow((float_type, [None, None]), session_config={"intra_op_parallelism_threads": 1,
                                                      "inter_op_parallelism_threads": 1,
                                                      "use_per_session_threads": True})
```

But prediction still uses all my cores! Does anyone have any idea what's causing this? Has anyone limited core usage in TensorFlow before?

**Comment by jameshensman** [comment]
@alexggmatthews has code to limit core usage, and I recall there were some difficulties.

**Comment by st--** [comment]
@markvdw I'm assuming this issue is out of date now; if for some reason there's still something to be done please re-open.
