### ISSUE TITLE
tri_to_vec timing

### ISSUE THREAD

**Issue by jameshensman** [GPflow/GPflow#228]
After a little discussion with @c0g today about this, it looks like we're missing a `-O2` flag when we compile the tf ops. However, I can't replicate the slowness of this op with or without that flag. Perhaps user ops have improved in tf11?

My test looks like this:

``` python
X = np.random.randn(1, 21)
L = GPflow.tf_wraps.vec_to_tri(X)
sess = tf.Session()
%timeit sess.run(L)
```

I get 155us. For reference, a simple reshape is almost exactly the same amount of time:

``` python
Y = tf.reshape(X, (3, 7))
%timeit sess.run(L)  # 155us
```

@markvdw , can you replicate these times? I suspect that you'll get slightly faster times all round on an ubuntu box.

**Comment by markvdw** [comment]
It'll take a few days, but I'll get round to it!

**Comment by icouckuy** [comment]
Fyi, on my laptop with tf0.11rc0 I get:
- vec_to_tri
The slowest run took 27.86 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 96.2 µs per loop

- reshape:
The slowest run took 19.93 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 98.7 µs per loop

**Comment by markvdw** [comment]
I don't get any difference either:
```
In [1]: import tensorflow as tf

In [2]: import GPflow

In [3]: %paste
X = np.random.randn(1, 21)
L = GPflow.tf_wraps.vec_to_tri(X)
sess = tf.Session()
%timeit sess.run(L)

## -- End pasted text --
The slowest run took 24.97 times longer than the fastest. This could mean that an intermediate result is being cached 
10000 loops, best of 3: 77.8 µs per loop

In [4]: %paste
Y = tf.reshape(X, (3, 7))
%timeit sess.run(L)  # 155us

## -- End pasted text --
The slowest run took 23.68 times longer than the fastest. This could mean that an intermediate result is being cached 
10000 loops, best of 3: 76.6 µs per loop\
```

**Comment by jameshensman** [comment]
> I'll see if I can replicate the issue with an older version of TensorFlow

I think that's what we need to get the feature back in.

**Comment by markvdw** [comment]
Ok, I can't replicate the op speeding up, not even with larger matrices, or a changing matrix for every `sess.run`. However, the situation that prompted us removing it, was the MNIST experiment slowing down. It should be easy to check whether this slowdown persists when using the 'LowerTriangular' transform.

I can do this once I get my GPU setup working.

**Comment by icouckuy** [comment]
Our GPU setup has just been setup so if I can run something let me know (though only TF0.11rc1 as we need CUDA8).

**Comment by markvdw** [comment]
Ok that should work. Essentially, we need to run the MNIST demo, once normal, and once with the line:
`
m.q_sqrt = Param(m.q_sqrt.value, transform=GPflow.transforms.LowerTriangular())
`
after the model definition (where `m` is the model).

We need to confirm there is no significant slowdown. We also need to ensure that:
`
GPflow.settings.dtypes.float_type = 'float32'
`
Is set at the start.

**Comment by icouckuy** [comment]
My setup:
1. I checked out the mnist branch and merged master into it (I needed the TF11 fixes)
2. Then I adapted the mnist_demo script, changed gpflowrc for float32 etc.
3. I then just ran the full mnist_demo normally. I will post the full results later, it was about 34 min per 20k iterations.
Then I added:
m_vb.q_sqrt = GPflow.param.Param(m_vb.q_sqrt.value, transform=GPflow.transforms.LowerTriangular())

But got the following error running the demo:
```
m_vb.optimize( tf.train.AdadeltaOptimizer(learning_rate=step_rates[repeatIndex], rho=0.9, epsilon=1e-4, use_locking=True) , maxiter=vb_max_iters[repeatIndex] )
  File "/home/ibcn/icouckuyt/projecten/GPflow/GPflow/model.py", line 217, in optimize
    return self._optimize_tf(method, callback, maxiter, **kw)
  File "/home/ibcn/icouckuyt/projecten/GPflow/GPflow/model.py", line 223, in _optimize_tf
    opt_step = self._compile(optimizer=method)
  File "/home/ibcn/icouckuyt/projecten/GPflow/GPflow/model.py", line 124, in _compile
    self._free_vars = tf.Variable(self.get_free_state())
  File "/home/ibcn/icouckuyt/projecten/GPflow/GPflow/param.py", line 751, in get_free_state
    return np.hstack([p.get_free_state() for p in self.sorted_params] +
  File "/home/ibcn/icouckuyt/projecten/GPflow/GPflow/param.py", line 245, in get_free_state
    return self.transform.backward(self.value.flatten())
  File "/home/ibcn/icouckuyt/projecten/GPflow/GPflow/transforms.py", line 231, in backward
    y = np.reshape(y, (N, N, self.num_matrices))
  File "/home/ibcn/icouckuyt/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 225, in reshape
    return reshape(newshape, order=order)
ValueError: total size of new array must be unchanged
```
I will take a more in-depth look when I have more time, and also post the full mnist_demo script. but if someone can pinpoint me the problem that would be great.

**Comment by jameshensman** [comment]
That stack looks like a bug in vec2tri, @markvdw ?

**Comment by markvdw** [comment]
This needs some revisiting. It's definitely `vec_to_tri`, raising the exception, but it could be a bug elsewhere ;)

**Comment by icouckuy** [comment]
The results of the mnist run without LowerTriangular().
`repeatIndex  0

Timing:  2091.12238097  s
percent  0.9782
cycle_diff  2092.96525788

repeatIndex  1

Timing:  3018.79640388  s
percent  0.978
cycle_diff  3020.58506393

repeatIndex  2

Timing:  4033.80502486  s
percent  0.9789
cycle_diff  4035.56956697

repeatIndex  3

Timing:  5032.007231  s
percent  0.9794
cycle_diff  5033.88060594

repeatIndex  4

Timing:  6034.48720789  s
percent  0.9793
cycle_diff  6036.31502199`

'Timing' is the optimization time. Cycle diff is the time of optimization + prediction.

And also the modified mnist_demo.py if it may help:
https://gist.github.com/icouckuy/740bb55b9a33226705f618e3d32d6173
Disregard me trying to set float32 in code. I had to change gpflowrc after all as modules set float_type on import.

**Comment by markvdw** [comment]
Ok, so for each repeat the speed is about 9.56 iter per second?

**Comment by alexggmatthews** [comment]
No longer relevant because of #430
