### ISSUE TITLE
gpflowrc missing when installing gpflow as a dependency

### ISSUE THREAD

**Issue by javdrher** [GPflow/GPflow#232]
I included gpflow as a dependency in setup.py of one of our projects (using dependency_links pointing to this github, as gpflow is not yet on pypi). When I pip install the project, I can not use it because of an error which is caused by a missing file: site-packages/GPflow/gpflowrc. 

This is strange as running `python setup.py install` (my guess is pip does that?) in a clone of this repository does copy the file. The only reason I could think of is that gpflowrc is not listed in MANIFEST.in. Could it be included in that file?

**Comment by jameshensman** [comment]
Thanks for the report, I hope this is fixed by #233 

Could you check that out and report back? Thanks.

**Comment by icouckuy** [comment]
We will test it soon and get back to you, but I can imagine it will (myself I use the git repo).

**Comment by javdrher** [comment]
works, file now pops up, is also listed in SOURCES.txt.
Any chance of having this functionality in the tf11 branch? (was previously cloning from that)

**Comment by javdrher** [comment]
Thanks, solved with #233
