### ISSUE TITLE
Issues with use of default graph

### ISSUE THREAD

**Issue by jameshensman** [GPflow/GPflow#235]
GPflow currently build all the models on Tensorflow's default graph, I think this causes some problems. 

I suspect that is causes the issues in this file: https://github.com/GPflow/GPflow/files/545876/mweHensman.tar.gz described by @icouckuy.

It also causes problems if one build many GPflow models, where the computation time grows superlinearly (I guess memory is consumed too). 

My proposed fix is to use a single graph for each model, and separate graphs for the autoflow functions.

**Comment by icouckuy** [comment]
@jameshensman did you test the MWE? As I made a simple mistake (a leftover from tensorboard, I thought I removed all those changes) and it seems to work now. Sorry for that.

However this issue still remains relevant and I am indeed concerned about what overfull graphs will do to computation time and memory speed. I plan to use GPflow in complicated setups running different modeling pipelines over a long time period (e.g., multi-objective expected improvement optimization completely in TF).

It is nothing I can solve in our code: in the worst case just clear the default graph each iteration or use 'with myGraph.as_default():' with every GPflow call. But it would be good if GPflow could think about this, for instance:
- Model._compile(): sets the free variable as a tf.Variable and calls mk_tf_array
- Autoflow: sets the free variables as tf.placeholder and calls mk_tf_array
- Similarly, I call build_predict(tf.Variable) when optimizing the expected improvement and build_predict(tf.placeholder) for, e.g., plotting purposes.

So using just one GPflow model already creates multiple tensor flows in the same graph. In fact they create exactly the same flow expect for one tensor (which is a tf.Variable or tf.placeholder).
- Can GPflow models free their graph when garbage collected? Or does tensorflow already takes care of that automatically?
- Is there a way to have the free variables as tf.Variable and tf.placeHolder at the same time as model attributes *without* updating them ever? mk_tf_array now overwrites it each time. If I could just get a existing tf.placeholder for the free vars after the optimization I can feed it to session.run directly when doing predictions.
- for the prediction points x I would just call build_predict twice (with tf.Variable and tf.placeholder) and cache those tensors, I can even keep them when updating the GPflow model with new data (assuming GPflow does not create a new tf.Variable for the free variables each time I call Model.optimize().

Sorry for the long explanation, I hope it is somewhat clear what I am aiming for. If I missed some feature of GPflow that can (partially) solve this I'd be happy to be corrected.

**Comment by jameshensman** [comment]
Thanks for the detailed explanation @icouckuy , 

You can find the beginning of my work to fix this in #239. The main focus is on keeping the AutoFlow and 'main' computation on separate tf.Graphs.

**Comment by icouckuy** [comment]
Thanks @jameshensman, that should be a step in the right direction. I was wondering what the rationale was behind the make_tf_vars scheme?

As TF variables are persistent they store the optimal kernel parameters after optimization and you do not have to convert them to placeholders for prediction. Params could simply create one tf.Variable once in the constructor. a Param.getTfVariable() could return it if fixed=False else return []. The TF optimizer accepts a var_list=self.getTfVariables()) so only the non-fixed parameters are optimized. Param.value= is a simply tf.assign operation run in place in __set_attribute.

Of course reuse of TF variables after optimization requires the prediction and Autoflow methods to use the same graph (so one graph per model).

**Comment by jameshensman** [comment]
hi @icouckuy 

Yes, that's a plausible scheme, but you are missing two important things:
1) the make_tf_vars also remaps the parameters to keep required parameters positive
2) when using the numpy/scipy optimizers, everything has to be in a single vector. The current scheme does this tensorflow-side, I think you would have to concatenate the parameters using numpy.hstack, which gets slow for moderately complicated models.

**Comment by alexggmatthews** [comment]
@jameshensman @icouckuy . To clarify are we agreed that #239 is an improvement on the current situation and should therefore be merged? It seems to deal with the main criticism in my opinion. Happy to keep this going as a discussion.

**Comment by icouckuy** [comment]
Hi @alexggmatthews ,  yes this can be merged. At the very least it is a lot cleaner, but by creating a new graph on each optimize it is easier to add summary ops too. I updated my TB branch which is pretty clean now.

**Comment by icouckuy** [comment]
> 1) the make_tf_vars also remaps the parameters to keep parameters positive if required
I don't see how that would be a problem? getTfVariable can return the variable to pass on to the TF optimizer. And another getter can return the transformed tensor in the build_ functions.

> 2) when using the numpy/scipy optimizers, everything has to be in a single vector. The current scheme does this tensorflow-side, I think you would have to concatenate the parameters using numpy.hstack, which gets slow for moderately complicated models.
What are the advantages of the scipy optimizers vs the TF optimizers? I read somewhere that you are considering porting GPML's minimize. If you already use TF for most calculations why then don't take full advantage of TF. I'm assuming this will be faster, and more scalable (as a sidenote, a multistart - parallel? - approach to the MLE is tempting).

Not sure about the speed of hstack but it will be indeed slower than slicing of course.

**Comment by icouckuy** [comment]
Actually, you need to run hstack once (getting the values of the current TF variables? Then in obj(x) slice them and pass them with feed_dict as different TF variables instead of a single one:
{TFVar1: x[slice1:], TFVar2: x[:slice2], etc}

**Comment by jameshensman** [comment]
... and then you will have to hstack the gradients in each iteration to pass them back to the optimizer.

**Comment by alexggmatthews** [comment]
#239 merged so I have removed the bug label here.

**Comment by icouckuy** [comment]
Right, forgot about the gradients. tf.gradients only returns a python list, not a numpy array.

**Comment by jameshensman** [comment]
I think this is largely fixed by recent PRs. Feel free to start another conversation, @icouckuy if there are still queries.
