### ISSUE TITLE
Error when computing log likelihood with prior

### ISSUE THREAD

**Issue by alexisboukouvalas** [GPflow/GPflow#256]
The MWE below results in 
TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("X:0", shape=(?, ?), dtype=float64) is not an element of this graph.
If the _compile call is commented in the code works.

```import GPflow
import numpy as np
N = 10
X = np.random.rand(N, 1)
Y = np.sin(X) + np.random.randn(N, 1)
ki = GPflow.kernels.Matern32(1)
m = GPflow.gpr.GPR(X, Y, ki)
print('needs recompile', m._needs_recompile)
objInt = m.compute_log_likelihood()-m.compute_log_prior()
# m._compile()
objInt = m.compute_log_likelihood()-m.compute_log_prior()
print('needs recompile now?', m._needs_recompile)```

**Comment by jameshensman** [comment]
I can simplify slightly

"""python
N = 10
X = np.random.rand(N, 1)
Y = np.sin(X) + np.random.randn(N, 1)
ki = GPflow.kernels.Matern32(1)
m = GPflow.gpr.GPR(X, Y, ki)

m.compute_log_likelihood()
m.compute_log_likelihood()
m.compute_log_prior()
# m._compile()
m.compute_log_likelihood()
"""
 It seems that a second call to the AutoFlow function fails if there's another AutoFlow in the middle. I agree that this is a bug.
