### ISSUE TITLE
Why no whitening in KL divergences?

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#260]
Looking at kullback_leiblers.py we currently don't whiten the matrices before taking the Cholesky decomposition:

https://github.com/GPflow/GPflow/blob/master/GPflow/kullback_leiblers.py

It does't seem to be causing an issue but is there a strategic reason for this?

**Comment by jameshensman** [comment]
Not that I can think of. I suppose we should really be adding jitter in there for consistency.

**Comment by alexggmatthews** [comment]
Its the sort of thing that could make small changes to the behaviour of people's existing models. So it is worth thinking about what would be a good set of tests for this.  It might improve issues like #78 .

**Comment by alexggmatthews** [comment]
@jameshensman  another thing to consider. Why did we whiten by an absolute amount? We could for instance add 

`eye(num_data) * max(max(Kmm))*settings.numerics.jitter_level`

This would be invariant to changes in the units of Kmm , which would make us robust against imperfect data rescaling during preprocessing.
