### ISSUE TITLE
Ability to initialise likelihood params

### ISSUE THREAD

**Issue by thangbui** [GPflow/GPflow#264]
I think it would be great if the likelihood params can be initialised with non-default values, like how the kernel functions are handled (e.g. you can pass variance=some_value and lengthscales=some_values into the RBF constructor).

The default variance for the Gaussian likelihood is 1 which is too big(!) for many datasets and consequently makes VI prefer a local minimum that uses the noise to explain the data and reverts the q to the prior.

Cheers,
Thang.

**Comment by jameshensman** [comment]
Hi Thang, 

Yes, good plan. PR welcome!

In the meantime, I'm sure you already have a workaround such as 
```python
like = GPflow.likelihoods.Gaussian()
like.variance = 0.01
m = GPflow.svgp.SVGP(X, Y, kernel, like)
```
James.

**Comment by icouckuy** [comment]
A minor difference, but I just set everything just before calling optimize. I think it's supposed to be like that. Just remember it's python we are talking about, there is no private stuff.

```
m = GPflow.svgp.SVGP(X, Y, kernel, like)
m.likelihood.variance = 0.01
m.kern.variance = 666.6
m.optimize()
```

**Comment by st--** [comment]
GPflow master has likelihoods with parameter defaults supplied to `__init__`.
