### ISSUE TITLE
readme doesn't quite tell you how to install

### ISSUE THREAD

**Issue by danstowell** [GPflow/GPflow#267]
Hi - I'm reading the readme online on github. Under the "install package" heading it basically just says to execute "python setup.py develop" - but you haven't told the reader how to _get_ GPflow yet!

One presumes that your preferred way of working at the moment is for people to clone the repository. (The master branch? ... Guess so!) You might like to state that step.

**Comment by alexggmatthews** [comment]
Hi, @danstowell sure we can do that.
