### ISSUE TITLE
docs should include reference to GPLVM methods

### ISSUE THREAD

**Issue by jameshensman** [GPflow/GPflow#279]
Hi @alexisboukouvalas , 

You noted that the docs don't include a reference to the GPLVM yet, even though there is a notebook. 

The way to add the notebook to the docs is to modify doc/source/index.rst. It will be obvious how to add the notebook when you open the file :)

You could also modify doc/source/intro.rst, thich contains some description of the project, and what's included. Suggest you update this also. 

To build the docs, install the dependencies
```
pip install sphinx nbsphinx numpydoc
```
Then from the doc directory, type `make html` and the open doc/build/index.html

Once the edits are pushed to master, they will appear automatically within a few minutes on readthedocs.org. If you'd like access to GPflow on readthedocs.org, which will let you automatically build docs on branches, make an account there and I will give you access. 
James.

**Comment by alexisboukouvalas** [comment]
I think this is a bug as intro.rst points to the GPLVM notebook.
