### ISSUE TITLE
Implement FITC for regression in GPflow

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#29]
Although I prefer the Titsias method for a number of reasons, many people still want to compare to FITC which was first created by Snelson and Ghahramani 2006 Sparse Gaussian Processes using Pseudo-inputs. Therefore I am going to implement it in GPflow.

**Comment by jameshensman** [comment]
Perhaps this lives in the sgpr.py file?

Or perhaps we should have a GPflow/sandbox project. I'm working on
similarly related things at the moment.

James.

**Comment by alexggmatthews** [comment]
sgpr.py is fine by me. Don't want to repeat work. Are you happy for me to do this bit?

**Comment by jameshensman** [comment]
Oh please do.

**Comment by alexggmatthews** [comment]
This is now being discussed in #37
