### ISSUE TITLE
GPflow @ NIPS 

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#290]
I will be going to all of NIPS 2016 ( https://nips.cc/ )  if you want to talk about the GPflow project. Feel free to contact me via my webpage if you want to chat:

http://mlg.eng.cam.ac.uk/?portfolio=alex-matthews

**Comment by alexggmatthews** [comment]
@jameshensman did you decide if you were coming to the workshops in the end?

**Comment by alexggmatthews** [comment]
@markvdw are you coming?

**Comment by markvdw** [comment]
I'll be there!

**Comment by javdrher** [comment]
I'll be at NIPS from Ghent University and it would be great to have a chat. Today @icouckuy is also going to update me on some of his questions.

**Comment by jameshensman** [comment]
I'll not be there, you guys have a great time.

**Comment by alexggmatthews** [comment]
@markvdw great!
@jameshensman shame - hope it went well in Germany. 
@javdrher I'm happy to meet if you email me (am554 -at - cam.ac.uk ) and suggest a couple of times.
