### ISSUE TITLE
Installation issues: windows10

### ISSUE THREAD

**Issue by cstah** [GPflow/GPflow#295]
Hi all.

I'm running tensorflow on windows 10 and I would very much like to try the GPflow framework.
I have tried to run the setup.py but I can see that the setup.py currently only distinguish between mac and linux, which makes perfectly sense as the tensorflow for windows was just released ~2 weeks ago.

Any suggestions on how I can get GPflow up running on my windows installation?
What should I modify in setup.py (the compile command) in order to be able to build GPflow successfully.

I get the following error message after executing "import GPflow":

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Carsten\GPflow\GPflow\__init__.py", line 18, in <module>
    from . import likelihoods, kernels, ekernels, param, model, gpmc, sgpmc, priors, gpr, svgp, vgp, sgpr, gplvm, tf_wraps, tf_hacks
  File "C:\Users\Carsten\GPflow\GPflow\likelihoods.py", line 17, in <module>
    from . import densities, transforms
  File "C:\Users\Carsten\GPflow\GPflow\transforms.py", line 18, in <module>
    from . import tf_wraps as tfw
  File "C:\Users\Carsten\GPflow\GPflow\tf_wraps.py", line 32, in <module>
    _custom_op_module = tf.load_op_library(os.path.join(os.path.dirname(__file__), 'tfops', 'matpackops.so'))
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: C:\Users\Carsten\GPflow\GPflow\tfops\matpackops.so not found

**Comment by jameshensman** [comment]
Hi @cstah , 

The error message you provided indicates that the binary blob 'matpackops.so' can't be found. This might be because
 - The file should be called `matpackops.dll`
 - The file has not been compiled at all
 - both of the above. 

Inside setup.py, we compile some extensions following the tensorflow tutorial https://www.tensorflow.org/versions/r0.12/how_tos/adding_an_op/index.html#adding-a-new-op

There don't seem to be any windows specific options in the tutorial yet. My suggestion is that you follow that tutorial, adapting the compile steps for compilation on windows, and then report back here so we can work out how to modify setup.py together.

**Comment by vals** [comment]
I'm not sure if your error message has to do with the custom ops, but currently, custom ops aren't supported in the Windows build of Tensorflow: https://github.com/tensorflow/tensorflow/blob/r0.12/RELEASE.md#release-0120

> TensorFlow now builds and runs on Microsoft Windows (tested on Windows 10, Windows 7, and Windows Server 2016). Supported languages include Python (via a pip package) and C++. CUDA 8.0 and cuDNN 5.1 are supported for GPU acceleration. **Known limitations include: It is not currently possible to load a custom op library**. The GCS and HDFS file systems are not currently supported. The following ops are not currently implemented: Dequantize, QuantizeAndDequantize, QuantizedAvgPool, QuantizedBatchNomWithGlobalNormalization, QuantizedBiasAdd, QuantizedConcat, QuantizedConv2D, QuantizedMatmul, QuantizedMaxPool, QuantizeDownAndShrinkRange, QuantizedRelu, QuantizedRelu6, QuantizedReshape, QuantizeV2, RequantizationRange, and Requantize

**Comment by cstah** [comment]
Hi @jameshensman and @vals 
Thanks for the replies. Seems as I need to wait until tensorflow supports custom ops. In the mean time I think I will try an alternative installation of GPflow/tensorflow on my bash-on-ubuntu-on-windows installation.
Carsten

**Comment by vals** [comment]
@cstah I can confirm this works fine! Though there are some weird inconsistencies about file persistence.

**Comment by cstah** [comment]
@vals Thanks.

**Comment by mrksr** [comment]
Just a quick note: After the merge of #440, installing GPflow on Windows just works now. The test suite also passes.
