### ISSUE TITLE
Pull requests need to be up to date with master?

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#32]
At the moment we are able to merge a PR if it has no merge conflicts with the master branch.

The problem with this is that we run the tests on code that isn't actually what ends up master. Hence the PR tests could pass but master could fail. 

We had a recent example of this when the unit tests became too long for Travis and this wasn't spotted before it took down master. 

I wonder: Is it possible to get Travis to merge from master then run the tests? This would mean that what you see when you look at the results of tests is what you get.

**Comment by alexggmatthews** [comment]
OK I have added some checks to master branch. To view them look here. 

https://github.com/GPflow/GPflow/settings/branches/master

**Comment by jameshensman** [comment]
Looks good, let's tick that 'include administrators' box too.

**Comment by alexggmatthews** [comment]
It looks as though it is still possible to merge even if there are commits on master that aren't on the PR as long as there are no merge conflicts. So we still haven't quite got the behaviour we want.

**Comment by jameshensman** [comment]
Hmmn, I guess it's an unusual case that an automatic merge could take two
branches which both pass and create one that fails. That's what happened to
us, but only because of the increased build time. Perhaps we should't worry
about it unless it becomes a recurring problem.

**Comment by alexggmatthews** [comment]
I guess but we're still quite close the timeout threshold. Let's see what happens.
