### ISSUE TITLE
Independent hyperparameters for multiple independent outputs

### ISSUE THREAD

**Issue by robertocalandra** [GPflow/GPflow#323]
Hi,
I am trying to train a model with multiple output (i.e., Y is a matrix), with a simple kernel (e.g., RBF). 
According to [the documentation](http://gpflow.readthedocs.io/en/latest/model_options.html#module-GPflow.gpr), I should be able to simply give a Y matrix at training time to train multiple independent GP. However, I noticed that when doing so the hyperparameters of the kernel are shared between the output covariates (and trained jointly). 
Is there a way to have independent hyperparameters (or even different kernels) for each independent output covariate? 
Sorry for the silly question and thank you for you help! :)

PS: is there a function to extract all the hyperparameters at once in a matrix form? I wrote my own piece of code for doing this, if it is useful I can push it.

**Comment by Bonnevie** [comment]
Most of the standard models implemented take a single kernel _instance_ as input, meaning that all hyperparameters have already been set up by the time you initialize the model. So there's no way to get more hyperparameters.
The easiest way to handle this would be to just split Y into columns and train a GP on each column independently. Is this not sufficient for your purposes?

For getting all parameters out of a model it looks like `get_parameter_dict` or `sorted_params` is the way to go.

**Comment by jameshensman** [comment]
First thing would be to fit al the models separately, like @Bonnevie suggests. 

Another thing to do would be build a 'super' model that contains the model for each column. I wrote a snippet for that in #297 , here it is again:

```python
import GPflow
from functools import reduce

X1, Y1, X2, Y2 = my_data_loading_function()
m1 = GPflow.gpr.GPR(X1, Y1, GPflow.kernels.Matern32(1))
m2 = GPflow.gpr.GPR(X2, Y2, GPflow.kernels.Matern32(1))

class ProductModel(GPflow.model.Model):
    def __init__(self, models):
        GPflow.model.Model.__init__(self)
        self.models = GPflow.param.ParamList(models)

    def build_likelihood(self):
        return reduce(tf.add, (m.build_likelihood() for m in self.models))


m = ProductModel([m1, m2])
m.optimize()  # works as expected
print(m) 
```

**Comment by jameshensman** [comment]
> is there a function to extract all the hyperparameters at once in a matrix form?

We have `m.get_free_state()` and `m.get_parameter_dict()`, what else could you possibly need ;)

**Comment by robertocalandra** [comment]
Ok, I created a super class with a separate model for each output covariate. Thank you for the snippet of code (especially for building the likelihood) :)

and yes, `m.get_free_state()` worked perfectly (after converting back with Log1pe)

Since this kind of model is quite common in practice, it might be valuable for future users to either create an official wrapper or to bring it as an example in the documentation

Anyway, thank you very much for you help :) So far I am liking the GPFlow codebase, it is quite neat!
