### ISSUE TITLE
Numerical conditioning of matrix inversion in implementation of Titsias' regression method

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#33]
This question is directed a @jameshensman specifically.

In the explanation of Titsias' method given in notebooks/SGPR notes.ipynb it says the following

Now to obtain a better conditioned matrix for inversion we rotate by L where LL^T = Kuu .

Could you explain a bit more about why the rotated matrix will be better conditioned please? I'm happy to add the answer to the notebook if you like.

**Comment by jameshensman** [comment]
the matrix $$[ K_{uu} + K_{uf} K_{fu}\sigma^{-2}]^{-1}$$ might be nasty to invert. After multiplying by L, we end up with $$[I + A A ^T]$$, whose eigenvalues are bounded. Does that help?

**Comment by alexggmatthews** [comment]
Yes it does. Thank you. I am reminded that this is explained in section 3.4.3 of GPML which can be found here:

http://www.gaussianprocess.org/gpml/chapters/RW.pdf
