### ISSUE TITLE
Benchmark between GPy and GPflow

### ISSUE THREAD

**Issue by junpenglao** [GPflow/GPflow#331]
Hi there,
I have been using GPy for some high dimension problem and sometimes they are quite slow. Is there any speed advantage of using GPflow? Do you have a benchmark comparison between the two?
This is not really a bug/issues so if it is not appropriate here I can delete it.

**Comment by alexggmatthews** [comment]
GPflow will be about the same as GPy on a small number of CPUs. GPflow has a big variety of GPU code which is a benefit of using TensorFlow. Using a GPU you will be able to get the most speed up if you are using float32 (or possibly a Pascal GPU though I haven't been able to try it) . We have some benchmarks but would like to increase them. See also the Arxiv paper:

https://arxiv.org/pdf/1610.08733v1.pdf

**Comment by junpenglao** [comment]
Great thanks a lot!

**Comment by vals** [comment]
Just adding in case you're interested. I did a benchmark a while ago for a particular model (hierarchical GP) that (I was surprised to find) was a fair bit quicker on GPflow than GPy on CPU.

![nobs_vs_runtime](https://cloud.githubusercontent.com/assets/668803/22648321/ffad79fa-ec6d-11e6-8d57-b415205ad0a4.png)

This is wall-clock times and include stuff like initialising classes etc. But generally I find GPy quite slow in comparison... I might have a bad installation of it. (The green dots are almost an order of magnitude faster than the red dots)

**Comment by junpenglao** [comment]
>  I did a benchmark a while ago for a particular model (hierarchical GP)...  
Thanks vals, do you have some code snippet or notebook for the hierarchical GP you are doing? I am trying to do some hierarchical modelling as well - will greatly appreciate if you could share some of your experience!

**Comment by vals** [comment]
The entire analysis is a bit messy and currently split between a few different ongoing projects..

But I can paste in the (simple) GPflow implementation of the hierarchical kernel I used below here:

    class Hierarchical(GPflow.kernels.Combination):
        '''
        Kernel for hierarchical models

        Hensman et al 2013, "Hierarchical Bayesian modelling of gene expression time
        series across irregularly sampled replicates and clusters"
        http://www.biomedcentral.com/1471-2105/14/252

        The active_dims argument to the underlying kernels inform the kernel which
        columns of X to use to calculate covariance.

        The list indicator_dims tells the kernel which columns of X to use for
        indicating batches.

        Example initialization:

            k = Hierarchical([GPflow.kernels.RBF(1, active_dims=[0]),
                            GPflow.kernels.RBF(1, active_dims=[0])], indicator_dims=[1])
        '''
        def __init__(self, kern_list, indicator_dims=[1]):
            GPflow.kernels.Combination.__init__(self, kern_list)
            self.indicator_dims = indicator_dims

        def K(self, X, X2=None):
            K = self.kern_list[0].K(X, X2)

            if X2 == None:
                X2 = X

            for i, ind_dim in enumerate(self.indicator_dims):
                indX, indX2 = X[:, ind_dim:ind_dim + 1], X2[:, ind_dim:ind_dim + 1]
                mask = tf.to_double(tf.equal(indX, tf.transpose(indX2)))

                k = self.kern_list[i + 1]

                K += mask * k.K(X, X2)

            return K

        def Kdiag(self, X):
            return tf.diag_part(self.K(X))

I haven't contributed it because it does some hard-coding I'd prefer to avoid in a final version.

**Comment by junpenglao** [comment]
@vals Is it work in a way similar to `GPy.mappings.compound`?

**Comment by junpenglao** [comment]
@vals Actually it is quite clear from the paper. Thanks again for the code!

**Comment by vals** [comment]
@junpenglao Hm I'm not familiar with the compound mapping. Though it looks like something I should look in to.

The code I pasted is a simple port of this: https://github.com/SheffieldML/GPy/blob/devel/GPy/kern/src/independent_outputs.py#L155

aka `GPy.kern.Hierarchical`

**Comment by junpenglao** [comment]
@vals LOL somehow I completely miss that! Thanks again!
