### ISSUE TITLE
Use tf distributions once they make it into tf main

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#332]
@dustinvtran suggests the following in #322
`
As another example, instead of coding up a separate densities.py and transforms.py, it would be nice to take advantage of the distributions and Bijectors class in tf.contrib.distributions. These are more comprehensive in robustness and vectorization. As tf.contrib.distributions is moving soon into core TensorFlow, it will continue to be expanded upon as the official distribution (and transformations) library.`

I think this would be worth considering once they are into the core tf code as we can then be sure of the test coverage.

**Comment by goldingn** [comment]
Just a heads up that some of the darker corners ([one](https://github.com/tensorflow/tensorflow/issues/10131), [two](https://github.com/tensorflow/tensorflow/issues/10149)) of that module are a bit buggy at present. Hopefully they'll be fully tested when they move to main, but something to watch out for!

**Comment by alexggmatthews** [comment]
As an update the tensorflow distributions library has made a lot of progress recently and now has a long description that can be found here:
https://t.co/S1PuBVC1kA

**Comment by alexggmatthews** [comment]
It expect we would make gains in terms of composability with native tensorflow and speed if we incorporated it. 
@goldingn how has your experience been with this recently?

**Comment by goldingn** [comment]
Awesome! I haven't taken a look in a while, but am thinking of switching over myself now

**Comment by markvdw** [comment]
There are more recent discussions of this.
