### ISSUE TITLE
Constrain to interval transform

### ISSUE THREAD

**Issue by markvdw** [GPflow/GPflow#334]
Is there a transform in GPflow that constrains a parameter to a particular interval? I'd be happy to contribute.

**Comment by jameshensman** [comment]
Clearly this transform could do with a docstring :(

https://github.com/GPflow/GPflow/blob/master/GPflow/transforms.py#L147

**Comment by markvdw** [comment]
Wow I stared at the code, but was looking for words. I'll add that.
