### ISSUE TITLE
GPflow logo

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#338]
I think we could do with a better GPflow logo. Suggestions appreciated! Maybe we should also do T-shirts for the next conference.

**Comment by mathDR** [comment]
@alexggmatthews where is the current logo?

**Comment by jameshensman** [comment]
go to github.com/GPflow, observe the "red six" near the top that I threw up as a temporary logo (it's an inducing point in an mnist classifier)

**Comment by mathDR** [comment]
Is this too literal?  (I have a big spark job running and had some time on my hands =P )
[GPFlow.pdf](https://github.com/GPflow/GPflow/files/777776/GPFlow.pdf)

**Comment by alexggmatthews** [comment]
That's cool I think my first thought was for something more classic, though:

![simplelogo](https://cloud.githubusercontent.com/assets/6596998/23020514/5a9217da-f43f-11e6-87a6-351bea8d6662.png)

**Comment by alexggmatthews** [comment]
We could potentially add an arrow to the bar of the "f" and add a bounding box.

**Comment by jameshensman** [comment]
Alright here's my lame attempt
![gpflow](https://cloud.githubusercontent.com/assets/154383/23022520/32a837fe-f449-11e6-97c8-03c4b9e8a5cf.png)

**Comment by jameshensman** [comment]
I do like the \mathcal{GP}, @alexggmatthews

**Comment by nknudde** [comment]
Since you all seem so enthusiastic about the new logo, I decided to give GPflow a shot at it.

![figure](https://cloud.githubusercontent.com/assets/25064436/23031484/69077c88-f471-11e6-8f08-1d9669d3d6c5.png)

**Comment by markvdw** [comment]
That's really cool! Is this multi-output regression for a 1D input?

**Comment by nknudde** [comment]
Yes, I drew some points sequentially, put the coordinates in a regular GPR model and drew some samples from the predictive distribution.

**Comment by icouckuy** [comment]
I do miss some color though. Nicolas, maybe we can assign a colormap to the likelihood of each sample drawn (or just two colors , for the MLE and the other samples)

**Comment by nknudde** [comment]
Marbe you are looking for something like this @icouckuy ?
![gp](https://cloud.githubusercontent.com/assets/25064436/23037850/2c94a8d6-f488-11e6-98ea-4eabc613db25.png)

**Comment by mathDR** [comment]
@nknudde Did you generate that with a bunch of draws?  That is pretty cool...

**Comment by nknudde** [comment]
Yes @mathDR, the thick line is the mean and the thin lines are a bunch of draws

**Comment by awav** [comment]
:) had fun with logo too, here is my attempt:

![gpflow-2](https://user-images.githubusercontent.com/24483645/28896978-a98e3042-77d6-11e7-9dcf-ea3099503e33.png)

**Comment by jameshensman** [comment]
That is very cool!

**Comment by alexggmatthews** [comment]
@awav that is a good effort.

**Comment by awav** [comment]
My Adobe Illustrator trial version expires by tomorrow, so here is another version:
<img width="396" alt="gpflow-logo-2" src="https://user-images.githubusercontent.com/24483645/29041868-67650e3c-7bac-11e7-842c-5f81858dd2eb.png">

**Comment by markvdw** [comment]
I love it.

**Comment by alexggmatthews** [comment]
Even better - but might have to check the copyright :)

**Comment by awav** [comment]
@alexggmatthews hah, GPflow is built on top of TensorFlow to take an advantage :) Here is the same.

**Comment by st--** [comment]
GPflow does have a new logo now (and there were t-shirts at NeurIPS last year)...
