### ISSUE TITLE
Question about test_method_equivalence unit test. 

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#34]
Here:

https://github.com/GPflow/GPflow/blob/master/testing/test_method_equivalence.py#L26

Some of the methods are given an additional white noise term in the kernel and some are not. Why?

**Comment by jameshensman** [comment]
These were initially necessary to maintain stability of the code. They don't seem to have any effect, so I removed them from both the test and the SanityCheck notebook, see PR #35
