### ISSUE TITLE
maxiter deprecation warning

### ISSUE THREAD

**Issue by dcam0050** [GPflow/GPflow#369]
Hi, I've been trying out the tutorial notebooks that come with the master branch in the doc folder ... specifically 
`master/doc/source/notebooks/GPLVM.ipynb`
`master/doc/source/notebooks/coreg_demo.ipynb`
`master/doc/source/notebooks/classification.ipynb`

and I get the following error when issuing the call to model.optimise:

```/home/daniel/HBP/GPflow/GPflow/model.py:288: VisibleDeprecationWarning: Use `maxiter` instead of deprecated `max_iters`.
warnings.warn("Use `maxiter` instead of deprecated `max_iters`.", np.VisibleDeprecationWarning)```

(function trace)

``` InvalidArgumentError (see above for traceback): partitions[0] = -13628892 is not in [0, 2) [[Node: model.build_likelihood/model.likelihood.variational_expectations/DynamicPartition_2 = DynamicPartition[T=DT_DOUBLE, num_partitions=2, _device="/job:localhost/replica:0/task:0/cpu:0"](model.build_likelihood/model.likelihood.variational_expectations/transpose_2/_89, model.build_likelihood/model.likelihood.variational_expectations/Cast/_79)]] ```

I have just installed it today and ran all the tests which returned ok. My tensorflow version is 1.0.0 which as I understand from travis.yml is the current supported version. I have the gpu version installed. 

Any pointers? Thanks!

**Comment by alexggmatthews** [comment]
Hi Daniel, This looks like a bug to me. We will look into it.

**Comment by alexggmatthews** [comment]
@dcam0050 I'm not able to replicate this in the classification notebook. To chase this down I'm going to need to know more about your setup. Is it possible you are using the release candidate version of tf 1.0.0 by any chance?

**Comment by dcam0050** [comment]
How can I check if I'm using the release candidate?

**Comment by dcam0050** [comment]
I've updated tensorflow from 1.0.0 to 1.0.1 and everything works great. Thanks!
