### ISSUE TITLE
Run notebooks in tests

### ISSUE THREAD

**Issue by alexisboukouvalas** [GPflow/GPflow#373]
Run all notebook code in tests. Perhaps with ability to blacklist heavy notebooks.
This issue based on discussion in #371 

What is a good way to accomplish this?

**Comment by jameshensman** [comment]
http://blog.thedataincubator.com/2016/06/testing-jupyter-notebooks/

**Comment by jameshensman** [comment]
this is done, thanks to you @alexisboukouvalas
