### ISSUE TITLE
How to use tf optimizer?

### ISSUE THREAD

**Issue by bin-yan** [GPflow/GPflow#378]
Can anyone give a code example of how to use a tensorflow optimizer in m.optimize()?

I am reading Alexander Matthews' [thesis](http://mlg.eng.cam.ac.uk/matthews/thesis.pdf). On page 102 it says "GPflow uses TensorFlow for its core computations rather than numeric Python". So what part of "core computations" relies on TensorFlow instead of numeric Python? The Cholesky decomposition? If I just use a scipy optimizer as shown in the GPflow tutorial, does my GP regression model use any TensorFlow neural network features at all? Thanks!

**Comment by jameshensman** [comment]
http://gpflow.readthedocs.io/en/latest/notebooks/svi_test.html

No neural network features are used, since there are no neural networks in GPflow. But all of the computations are done using tensorflow, if that's what you're asking.
