### ISSUE TITLE
Keyword Arguments for AutoFlowed Functions

### ISSUE THREAD

**Issue by mrksr** [GPflow/GPflow#383]
Hello everyone!

The Problem
---
While playing with one of my models, I had a few issues with the (very convenient) AutoFlow, previously discussed in #178, namely, that a AutoFlowed function only takes arguments which are converted to tensorflow-variables. While this is usually enough, it gets a bit tricky when some function interacting with tensorflow has multiple (usually boolean) arguments which slightly alter their behaviour. An example in the current GPflow code can be seen in model.py, where the two functions
```python
    @AutoFlow((float_type, [None, None]))
    def predict_f(self, Xnew):
        return self.build_predict(Xnew)

    @AutoFlow((float_type, [None, None]))
    def predict_f_full_cov(self, Xnew):
        return self.build_predict(Xnew, full_cov=True)
```
only differ in a boolean argument.

This workaround becomes an issue in two cases:

1) A function which takes multiple boolean arguments.
2) A function which takes (say) a constant float as an argument (think quantiles).

In the first case, a rather large number of function is needed to cover all possible boolean combinations and in the second case I am not aware of a workaround other than doing things on the tensorflow side, which might incur a runtime cost.

Wrong solution
---
An obvious thing to try is to just cache the keyword arguments via a wrapper function, like this:
```python
    def predict_f(self, Xnew, **kwargs):
        @AutoFlow((float_type, [None, None]))
        def _predict_f(self, Xnew):
            return self.build_predict(Xnew, **kwargs)

        return _predict_f(self, Xnew)
```
While this seems to work on first glance, it only does so with the first set of keyword arguments, because of AutoFlow's internal caching of the tensorflow graph. Additionally, the name of the internal wrapper function (`_predict_f`) needs to be unique in the class-scope, since otherwise graphs are shared between functions with no shared visibility in the code. In short: this does not work.

My current solution
---
The problem with the wrong solution is the way Autoflow does caching. The map from function names to graphs is done using the name of the function only, see [param.py#L515](https://github.com/GPflow/GPflow/blob/master/GPflow/param.py#L515):
```python
storage_name = '_' + tf_method.__name__ + '_AF_storage'
```
The goal therefore is to have every cached function wrapper to have a unique name, dependent on the kwargs. Inspired by [functools.lru_cache](https://docs.python.org/3/library/functools.html#functools.lru_cache) via [stackoverflow](http://stackoverflow.com/a/10220908), I came up with my rather hacky solution of an additional decorator (which might be incompatible to python 2.7 in the current formulation).
```python
def pass_to_unique_name(**kwargs):
    suffix = hash(tuple(sorted(kwargs.items())))
    def unique_decorator(func):
        @wraps(func)
        def func_wrapper(*inner_args, **inner_kwargs):
            return func(*inner_args, **inner_kwargs, **kwargs)

        func_wrapper.__name__ = '{}_{}'.format(func.__name__, suffix)
        return func_wrapper

    return unique_decorator
```
With this decorator, the previously incorrect solution looks like this:
```python
def predict_f(self, Xnew, **kwargs):
    @AutoFlow((float_type, [None, None]))
    @pass_to_unique_name(**kwargs)
    def _predict_f(self, Xnew, **other_kwargs_name_for_clarity):
        return self.build_predict(Xnew, **other_kwargs_name_for_clarity)

    return _predict_f(self, Xnew)
```
With this definition, code like this works:
```python
_ = model.predict_f(Xnew, full_cov=False)
_ = model.predict_f(Xnew, full_cov=True, some_other_param=(3., True))
```
For every set of parameters, a new graph has to be built but the caching still works thanks to the deterministic name the decorator creates.

I currently use this decorator to scratch my own itch but I thought it might be interesting to you. I'd appreciate any thoughts :). I am also quite sure that there is a more elegant implementation for this.

**Comment by jameshensman** [comment]
Hi!

Sorry for delaying in replying to this. I had to summon enbough time to be able to write a response that such effort deserved. 

Non-tf args in AutoFlow have been requested a couple of times, and this is the best attempt I've seen at making them work. I think the memoizing is probably the main difficulty, and yopu seem to have cracked that. 

I think I would probably choose a differnt syntax, though. Perhaps this:

```python
@GPflow.AutoFlow(X=(tf.float64, [None]), Y=(tf.int32, [2, 2]))
def myfunc(X, Y, Z, W):
    if Z:
        return foo(X)
    if W:
       return foobar(Y)
```
In this (hypothetical) example, X and Y get "autoflowed", the other arguments Z and W do not. I think would create a really nice syntax for autoflow. 

The two challenges in this are (1) memoizing graphs based on the arguments Z and W (which I think your code solves, @mrksr ?) and introspection of `myfunc` inside the AutoFlow decorator. I did have a play with that, the introspect module looks like a lot of fun, but I don;t have time for it right now.

**Comment by mrksr** [comment]
Memoizing the graphs works fine as long as the (keyword-)arguments are hashable. Some notable none-hashable things are lists, dicts, sets and numpy arrays. A tuple is hashable however and can be used to represent the collections if necessary.

I like your proposed syntax. I chose my rather roundabout approach to avoid having to patch GPflow. By introspection you mean the need to manipulate (only part of) the arguments when the function is called?

I will take a stab at implementing this properly when #356 is done.

**Comment by mrksr** [comment]
I played a bit with the inspection-part of the problem and I think it can be done fairly elegantly, like so:
```python
import inspect
from functools import wraps


def replace(**replacements):
    def decorator(method):
        @wraps(method)
        def wrapper(*args, **kwargs):
            original_parameters = inspect.signature(method).parameters

            call_params = {**dict(zip(original_parameters.keys(), args)), **kwargs} # 3.6 only
            print('would call:', call_params)

            replaced_params = {**call_params, **replacements} # 3.6 only
            print('will call:', replaced_params)

            method(**replaced_params)

        return wrapper
    return decorator


@replace(a='hi there', d='this is fun')
def func(a, b, c='c', d='d'):
    print(a, b, c, d)


func(2, b=3)
```
with output:
```
would call: {'a': 2, 'b': 3}
will call: {'a': 'hi there', 'b': 3, 'd': 'this is fun'}
hi there 3 c this is fun
```

Inspection is basically only needed to match the `*args` with the name of their parameter in order to be able to replace them. Not sure if this can be avoided, so this is a work in progress. Also, for brevity, I am using some python 3.6 syntax here. In GPflow this would be a bit longer.
