### ISSUE TITLE
Update TF version for install instructions in readthedocs

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#386]
Currently says tf0.12 should be tf1.

**Comment by mrksr** [comment]
I changed those in #342, so it should be enough to remake the docs I guess.

**Comment by alexggmatthews** [comment]
Thanks @mrksr I tried to rebuild and found that readthedocs gives an error on tensorflow 1.00 

`tensorflow-1.0.0-cp34-cp34m-linux_x86_64.whl is not a supported wheel on this platform.`

I will look into it.

**Comment by alexggmatthews** [comment]
This looks to be an easy fix, we've simply ended up with py 3.4 in docs_require rather than py 3.5 I will do a PR.
