### ISSUE TITLE
Initialising GP regression model with no data

### ISSUE THREAD

**Issue by paruby** [GPflow/GPflow#390]
Hey all!

I'd like to initialise a GP regression model _without_ data so that I can draw samples from the GP prior without having conditioned on data. A simple example of something like what I'd like to run:

```
import GPflow
import numpy as np

X = []
Y = []
m = GPflow.gpr.GPR(X, Y, kern=GPflow.kernels.Matern32(1))
```

But running the above code throws an error. It is possible to run 

```
X = np.array([[]])
Y = np.array([[]])
m = GPflow.gpr.GPR(X, Y, kern=GPflow.kernels.Matern32(1))
```

without getting an error, but then trying to get the GP predictions throws an error:

```
xx = np.linspace(-6,6,100)[:,None]
m.predict_f(xx)
```

Is this possible?

[EDIT: corrected typo in second code block. Code still throws error ;) ]

**Comment by mrksr** [comment]
My simple but hacky solution to this problem: Add a single point far away from the data.
```python
X = np.array([[-1e6]])
Y = np.array([[0.]])
m = GPflow.gpr.GPR(X, Y, kern=GPflow.kernels.Matern32(1))
```
Depending on your choice of kernel, this might be problematic of cause, say for a periodic kernel. But for stationary kernels, this should work fine.

**Comment by paruby** [comment]
Thanks very much @mrksr ! This should work for my immediate application. But it would also be good to know a more elegant solution for the future.

**Comment by alexisboukouvalas** [comment]
I usually sample from the kernel directly:
```
    ''' Sample GP, D is number of independent output dimensions '''
    kern = GPflow.kernels.Matern32(1)
    K = kern.compute_K(X, X)  # NxM
    L = np.linalg.cholesky(K + np.eye(K.shape[0]) * tol)
    samples = L.dot(np.random.randn(L.shape[0], D))
```

**Comment by alexggmatthews** [comment]
Hi Paul, did that work OK for you? If so I will close the issue.

**Comment by paruby** [comment]
Yes, all is good!
