### ISSUE TITLE
Changing dtype after import

### ISSUE THREAD

**Issue by befelix** [GPflow/GPflow#396]
It seems like it is not possible to change the dtype after importing the library. I think the main reason is
```
float_type = settings.dtypes.float_type
np_float_type = np.float32 if float_type is tf.float32 else np.float64
```
at the beginning of several files, which gets run at import-time and fixes the dtypes. It would be nice if it was possible to change the dtype without editing a settings file.

**Comment by markvdw** [comment]
I've noticed this too, it's minor, but if there's an elegant solution, I don't see why this couldn't be improved. It's useful for people using GPs heavily in practice.

I think the only way to fix this is to reference `settings.dtypes.float_type` like you suggest. It's a bit ugly though...

I was also thinking that an alternative solution would be to have each `Model` object make a copy of the settings and use the local one. The problem with this is that other functions like `conditional()` rely on the global settings... If this were to be implemented, all functions would require passing the local settings object around. This really isn't an option, as it would leave far too much room for bugs (e.g. if the wrong settings is passed, or none at all...).

**Comment by befelix** [comment]
I agree that it's annoying to reference them like this - somehow what you would want is a pointer to the float_type. The closest thing to that in Python is a list - so I guess one could do something like
`dtypes = settings.dtypes` and then get the dtypes from `dtypes.float_type` and `dtypes.float_type.as_numpy_dtype`. Another appealing thing could be to create an `np_dtype` property inside the dtypes-`NamedTuple` that automates the `as_numpy_dtype` step.

**Comment by st--** [comment]
No longer an issue
