### ISSUE TITLE
Multi-output GPs - distinct kernels and inducing inputs

### ISSUE THREAD

**Issue by ialong** [GPflow/GPflow#399]
Hi!

I have been using GPflow for a little while now and wanted to submit a question to the community (which could potentially lead to a pull request/minor extension).

## Set up:
I have a set of inducing inputs which can be stored in a ExMxE tensor (i.e. I have E sets of M, E-dimensional inputs). This is because I have E sparse GPs whose input space **X** is E-dimensional (as in the multi-output regression case Reals^E -> Reals^E).

Because I want to optimize the inducing inputs I have put them in a GPflow.param.Param object (let’s call it **Z**). 

## Question: 
to compute the E kernel matrices (one for each set of inducing inputs) I need to access Z[e, :, :], however the Param class has no “getitem” method defined. If I do Z.value[e, :, :] that returns a copy, so am I right in assuming gradients won’t be fed back to the original?
Is the best solution to just use a list of Params (i.e. [Z_1, …, Z_E])?

Have I missed a more elegant way of doing multi-output sparse GP regression in GPflow? 

Any suggestions are very welcome!

Alessandro

**Comment by jameshensman** [comment]
Hi @ialong 

My answer comes in two parts. First, regarding getitem on Param instances, then on multi-output Sparse GPs.

1. The param class has no `__getitem__`, you're right. So the following fails

```python
m = GPflow.model.Model()
m.Z = GPflow.param.Param(np.zeros((3, 2, 1)))
m.Z[1, :, :]  # Param objectis is not scriptable
```

but this works:
```python
m.build_likelihood = lambda : 0.  # a nonsense likelihood just for demo
m._compile()  # crucially calls make_tf_array. This is silently called before optimization.
with m.tf_mode():
    print(m.Z[1, :, :])  # Tensor("strided_slice_2:0", shape=(2, 1), dtype=float64)
```
Inside the `tf_mode`context, the Param object appears as a tensorflow variable. this is how GPflow attaches Params into the tensorflow graph. the `build_likelihood()` function is always called with that context enabled, so inside that function you can think of `Z` as a tf.Tensor. 

2.  multi-output Sparse GPs. 

By default, GPflow models multiple coluimns of the Y matrix as independent GPs, sharing the same kernel. We inherited this behaviour from GPy (and in turn from Neil Lawrence's old matlab code), and I think it makes sense. 

So to make a very simple multi-output GP, just stack all the outputs into the columns of Y. Of course this only works if you have 'fully observed' data, i.e. you have every output wherever you have an input.  And the independence assumption may not be what you want.

If you want stronger models with multi-outputs in GPflow, that's easy enough too. The trick for this is to stack all the outputs into a single column, and use an additional coluimn of `X` to index which output you have. You can make some very powerful models this way, including the 'linear model of coregionalization' (see Alvarez and Lawrence's review). 

Here's a very simple demo of coregionalizatino in GPflow (this demo is intrinsic coregionalization, a little less powerful but easily understood). 

http://gpflow.readthedocs.io/en/latest/notebooks/coreg_demo.html

hth. James.

**Comment by ialong** [comment]
Hi @jameshensman thank you so much for the quick answer! (on Easter day!)

This really helps, good to know I can index Params as normal. 
Unfortunately I don't think I'll be able to use GPflow's slick indicator-based multi-output functionality as I need to compute expectations of kernel matrices (which Mark kindly implemented in ekernels) with respect to GP inputs and outputs (I guess I slyly omitted that I am dealing with a time-series model) and so I need to alter the guts of the inference process.

Thank you!

**Comment by markvdw** [comment]
If this has not been answered to satisfaction, feel free to re-open.

**Comment by nrontsis** [comment]
@jameshensman thanks for the nice explanation above.

Suppose that I would like to handle multiple (say k) columns of the Y matrix as independent GPs that have **different kernels**. This formulation has been suggested for dynamical systems in [PILCO](https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiv8_-ShrzZAhXBORQKHQoOCmQQFggpMAA&url=http%3A%2F%2Fmlg.eng.cam.ac.uk%2Fpub%2Fpdf%2FDeiRas11.pdf&usg=AOvVaw3dwzxvQeA7neCl_OTne4WK).

I believe that GPR can be slightly modified (obviously without the need of any for loops) to handle such cases, assuming that a kernel function K: X \in R^(N x N) -> Y \in R^{k x N x N} is used.

Do you think that such an approach is good? I could create a PR to facilitate discussion.

Thanks a lot!

**Comment by markvdw** [comment]
We're working on a framework for multi-output GPs. One thing we're thinking of supporting is support for tensor valued kernels to represent covariances between different outputs, which I think is along the lines of what you're suggesting.

**Comment by nrontsis** [comment]
Great! Do you want code in a branch that I could look?
