### ISSUE TITLE
Printing all hyper-parameters for multi-dimensional input

### ISSUE THREAD

**Issue by ktiwari9** [GPflow/GPflow#401]
Hi there,
I have a 3-D input X and a 1-D target Y which stores the values at the corresponding X's. I ran GPFlow and I want to see the learnt hyper-parameters. My guess is I should see 5 values: [signal_var,noise_var,latent_length_1,latent_length_2,latent_length_3] but I am unable to print them. Could you please help me with the command needed to print out all 5 hyper-parameters from the model ? I already tried `m.kern.lengthscales.value` but unlike GPy which had `m.kern.lengthscales.values` to print all 3 length scales, for GPFlow, I am able to print only one.

Any hints/help would be much appreciated.
Regards.

**Comment by vdutor** [comment]
Hi,

When initializing the kernel you should set the ARD parameter to `True`. ARD specifies whether the kernel has one lengthscale per dimension `(ARD=True)` or only a single lengthscale `(ARD=False)`.

Hope this solves your problem.

**Comment by ktiwari9** [comment]
Oh that works. Thanks for pointing out.
