### ISSUE TITLE
Adding White noise to rbf kernel

### ISSUE THREAD

**Issue by ktiwari9** [GPflow/GPflow#402]
In GPy, we could add white noise kernel to an rbf kernel to represent noisy training samples but in GPFlow is there a provision for such white noise kernel ? How can I initialize a kernel as a summation of rbf for 3-D input and white noise added to it ?

**Comment by jameshensman** [comment]
Sure. 

```python
X = np.random.randn(10, 3)
k = GPflow.kernels.RBF(3) + GPflow.kernels.White(3)
plt.matshow(k.compute_K_symm(X))
```

**Comment by AntixK** [comment]
How do we impose constraints on the hyper-parameters of RBF after adding white noise?
I get the following error -
AttributeError: 'Add' object has no attribute 'lengthscales'

Basically I am trying -
```
k = GPflow.kernels.RBF(3, variance=1., lengthscales=1., ARD = True)+GPflow.kernels.White(3)
m = GPflow.gpr.GPR(X,Y,kern=k)
m.kern.lengthscales.transform = GPflow.transforms.Logistic(1e-5,5)
```

**Comment by manuelhaussmann** [comment]
You have to specify which kernel you are accessing, i.e. `m.kern.rbf` (and `m.kern.white` for the white noise).
The following should work:
```
m.kern.rbf.lengthscales.transform = GPflow.transforms.Logistic(1e-5,5)
```

**Comment by AntixK** [comment]
Thank you helping. It works!!
