### ISSUE TITLE
Declaring an RBF Kernel from ekernel versus kernel modules

### ISSUE THREAD

**Issue by ktiwari9** [GPflow/GPflow#405]
What is the difference between declaring an RBF Kernel using: `GPflow.kernels.RBF(1)` and `GPflow.ekernels.RBF(1)` ?

**Comment by nknudde** [comment]
Hi @ktiwari9. For models like GPR there is no difference. The only difference is that the ekernel version can calculate the expectation value of the kernel under input distributions analytically, while kernel calculates these with quadrature approximations. These are necessary for example in Bayesian GP-LVM models.
