### ISSUE TITLE
Page or section with GPflow usages

### ISSUE THREAD

**Issue by alexisboukouvalas** [GPflow/GPflow#407]
Could we put somewhere a list of projects that are using GPflow?
I am curious what people are doing with GPflow and it would help to advertise other projects building on GPflow.

If you think this is a good idea, perhaps the simplest way would be to add a section at the bottom of the readme.md page?

@jameshensman @alexggmatthews @markvdw  thoughts?

**Comment by jameshensman** [comment]
I am 100% behind this and would happily merge a pr.

**Comment by AjayTalati** [comment]
Dear @alexggmatthews, @jameshensman, I'm very new to this code base, but would to love to work on some simple continuous control applications of it - that would be really fun :+1: 

Is there anyone working on [MuJoCo](https://github.com/openai/mujoco-py) applications? If its not already done I could benchmark against an A3C implementation I have, (which sort of sucks at the moment), and also [OpenAIs GA](https://github.com/openai/evolution-strategies-starter), (which rocks)

Very open to any suggestions you guys might have :+1: Also I've got some free time to do some documentation if I can get it to work, and to port very basic parts of the repo over to PyTorch.

All the best,

Ajay

**Comment by AjayTalati** [comment]
Any code to accompany @jameshensman your paper, 

[Identification of Gaussian Process State Space Models](https://arxiv.org/abs/1705.10888)

would be really insightful
