### ISSUE TITLE
Simple interaction model

### ISSUE THREAD

**Issue by evoclue** [GPflow/GPflow#414]
Is it possible to define a model somehow that will be equivalent to:

```
k = GPflow.kernels.RBF(200)
k2 = k + (k*k)
m = GPflow.gpr.GPR(Y, X, kern=k2)
```

I would like to avoid specifying three separate kernels, e.g., k2 = k_1 + (k_2 * k_3), because then I will have three different length scales. I am under the impression from #322 that this cannot be done yet.

**Comment by jameshensman** [comment]
how about something like this?

```python
class InteractKern(GPflow.kern.Kern):
    def __init__(self, k):
        super().__init__()
        self.k = k

    def K(self, X, X2=None):
        return self.k(X, X2) + self.k(X, X2) * self.k(X, X2)

    def Kdiag(self, X):
        return self.k.Kdiag(X) + self.k.Kdiag(X) * self.k.Kdiag(X)

k = GPflow.kernels.RBF(1)
k2 = InteractKern(k)
```

This code is not tested, and is off the top of my head. I think you could generalize to any simple function, instead of just k + k*k quite easily, like this:

```python

class InteractKern(GPflow.kern.Kern):
    def __init__(self, k, f):
        super().__init__()
        self.k, self.f = k, f

    def K(self, X, X2=None):
        return self.f(self.k(X, X2))

    def Kdiag(self, X):
        return self.f(self.k.Kdiag(X))

def f(K):
    return K + K * K

k = GPflow.kernels.RBF(1)
k2 = InteractKern(k, f)
```

Of course this is only valid a limited set of functions `f`: addition and multiplication are fine.
