### ISSUE TITLE
Directly get likelihood of data given the model

### ISSUE THREAD

**Issue by PabloLeon** [GPflow/GPflow#42]
Is there a way of getting the likelihood of the data given the model? The standard GPy ways seem not to work. I need to extract the likelihood of my regression model as a numeric value.

**Comment by jameshensman** [comment]
This is a good feature request, we should have this. 

A simple workaround for the moment is to use

```python
m._compile()
print -m._objective(m.get_free_state())[0]
```

I just created a PR: #43

**Comment by alexggmatthews** [comment]
Done.

**Comment by PabloLeon** [comment]
Thanks!
