### ISSUE TITLE
NaNs in predictions with Matern52 and Matern32 kernels

### ISSUE THREAD

**Issue by rm4216** [GPflow/GPflow#421]
Dear all

I have been using the GPR regression model to make posterior predictions with Gaussian likelihood using Matern52, and Matern32 kernels. However, with a particular set of 3-dimensional pints and a particular choice of lengthscales I obtained all NaNs on posterior mean and variance, both for isotropic and ARD version of each kernel. Here is the code that should reproduce the issue. (I also modified the Matern52 kernel to be able to obtain numerical values of the covariance matrix "npK52_iso" and "npK52_ARD", I did not apply any modification to Matern32)
# Dataset
```pythonscript
import numpy as np
import tensorflow as tf
import GPflow

full_dim = 3
# Five data points in 3 dimensions
D_X = np.array([
 [31.55437035,  31.55437038,  32.36345678],
 [31.55437037,  31.55437037,  32.36345679],
 [31.55437037,  31.55437037,  32.36345679],
 [28.31802469,  21.84533348, -29.12711068],
 [28.31802469,  21.84533348, -29.12711111],
])
# Trying with different dataset does not show any problem
# D_X = np.random.uniform(-32, 32, 5*full_dim).reshape(-1, full_dim)

Y = np.random.uniform(2, 7, D_X.shape[0]).reshape(-1, 1)    # any random choice
X_test = np.random.uniform(-32, 32, 10*full_dim).reshape(-1, full_dim)  # random test set
```
# Matern52 tests
```pythonscript
# Matern52 test isotropic
kernel52_iso = GPflow.kernels.Matern52(input_dim=3, ARD=False)
kernel52_iso.lengthscales._array = np.array([0.01095283])     # critical lengthscale

GPmodel = GPflow.gpr.GPR(D_X, Y, kernel52_iso)
mean52_iso, vars52_iso = GPmodel.predict_f(X_test)  # posterior mean is all nan

K52_iso = kernel52_iso.K(D_X)
gg = K52_iso.graph
sess = tf.InteractiveSession(graph=gg)
npK52_iso = K52_iso.eval(session=sess)  # Covariance matrix contains nan

# Matern52 test ARD
kernel52_ARD = GPflow.kernels.Matern52(input_dim=3, ARD=True)
kernel52_ARD.lengthscales._array = np.array([0.01095283, 0.01095283, 0.01095283])     # critical lengthscales

GPmodel = GPflow.gpr.GPR(D_X, Y, kernel52_ARD)
mean52_ARD, vars52_ARD = GPmodel.predict_f(X_test)

K52_ARD = kernel52_ARD.K(D_X)
gg = K52_ARD.graph
sess = tf.InteractiveSession(graph=gg)
npK52_ARD = K52_ARD.eval(session=sess)
```
# Matern32 tests
```pythonscript
# Matern32 test isotropic
kernel32_iso = GPflow.kernels.Matern32(input_dim=3, ARD=False)
kernel32_iso.lengthscales._array = np.array([0.01095283])

GPmodel = GPflow.gpr.GPR(D_X, Y, kernel32_iso)
mean32_iso, vars32_iso = GPmodel.predict_f(X_test)

# Matern32 test ARD
kernel32_ARD = GPflow.kernels.Matern32(input_dim=3, ARD=True)
kernel32_ARD.lengthscales._array = np.array([0.01095283, 0.01095283, 0.01095283])

GPmodel = GPflow.gpr.GPR(D_X, Y, kernel32_ARD)
mean32_ARD, vars32_ARD = GPmodel.predict_f(X_test)
```
If I try with a slightly different dataset or different lengthscales, NaNs do not appear, and predictions return normal numerical values. I could not understand what may be going wrong with these predictions. The only thing I noticed is that the numerical covariance matrices "npK52_iso", and "npK52_ARD" contain NaNs outside the diagonal, and that, using RBF kernel, predictions return numerical values.

Can you reproduce this problem? Am I missing something in the implementation?

Thank you!

**Comment by markvdw** [comment]
Your dataset contains some data points that are very close to each other, which often causes numerical issues in kernel computations. Initialising with a much shorter lengthscale can work, or by standardising the inputs to zero mean and unit standard deviation.

**Comment by rm4216** [comment]
Thank you for the advice, I will try standardising the inputs to avoid numerical issues, and set initial lengthscales to small values before hyperparameters' optimization.

**Comment by hughsalimbeni** [comment]
Whenever I use mattern I always do the following to get over the nan problem:

```python
class SafeMatern52(Matern52):
    def euclid_dist(self, X, X2):
        r2 = self.square_dist(X, X2)
        return tf.sqrt(r2 + 1e-9) # or 1e-6. I find 1e-12 is too small
```

Maybe this works for you too

**Comment by rm4216** [comment]
Thank you for the suggestion. The problem is exactly in the computation of square distances, which sometimes returns "small" negative numbers. I tried with 1e-09, 1e-06 and 1e-04. Now, it seems to work with 1e-03.  Thank you!
