### ISSUE TITLE
Import fails with TF 1.2.0-rc1

### ISSUE THREAD

**Issue by rhofour** [GPflow/GPflow#423]
I'm currently running the latest Tensorflow pre-release, 1.2.0-rc1. GPflow installs with it, but I get an error on trying to import it.

`tensorflow.python.framework.errors_impl.NotFoundError: <my system path>/GPflow/GPflow/tfops/matpackops.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv`

It looks like something in the C++ code is broken in the latest version of TF.

**Comment by icouckuy** [comment]
Try removing the two lines adding a GCC define in setup.py

Don't know them by heart but it should be obvious

**Comment by icouckuy** [comment]
And of course run python setup.py build to compile matpackop.so again

**Comment by rhofour** [comment]
I can confirm that fixes it. It's [line 31](https://github.com/GPflow/GPflow/blob/master/setup.py#L31).

I'm running 64-bit Fedora with: gcc (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1)

I'm not entirely sure what that define does so I'm not sure how to approach fixing this.

**Comment by icouckuy** [comment]
It is the toggle between the old and new ABI compatbility that was introduced in gcc 5 and upwards. See
https://www.tensorflow.org/install/install_sources#build_the_pip_package

There is not that much you can do except trying to detect with what the installed TF was compiled. It can be installed from pip (which uses gcc 4) or a custom compiled version.

**Comment by markvdw** [comment]
@rhofour: Did you compile your own tensorflow version?

**Comment by rhofour** [comment]
Yes, I compiled the version of tensorflow I'm using.

Are these ops the kind of thing that could be upstreamed to tensorflow? That's the most obvious solution to this problem that I can see right now.

**Comment by markvdw** [comment]
Yes, this is a bit of an issue. At the moment we're supporting the pre-compiled versions of TensorFlow. However, it's becoming more common (to the point of being recommended) to compile one's own version. However, as mentioned above, this requires detecting which version of gcc tf was compiled with. The idea now, is if you're able to compile you're own version of tensorflow, then you're probably also able to comment out the two lines or modify them as needed.

That said, it's not a satisfying long term solution. There may be a good way now to convert a vector to a lower triangular matrix.

**Comment by alexggmatthews** [comment]
@markvdw that looks like a good idea, no?

**Comment by markvdw** [comment]
Yes, it'll have to be benchmarked though.

**Comment by alexggmatthews** [comment]
Fixed in #440 please re-open if you have any further problems.
