### ISSUE TITLE
Out Of Sample Problem

### ISSUE THREAD

**Issue by lanhnguyen2010** [GPflow/GPflow#428]
Hi, Iam a newbie, I have a model like that:

m = GPflow.gplvm.GPLVM(X_mean=X_mean, Y=Y,              
                       kern=k, latent_dim=Z.shape[1])   
m.likelihood.variance = 0.01                            
m.optimize(disp=True, maxiter=100)            

Do we have any way to convert from Ynew (outside training set) to the latent variable Xnew?
Thanks

**Comment by icouckuy** [comment]
There is a PR for that: https://github.com/GPflow/GPflow/pull/341

**Comment by lanhnguyen2010** [comment]
It is really cool. Thanks a lot.
Btw, Maybe It is a stupid concern: Can you use this for GPLVM not BayesianGPLVM?
