### ISSUE TITLE
Error testing GPFlow

### ISSUE THREAD

**Issue by AAbusnina** [GPflow/GPflow#429]
I am having trouble installing GPflow on windows 10. I installed TensorFlow 1.0 and activated Python 3.5 env and then ran "python setup.py" test after cd to the setup.py. I got the folloing error:

matpackops.so not found

Is there an easy way of getting around this?

**Comment by markvdw** [comment]
Currently, only `python setup.py develop` is supported. That said, we're working on a method to get rid of `matpackops.so`, so this won't be a problem any more.

**Comment by AAbusnina** [comment]
Actually when I run` python setup.py develop` , it says: "Finished processing dependencies for GPflow==0.3.5". Then wen I try to import GPflow, I receive the ssame error: "matpackops.so not found"

**Comment by BadrulAlom** [comment]
Similarly I'm getting the error: "\GPflow\likelihoods.py", line 16
    raise NotImplementedError, "implement the logp function for this likelihood" -when running the test script. But I am using Tensoflow 1.1 not 1.0?

**Comment by alexggmatthews** [comment]
These problems should be fixed in #440 so closing. Please re-open if you have any further problems.
