### ISSUE TITLE
Windows 10 importing GPflow error: "matpackops.so not found"

### ISSUE THREAD

**Issue by ShahidB** [GPflow/GPflow#434]
Dear all,

I have attempted to install and use GPflow to support my academic work but have run into an issue. There appears to be a file missing that didn't get built/installed during the original setup of GPflow.

Upon:

`import GPflow`

I get back an error mesage, here is the final line:

`NotFoundError: C:\Program Files\Anaconda3\lib\site-packages\gpflow-0.3.6-py3.5.egg\GPflow\tfops\matpackops.so not found`

TensorFlow 1.2.0 is installed and runs without problems.

My setup is:

- Lenovo ThinkPad E560
- Windows 10 Pro, version 1607, build 14393.1358
- Intel Core i7-6500U @ 2.50 Ghz
- 16.0 GB
- Anaconda3 version 4.4.0

I installed GPflow by pulling from GitHub then installing by first trying:

`python setup.py install`

When I got the aforementioned error I then tried:

`python setup.py develop`

I'm trying to use GPflow via Jupyter Notebook, but also get the error if I import GPflow via the Anaconda Prompt CLI.

The full error code returned in Jupyter Noteook is:

```
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-2-d5391a053bbd> in <module>()
----> 1 import GPflow

C:\Program Files\Anaconda3\lib\site-packages\gpflow-0.3.6-py3.5.egg\GPflow\__init__.py in <module>()
     16 # flake8: noqa
     17 from __future__ import absolute_import
---> 18 from . import (likelihoods, kernels, ekernels, param, model, gpmc, sgpmc, priors, gpr, svgp, vgp, sgpr, gplvm, tf_wraps,
     19                tf_hacks)
     20 from ._version import __version__

C:\Program Files\Anaconda3\lib\site-packages\gpflow-0.3.6-py3.5.egg\GPflow\likelihoods.py in <module>()
     15 
     16 from __future__ import absolute_import
---> 17 from . import densities, transforms
     18 import tensorflow as tf
     19 import numpy as np

C:\Program Files\Anaconda3\lib\site-packages\gpflow-0.3.6-py3.5.egg\GPflow\transforms.py in <module>()
     18 import tensorflow as tf
     19 
---> 20 from . import tf_wraps as tfw
     21 from ._settings import settings
     22 

C:\Program Files\Anaconda3\lib\site-packages\gpflow-0.3.6-py3.5.egg\GPflow\tf_wraps.py in <module>()
     34 
     35 
---> 36 _custom_op_module = tf.load_op_library(os.path.join(os.path.dirname(__file__), 'tfops', 'matpackops.so'))
     37 vec_to_tri = _custom_op_module.vec_to_tri
     38 tri_to_vec = _custom_op_module.tri_to_vec

C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\load_library.py in load_op_library(library_filename)
     62       # pylint: disable=protected-access
     63       raise errors_impl._make_specific_exception(
---> 64           None, None, error_msg, error_code)
     65       # pylint: enable=protected-access
     66   finally:

NotFoundError: C:\Program Files\Anaconda3\lib\site-packages\gpflow-0.3.6-py3.5.egg\GPflow\tfops\matpackops.so not found
```

The error code in Anaconda Prompt is:

```
(C:\Program Files\Anaconda3) C:\WINDOWS\system32>python

Python 3.5.3 |Anaconda 4.4.0 (64-bit)| (default, May 15 2017, 10:43:23) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

>>> import GPflow

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\mypy\gpflow\GPflow\__init__.py", line 18, in <module>
    from . import (likelihoods, kernels, ekernels, param, model, gpmc, sgpmc, priors, gpr, svgp, vgp, sgpr, gplvm, tf_wraps,
  File "c:\mypy\gpflow\GPflow\likelihoods.py", line 17, in <module>
    from . import densities, transforms
  File "c:\mypy\gpflow\GPflow\transforms.py", line 20, in <module>
    from . import tf_wraps as tfw
  File "c:\mypy\gpflow\GPflow\tf_wraps.py", line 36, in <module>
    _custom_op_module = tf.load_op_library(os.path.join(os.path.dirname(__file__), 'tfops', 'matpackops.so'))
  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: c:\mypy\gpflow\GPflow\tfops\matpackops.so not found
```

Thank you in advance for your help. I'm not the strongest when it comes to the nuances of installing packages and compiling things but I'm trying to learn as much as I can.

Thanks again,

Shahid

**Comment by mrksr** [comment]
Hi!
The file in question implements a custom tensorflow operation which are a bit problematic on Windows. Have a look at #295 #429 and #423 (Where the potential solution mentioned in #429 is shown) for some discussion on the matter. If possible I would suggest using GPflow on Linux as it is much easier to handle, but maybe somebody else has some insight on how to get things running on Windows?

**Comment by ShahidB** [comment]
Hi there, thanks for those links they're informative. For now I'll run Ubuntu-on-VirtualBox-on-Windows; I tried it last light and the GPflow install was painless and worked fine. But I look forward to the future fixes.

Thanks again!

**Comment by hughsalimbeni** [comment]
Just in case you're prevented from using GPflow by this: as a hack to get it working you can just comment out everything from line 36 down in tf_wraps. The custom ops don't actually get used anyway.

**Comment by ShahidB** [comment]
@hughsalimbeni I've just tried that and now the import runs fine, I just ran through this example with no problems: http://gpflow.readthedocs.io/en/latest/notebooks/regression.html

Thanks a bunch everyone. That was an easy fix.

**Comment by mrksr** [comment]
Just a quick note: After the merge of #440, installing GPflow on Windows just works now. The test suite also passes.

**Comment by alexggmatthews** [comment]
Nice.

**Comment by alexggmatthews** [comment]
Closing as fix has been reported. Please re-open in any further difficulty is encountered.
