### ISSUE TITLE
Making sense of the GPflow-TensorFlow version/release matching

### ISSUE THREAD

**Issue by vuw-ecs-kevin** [GPflow/GPflow#447]
Hi there,

I'm trying to help someone sort out the following issue

https://github.com/numbbo/coco/issues/1436

where the `cocoex` code base builds upon TensorFlow and GPflow.

At one point, as you will see in the cocoex issue ticket, 

https://github.com/numbbo/coco/issues/1436#issuecomment-312164990

I had managed to build, 

`GPflow 0.3.4` against `TensorFlow 1.2.0`

however, when trying to build 

`GPflow 0.3.5`

there appears to be an explict dependency (in GPflow's `setup.py`) for `tensorflow==0.12.1`
which precludes using the `TF 1.n` series.

What I have since seen is that the `GPflow 0.3.4` requirement is actually  `tensorflow>=0.11.0rc1` 
which doesn't mandate the `TF 0.n` series, hence, presumably me being able to compile 'GPflow 0.3.4' against 'TensorFlow 1.2.0' ?

I note on the current GPflow front-page that there's an explictl mention pf `TF 1.0`

```
1) Install TensorFlow.

Please see instructions on the main TensorFlow webpage. You will need version 1.0. 
```
however when I look at the GPflow version history

https://github.com/GPflow/GPflow/blob/master/RELEASE.md

 (also linked to from the GPflow front-page) I see even newer versions, 

```
Release 0.3.8

    Change to LowerTriangular transform interface.
    LowerTriangular transform now used by default in VGP and SVGP
    LowerTriangular transform now used native TensorFlow
    No longer use bespoke GPflow user ops.

Release 0.3.7

    Improvements to VGP class allow more straightforward optimization

Release 0.3.6

    Changed ordering of parameters to be alphabetical, to ensure consistency

Release 0.3.5

    Update to work with TensorFlow 0.12.1.

Release 0.3.4

    Changes to stop computations all being done on the default graph.
    Update list of GPflow contributors and other small changes to front page.
    Better deduction of input_dim for kernels.Combination
    Some kernels did not properly respect active dims, now fixed.
    Make sure log jacobian is computed even for fixed variables
```

but there's no mention of any updates to work against the  `TensorFlow 1.n` series

This, the move from `TF 0.n` to `TF 1.n` seems (to me anyway) like a big jump but it's not
actually noted anywhere ?

I also note that on the GPfow release page, 

https://github.com/GPflow/GPflow/releases

that things are still only showing a 0.3.5  which is labelled as a "pre-release" and not 
the 0.3.6, 0.3.7 or 0.3.8 ?

Similarly, the `GPflow` tags page

https://github.com/GPflow/GPflow/tags

only shows a 0.3.5 too.

So, did `GPflow` swap from the `TF 0.n` series to the `TF 1.n` series for 
`GPflow` versions greater than `0.3.5` ?

The researcher I am trying to help says that when he clones the `GPflow master`,
he ens up building a `GPflow-0.3.6` which, given that I have seen mention of `0.3.7` and 
`0.3.8`  has confused me even more as to what the match-up between GPFlow
and TensorFlow version/releases currently is.

Any insight welcome,
Kevin

Kevin M. Buckley

eScience Consultant
School of Engineering and Computer Science
Victoria University of Wellington
New Zealand

**Comment by st--** [comment]
As far as I know, GPflow should currently build with tf 1.4 and maybe 1.5, with active progress towards making it work with 1.6/1.7. If you still have any issues with gpflow/tensorflow version matching, please let us know!
