### ISSUE TITLE
Support for Multivariate Priors

### ISSUE THREAD

**Issue by mohaghasemzadeh** [GPflow/GPflow#450]
Hi,

Is GPFlow going to support multivariate priors in next releases?

**Comment by hughsalimbeni** [comment]
That would be fairly straightforward to implement for e.g. multivariate Gaussian, but I can't think where this would be useful for GP models. Do you have a use case in mind?

**Comment by Bonnevie** [comment]
I think some of the papers on GP priors are fairly adamant that joint priors on things like lengthscale and noise variance is an absolute necessity as they
