### ISSUE TITLE
Change point kernels

### ISSUE THREAD

**Issue by cap76** [GPflow/GPflow#453]
Not so much an issue, but I'm thinking of adding change point kernels a la Lloyd _et al._ (2014). I had a quick look through and couldn't see this functionality, but wanted to check this hasn't already been implemented or has people currently working on it?

Edit: also thinking about integral observations, which may become increasingly useful.

**Comment by jameshensman** [comment]
Hi @cap76 , 

The general rule for GPflow is that we try to keep the package as lean as we can. We try not to implement every kernel, or every possible likelihood, but I think the framework is there for people to implement their own. 

That said, if a kernel is non-trivial and useful to others then we'd consider including it. And we'd certainly be happy to link to your work on github if the consensus is that it's outside the scope of GPflow. 

I don't know of anyone working on that kernel: feel free to post code here for more comment. Same goes for integral observations (which I presume you want to do via a special kernel?)

**Comment by nknudde** [comment]
Hi @cap76 

I implemented a ChangePoint kernel a while ago for usage in a time domain signal. The kernel is not tested, so usage is on your own risk. As far as I can remember the main issue was the initialisation.

```
class ChangePoint(Combination):
    def __init__(self, kern_list, offset, variance):
        super(ChangePoint, self).__init__(kern_list)
        self.offset = Param(offset)
        self.variance = Param(variance)


    def K(self, X, X2=None, presliced=False):
        # assert len(self.kern_list) != 3, "has to have two kernels only"
        if X2 is None:
            X2 = X
        XXT = self.variance * tf.squeeze(tf.matmul(tf.expand_dims(X, axis=1), tf.expand_dims(X, axis=2))) + self.offset
        XXT2 = self.variance * tf.squeeze(tf.matmul(tf.expand_dims(X2, axis=1), tf.expand_dims(X2, axis=2))) + self.offset
        sigm = tf.sigmoid(XXT)
        sigm2 = tf.sigmoid(XXT2)
        sig1 = tf.matmul(tf.expand_dims(sigm, axis=1),
                         tf.expand_dims(sigm2, axis=0))
        sig2 = tf.matmul(tf.expand_dims((1. - sigm), axis=1),
                         tf.expand_dims((1. - sigm2), axis=0))
        a1 = reduce(tf.mul,
                    [sig1, self.kern_list[0].K(X, X2)])
        a2 = reduce(tf.mul,
                    [sig2, self.kern_list[1].K(X, X2)])
        return reduce(tf.add, [a1, a2])


    def Kdiag(self, X, presliced=False):
        # assert len(self.kern_list) != 3, "has to have two kernels only"
        XXT = self.variance * tf.squeeze(tf.matmul(tf.expand_dims(X, axis=1), tf.expand_dims(X, axis=2))) + self.offset
        sigm = tf.sigmoid(XXT)
        a1 = reduce(tf.mul, [sigm, self.kern_list[0].Kdiag(X),
                             sigm])
        a2 = reduce(tf.mul, [(1. - sigm), self.kern_list[1].Kdiag(X),
                             1. - sigm])
        return reduce(tf.add, [a1, a2])
```

**Comment by cap76** [comment]
Excellent, thanks for the snippet, nknudde. I'll take have a  play. 

James, I certainly see the advantage of keeping things lean. That said, I think CP kernels are slightly different in scope from an arbitrary kernel, more akin to an operation, so they could potentially be of use. At any rate, kudos to you and Alex (and other contributors), I'm finding GPflow to be very neat. It may even shift me away from Matlab!
