### ISSUE TITLE
Update readme list of contributors

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#461]
Looking through the list of contributors in the readme there are people who have made non-trivial contributions to the code base who's name does not appear. 

It is more difficult to fix this because the use of merge commits can obfuscate who did the work on a pull request.

I think as an open source project it is important we acknowledge our broad range of contributors.

**Comment by alexggmatthews** [comment]
Finding these as I go along. 
@awav is missing from the list.
@mrksr is missing from the list.
@dustinvtran is missing from the list.

**Comment by alexggmatthews** [comment]
@john-bradshaw is missing from the list.

**Comment by st--** [comment]
Resolved by #1660 .
