### ISSUE TITLE
Running GPLVM on GPU

### ISSUE THREAD

**Issue by alexisboukouvalas** [GPflow/GPflow#466]
Dear all,
 I am trying to run the Bayesian GPLVM model on a GPU using float32 precision.
After a small fix #465  I am continuously running into numerical issues manifesting as Cholesky decomposition errors.

I created a  [gist example](https://gist.github.com/alexisboukouvalas/dd66130176e57e61a3464bb9a6e2a605) to demonstrate the issue. When using M=6 inducing points with tf.float32, decomposition fails (M=5 works).

What is your advice on getting things to run properly on the GPU?
1. As in the MNIST demo, I tried using AdadeltaOptimizer (set opti=2 in script) with poor results. Still get numerical issues and local minima solution is poorer.
Which optimizer to use?

1. Any other advice? Right now I am fixing all the hyperparameters and the inducing points to help.

**Comment by alexggmatthews** [comment]
Hi Alexis, try upping the jitter level in the gpflowrc. If that doesn't work let us know.

**Comment by alexisboukouvalas** [comment]
thanks @alexggmatthews. I have tried jitter levels of 10^-1 to 10^-3 without any effect.
Any advice on how to proceed? So far I have been trying tricks around fixing most model parameters (see the script). With M=5 inducing points the code works, with M=6 it falls over with Cholesky problems during optimisation with the L-BFGS optimizer. This falls over even with a very large nugget (19!).
Numerical stability is a bit better with AdadeltaOptimizer but the optimisation is poorer (the minima we reach is not nearly as good).
Now when I unfix the hyperparameters, the code blows up even with the AdadeltaOptimizer.

What is a good way to optimise GPflow models with float32? Do we need to add constraints to all parameters, and/or use a tensorflow optimiser with some recommended settings?

Any ideas appreciated, many thanks!

**Comment by alexggmatthews** [comment]
Changed issue name to be more specific.

**Comment by alexggmatthews** [comment]
The GPLVM stuff that you and @markvdw did was finished since I wrote the paper. I agree it would be nice to test on float32 but we're constrained in terms of how many builds we can do. Things like this raise it in the priority list. 

Seems possible (incorrectly) that the jitter level isn't being used everywhere.

Try changing the kernel declaration to:

`k = GPflow.kernels.RBF(2, ARD=True) + GPflow.kernels.White(2, 1e-3)`

Does that change things?

**Comment by alexggmatthews** [comment]
Also what model of GPU are you using? Generally speaking themore recent  _Pascal_ nvidia series has less of a difference between float32 and float64 then the _Maxwell_ one .

**Comment by alexisboukouvalas** [comment]
If I use the +White kernel as you suggest @alexggmatthews things look better. The optimiser gets through 10 iterations prior to falling over.
So perhaps jitter not used somewhere it should as you suggest.
Also we are now using quadrature rather than having an analytic expression for the psi statistics.

I am using tensorflow CPU for testing out float32 on my desktop and occasionally running the code on a Tesla K40 in the cluster.

Btw, we also noticed using float32 speeds up tensorflow-CPU. Perhaps due to better cache locality?

**Comment by alexggmatthews** [comment]
With a K40 you can therefore expect quite a difference in performance on your GPU between single and double precision:
https://en.wikipedia.org/wiki/Nvidia_Tesla

Interesting about the CPU. 

Good about the kernel but obviously we would like more than 10 iterations!

**Comment by alexggmatthews** [comment]
Ok I've found at least one problem. See the linked issue:

**Comment by alexggmatthews** [comment]
Whilst we are fixing that it should give a similar effect to fix the variance of the white kernel that we added.

**Comment by alexisboukouvalas** [comment]
@alexggmatthews I can confirm this helps quite a bit. In fact setting jitter=1e-2 allows the pods repro above to converge!

**Comment by markvdw** [comment]
Is this fixed with #465?

**Comment by alexisboukouvalas** [comment]
hi @markvdw @alexggmatthews I can confirm with #465 stability is much improved. Happy to close this.
