### ISSUE TITLE
Distributed training for GPflow

### ISSUE THREAD

**Issue by Mylak1995** [GPflow/GPflow#473]
Is there any in-built way to run GPflow on multiple machines leveraging distributed tensorflow? Would I have to modify the optimize function in order to make GPflow work in distributed setting?

**Comment by hughsalimbeni** [comment]
There isn't an easy way to do this, I'm afraid.

**Comment by markvdw** [comment]
There are some active development plans to make this easier to support, but currently it would require modifying the internals, as you say.

**Comment by Mylak1995** [comment]
I have managed to run some of the training in a distributed setting, but another issue came up: it seems there is only 1 big TensorFlow variable inside the program, so it cannot be distributed by default to a number of parameter servers. Is there any quick way you can think of to shard the variable, while not having to change vast parts of the code?

**Comment by markvdw** [comment]
I don't think there's an easy way to fix this. But, we are working on ways to fix this.

**Comment by awav** [comment]
@Mylak1995, _GPflow-1.0-RC_ doesn't have one big variable inside. You can give a try to distributed training experiment with new GPflow. If you have troubles with _GPflow-1.0-RC_, please refer them at https://github.com/GPflow/GPflow/issues/519.
