### ISSUE TITLE
GPflow with TF > 1.0 

### ISSUE THREAD

**Issue by diego-ardila-alvarez** [GPflow/GPflow#479]
Hi,

At the moment, the [intro doc](http://gpflow.readthedocs.io/en/latest/intro.html) says that GPflow uses TF 1.0.0. Can I also use it with TF 1.2?

Thanks,
Diego

**Comment by markvdw** [comment]
Yes, that's possible. We generally try to use the most recent version of TensorFlow. Usually the updates happen pretty quickly (or even before the new version is out :) ). Perhaps we should update the readme to indicate this.

**Comment by markvdw** [comment]
We clarified this in #484.
