### ISSUE TITLE
Recommended way to serialize and de-serialize model class?

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#48]
Do we have in mind a particular way to serialize and de-serialize models so that they can be stored? Pickle doesn't currently work.

**Comment by markvdw** [comment]
I did this for a while and I just stored the full parameter vector. I had to add to modify the GPflow source to ensure that if an object was created in the same way, the parameters were flattened in the same order. This involved adding a local variable inside `param.py` that counted up every time a `Parameterized` object was made. It was definitely not ideal. It was brittle in the sense that if you reconstructed the object in a different way, it may cause the parameters to be interpreted in the wrong way.

I think pickle currently doesn't work because functions are assigned to variables in the object (e.g. `._objective`), and functions aren't picklable.

I for one would like to see a lightweight pickling method that just stores the current parameter values, and not the dataset. I think this would be really useful to make scripts re-startable, or for logging past parameter values during optimisation.

**Comment by alexggmatthews** [comment]
Slightly thinking out loud here. What about an xml serializer / de-serializer that uses the param class? I.e we make every param serializable and the xml tree respects the param tree?  I guess what this would be missing is how the params relate to the class. Maybe we just need to find a principled and robust way to guarantee the parameter order in the tf array. 

Thoughts? @jameshensman ?

**Comment by markvdw** [comment]
That could work. Although the downside of XML is its size. A binary representation would be a lot more compact and quicker to load for large models.

I think the basic requirement is that the model object should be able to be reconstructed from the pickled parameters, without the data. In terms of the code interface, we could have `Model.save(filename)` and `Model.load(filename, X, Y)` functions. `load` would have to construct the correct Model and assign the dataset.

**Comment by jameshensman** [comment]
I see three options. 

1) Pickle. 
Pros:
 - Ease of use for saving /loading models to disk

Cons:
 - possible incompatibility across GPflow versions
 - inefficient storage
 - would require some definitions of which bits of the model to pickle.

2) dump the get_free_state() vector to disk
Pros: 
 - efficient storage (don't store the data)

Cons:
 - Would require us to guarantee the order of the parameters in the model

3) other (as @markvdw suggested, or xml as @alexggmatthews suggested)
Pros:
 - efficient storage
 - compatibility across GPflow versions

Cons:
 - Would require significant coding effort to implement and maintain. 

I think it's not such a big ask to get both 1) and 2) working. For 1, we already have the _compile function, which we could re-run after unpickling. For 2, I though Mark's solution was kind of okay.

**Comment by jameshensman** [comment]
also, dill looks like a more powerful version of pickle: https://github.com/uqfoundation/dill

**Comment by jameshensman** [comment]
I just added a few small commits to the pickle branch that allow us to pickle a simple model using dill. I can't vouch for how well it works yet, but a model will now pickle and unpickle without errors: see test_pickle.py

**Comment by alexisboukouvalas** [comment]
I have to deal with this problem as I have code that builds a lot of models with the same training data but different kernels and parametrisations. 
I have implemented the suggested approach (2) using numpy.save and it seems to work. (This is the approach recommended by Max for GPy).

My understanding is this is fragile to version changes so perhaps one of the other approaches would work better. Having the option to avoid storing the data would be very helpful in any approach.

Some code to demonstrate the approach I currently use is given below. 

```
#import tests
#tests.testSingleBranchPointInference()
import GPflow
import numpy as np
def getData():
    rng = np.random.RandomState( 1 )
    N = 30
    X = rng.rand(N,1)
    Y = np.sin(12*X) + 0.66*np.cos(25*X) + rng.randn(N,1)*0.1 + 3
    return X,Y
if __name__ == '__main__':
    X,Y = getData()
    k = GPflow.kernels.Matern52(1)
    meanf = GPflow.mean_functions.Linear(1,0)
    m = GPflow.gpr.GPR(X, Y, k, meanf)
    m.likelihood.variance = 0.01
    m._compile()
    m.kern.lengthscales = 2
    print "Here are the parameters before optimization"
    print m
    fs = m.get_free_state()
    np.save('saveModelState',fs)
    msstate = np.load('saveModelState.npy')
    m2 = GPflow.gpr.GPR(X, Y, k, meanf)
    m2.set_state(msstate)
    print 'm2 state'
    print m2    
    print 'done'
```

**Comment by mathDR** [comment]
I see that you have already gone down the road on pickling objects.  Just a thought:  have you looked at how keras saves models?  Uses json for the architecture and hdf5 for the parameters?  The source is all there to look at, and that project supports tensorflow as a backend so it is all compatible.

In any case, my two cents.

**Comment by jameshensman** [comment]
Hi @mathDR 

That looks like a nice thing, thanks for the heads-up. I'd really like to be able to pickle to the model because it would shift responsibility for maintenance onto someone else! Ideally, I'd like to use straight-forward pickle (cf dill), so that we're only dependent on the standard library: that seems far fetched though.

**Comment by mathDR** [comment]
That is a valid point.  Although, even when I use pickle, I import cPickle, so I don't know if the standard library is applicable even for this!

**Comment by vals** [comment]
Hey, I saw that the "TF-Learn" submodule of TensorFlow does model persistence. 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/estimators/base.py#L316

They seem to write a JSON file with parameters. Wouldn't it make sense to "inherit" the persistence strategy from there?

**Comment by jameshensman** [comment]
That looks like a nice way to go, json seems like a sensible choice for
model representation.

**Comment by markvdw** [comment]
Ok, so the serialising works really well now, but there's still an issue with storing things like a history of old parameter values, that the order in get_free_state() changes. The only time when the changing order is ever a problem, is when we want to reload parameter values after recreating a model. And I now think that to_dict is actually the perfect way to solve this.

So @jameshensman are you happy if I set up the to_dict branch for a merge?

**Comment by jameshensman** [comment]
> to_dict is actually the perfect way to solve this.

I'm so happy you agree! Yes, please set up the PR and we'll see if we can persuade @alexggmatthews too.

**Comment by markvdw** [comment]
Ready to merge! https://github.com/GPflow/GPflow/pull/112

**Comment by markvdw** [comment]
Ok, so continuing on the discussion from #112. My thoughts mirror those mentioned there, but I'll summarise:
- Pickle shouldn't be used to actually store models, especially for extended periods.
- Pickle is required for sending around objects for e.g. parallel computing.
- `get/set_parameter_dict` is a good way of storing parameters in a human readable format.

Storing models is still an issue though. I would advocate for using pickle for short-term storage, say you're running a bunch of experiments and you want to be able to re-start them (which is my use case). For long term storage, I think storing the parameters using `get_parameter_dict()`, together with model creation code is the only real option. Separately maintaining serialisation code would be a huge pain, and would likely lose backwards compatibility quickly anyway, given the pace at which GPflow is being developed. With code and parameters, at least the idea is there, and the model could be recreated with some effort if it was really necessary.

So, to cut a long story short, I'd say long term storage of models is too much of a pain to support. And for short term, pickle does fine. Given that these issues are solved, is this topic closed?

**Comment by alexggmatthews** [comment]
Hi @markvdw @jameshensman On the storing model issue. I understand we need additional functionality but it is good to be aware of what TensorFlow does and doesn't supply in related areas. See:

https://www.tensorflow.org/versions/r0.9/how_tos/variables/index.html#saving-and-restoring

**Comment by alexggmatthews** [comment]
This is solved now so closing.
