### ISSUE TITLE
Accessing free state variable in TF mode

### ISSUE THREAD

**Issue by javdrher** [GPflow/GPflow#480]
Accessing the free state variable (e.g., to take a gradient w.r.t theta) from within the model optimization graph is quite straightforward: after compiling it is available in `model._free_vars` and can therefor be easily used in the code.

However, in AutoFlow methods this is a little more difficult: `_free_vars` is in a different graph and currently the only way seems to be to access it directly in the AF storage:
```python
@AutoFlow((float_type,[None, None]))
def predict_f(self, Xcand)
     theta = self._predict_f_AF_storage['free_vars']
     mu, var = self.build_predict(X, theta)
```
This feels hacky as identifying the AF storage is only possible in the method itself which may require overriding some standard interfaces. This also introduces a problem when using `build_predict` in general AutoFlow methods in different (for instance parent) objects (this is not uncommon in GPflowOpt) as it now has a theta parameter. A straightforward solution could be to set _free_vars in AutoFlow to point to the representation of the free state in the AutoFlow graph before running tf_method, and reverting it to its original value after the call. This change would turn the `_free_vars` member variable into an accessible representation of the free state in all methods running in TF mode.

**Comment by nknudde** [comment]
This would be a very useful feature to do some things I want to do in GPflowOpt.

**Comment by markvdw** [comment]
I think this is a question that will require some serious thought. Currently, the design is that free_state is _never_ referenced by the code constructing the graph itself. The graph is only constructed by referencing `Param` objects.

To elaborate on the use case (after taking to @javdrher), this is necessary if one wants to build a graph that contains the derivatives (or Hessian) with respect to _all_ parameters. I don't think there's a good way to do this any other way. You can't take a derivative w.r.t. a variable that is not a direct ancestor of the variable that is being differentiated. So it's not possible to construct a free_vars stand-in within the graph construction.

My take is that this is currently outside the remit of GPflow, as GPflow is designed to specify an objective function of a GP model, and then optimise it. However, I do think that in a next iteration of GPflow, where we want it to be a flexible way of specifying a graph with GP operations in it, this will have to be supported. And, as mentioned, other projects rely on this as well.

**Comment by javdrher** [comment]
Although free state seemed like a good idea I found some cases where this wouldn't work at all (e.g., a model wrapped in another model or parameterized, where build_predict is used in AutoFlow might have a free state which has an extended free state). So my proposed change is not guaranteed to work, hence I'm no longer in favor. 
Unfortunately, I can not think of a way to solve this currently. I'm closing this and we'll stall the feature. Feel free to contact us with ideas on how to accomplish this.
