### ISSUE TITLE
Undefined Symbol: _ZNK10tensorflow6Tensor20ComputeFlatInnerDimsEx

### ISSUE THREAD

**Issue by Chaztikov** [GPflow/GPflow#481]
Hi there,

Thanks for making GPflow.  I just installed it along with tensorflow and tensorflow-gpu via conda.  Tensorflow seems to work with the gpu and cpu.  

When I import GPflow, I receive this error:

tensorflow.python.framework.errors_impl.NotFoundError: /home/charles/anaconda3/lib/python3.5/site-packages/GPflow/tfops/matpackops.so: undefined symbol: _ZNK10tensorflow6Tensor20ComputeFlatInnerDimsEx

The version:
gpflow                    0.3.5a                   py35_0    omnia/label/dev

Thanks!

**Comment by icouckuy** [comment]
Hi Chatzikov,

Seems conda has an old version which still requires compiling custom tensorflow ops. Update to the latest version which is more friendly to install. However, it is not available on pypi. Just clone the repository and pep install -e .

**Comment by markvdw** [comment]
This is correct. Feel free to re-open the issue if this does not fix your problem.
