### ISSUE TITLE
Remove TensorFlow import in setup.py

### ISSUE THREAD

**Issue by javdrher** [GPflow/GPflow#487]
It seems that now the custom ops are no longer included, the TensorFlow import in setup.py is no longer required. This way, we could also add it as a dependency to install requires, which means GPflow could be installed simply by running `pip install .` after checkout and TF doesn't have to be pre-installed.

**Comment by markvdw** [comment]
Perfect! Are you offering to do a PR as well? :)

**Comment by markvdw** [comment]
Fixed with #488.
