### ISSUE TITLE
`q_sqrt` over-parametrisation

### ISSUE THREAD

**Issue by markvdw** [GPflow/GPflow#49]
I'm quite keen to get rid of the `q_sqrt` overparameterisation in `SVGP`. Currently a full square matrix is stored, even though only the bottom half is used. This has caused me some annoyances when optimising large amounts of inducing points. It slows down BFGS unnecessarily and makes the sizes of my parameter history files twice as large as they need to be.

I'm willing to put in some work to fix this, any tips on how to proceed? I could contribute to your current Tensorflow branch, or alternatively, the main Tensorflow branch. I think this is tangentially mentioned in https://github.com/GPflow/GPflow/issues/10.

**Comment by jameshensman** [comment]
Hi Mark,

I'd like that too. It's actually not as easy as I'd like though: you need a
wrapper for

(d|s|c)tpttf

and

(d|s|c) trttf

if that looks alien to you, the first letter is double|single|complex type,
and tpttf converts a 'packed' triangular matrix into a dense matrix (with
the zeros in ) and trttf converts back again.

I'm not sure if those are available in Eigen, but they're definitely
available in BLAS. The learning curve for getting a new tensorflow op up
and running seems steep to me, but Alex will give you some pointers I'm
sure.

**Comment by alexggmatthews** [comment]
See also this issue on the main tf repo
https://github.com/tensorflow/tensorflow/issues/1825

**Comment by markvdw** [comment]
I've started a bespoke TensorFlow op in #150. I'd appreciate some pointers.

**Comment by markvdw** [comment]
Also, why is it that `q_sqrt` stores the matrices in the outer dimensions (i.e. the most "left"), rather than the inner dimensions? E.g., to access the first q_sqrt matrix, `q_sqrt[:, :, 0]` is used, right?

Assuming a row-first memory layout, storing the matrices in the inner dimension should be faster, right? Since otherwise the strides between consecutive elements become large.

**Comment by jameshensman** [comment]
> why is it that q_sqrt stores the matrices in the outer dimensions

Well, I guess my (perhaps flawed) reasoning was that the data-matrix Y
usually appears in columns, so we should keep that Fortran-style ordering
for these too.

When we make predictions of the variance,

mu, var = m.predict_f(Xnew)

we want the means and variances of the different outputs in columns, right?
var.shape should match mu.shape.

when we do predict_full_cov(Xnew)

where should we put the extra dims? mu is N x D, should var be N x N x D or
D x N x N?

What about when q_sqrt contains diagonal matrices? Surely we want it to
match the shape of the mean?

I'm happy to change the ordering, I think it could make things nicer in
some cases. I'll look into submitting a PR for this; @markvdv, could you
make your op c-ordered, i.e., flat matrices stored in rows? I guess for
consistency you'd make one op for a single matrix, and another "batch_foo"
op for working with multiple rows.

**Comment by markvdw** [comment]
So you correctly guessed why I'm interested in this :)

I can definitely see the logic in this ordering now. I would agree with your ordering for the outputs. My thoughts for intermediate computations would be (as you could tell) to store "objects of interest" in the most memory-consecutive way possible, i.e. DxNxN, but I'm not too fussed, so don't jump straight into a pull request for my sake!

As for the ops, @jameshensman, you think C ordered is the right way to go? E.g. `vec_to_tri` would convert an KxL to a KxNxN tensor (K NxN matrices)? I think this is similar to other TensorFlow ops. `batch_matrix_band_part`, for example, also leaves the left most indices untouched...

**Comment by markvdw** [comment]
Fixed with PR #150
