### ISSUE TITLE
Support for multi-CPU processing in GPR prediction step

### ISSUE THREAD

**Issue by estebanag** [GPflow/GPflow#492]
While running the GPR example provided in the [GPflow docs](http://gpflow.readthedocs.io/en/latest/notebooks/regression.html), I see that all CPUs are initially used by `predict_y()`. However, after a short time, only one CPU is used. The example below (taken from the docs) can be used to replicate this behavior:

```python
import GPflow
import numpy as np

N = 2000
X = np.random.rand(N,1)
Y = np.sin(12 * X) + 0.66 * np.cos(25 * X) + np.random.randn(N, 1) * 0.1 + 3
k = GPflow.kernels.Matern52(1, lengthscales=0.3)
m = GPflow.gpr.GPR(X, Y, kern=k)
m.likelihood.variance = 0.01
xx = np.linspace(-0.1, 1.1, 1000000)[:, None]
mean, var = m.predict_y(xx)
```

Is this expected or is there a way to enable support for multiple CPUs?

**Comment by markvdw** [comment]
The multithreading of operations is handled by TensorFlow, not GPflow. It sounds like there is an operation which can not be multi threaded by TensorFlow at the moment (possibly the Cholesky?). GPflow can't really do much about it. If you want faster prediction, you can consider using `SGPR`.

If you want to delve into this issue further, which would be very useful for us, you could create a profiling trace by setting `dump_timeline = True` in `gpflowrc`. Then you can view the trace in Chrome by loading it in `chrome://tracing`.

**Comment by estebanag** [comment]
Thanks for the reply. I'll try to find out what TensorFlow is being unable to mulithread.

**Comment by YiMX** [comment]
I think multi-device processing is a very difficult problem. An easy implementation by TensorFlow is to separate inputs into multi subsets and feed them to the model on different devices.
