### ISSUE TITLE
Query add-kernel

### ISSUE THREAD

**Issue by parcero4** [GPflow/GPflow#497]
Hello,

Sorry about the silly question but, is there any difference between "kadd1" and "kadd2" in the following code?

```
import GPflow 


k1 = GPflow.kernels.RBF(1) 
k2 = GPflow.kernels.Matern12(1)
kern_list = [k1, k2]
kadd1 = GPflow.kernels.Add(kern_list)
kadd2 = k1 + k2
```

Best

**Comment by markvdw** [comment]
They should be functionally the same. Is there any particular reason that this is important? E.g. does it give different behaviour / unexpected results?
