### ISSUE TITLE
Collapsed Titsias variational bound for Gaussian likelihoods

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#5]
In the Gaussian likelihood case I think there are instances where it would be good to work with the collapsed evidence lower bound of Titisias ( equation 16 of http://www.aueb.gr/users/mtitsias/papers/sparseGPv2.pdf ) rather than the uncollapsed "Big Data" bound used by Hensman et at (  http://auai.org/uai2013/prints/papers/244.pdf equation 4) . Perhaps we should consider implementing it?

**Comment by jameshensman** [comment]
I think it would 'complete the set' to have that method included. 

We should also make sure it get included in the 'sanity check' notebook.

**Comment by jameshensman** [comment]
I had a little play with this, have a look at the sgpr branch. The likelihood work but I've not gone through the maths for prediction yet.

**Comment by jameshensman** [comment]
Done in PR #20
