### ISSUE TITLE
Multiple Kernel for Multiclass MCMC Sparse Gaussian Process

### ISSUE THREAD

**Issue by rfelixmg** [GPflow/GPflow#502]
Hi guys,

I am just not sure about if I got the right idea from the paper [1].

In the paper, for the multiclass case it was written: "To do multi-class classification with Gaussian process, one latent function is defined for each of the classes". My interpretation is that for each class we define a gaussian process with it's own kernel, so the optimization is to find the parameters for each of those |C| (number of classes) kernels;

Am I write about it? For me it seems that when you instantiate:
`gpflow.sgpmc.SGPMC(X,Y, kern=gpflow.kernels.Foo()`, num_latent=3
all the latent functions share this same kern. When I was expecting
kern=[gpflow.kernels.Foo()]*3

as it refeers [2] in eq.5. $\mathbf{K}_k$, where $K_k$ is computed by a covariance function defined to $c_1(.,.) ... c_l(.,.)$

$\mathcal{P}(\mathbf{f}) = \prod_{k=1}^{l} \mathcal{N}(\mathbf{f}_k|0,\mathbf{K}_k)$

[1] @inproceedings{hensman2015mcmc,
  title={MCMC for Variatinoally Sparse Gaussian Processes},
  author={Hensman, James and Matthews, Alexander G. de G.
          and Filippone, Maurizio and Ghahramani, Zoubin},
  booktitle={Proceedings of NIPS},
  year={2015}
}
[2] @inproceedings{hernandez2011robust,
  title={Robust multi-class Gaussian process classification},
  author={Hern{\'a}ndez-Lobato, Daniel and Hern{\'a}ndez-Lobato, Jos{\'e} M and Dupont, Pierre},
  booktitle={Advances in neural information processing systems},
  pages={280--288},
  year={2011}
}

**Comment by hughsalimbeni** [comment]
GPflow does not support separate kernels for each latent function. But if you want such a model, something like this might do: 

```python
class SVGPMultiKernel(GPflow.svgp.SVGP):
    def __init__(self, X, Y, kern_list, likelihood, Z, **kw):
        GPflow.svgp.SVGP.__init__(self, X, Y, kern_list[0], likelihood, Z, **kw)
        del self.kern
        self.kern_list = GPflow.param.ParamList(kern_list)
        assert len(kern_list) == kw['num_latent']
    
    def build_predict(self, Xnew, full_cov=False):
        mu, var = [], []
        for k in range(len(self.kern_list)):
            q_mu = self.q_mu[:, k, None]
            q_sqrt = self.q_sqrt[:, k, None] if self.q_diag else self.q_sqrt[:, :, k, None]

            m, v = GPflow.conditionals.conditional(Xnew, self.Z, self.kern_list[k], q_mu, q_sqrt=q_sqrt, 
                                                   full_cov=full_cov, whiten=self.whiten)
            mu.append(m)
            var.append(v)
        mu = tf.concat(mu, -1)
        var = tf.concat(var, -1)
        
        return mu + self.mean_function(Xnew), var
    
```

Example 

```python
[multi_kernels.pdf](https://github.com/GPflow/GPflow/files/1306182/multi_kernels.pdf)
[single_kernel.pdf](https://github.com/GPflow/GPflow/files/1306183/single_kernel.pdf)


N = 10
X = np.linspace(0, 1, 10).reshape(-1, 1)
Y = np.array(np.random.choice(np.arange(3), N).reshape(-1, 1), dtype=float)
Y = np.array([0,0,0,0,1,0,1,2,2,2], dtype=float).reshape(-1, 1)
Xs = np.linspace(-0.5, 1.5, 200).reshape(-1, 1)

cols = ['r', 'g', 'b']

model_single = GPflow.svgp.SVGP(X, Y, GPflow.kernels.RBF(1, lengthscales=0.1), GPflow.likelihoods.MultiClass(3), X.copy(), num_latent=3)

kern_list = [GPflow.kernels.RBF(1, lengthscales=0.1), 
             GPflow.kernels.RBF(1, lengthscales=0.1),
             GPflow.kernels.RBF(1, lengthscales=0.1)]

model_multi = SVGPMultiKernel(X, Y, kern_list, GPflow.likelihoods.MultiClass(3), X.copy(), num_latent=3)

for model, name in zip([model_single, model_multi], ['single_kernel', 'multi_kernels']):
    model.optimize()

    m, v = model.predict_y(Xs)
    for i, c in enumerate(cols):
        plt.plot(Xs, m[:, i], c=c)
    plt.title(name)
    plt.savefig('{}.pdf'.format(name))
    plt.show()

```

[multi_kernels.pdf](https://github.com/GPflow/GPflow/files/1306184/multi_kernels.pdf)
[single_kernel.pdf](https://github.com/GPflow/GPflow/files/1306185/single_kernel.pdf)

**Comment by st--** [comment]
For future such questions please use stackoverflow instead, there's a gpflow tag: https://stackoverflow.com/questions/tagged/gpflow !
