### ISSUE TITLE
Nomenclature changes in gpflow rewrite

### ISSUE THREAD

**Issue by st--** [GPflow/GPflow#504]
Currently, there are some inconsistencies in the GPflow code base, mainly concerning kernels. It would be great to get rid of them in the impending GPflow rewrite. I'd propose the following name changes:

Be explicit rather than implicit, especially for names that *don't* get used a lot:
`kernels.Kern` -> `kernels.Kernel`
`kernels.Prod` -> `kernels.Product`
`ekernels.Prod` -> `ekernels.Product`

`kernels.Add` -> `kernels.Sum` -- the object *is* a "Sum", and then it'll be consistent with the product
`ekernels.Add` -> `ekernels.Sum` -- for the same reason

`kernels.PeriodicKernel` -> `kernels.Periodic` -- no other kernel has "Kernel" as part of the class name, as they all live in the `kernels` module anyways.

Also, I'd propose to make functions like `conditional()` use keyword-only args (see [PEP-3102](https://www.python.org/dev/peps/pep-3102/)), as otherwise it's easy to accidentally omit or swap arguments when you have a long function call such as `conditional(Xnew, X, kern, f, full_cov, q_sqrt, whiten)`...

(Maybe at that point worth converting `kullback_leiblers.gauss_kl` into a similar function-with-keywords to switch between whitened/unwhitened and diagonal/full-cov versions?)

**Comment by st--** [comment]
@awav looks like this got lost?

any thoughts on this ?

**Comment by alexggmatthews** [comment]
@st-- all the examples you've given make sense to me. Something that's always annoyed me is repeat math code as in #21 . It is the sort of thing that quite easily does not reach the top of the to do list.

**Comment by alexggmatthews** [comment]
@st-- if you prepared a PR with the changes you've suggested I'd be willing to accept it, unless anyone disagrees on here in say the next day.
