### ISSUE TITLE
Example of end-to-end training with GPFlow plus a neural net coded in tensorflow

### ISSUE THREAD

**Issue by mlopezm** [GPflow/GPflow#505]
Hello,

Is there any example on how to implement a neural network using tensorflow plus a final 'layer' implementing a GP process. Something similar to the architecture presented in: "Adversarial Examples, Uncertainty, and Transfer Testing Robustness in Gaussian Process Hybrid Deep Networks" [here](https://arxiv.org/pdf/1707.02476.pdf)

I would like to be able to train the resulting model end-to-end. I suppose using the variational model it could be possible to optimize the GP parameters plus the NN weights using gradient descent, all at the same time, but I do not know how to code to connect the two models (tensorflow NN and GPflow GP)

Thank you

**Comment by alexggmatthews** [comment]
Hi there, thanks for your interest in the software and our paper. @john-bradshaw is on internship at the moment but we would like to release code to do this.

**Comment by mlopezm** [comment]
Hi, I am glad to hear that. It would be great to have an example on how to do this. A partial example with just one dense NN layer and one GP 'layer' is enough. It is just to see how to connect the two pieces.

I have seen [here](http://gpflow.readthedocs.io/en/latest/notebooks/models.html#Building-new-models) how to implement a linear classification using cross-entropy as the likelihood, but, in this case, the weights of the model are given as GPflow parameters (not Tensorflow variables).

I have investigated Edward. In Edward it is possible to mix a Tensorflow NN and a final 'bayesian' layer. But, they lack the GP-oriented functionality (kernels) provided by GPflow. 
The package keras-gp can perform this too, but it requires on top of Tensorflow to have Matlab or Octave installed, which is not always possible. 

This is why I think to be able to do something similar with GPflow would be really interesting. The functionality of GPflow is really good and it would be great to know how to train an NN/GP mixed model.

Thank you and best regards

**Comment by hughsalimbeni** [comment]
Just to add: if you only want fully connected networks you can do this right now with GPflow, as long as you create the network with Param objects. Here's some code I often use:

```python
def xavier(dim_in, dim_out):
    return np.random.randn(dim_in, dim_out)*(2./(dim_in+dim_out))**0.5

class NN(Parameterized):
    def __init__(self, dims):
        Parameterized.__init__(self)
        self.dims = dims
        for i, (dim_in, dim_out) in enumerate(zip(dims[:-1], dims[1:])):
            setattr(self, 'W_{}'.format(i), Param(xavier(dim_in, dim_out)))
            setattr(self, 'b_{}'.format(i), Param(np.zeros(dim_out)))

    def forward(self, X):
        if X is not None:
            for i in range(len(self.dims) - 1):
                W = getattr(self, 'W_{}'.format(i))
                b = getattr(self, 'b_{}'.format(i))
                X = tf.nn.tanh(tf.matmul(X, W) + b)
            return X
```

Then to make a RBF kernel with this network
```python
class NN_RBF(RBF):
    def __init__(self, nn, *args, **kw):
        RBF.__init__(self, *args, **kw)
        self.nn = nn
    
    def square_dist(self, X, X2):
        return RBF.square_dist(self, self.nn.forward(X), self.nn.forward(X2))
```

and then use it like this:
```python
net = NN([5, 10, 2])  # for 5D inputs and a 2D GP
kern = NN_RBF(net, 2)
```

You can add this kernel to any GPflow model and the network weights will get optimized along with everything else. Of course, to do more fancy things like convolutions and batch norm you probably want something like keras, which currently isn't easy to use with GPflow, but this functionality is one of exiting things to come in the upcoming 1.0 release

**Comment by mlopezm** [comment]
Thank you Hugh!!,
It is a great example. I saw something similar in the documentation using Param objects.
What I actually try to do is to use a combination of convolutional and LSTM networks plus a final GP layer. I currently have implemented it with keras but I could redo it in pure Tensorflow if that is needed. That is the reason I wanted to see an example using Tensorflow variables.
I see now that what I am trying to do can be difficult, and It would be great to have access to the next release that you mention.
Thank you again and congratulations for your great work

**Comment by awav** [comment]
@mlopezm, I'm sure, new GPflow-1.0-RC is worth a try. Mixing TensorFlow models with GPflow-1.0 became much easier. Feel free to share your thoughts and questions about it in https://github.com/GPflow/GPflow/issues/519.

**Comment by hoangcuong2011** [comment]
Hello,
I just want to second @mlopezm and hope you will provide the code to do this. I enjoyed reading the paper a lot.
Best,

**Comment by yatuzhang** [comment]
Hello,
I am also interested in doing something similar to a hybrid GPDNN mentioned in https://arxiv.org/pdf/1707.02476.pdf

I got a fully-connected NN somewhat working but I am having trouble with CNNs.  Specifically, I am wondering how I can use something like tf.nn.conv2d on Params and MinibatchData since this operation does not support such types.  An example on this would be of great help.

Thanks!

**Comment by john-bradshaw** [comment]
Sorry for the delayed response.
Here's a gist on how one can do such a thing using the new GPflow:
https://gist.github.com/john-bradshaw/11bbf17dbca013d9fc3886a7bfe46840

It's just a simple 4 layer network with a GP on top and seems to be working okay:
![screen shot 2017-11-07 at 14 25 34](https://user-images.githubusercontent.com/7681251/32498608-0ddfe3fa-c3c8-11e7-8234-310eac568c1a.png)

**Comment by yatuzhang** [comment]
Thank you for this awesome example @john-bradshaw!!
I tried to run the code in your Gist as is, with the latest TF (1.4.0) and GPflow (1.0.0), but ran into this issue:
**gpflow.core.base.GPflowError: Tensor "SVGP" uses different graph.**
I thought the code already took care of putting the NN part and GP part into the same graph, but looks like it is not?  Is there any additional step I am missing?
Thanks!

**Comment by john-bradshaw** [comment]
What GPflow git commit are you using? 

I wrote this for GPflow git commit hash: f618fe4d9aa096b32a3d24576d68f46a3f260116
I think GPflow 1.0 has been updated in the last few days to compile automatically. To avoid this you also have to use the context manager `gpflow.defer_build()` to stop it compiling automatically on the default TF graph.

**Comment by yatuzhang** [comment]
@john-bradshaw Thanks, that solved the problem.

**Comment by john-bradshaw** [comment]
Great! Glad to hear it.

**Comment by silburt** [comment]
@mlopezm I am wondering if your Keras/GPflow implementation is available somewhere that I could look at? I am interested in using Keras with a top layer GP, but will switch to tensorflow if it is a pain to do...

Thanks in advance.

**Comment by silburt** [comment]
@yatuzhang @john-bradshaw 
I have been trying to run the same example and got the same error: gpflow.core.errors.GPflowError: Tensor "SVGP" uses different graph.

I've installed GPflow from that specific commit (https://github.com/GPflow/GPflow/commit/f618fe4d9aa096b32a3d24576d68f46a3f260116) and am (I think correctly) using the context manager, but still getting the same error. Is
```
with gpf.defer_build():
         gp_model = gpf.models.SVGP(h, phs.label, kernel, likelihood, np.ones((num_inducing, num_h), gpf.settings.np_float),num_latent=num_classes, whiten=False, minibatch_size=None, num_data=x_train.shape[0])
```
not the right way to implement the context manager? 

Thanks very much,
Ari

**Comment by john-bradshaw** [comment]
Hey @silburt !

Are you sure you are using the version of GPflow (f618fe4). I don't think that `gpf.defer_build()` did not exist as a method back then so I would expect it to raise an exception on trying to use that context manager before it got to the graph bit.

Anyway, if you do want to use a newer version of GPflow then this should work on the current master (git commit f42fc3ea33ec3a8c37a45d3ccdd41e60bed5690e):
https://gist.github.com/john-bradshaw/e6784db56f8ae2cf13bb51eec51e9057
I've yet to run it all the steps but it seems to start okay.

Hope this is helpful, John

**Comment by silburt** [comment]
@john-bradshaw I gave your new script a try and it works. Thanks so much for the speedy reply and help, I really appreciate it!

**Comment by john-bradshaw** [comment]
Cool, no problem, glad that it now works.

**Comment by silburt** [comment]
@hughsalimbeni for your post here from above - https://github.com/GPflow/GPflow/issues/505#issuecomment-333201730 - do I understand it correctly that the following is an appropriate generalization:
```
net = NN([5, 10, 2])  # for 5D inputs and a 2D GP
kern = NN_RBF(net, 2)
```
generalizes to:
```
input_dim = 5                            #input dimension
output_dim = 2                         #output dimension
number_hidden_layers = 3       #number of hidden layers in neural network
units_per_hidden_layer = 10    #units per hidden layer in neural network

nn_array = [input_dim]
for i in range(number_hidden_layers):
    nn_array.append(units_per_hidden_layer)
nn.array.append(output_dim)

net = NN(nn_array)  # for 5D inputs and a 2D GP
kern = NN_RBF(net, output_dim)
```
Thanks :).

**Comment by hoangcuong2011** [comment]
Hi @john-bradshaw ,

Thanks for the code. I am trying to run it without success though. There are several types of errors as below:
1. line 85
    def suggest_good_intial_inducing_points(phs: DataPlaceholders, x_data, h, tf_session, num_inducing):
SyntaxError: invalid syntax at phs: DataPlaceholders
2. line 158
    log_likelihood_predict = gp_model.likelihood.predict_density(*gp_model._build_predict(h), phs.label)
SyntaxError: only named arguments may follow *expression
3. ImportError: /home/hoangcuong2011/anaconda2/envs/py27_env_gpflow_specific_commit/lib/python2.7/site-packages/tensorflow/python/../../../../libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/hoangc
uong2011/anaconda2/envs/py27_env_gpflow_specific_commit/lib/python2.7/site-packages/google/protobuf/pyext/_message.so)

I fixed the first and second types of error by changing phs: DataPlaceholders to phs only, and I remove the * character. But I could not fix the last one.

Do you have any suggestion?

Thanks a lot,

**Comment by hoangcuong2011** [comment]
Hi @john-bradshaw 

I just fixed the problem. It turns out the problem is because I already installed tensorflow in the first place before installing gp-flow.

When I create a new anaconda environment, and install gp-flow (and its dependencies) with specific commit hash: f618fe4, everything works well on that environment.

I hope my experience is useful for other people who encounter similar problems.

Thanks.

Best,

**Comment by VA70** [comment]
Hello, 

I've been looking at using GPflow with tensorflow to recreate a manifold GP (https://arxiv.org/abs/1402.5876).  I stumbled across this discussion thread which very helpfully introduced me to John's paper on GPDNNs.  While trying to apply the method to a much simpler problem (an mGP for a step function) and looking at John's code at **john-bradshaw/gpdnns.py** I did come across an issue which I haven't been able to work out myself, and wondered if anyone else had any ideas...

When learning the NN and GP hyperparameters I presume the objective function being minimised is the negative log marginal likelihood:
1/2 * **Y**^T(**K**+**sigma**^2 **I**)^(-1)T***Y** + 1/2 * log[det(**K**+**sigma**^2 **I**)] 
where **sigma** is the usual gaussian likelihood std and **K** is the (RBF, say) kernel applied to the inputs passed through the **NN** and **Y** are the training set labels.  As I understand it, the tensorflow graph uses the placeholder inputs to forward propagate the inputs **X,Y** through the graph and these are used fo calculate the loglikelihood.  

In **john-bradshaw/gpdnns.py** implementation when calling the 
gp_model.likelihood.predict_mean_and_var(* gp_model._build_predict(h)) 
for the accuracy calculation the placeholders in tf_session.run([avg_acc, avg_ll], feed_dict=fd) 
used **X_test, Y_test**
However, should we not be using the predictive equation for the mean of the GP
1/2 * **k**^T(**K**+**sigma**^2 **I**)^(-1)T***Y**
where **K** and **Y** are as before but **k** is kernel applied to the **X_train** and **X_test**

I realize that predict_mean_and_var(self, x_test) is designed to allow a prediction of **Y** for a different set of inputs having calculated **K** and using the training set **Y** labels when creating the GPflow.model, but in this case doesn't the feed_dict use the **X_test** sets to recalculate **K** and it will use **Y_test** rather than the original **Y_train**?

If so how can we stop the graph from 'recreating' GPflow.model using the test set when testing?

Many thanks,

Vlad

**Comment by VA70** [comment]
Hello @john-bradshaw and @alexggmatthews , I posted above but being new to Github didn't realise I that adding '@name...' might be necessary to add your names to the body of the text.

Regards

**Comment by timhouben** [comment]
Currently i'm working on a GPDNN and took the code of @john-bradshaw as an example. The example is trained with Adam optimiser end-to-end. But I discovered only the network weights are being optimised. The trainable parameters of the gaussian process remain the same.

I've tried to implement gpflows ScipyOptimizer into the code but without success. Got complains about feeding the right placeholders to the optimiser. Tried several things but nothing worked.

Does someone have a solution for optimising both the NN and the GPFlow model end-to-end?

Thanks a lot!

**Comment by john-bradshaw** [comment]
@va70: sorry for the delayed reply.

Yes you're right, if we were using a normal GP we would need to feed tensors through the NN part twice. Once for `X_train` (to create `h_train`) and one for `X_test` (to create `h_test`). We would want to make sure that the NN was using the same weights for both parts (or to put it another way `h_train = f(X_train, W)` and `h_test = f(X_test, W)` with same `f` and `W`). As I've used a `tf.template` in my Gist it is simple to feed multiple inputs through the same network.

However, the reason we do not need to do this in this example is that we are using Sparse Variational GP (SVGP). This model uses inducing inputs, $$\bm{Z}$$, that live in the same space as the features produced by the NN. Check out http://proceedings.mlr.press/v38/hensman15.pdf. 
In particular check out equation 19 of this paper, which is the objective we use for training. And for predictions equation 21. If you prefer to look at the code you can also  comapre the `_build_predict` method of  _"GPflow/gpflow/models/svgp.py"_ versus _"GPflow/gpflow/models/gpr.py"_

Following these through hopefully you can see we only need the kernel evaluated between the inducing points and `h_test` at prediction time, so we reuse the NN we have created to avoid unnecessarily creating an extra large TF graph. 


@timhouben: Sorry for the slow reply. I'm a bit confused as to your question. In my example the GP parameters are being trained.
You can see this by printing (before and after training):
`gp_model.kern.lengthscales.read_value(tf_session)`

Alternatively, you can add the GP's parameters to TensorBoard, with something like:
[tf.summary.scalar(param.full_name, param.constrained_tensor)
                    for param in gp_model.parameters if param.shape == ()]

Doing this I see the kernel's variance and lengthscale change as function of step number:
![screen shot 2018-03-20 at 11 44 57](https://user-images.githubusercontent.com/7681251/37653175-db3c1e74-2c35-11e8-9589-e14ac53a02d8.png)

**Comment by hughsalimbeni** [comment]
I've recently put together a notebook with some examples of incorporating other models into gpflow 

https://github.com/GPflow/GPflow/blob/hugh/advanced_usage_notebook/doc/source/notebooks/advanced_usage.ipynb

I'd be interested in your thoughts

**Comment by john-bradshaw** [comment]
Nice work Hugh!

**Comment by boliu68** [comment]
Thanks for sharing the inspiring code @john-bradshaw . I came across one problem when I test your code. I repeat executing the code many times with the random initialization. In most cases, I obtained the reasonable testing performance which is the same as you posted in the figure. However, in some circumstances, the likelihood of the test set get stuck no matter how training loss decreases. I would be appreciated for your hint.

**Comment by litpuvn** [comment]
i am curious about the example of GP with mnist dataset.
https://gist.github.com/john-bradshaw/11bbf17dbca013d9fc3886a7bfe46840


```
    gp_model = gpf.models.SVGP(h, phs.label, kernel, likelihood, np.ones((num_inducing, num_h), gpf.settings.np_float),
                               num_latent=num_classes, whiten=False, minibatch_size=None, num_data=x_train.shape[0])

```

`        minimise = optimiser.minimize(gp_model.objective)  # this should pick up all Trainable variables.
`
The objective function of the network is the objective of GP model. And the GP model takes last hidden layer and the labels as inputs for optimization.

Is this correct if we train entire network with that objective?
Is it equivalent  if i just split into two networks, one is the neural network and the other is GP. Then i train the neural network and use its output to feed into GP?
