### ISSUE TITLE
Question: gpflow vs GPflow versioning

### ISSUE THREAD

**Issue by JustinBewsher** [GPflow/GPflow#507]
Hey,

I've just moved to the new release of gpflow with the name rebranding. However, I had saved a number of results, including learnt GP models, previously, using GPflow branding into pickle files.

Now when I attempt to load them, I run into issues because it cannot find "GPflow" objects  anymore.

I know there were some commands to change code, but is there a way to update the saved files to make them compatible or will I need a separate instance of eg  GPflow  0.3.8 somewhere on my computer to access them?

Thanks for your help.

Best,
Justin

**Comment by markvdw** [comment]
No, not as I know. This is a known weakness of pickle, that it's sensitive to changes in the code. Pickle is only meant to be a short-term temporary storage, not a long term one.

A more reliable way of saving models is to store the parameter dict from `model.get_parameter_dict()`.  Restoring can be done by recreating the model and using `mode.set_parameter_dict(dict)`. You could write a script to load the pickled models with the old version, and store the dicts instead.
