### ISSUE TITLE
Number of inducing points

### ISSUE THREAD

**Issue by hoangcuong2011** [GPflow/GPflow#509]
Hello,

Thanks for creating such a great GP library. I am about doing some experiments with GPflow and regression. One thing that is not so clear to me is to select the number of inducing points for sparse GP model. 

I took a look at http://gpflow.readthedocs.io/en/latest/notebooks/Sanity_check.html. I can imagine I should create a sparse GP model using GPflow as follows:

m = gpflow.sgpr.SGPR(X, Y, kernel = some_kernel, Z=X.copy())

But how is about to select the number of inducing points instead of using a (fixed) number of data points for Z. Did I miss anything? Could you instruct me how to  so?

Thanks!

Best,

Hoang Cuong.

**Comment by hughsalimbeni** [comment]
Glad you like GPflow!

By passing Z = X.copy() you have inducing points at every data point, so you may as well use GPR (which is exactly this model but implemented more efficiently). The notebook to which you refer is there to check method equivalence, and isn't an example of a practical use.  

If you want to have a smaller number of inducing points you need to specify their initialization. Here are some options:
```python
Z = np.random.choice(X, M, replace=False)  # a random subset of data

from scipy.cluster.vq import kmeans2
Z = kmeans2(X, M, minit='points')[0]  # use k-means. This is recommended for most situations

Z = np.random.randn(M, X.shape[1])  # random locations. NB be careful with this in high dimensions
```

In all cases, you then you create the model:
`m = gpflow.sgpr.SGPR(X, Y, kernel=some_kernel, Z=Z.copy())
`

I would suggest taking `M` to be about 50-1000, depending on the complexity of your function and the computational available (lower is `M` cheaper, but less expressive). You'll find things very slow if you go much higher than 1000

**Comment by hoangcuong2011** [comment]
Thanks @hughsalimbeni for your answer! Pretty clear!
