### ISSUE TITLE
GPflow on pypi

### ISSUE THREAD

**Issue by jameshensman** [GPflow/GPflow#51]
Installing GPflow should be as easy as 

```
pip install gpflow
```

via the python package index. It might also be nice to have an anaconda package.

**Comment by alexggmatthews** [comment]
Hi @jameshensman , this is now possible with the release of tf 0.9.0 as a pip package on the main tf webpage.

**Comment by alexisboukouvalas** [comment]
I am happy to help with this. How difficult is it to create a PyPI package?

**Comment by jameshensman** [comment]
I think it's one of those things that's easy when you know how. Max
Zwiessele handles it for GPy, there might be some documentation lying
around.

James.

**Comment by ediphy-azorab** [comment]
Are there any plans to pursue this?

**Comment by awav** [comment]
@ediphy-azorab yes
