### ISSUE TITLE
Question: X_var initialization in BayesianGPLVM

### ISSUE THREAD

**Issue by ZhengYi0310** [GPflow/GPflow#522]
Hey,
      In the BayesianGPLVM class in gplvm.py file, the **_X_var_** matrix (which seems to be the covariance matrix associated with the variational distribution _**q(X)**_ ) is initialized to have a shape **_N x Q_**. Does this implicitly assume the full independence for _**q(X)**_  therefore the covariance matrices along each dimension are diagonal and they can be fully factorized ? If we follow the general assumption that _**X**_ is not **i.i.d**, then they can only factorized along each dimension, and the X_var should have a shape **_N x N x Q_** right ?
###############################################
Edit:
Found the implementation for full covariance matrix in the gplvm-fullconv branch. But in that branch the **_X_std_** is  _**N x Q x Q**_. According to [Variational Gaussian Process Dynamical Systems, A. Damianou, M. K. Titsias and N. D. Lawrence. (2011), NIPS](http://staffwww.dcs.shef.ac.uk/people/A.Damianou/papers/vgpds/vgpdsNIPS11.pdf), the variational distribution _**q(X)**_ can only be factorised along each dimension, and for each dimension the covariance matrices has shape **_N x N_**. Can anyone help with my confusion ?

Thanks very much for your time and patience.
Yi

**Comment by ZhengYi0310** [comment]
Found the implementation for full covariance matrix in the gplvm-fullconv branch.

**Comment by hughsalimbeni** [comment]
The paper to which you refer is actually more of a Deep GP paper, where the first layer is used to correlate a (1D) latent variable using time as the covariate. The machinery is very similar to the BayesianGPLVM, but with a crucial difference: in the BayesianGPVLM the prior over the latents is i.i.d., so the posterior might be reasonably close to factorized; in the VGPDS paper the prior over the latents is correlated, so an uncorrelated posterior would not work well (it would be a bit like trying to do mean-field VI for simple GP model: you can, but it doesn't work effectively). Regarding correlations over the $$Q$$ dimensions, this is possible but might not make all that much of a difference and is harder to implement. In summary, just using the $$N\times Q$$ version (i.e. factorised both directions) is what GPflow currently implements, and is likely to be sufficient.
