### ISSUE TITLE
Parameter tying

### ISSUE THREAD

**Issue by Hava842** [GPflow/GPflow#538]
I am having difficulties with parameter tying. I have two separate kernels and I want them to share their lengthscales.

I tried
`kern1.lengthscale = kern2.lengthscale` however this is not allowed because the parameter tree already contains kern2.lengthscale [https://github.com/GPflow/GPflow/blob/master/gpflow/param.py#L805](url)

Help is much appreciated

**Comment by Hava842** [comment]
realized that this is a duplicate: https://github.com/GPflow/GPflow/issues/322

**Comment by markvdw** [comment]
The easiest way to do this is to write your own kernel which shares a `Param` object for the shared lengthscales, have the object compute the two kernels in separate functions. May need some tweaking of the models.

**Comment by Hava842** [comment]
Thank you. I implemented as you said and it worked, although its not very elegant.

Maybe we should consider adding a class TiedParam(Param) that does not show up in the free variables and just refers to the tf array of the other Param that it is tied with. Additionally, we need to ensure that the other Param is in the same tree... Just speculating.

**Comment by markvdw** [comment]
In the next version of GPflow (released next Friday), you can do a very elegant solution where you define a shared external tensor for two parameters. One may be able to even put this logic in a transform.
