### ISSUE TITLE
GPflow-1.0 release

### ISSUE THREAD

**Issue by awav** [GPflow/GPflow#539]
Hello everyone,

Next week on Friday, November 10, we are going to merge (release) `GPflow-1.0-RC` into master. Feel free to post questions, objections ;)

**Comment by markvdw** [comment]
This is great! 10 Nov?

**Comment by awav** [comment]
@markvdw yes

**Comment by alexisboukouvalas** [comment]
Great job, I look forward to trying the new version.
Is there a list somewhere on the main changes and the major sources of backwards compatibility breaking? I will need to go in and update my code and I suspect others as well.

thanks again for working on this

**Comment by icouckuy** [comment]
Great, thanks for the heads up. Unfortunately I haven't had much time to test it yet. With merge (release) do you mean you are also going to tag it 1.0?

**Comment by alexggmatthews** [comment]
Note we will only be supporting Python 3 going forward https://github.com/GPflow/GPflow/issues/516

**Comment by hughsalimbeni** [comment]
Looks great! Small niggle: the scipy optimizer doesn't seem to take a maxiter argument. And I couldn't immediately see how best to use a callback (I know @markvdw has a fancier way of doing this with tensorboards, but something simple would be nice too) 

Also, will there be an external variables demo (e.g. keras/slim/tf.Variable) showing the intended way to hook these things together? That would be really useful.

**Comment by markvdw** [comment]
Doing a simple callback would be great as well, but it's difficult to create a unified interface for scipy and tensorflow optimisers. For tf optimisers, I would just inherit from the optimiser, and create your own loop. Few lines of extra code and you get total control.

**Comment by john-bradshaw** [comment]
@hughsalimbeni 
Think you do it like:
`    gpflow.train.ScipyOptimizer(options=dict(maxiter=200)).minimize(m)`
so at the Minimizer class creation time rather than with the minimize function.

**Comment by alexggmatthews** [comment]
@awav do we want to get rid of the `from tensorflow.contrib.data import Dataset` in `dataholders.py` ? In _tensorflow_ 1.4 I get a deprecation warning telling me to use `tf.data.Dataset` . This relates to the question of what version of _tensorflow_ we should require for GPflow 1.0

**Comment by awav** [comment]
@icouckuy, yes, I would tag it as `1.0`

@john-bradshaw, gpflow.train.ScipyOptimizer().minimize(m, maxiter=200) works too

@alexggmatthews, stable `dataset` interface is available from 1.3, but it is in `contrib` folder, so technically we will require tensorflow >=1.3. As I understood tensorflower's intend to replace queueing mechanism with `dataset` and deprecate queues at all.

**Comment by awav** [comment]
@alexggmatthews 
```
        if parse_version(tf.VERSION) < parse_version('1.4.0rc0'):
            from tensorflow.contrib.data import Dataset
        else:
            from tensorflow import data
            Dataset = data.Dataset
```

**Comment by awav** [comment]
@alexisboukouvalas this release breaks lots of things, but the gpflow method and class interfaces stayed the same. Most of the internals were rewritten and we added some features. Breakthrough change is that model's parameters are no longer represented as a flat variable, but distinct tensorflow trainable variables. I will post release notes on thursday.

**Comment by alexggmatthews** [comment]
@awav @jameshensman  I guess we could also just pin to tensorflow v1.4 ? It is beyond the release candidate stage. We've never really planned to maintain backwards compatability with old versions of tensorflow. I don't feel strongly either way.

**Comment by markvdw** [comment]
I feel strongly towards only supporting the newest version of TensorFlow. I'm pretty sure that not everything would have worked with tf1.0 for a long time, even though that was the requirement. TensorFlow is moving too fast, with too many good new features to stay backwards compatible.

One current example is that `tf.matmul()` doesn't broadcast properly. This negatively influences the neatness of our code and our performance. This will hopefully be fixed in a near version of TensorFlow, and I reckon we should use it asap. This is just one example of many where GPflow will want to use the latest version of TF as soon as it has been released.

I reckon the policy should be to not guarantee support of old versions of TF if a new version has come out of its RC stage. It doesn't take a lot of effort to upgrade, TF does not release updates that break old code (often :) ), and we really do need the new features.

**Comment by icouckuy** [comment]
I also prefer to support only one tensorflow version at a time. As long as tensorflow is free (and opensource) on all platforms everybody can just update TF.

They only disadvantage I see is that other libraries might stay behind in supporting tensorflow which makes it harder to mix them with GPflow (e.g., combining deep networks with GPs).

**Comment by markvdw** [comment]
That's a risk, but if anything, I think deep learning packages move faster than GPflow does.

If this is a problem, end users always have the choice to not use the most bleeding edge commit of GPflow.

**Comment by alexggmatthews** [comment]
@awav @jameshensman might be worth talking about how exactly we want to do this in terms of Git procedure. Does master currently merge into the release candidate / vice versa without conflicts?

**Comment by awav** [comment]
GPflow 1.0 released!

**Comment by awav** [comment]
@alexisboukouvalas https://github.com/GPflow/GPflow/releases/tag/1.0.0
