### ISSUE TITLE
Multiple GP outputs with deep learned kernel

### ISSUE THREAD

**Issue by silburt** [GPflow/GPflow#542]
Hello,
I am interested in modelling multiple timeseries that are correlated by some underlying GPs, with a deep learned kernel (vs. a rigid standard kernel that you choose apriori). An example of such timeseries is attached in the figure (y-axis = data values, x-axis = time), and maybe their inherent relationship to each other is, e.g. (d=data, t=time, X=GP, a,b,c=coefficients):
d_1(t) = a_1 + b_1 X_1(t) + c_1 X_2(t)
d_2(t) = a_2 + b_2 X_1(t) + c_2 X_2(t)
d_3(t) = a_3 + b_3 X_1(t) + c_3 X_2(t)

From this post - https://github.com/GPflow/GPflow/issues/312 - and this - https://github.com/GPflow/GPflow/issues/505 - it seems like this should be possible, but I can't quite wrap my head around how to put this together. Is there maybe a toy/skeleton example somewhere I could get my hands on and play around with, or maybe a point in the right direction?

Many thanks in advance, and apologies if this was not the correct place to post this question.

Ari

![example_data](https://user-images.githubusercontent.com/9949184/32573777-21f8a1f8-c49d-11e7-967a-0737caeac942.png)

**Comment by silburt** [comment]
OK, so after more digging it seems like the first step is to use a coregion kernel:
```
#set up coregionalized kernel
ndim = 3
coreg = gpflow.kernels.Coregion(1, output_dim=ndim, rank=1, active_dims=[1])
lik = gpflow.likelihoods.SwitchedLikelihood([gpflow.likelihoods.StudentT()]*ndim)
k1 = gpflow.kernels.Exponential(1)
kern = k1 * coreg

#set up model
m = gpflow.svgp.SVGP(X_augmented, Y_augmented,
                     kern=kern, likelihood=lik, num_latent=1,
                     Z=X_augmented[::3].copy())
```
But I think(?) this creates a coregion kernel corresponding to:
d_1(t) = a_1 X_1(t)
d_2(t) = a_2 X_1(t)
d_3(t) = a_3 X_1(t)

Is there a way to modify ```kern``` to accomplish:
d_1(t) = a_1 + b_1 X_1(t) + c_1 X_2(t)
d_2(t) = a_2 + b_2 X_1(t) + c_2 X_2(t)
d_3(t) = a_3 + b_3 X_1(t) + c_3 X_2(t)

Maybe something like:
```
coreg = gpflow.kernels.Coregion(1, output_dim=ndim, rank=1, active_dims=[1])
k1 = gpflow.kernels.Exponential(1)
k2 = gpflow.kernels.RBF(1)
kern = k1 * coreg + k2*coreg (+ a constant somehow)
```

**Comment by jameshensman** [comment]
Hi @silburt ,

what you're describing is just a change to the rank of the coregion kernel.  Simply set the rank to two, and that will get what you need apart from the constant. 

To get the constant term in there too, I suggest you add anouther kernel. So:
```python
k = gpflow.kernels.RBF(1) * gpflow.kernels.coregion(1, output_dim=3, rank=2, active_dims=[1]) + \
    gpflow.kernels.Constant(1) * gpflow.kernels.coregion(1, output_dim=3, rank=1, active_dims=[1])
```
You could also go crazy and add some more (coregionalized) kernels in there: this is the Linear model of Coregionalization (see Alvarez's review).

Please heed the warning in the Coregionalization notebook about initializing the kernel sensibly :)

**Comment by silburt** [comment]
@jameshensman 
Thanks for your response. Yes, I've read the Alvarez review in some detail and with great interest. However, to my understanding, increasing the rank yields new latent functions which all share the _same_ covariance kernel. Thus, for the following scenario:
d_1(t) = a_1 + b_1 X_1(t) + c_1 X_2(t)
d_2(t) = a_2 + b_2 X_1(t) + c_2 X_2(t)
d_3(t) = a_3 + b_3 X_1(t) + c_3 X_2(t)

If I wanted X_1(t) to use the RBF kernel, and X_2(t) to use the Matern32 kernel, I don't think that increasing the rank will get me there, right? But, it looks as though you added multiple coregion matrices together to include the constant in your example above, so maybe:
```
k = gpflow.kernels.RBF(1) * gpflow.kernels.coregion(1, output_dim=3, rank=1, active_dims=[1]) +\
      gpflow.kernels.Matern32(1) * gpflow.kernels.coregion(1, output_dim=3, rank=1, active_dims=[1]) +\
gpflow.kernels.Constant(1) * gpflow.kernels.coregion(1, output_dim=3, rank=1, active_dims=[1])
```
achieves the scenario I desire? This code seems to compile and run, and the output seems to suggest that this does what I want.

And yes, thanks, I've been initializing the coregional matrix with random weights :).

Thanks,
Ari

**Comment by silburt** [comment]
@jameshensman - from https://github.com/GPflow/GPflow/issues/563#issuecomment-347375241 - you seem to confirm what I wrote above, so I think I'm good to go 🥇 . Thanks a lot for all your help.
