### ISSUE TITLE
Save and Restore model

### ISSUE THREAD

**Issue by lanhnguyen2010** [GPflow/GPflow#543]
Hi All,
With GPLVM, can we store trained model to file so that we can restore to continue training or prediction?

**Comment by mrksr** [comment]
Pickling does not seem to be an option anymore (?). Is there a nice way to persist GPflow models now?
I guess one could use the tensorflow Savers, but this would - I think - only give the graph back and not the "rich graph" provided by GPflow. Am I missing something?

**Comment by markvdw** [comment]
The correct way is to use code to recreate the model. Then either TensorFlow Saver objects can be used for re-loading the parameters, which has the added advantage that it also restores the state of optimisers e.g. Adam (this is important for restarting optimisation). Alternatively, you can use `model.assign()` and pass it a dict with the full names of the parameters and their respective values. You can get such a dictionary for storage using:

`param_dict = {p[0].full_name.replace('SGPR', 'SGPU'): p[1] for p in zip(vfe.trainable_parameters, vfe.read_trainables())}`

We may make a convenience function for this as well.

**Comment by st--** [comment]
:+1: for still supporting get_parameter_dict()

**Comment by lanhnguyen2010** [comment]
`
k = ekernels.RBF(2, ARD=True, active_dims=[0,1])
m = GPflow.gplvm.BayesianGPLVM(X_mean=X_mean, X_var=0.1*np.ones((N, Q)), Y=Y, kern=k, M=M, Z=Z)
m.likelihood.variance = 0.01
m.optimize(disp=True, maxiter=100)`
I have a simple model like that. Can you please help me an example how to save model m?

**Comment by markvdw** [comment]
Currently the best thing to do is to adapt the `param_dict = ...` code above, and pickle the resulting dictionary. You can restore by recreating the model and using the `assign()` method.

**Comment by mathDR** [comment]
@lanhnguyen2010 The documentation for saving and restoring tensorflow objects is [here](https://www.tensorflow.org/programmers_guide/saved_model)

**Comment by lanhnguyen2010** [comment]
@markvdw Thank a lot, I will try with that.
@mathDR I have used it. very appreciated your suggestion.

**Comment by markvdw** [comment]
Actually @st--, @lanhnguyen2010: it seems like `model.read_trainables()` now returns a dict, which is essentially the behaviour in the code above. This makes things pickle-able.

Additionally, @lanhnguyen2010 @mathDR, if you are interested in saving models the TensorFlow way, you may want to check out [gpflow-monitor](https://github.com/markvdw/gpflow-monitor). This project (under construction) provides helpers to monitor and store models while training. One thing it can do is store models using TensorFlow FileWriters.

**Comment by st--** [comment]
@awav pickling of kernel objects no longer seems to work, I get the following error:
```
        with open(fn_kern, 'wb') as f_kern:
>           pickle.dump(self.k, f_kern)
E           _pickle.PicklingError: Can't pickle <class 'module'>: attribute lookup module on builtins failed
```

I noticed that the old gpflow defined `__getstate__` and `__setstate__` in the Parentable class, and no longer exist, is that related? Any suggestions for how to get it to work?
