### ISSUE TITLE
Model object has no attribute 'optimize'

### ISSUE THREAD

**Issue by Joshuaalbert** [GPflow/GPflow#549]
## Problem
I've installed gpflow with `python setup.py install` and then attempted to run a simple example, given below.
I get a traceback:
`AttributeError: 'GPR' object has no attribute 'optimize'`

I also installed with `python setup.py develop` same result. Sam.e with `pip install .`

## Update
I think the answer to my problem is that there was a complete overhaul of the API recently that is not reflected in the documentation.

## MVCE

```
import gpflow as gp
import numpy as np

X1 = np.random.rand(100, 1)
X2 = np.random.rand(50, 1) * 0.5
Y1 = np.sin(6*X1) + np.random.standard_t(3, X1.shape)*0.03
Y2 = np.sin(6*X2+ 0.7) + np.random.standard_t(3, X2.shape)*0.1

k1 = gp.kernels.Matern32(1)
coreg = gp.kernels.Coregion(1, output_dim=2, rank=1, active_dims=[1])
kern = k1 * coreg
X_augmented = np.vstack((np.hstack((X1, np.zeros_like(X1))), np.hstack((X2, np.ones_like(X2)))))
Y_augmented = np.vstack((np.hstack((Y1, np.zeros_like(X1))), np.hstack((Y2, np.ones_like(X2)))))

#gp.gpr.GPR does not exist
m = gp.models.GPR(X_augmented, Y_augmented,
                     kern=kern)
print(m)
m.optimize()
```

**Comment by awav** [comment]
That's right, look at changes https://github.com/GPflow/GPflow/releases/tag/1.0.0

```
opt = gpflow.train.OPTIMIZER_WHICH_YOU_WANT_TO_USE
opt.minimize(m, ...)
```

We will publish tutorial shortly how to use `GPflow1.0`.

**Comment by Joshuaalbert** [comment]
Thanks very much!
