### ISSUE TITLE
mean function expectations?

### ISSUE THREAD

**Issue by markvdw** [GPflow/GPflow#562]
With the addition of https://github.com/GPflow/GPflow/pull/536, we should also think about the contribution of the mean function. Currently, this PR requires the mean function to be zero. In order to do this, we need mean functions to have methods for calculating their mean and variance under an input distribution.

This is easy to do for the linear mean function, and we can do `NotImplementedError` or quadrature for the rest. Or any other suggestions.

Unless anybody has strong opinions to *not* include these things, we an make this happen.

**Comment by vdutor** [comment]
I think this would be super useful. I would be happy to help implementing this.

**Comment by st--** [comment]
Done
