### ISSUE TITLE
Implementing Linear Model of Coregionalization (LMC)

### ISSUE THREAD

**Issue by silburt** [GPflow/GPflow#563]
Hello,
I've been trying to implement an LMC (e.g. equations 18-20 in https://arxiv.org/abs/1106.6251 -Kernels for Vector-Valued Functions: a Review), but I'm having trouble specifying multiple latent functions in my model. 

To be specific, I have a single dimensional input of times and a multi-dimensional output of values. I'm trying to set up a coregionalized model such that:
f_1 = a_1 u_1(t) + b_1 u_2(t)
f_2 = a_2 u_1(t) + b_2 u_2(t)
f_3 = a_3 u_1(t) + b_3 u_2(t)

where f_i are my outputs, u_q are my latent functions (Q=2 here) and a/b are variables that compose each coregionalized matrix B_q. Each latent random function needs a covariance kernel specified for it though, and in the context of GPflow it looks like I can only specify one covariance kernel:

```
in_dim, out_dim = 1, 3
coreg = gpflow.kernels.Coregion(in_dim, output_dim=out_dim, rank=out_dim, active_dims=[1])
k1 = gpflow.kernels.Exponential(1)
kern = k1 * coreg

m = gpflow.svgp.SVGP(X, Y, kern=kern, likelihood=lik, num_latent=2, Z=X[::3].copy())
```
If I try to make ```kern``` a list, e.g. ```[k1*coreg, k2*coreg]```, I get an error, and making ```k``` a sum of kernels (e.g. ```k = gpflow.kernels.Exponential(1) + gpflow.kernels.Matern32(1)```) seems to just complexify a single latent function, vs. specify kernels for each latent function. I saw this notebook - http://gpflow.readthedocs.io/en/latest/notebooks/GPLVM.html - and looks like it might be useful, but I couldn't quite follow it. I see no mention of ```ekernels``` in the documentation, and to my knowledge ```active_dims``` specify the *input* dimension (not output dimension), which in my case is 1. 

Is someone able to advise me how to proceed?

Thanks in advance,
Ari

**Comment by markvdw** [comment]
You were on the right track with a list of kernels. In order to let GPflow know about these parameters, you should store them in a `ParamList`.

**Comment by silburt** [comment]
@markvdw Thanks for your speedy reply. If I give that a try:
```
in_dim, out_dim = 1, 3
coreg = gpflow.kernels.Coregion(in_dim, output_dim=out_dim, rank=out_dim, active_dims=[1])
k1 = gpflow.kernels.Exponential(1) * coreg
k2 = gpflow.kernels.Matern32(1) * coreg
kern = ParamList([k1,k2])

m = gpflow.svgp.SVGP(X, Y, kern=kern, likelihood=lik, num_latent=2, Z=X[::3].copy())
m.optimize(maxiter=500)
```
I end up with an error:
```
/storage/home/ajs725/tf-ml/lib/python2.7/site-packages/gpflow/conditionals.pyc in conditional(Xnew, X, kern, f, full_cov, q_sqrt, whiten)
     62     num_data = tf.shape(X)[0]  # M
     63     num_func = tf.shape(f)[1]  # K
---> 64     Kmn = kern.K(X, Xnew)
     65     Kmm = kern.K(X) + tf.eye(num_data, dtype=float_type) * settings.numerics.jitter_level
     66     Lm = tf.cholesky(Kmm)

/storage/home/ajs725/tf-ml/lib/python2.7/site-packages/gpflow/param.pyc in __getattribute__(self, key)
    730         will have aname scope applied.
    731         """
--> 732         o = object.__getattribute__(self, key)
    733 
    734         # if _tf_mode is False, or there is no _tf_mode, just return the object as normal.

AttributeError: 'ParamList' object has no attribute 'K'
```

Any idea?
Thanks very much

**Comment by markvdw** [comment]
Ah yes, `SVGP` does not know how to use multiple kernels for different latent GPs. You'll have to adapt `SVGP` in your own way for that.

I'm starting to see what you want to do. You can definitely implement this in GPflow, but it may require deriving your own inference, and implementing your own model. Unless your case completely subsumed by the coregionalization kernel? By placing the output as an argument on the input, you can build a large covariance matrix for all outputs, which allows using `SVGP`, I believe. But sadly, I don't know the details, so someone else will have to chip in here.

**Comment by silburt** [comment]
There might be some fancy way to subsume all the latent kernels into one master kernel and feed that to SVGP, I'd have to think about it. If possible that would probably be the quickest answer to my problem. Thanks for the replies, hopefully someone else will chime in.

**Comment by hughsalimbeni** [comment]
Perhaps #502 is relevant

**Comment by silburt** [comment]
@hughsalimbeni thanks for the suggestion. I think I'm getting close but still not quite. My current code is:
```
X = np.vstack((t,l)).T          #(100,2) matrix: first column=X values, second column=dimension number (0,1,2)
Y = np.vstack((y,l)).T         #(100,2) matrix: first column=Y values, second column=dimension number (0,1,2)

idim, odim = 1, 3    #input, output dimensions
coreg1 = gpflow.kernels.Coregion(idim, output_dim=odim, rank=1, active_dims=[1])   #coregionalization matrix
coreg2 = gpflow.kernels.Coregion(idim, output_dim=odim, rank=1, active_dims=[1])
coreg3 = gpflow.kernels.Coregion(idim, output_dim=odim, rank=1, active_dims=[1])

kern_list = [gpflow.kernels.Exponential(1)*coreg1, 
             gpflow.kernels.Matern32(1)*coreg2,
             gpflow.kernels.Exponential(1)*coreg3]

lik = gpflow.likelihoods.SwitchedLikelihood([gpflow.likelihoods.StudentT()]*odim)

model_multi = SVGPMultiKernel(X, Y, kern_list, lik, X.copy(), num_latent=len(kern_list))
```
when I try to optimize, I get a long error that starts with (I could post the full error if you're interested):
```InvalidArgumentError: Incompatible shapes: [100,20] vs. [300,20]```

When I change the number of kernels in ```kern_list``` to X (i.e. the number of latent functions, each with it's own unique kernel) then the error changes accordingly to ```InvalidArgumentError: Incompatible shapes: [100,20] vs. [X00,20]```. So it seems like gpflow is not interpreting these kernels quite correctly, and multiplying the number of outputs by each kernel. Any idea how to proceed? 

Thanks.

**Comment by silburt** [comment]
Upon further testing, it seems like this issue has something to do with ```num_latent``` not being properly understood. If I make a single latent co-regionalized model:
```
#arrange data
X = np.vstack((t,l)).T
Y = np.vstack((y,l)).T

idim, odim = 1, 3
coreg = gpflow.kernels.Coregion(idim, output_dim=odim, rank=1, active_dims=[1])
kern = gpflow.kernels.Exponential(1) * coreg
lik = gpflow.likelihoods.SwitchedLikelihood([gpflow.likelihoods.StudentT()]*odim)

m = gpflow.svgp.SVGP(X, Y, kern=kern, likelihood=lik, num_latent=1, Z=X[::3].copy())
```
everything compiles and optimizes fine. However, if I change ```num_latent=3``` and execute the exact same code I get the error from above, i.e. ```InvalidArgumentError: Incompatible shapes: [100,20] vs. [X00,20]``` where ```X=num_latent```.

**Comment by jameshensman** [comment]
Hi @silburt ,

We should document num)_latent better. This is the number of independent, aligned GPs that the model has. It's mostly useful in the GPLVM and in multi-class classification. 

Let's ignore inference (GPR/SVGP) and likelihoods for a second, and implement the intrinsic and linear models of coregionalization through a kernel. You should be able to apply the kernel to any inference class (GPR, ...) if you're okay with a fixed likelihood.

I'm looking at eqn. 18 in https://arxiv.org/pdf/1106.6251.pdf, and letting
D=3, Q=2, R_q=[1, 2]

```python
D=3
Q=2
R = [1, 2]
input_dim=1

coregions = [gpflow.kernels.Coregion(input_dim, output_dim=D, rank=R[q], active_dims=[1])
             for q in range(Q)]
base_kernels = [gpflow.kernels.Matern32(input_dim, lengthscales=np.random.randn(1)
                for q in range(Q)]
k = coregions[0] * base_kernels[1] + coregions[1] * base_kernels[1]
```

Notes:
1) I used a random lengthscale to initialize each kernel. Otherwise, there will be a symmetry issue with the optimization, and you'll find that the two Materns always have the same lengthscale

2) Our implementation is *slightly* different to Alvarez's: the B matrix in our Coregion kernel is always positive definite, constructed as

$ B[i, j] = \sum_r W[i, r] * W[j, r] + \delta_{i,j}\kappa_i$

Alvarez does not have those kappa terms. You could always force them to be zero (or small) and untrainable. 

3) Inducing points may work for your application, or you may want to have a look a Kronecker structured algebra, if your outputs are all observed simultaneously. GPflow doesn't have any support for that at the moment, but I think it's a feature we'd welcome!

**Comment by silburt** [comment]
@jameshensman - last question: I still get the same error shown in https://github.com/GPflow/GPflow/issues/563#issuecomment-346080533 if ```num_latent``` > 1. You mention that ```num_latent``` is the number of independent, aligned GPs that the model has, which in my case I thought would be equal to ```Q```? Maybe ```num_latent``` is referring to something different than ```Q```, the number of latent functions in my model?

**Comment by orpia** [comment]
@silburt Could you solve the issue?

**Comment by silburt** [comment]
@orpia I have a notebook showing a version of what I got able to work here, feel free to take a look - https://github.com/silburt/gp_nn/blob/master/Coregion-py3.ipynb

**Comment by orpia** [comment]
Hi,

Thanks!
