### ISSUE TITLE
Combine mean functions

### ISSUE THREAD

**Issue by PabloLeon** [GPflow/GPflow#57]
What would the best way be to combine mean functions? Ideally I would like to add addition and multiplication to the MeanFunction class, but I keep running into problems with the Parameter specifications (and I feel that your setup would allow a more elegant solution that implementing multiplicative/additive mean function classes).

**Comment by jameshensman** [comment]
Hi @PabloLeon 

I agree it would be nice to have addition and multiplication of the mean function classes. Maybe you could share what you've done already as a pull request and we can have a look?

Another nice thing would be to give the mean_function classes the ability to slice their inputs, like the kernels can.

**Comment by alexggmatthews** [comment]
@PabloLeon @jameshensman . What is the status of this? Can we close  it?

**Comment by jameshensman** [comment]
I think it's all up and running, right @PabloLeon ?

**Comment by PabloLeon** [comment]
yea basic functionality should be there!

**Comment by alexggmatthews** [comment]
Thanks for your efforts.
