### ISSUE TITLE
Broken tutorial on the webpage

### ISSUE THREAD

**Issue by zzzace2000** [GPflow/GPflow#582]
Hi,

I found the second half of the tutorial of GP regression is broken.
http://gpflow.readthedocs.io/en/latest/notebooks/regression.html

**Comment by jameshensman** [comment]
yikes! good spot. I just submitted a PR to fix this, thanks.

**Comment by ngaloppo** [comment]
Somehow this still hasn't been fixed. Which PR are you referring to, @jameshensman ?

**Comment by st--** [comment]
Superseded by #703.
