### ISSUE TITLE
   File "/home/xxx/.conda/envs/tensorflow/lib/python2.7/site-packages/gpflow/core/compilable.py", line 110     class ICompilable(metaclass=AutoBuild):       ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by jluite** [GPflow/GPflow#585]
installed tensorflow 1.4.0 with Anaconda  on Ubuntu 16.4  ,  testing ok for tensorflow . 
and  type "pip install ."  or "python setup.py develop" in the virtual env named tensorflow  ,  there is the same error like "

File "gpflow/__init__.py", line 28, in <module>
    from . import transforms
  File "gpflow/transforms.py", line 22, in <module>
    from .core.base import ITransform
  File "gpflow/core/__init__.py", line 17, in <module>
    from .compilable import Build
  File "gpflow/core/compilable.py", line 110
    class ICompilable(metaclass=AutoBuild):
                               ^
SyntaxError: invalid syntax

How to handle this ?  Any help is appreciated .  Thank you very much .

**Comment by st--** [comment]
Hi, what's the output of `python --version`? GPflow now supports python3 only. If you are still using python2, I would strongly suggest switching to python3, but if that's not possible, you can still use the previous release of GPflow: https://github.com/GPflow/GPflow/tree/0.5.0

**Comment by jluite** [comment]
@st--  thank you .  Yes , I still use python2 . And I switch to python 3.5 with anaconda and tensorflow 1.4.0 , then it works .
