### ISSUE TITLE
_check_targets method  in likelihoods.py is not used anywhere

### ISSUE THREAD

**Issue by awav** [GPflow/GPflow#587]
Hello everyone,

Look at subj. Super calls to `_check_targets` are made only inside successors `_check_targets`.

<img width="681" alt="screen shot 2017-12-02 at 20 10 06" src="https://user-images.githubusercontent.com/24483645/33519393-7291c65e-d79d-11e7-9294-eb964c60565a.png">

**Comment by hughsalimbeni** [comment]
Hi sorry for the delay. Shall we just delete them all? They were there to check the user didn't use invalid inputs, but perhaps this is too nannyish for gpflow.

**Comment by alexggmatthews** [comment]
Hmm. The TensorFlow graph is fairly strictly typed anyway. Can whoever put these in suggest what they originally intended?

**Comment by hughsalimbeni** [comment]
It was there because of the multiclass int/float confusion. But now everything is consistent things are better.
