### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by nationalflag** [GPflow/GPflow#59]
Your branch of tensorflow  support GPU？

**Comment by jameshensman** [comment]
Hi @nationalflag 

Out provided whl files do not support GPU, they were compiled cpu-only. 

You could grab a recent GPU build of tensorflow from e.g. github.com/tensorflow; I see no reason why GPflow wouldnt work on a GPU.

**Comment by alexggmatthews** [comment]
Yes it should work if you build tensorflow master with the GPU options. When master turns into the next release you will just be able you use standard TensorFlow for this.

**Comment by c0g** [comment]
I have added GPU support for some previously unsupported ops (cholesky, cholgrad, diag, etc) in this fork: https://github.com/c0g/tensorflow
