### ISSUE TITLE
Deferring build in Parameterized classes?

### ISSUE THREAD

**Issue by aboustati** [GPflow/GPflow#593]
Hello,

I was wondering if there is a way to turn off automatic building in Parameterized objects. As far as I understand, whenever a Parameterized object is construct a 'build' method is called that builds that object into a Tensorflow graph? I would like to defer that process such that I am able to add attributes to the Parameterized object via methods that I define and then build it into the graph at a later stage. Is this possible?

Example:
```python
class OutputLayer(Layer):
    def initialize_forward(self, X, Z, mean_function):
        """
        Initialize Layer and Propagate values of inputs and inducing inputs
        forward
        """

        self.Z = Parameter(Z)
        self.mean_function = mean_function
```

This is an example of a Deep Gaussian Process output layer. I'd like to call the `initialize_forward` method after the object was constructed to set the values of the inducing inputs and the mean function.

Thanks!

**Comment by awav** [comment]
Hello @aboustati,

Yes, you can defer build.

1. Decorator
```python
@gpflow.defer_build()
def method_with_gpflow_objects():
    pass
```

2. Context Manager
```python
with gpflow.defer_build():
    p = gpflow.Param(..)
    m = gpflow.models.SVGP(...)
```

3. Autobuild option
```python
p = gpflow.Param(.., autobuild=False)
```

**Comment by awav** [comment]
@aboustati I'm closing this issue. Feel free to re-open it, if you have more questions.

**Comment by aboustati** [comment]
@awav thanks for your reply and sorry getting back to you this late (holiday period!).

I managed to use the `defer_build` decorator to change values of attributes that are already set. However, I am still struggling with setting new attributes. More specifically, I get the error "`Cannot be added to assembled node.`", when I call the `initialize_forward` method in the example above. The error occurs when I try to set the value of the attribute `Z` in the line:
```python
self.Z = Parameter(Z)
```
Is this due to the build process still or is it a different issue specific to the  `Parameterized` class?

Thanks!

**Comment by aboustati** [comment]
@awav I realised that I am unable to re-open this issue myself as it has been closed by a repo collaborator. Is it possible to re-open it from your end?

Thanks!
