### ISSUE TITLE
[Question] kernels.Stationary.square_dist

### ISSUE THREAD

**Issue by smcveigh-phunware** [GPflow/GPflow#597]
```
    @params_as_tensors
    def square_dist(self, X, X2):
        X = X / self.lengthscales
        Xs = tf.reduce_sum(tf.square(X), axis=1)

        if X2 is None:
            dist = -2 * tf.matmul(X, X, transpose_b=True)
            dist += tf.reshape(Xs, (-1, 1))  + tf.reshape(Xs, (1, -1))
            return dist

        X2 = X2 / self.lengthscales
        X2s = tf.reduce_sum(tf.square(X2), axis=1)
        dist = -2 * tf.matmul(X, X2, transpose_b=True)
        dist += tf.reshape(Xs, (-1, 1)) + tf.reshape(X2s, (1, -1))
        return dist
```

So is square_dist with X2=None is equivalent* to [scipy.spatial.distance.pdist](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.pdist.html) and X2!=None  is equivalent* to [scipy.spatial.distance.cdist](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html)? 
*(squared of course)

**Comment by hughsalimbeni** [comment]
yes

**Comment by vdutor** [comment]
Don't forget that `square_dist` takes into account a lengthscale in each direction. I believe `scipy.spatial.distance` doesn't do this.
