### ISSUE TITLE
global_variables_initializer errors

### ISSUE THREAD

**Issue by befelix** [GPflow/GPflow#598]
Hey,

```
import tensorflow as tf
import gpflow

kernel = gpflow.kernels.Matern32(1)

# ... some other code that create variables and depends on kernel ...

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
```

the code above throws the following error
```
InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor '0/Matern32/lengthscales/initial_unconstrained_value' with dtype double
	 [[Node: 0/Matern32/lengthscales/initial_unconstrained_value = Placeholder[dtype=DT_DOUBLE, shape=[], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

I know that I can fix this error simply by running passing the `kernel.initializable_feeds` feed_dict, but is there a way to avoid creating placeholders for the initial values in the first place? It's a bit annoying to have to go back and collect all the feeds from different GPs in a larger system.

Other than that I like how much easier it is to deal with gpflow 1.0 as a subpart of a graph👍 

Thanks,
Felix

**Comment by awav** [comment]
Hi @befelix! Thank you for feedback! Unfortunately, placeholders are part of parameters and provide other important features in GPflow framework. You can derive from Parametrized class and create a model-like collection of kernels, parameters, other models under one roof with nice access to full list of initializable_feeds. Something like:
```python
class MyGPCollection(gpflow.Parameterized):
    def __init__(self):
        self.kernel = gpflow.kernels.Matern32(1)
        ...

gp_collection = MyGPCollection()
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer(), feed_dict=gp_collection.initializable_feeds)
```

But, even better way is putting all tensors under parameterized object and override `initializables` property, therefore you could just call `collection.initialize()` within new session or at default gpflow's tensorflow session.
