### ISSUE TITLE
Bayesian GPLVM with Poisson likelihood

### ISSUE THREAD

**Issue by alexisboukouvalas** [GPflow/GPflow#599]
I am looking into implementing Bayesian GPLVM with a Poisson likelihood in GPflow. 

My expectation is to do a variational approximation using existing GPflow code. The SVGP models allows GP regression with non-gaussian likelihood. This uses variational_expectations. This computes:
\int (\log p(y|f)) q(f) df

By default this is computed by quadrature. However for Poisson with exponential link this is analytic
            return Y * Fmu - tf.exp(Fmu + Fvar / 2) * self.binsize \
                   - tf.lgamma(Y + 1) + Y * tf.log(self.binsize)

How could the BGPLVM bound be changed to use the variational expectations? 

thanks for your help

**Comment by hughsalimbeni** [comment]
The moments of p(F|X)q(X) are given with the new `uncertain_conditional` code, but the distribution is non-Gaussian so the variational expectations (including quadrature) wouldn't be valid except for the Gaussian likelihood. You could do quadrature over q(X), but this can be expensive as the cholesky needs calculating for each quadrature point and the number of points blows up exponentially with dim X. There's a paper that does something similar for categorial Y  http://proceedings.mlr.press/v37/gala15.html with MC sampling, which might be of interest. Implementing this approach would be straightforward, and could use the analytic expression above.
