### ISSUE TITLE
GPflow and real-time learning?

### ISSUE THREAD

**Issue by ruzakb** [GPflow/GPflow#603]
Hi,

I'm new to the GP world, sorry if I get some of the terminology wrong. Is GPflow capable of any of the following:
- online (real-time) updating with new data, such as Kernel Recursive Least Squares (KRLS)? or other? 
- GP prediction with uncertain inputs, e.g., for use in multi-step ahead forecasting? 
- Applying Nonlinear Autoregressive with Exogenous inputs (NARX)? 

Thanks!

**Comment by Joshuaalbert** [comment]
Gaussian processes, require observables taken at coordinates. The observables are not certain if you supply non-zero uncertainty. GP optimization then tries to maximize Bayes evidence over a parametrized kernel which lives in the coordinate manifold. This kernel provides regularization which let's you predict into unsampled coordinate regions. If you also want to optimize over the set of sampled observables this is also possible with SVGP. Some reading materials:
http://mlss2011.comp.nus.edu.sg/uploads/Site/lect1gp.pdf
http://www.gaussianprocess.org/gpml/chapters/RW.pdf

**Comment by markvdw** [comment]
In addition to @Joshuaalbert's points:
- Currently we do not support online learning. Bui & Turner have an [excellent recent paper](https://arxiv.org/abs/1705.07131) online learning.
- Yes, the recently added `uncertain_conditional()` code can perform be used to perform moment-matching predictions for uncertain inputs.
- NARX is probably possible, but you will have to implement the model yourself. We are happy to link to any new open source implementations of models.
