### ISSUE TITLE
Pseudo "Non-Stationary" GPModel variants

### ISSUE THREAD

**Issue by smcveigh-phunware** [GPflow/GPflow#606]
Hi,

Thanks for all the great work on this project.

Im trying to build some additionally functionality around the regression models. For example, my process is localized around an origin that I'd like to train (i.e., locally stationary). The origin is used to to transform data from a reference coordinate system to the domain for `X`.  Ideally, the `X` training points would be updated when the origin is updated.  Could anyone provide some insight as to what I could do to ensure updating `X` and that origin is trained?
 
Thanks

**Update**

I was looking at `Parameterized` class, specifically `assign(values, ...)`:

```python
class Parameterized(Node):

    # [...]

    def assign(self, values, session=None, force=True):
        if not isinstance(values, (dict, pd.Series)):
            raise ValueError('Input values must be either dictionary or panda '
                             'Series data structure.')
        if isinstance(values, pd.Series):
            values = values.to_dict()
        params = {param.full_name: param for param in self.parameters}
        val_keys = set(values.keys())
        if not val_keys.issubset(params.keys()):
            keys_not_found = val_keys.difference(params.keys())
            raise ValueError('Input values are not coherent with parameters. '
                             'These keys are not found: {}.'.format(keys_not_found))
        prev_values = {}
        for key in val_keys:
            try:
                param = params[key]
                prev_value = param.read_value().copy()
                param.assign(values[key], session=session, force=force)
                prev_values[key] = prev_value
            except (GPflowError, ValueError):
                for rkey, rvalue in prev_values.items():
                    params[rkey].assign(rvalue, session=session, force=True)
                raise
```
 
I'm assuming values are the updated trainable parameters returned from the optimizer?
So would the following method override work?

```python
    def assign(self, values,  session=None, force=True)
        super().assign(values,  session, force)
        if self.origin.full_name in values:
            self.X = self.update_X_from_origin() . # do update
```

I'd be interested to know from people more experienced than myself: would updating the X values cause too much instability during the optimization? I'm assuming that my initial origin guess is relatively close to the ground truth.

**Comment by hughsalimbeni** [comment]
It's not clear to me exactly what you're asking here, but overriding `assign` seems unlikely to be the simplest way . If you want to shift the origin of the data then you could add a transform to the dataholder, but note that stationary kernels are translation invariant, and the non-stationary kernels can have translation parameters that can be optimized.
