### ISSUE TITLE
Some notebooks in doc/ not working

### ISSUE THREAD

**Issue by sanket-kamthe** [GPflow/GPflow#608]
Notebooks in doc are not working broken in multiple branches.

Unreadable Notebook: 
NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...',)

Fails to render on Github as well as on independent machine.

PS: 
update with tag: 

`Update notebooks from master branch.
 master (#592)`

messes it up

**Comment by a5a** [comment]
It's a messy merge, where it seems that merge conflicts were not resolved before pushing due to plenty of "<<<< HEAD"  and ">>>>>>> master" lines.

**Comment by st--** [comment]
Solved by #649
