### ISSUE TITLE
autoflow fails after reset_default_graph

### ISSUE THREAD

**Issue by jameshensman** [GPflow/GPflow#61]
Sometimes it's necessary to reseat tensorflow's graph for memory reasons. This can be done with `tf.reset_default_graph()`. 

Problem is, this breaks all out AutoFlow functions! Here's a MWE:
```python
tf.reset_default_graph()
k = GPflow.kernels.Matern32(1)
X, Y = np.random.randn(2, 10, 1)
m = GPflow.gpr.GPR(X, Y, kern=k)
m.predict_f(m.X)
```

This is because the Autoflow constructor takes placeholders as arguments. After reset_default_graph, those placeholders are not on the same graph as everything else.  I'm going to propose a fix where we just give AutoFlow enough information to *make* the placeholders, not the placeholders themselves.

**Comment by markvdw** [comment]
Could this be related to the following bug? If I recompile a model, suddenly the predictions go out the window!

```
import numpy as np
import numpy.random as rnd
import matplotlib.pyplot as plt
import GPflow

X = rnd.rand(100, 1)
Y = np.sin(X*4) + rnd.randn(100, 1)*0.1

# mod = GPflow.sgpr.GPRFITC(X, Y, GPflow.kernels.RBF(1), rnd.rand(10, 1))
mod = GPflow.sgpr.SGPR(X, Y, GPflow.kernels.RBF(1), rnd.rand(10, 1))
mod.optimize(max_iters=100)

pX = np.linspace(0, 1, 100)[:, None]
pY1, pYv1 = mod.predict_y(pX)

mod._compile()
pY2, pYv2 = mod.predict_y(pX)

plt.plot(X, Y, 'x')
plt.plot(pX, pY1)
plt.plot(pX, pY2)
```

**Comment by jameshensman** [comment]
Oh dear, what horrible behaviour. 

You'll be pleased to know that it seems to be fixed by #62 (try git checkout autoflow_graph_bug_bugfix)

I've not merged #62 yet because the tests timeout on the codeship server. I could really do with some help making the tests run faster.

**Comment by markvdw** [comment]
Do you have any pointers as to where speedups could be made?

**Comment by jameshensman** [comment]
I have a hypothesis: using an InteractiveSession() might help.

If that worked, I'd be really happy. If not, we might have to either look
at merging some tests (Alex has done this a bit in the past) or just
running the tests on a bigger machine, or in parallel. eek.

**Comment by alexggmatthews** [comment]
@markvdw I'm talking to @jameshensman about the slow tests on #67

**Comment by alexggmatthews** [comment]
@markvd @jameshensman I think that the problem might be that _compile() calls tf.initialize_all_variables() which will set all the variables back to their pre-optimized values.

**Comment by alexggmatthews** [comment]
I don't think that an InteractiveSession will help. Effectively that just sets up the one session object which is used by default and automatically under the hood.
