### ISSUE TITLE
'SVGP' object has no attribute 'feature' and gpflow.core.base.GPflowError: Model is not built.

### ISSUE THREAD

**Issue by hoangcuong2011** [GPflow/GPflow#613]
Hello,

I follow the tutorial of classification using GPflow https://github.com/GPflow/GPflow/blob/master/doc/source/notebooks/multiclass.ipynb without success.

To make it clear let me show my simpler code:

    num_inducing = 100
    num_classes = 2
    from scipy.cluster.vq import kmeans
    Z = kmeans(x_train, num_inducing)[0]
    mylikelihood = gpf.likelihoods.MultiClass(num_classes)

    m = gpf.models.SVGP(
        x_train, y_train, kern=gpf.kernels.RBF(input_dim=5, ARD=True),
        likelihood=mylikelihood, Z=Z)

    m.feature.set_trainable(True)

    opt = gpf.train.ScipyOptimizer()
    opt.minimize(m)

I got stuck at the line of code: set_trainable (AttributeError: 'SVGP' object has no attribute 'feature). When I commented this line I got stuck at another line opt.minimize(m) (gpflow.core.base.GPflowError: Model is not built.)

Any suggestion on how to fix the problem?

Thanks!

Best,

H.C.

**Comment by hoangcuong2011** [comment]
BTW I used GPflow git commit hash: f618fe4 (I used this specific gpflow version to run an example of end-to-end training with GPFlow plus a neural net coded in tensorflow as this link: https://github.com/GPflow/GPflow/issues/505#issuecomment-340985191)

**Comment by hughsalimbeni** [comment]
This is probably resolved now. There was a period of inconsistency with `.feature.Z` and `.Z`, but now things should be consistent. Please reopen if not.
