### ISSUE TITLE
Cholesky decomposition is slower on GPU

### ISSUE THREAD

**Issue by anh-tong** [GPflow/GPflow#616]
Hi,

I build a model using GPflow kernels.  The problem is that Cholesky decompositions which are done in GPU take a lot of time (~600ms) vs. on CPU (only 2ms). You can see the timeline trace: (I follow this profiling [https://stackoverflow.com/questions/34629613/how-to-profile-tensorflow-networks](https://stackoverflow.com/questions/34629613/how-to-profile-tensorflow-networks) ).

I go to Tensorflow document on `tf.cholesky`. It has note that

> The gradient computation on GPU is faster for large matrices but not for large batch dimensions when the submatrices are small. In this case it might be faster to use the CPU.

How can I have GPU computation advantages? Should I specify that `tf.cholesky` should be done in CPU.

Thanks a lot.

**CPU**
![cpu](https://user-images.githubusercontent.com/20637355/34667429-431a9d66-f4ac-11e7-9fad-efbc800f40cd.png)

**GPU**
![gpu](https://user-images.githubusercontent.com/20637355/34667434-4ce7a406-f4ac-11e7-8994-2e66ad12fe78.png)

>

**Comment by markvdw** [comment]
That is interesting. Can you give more information about the size of matrices that you're dealing with?

**Comment by anh-tong** [comment]
I tried to compute Cholesky decompositions for about 12 matrices size 130x130. 
Here is my piece of code
`computed_Ks = [kernel.K(t) for kernel in self.kernels]`
`Ls = [tf.cholesky(computed_K + tf.eye(self.D, dtype=tf.float64) * (likelihood / K)) for computed_K in computed_Ks]
`
As Tensorflow documenation's note, GPU will help if we deal with large matrices. But is there any benchmark on this to have a reference?

**Comment by anh-tong** [comment]
I may figure out the problem the problem. My Tensorflow uses cuSolver to perform Cholesky decompositions. Indeed, the larger input matrices are, cuSolver is better. I found this reference.
![explaination](https://user-images.githubusercontent.com/20637355/34674412-211a4c94-f4c9-11e7-8eeb-19fd13a1714d.png)
Reference:
http://www.lume.ufrgs.br/bitstream/handle/10183/151001/001009773.pdf
Thank you very much. I may close this issue.

**Comment by jacksonloper** [comment]
Wow that is terrible performance!  For modestly sized matrices cusolver is fully 100 times slower.  I guess we're pretty much tied to cusolver tho.  Well hopefully they fix that... soon...?
