### ISSUE TITLE
Weighting squared residuals in the likelihood function

### ISSUE THREAD

**Issue by awayt039** [GPflow/GPflow#619]
Hey all, I'm trying to analyze some survey data with gpflow and I would like to use the survey weights in my model to weight the square residual in the log likelihood formula. I figured all that I would need to do is implement a new likelihood function and add an argument for the weights and then fix the weights prior to optimization. I tried  the code below on synthetic data but it does not appear to be responding to the weights. Am I missing something?

```
class Gaussian(gpflow.likelihoods.Likelihood):
    def __init__(self, var=1.0, weight):
        super().__init__()
        self.variance = Parameter(
            var, transform=transforms.positive, dtype=settings.float_type)
        self.weight = Parameter(
            weight, transform=transforms.positive, dtype=settings.float_type)

    @params_as_tensors
    def logp(self, F, Y):
        return weight_gaussian(F, Y, self.variance, self.weight)

    @params_as_tensors
    def conditional_mean(self, F):  # pylint: disable=R0201
        return tf.identity(F)

    @params_as_tensors
    def conditional_variance(self, F):
        return tf.fill(tf.shape(F), tf.squeeze(self.variance))

    @params_as_tensors
    def predict_mean_and_var(self, Fmu, Fvar):
        return tf.identity(Fmu), Fvar + self.variance

    @params_as_tensors
    def predict_density(self, Fmu, Fvar, Y):
        return densities.gaussian(Fmu, Y, Fvar + self.variance)

    @params_as_tensors
    def variational_expectations(self, Fmu, Fvar, Y):
        return -0.5 * np.log(2 * np.pi) - 0.5 * tf.log(self.variance) \
               - 0.5 * (tf.square(Y - Fmu) + Fvar) / self.variance
def weight_gaussian(x, mu, var, weight):
    return -0.5 * (np.log(2 * np.pi) + tf.log(var) + tf.square(mu-x)*weight/var)
```

**Comment by jameshensman** [comment]
Hi @awayt039 , 

There are a couple of issues I can spot:
 - variational_expectations does not include the weight (this is wha tthe VGS/SVGP models use)
 - weight_gaussian is not a valid density (you need to include the weight term in the tf.log)
 - it's a bit clunky to include the weights as a parameter -- there's no clean way to tell the object what the weight is for a new Y point at test time. 

The last one is not critical, but would be nice.

**Comment by awayt039** [comment]
Hey James,
Thanks for the reply. In response to your comments

1) Would this work for variational inference
```@params_as_tensors
    def variational_expectations(self, Fmu, Fvar, Y):
        return -0.5 * np.log(2 * np.pi) - 0.5 * tf.log(self.variance) \
               - 0.5 * (tf.square(Y - Fmu)*self.weight + Fvar) / self.variance
```
2) I defined `weight_gaussian` at the end of the script. What do you mean by I need to include the weight term in the the tf.log?

3) Can you think of a cleaner implementation?

Thanks!

**Comment by Joshuaalbert** [comment]
From what I understand you want to optimize an objective function wherein the likelihood of each data point `y_i` is weighted by some statistical weight. The way you do this is not proper because the job of the likelihood is to return the probability of any data space vector given any model space (latent) vector. The way you have specified a `weight` makes it specific to one particular data space vector (the observations) and the likelihood function won't make sense for any other data space vector. The correct way is actually much simpler. You just need to modify the `_build_likelihood` function of the model you are using. For example to use the `GPR` model with a statistical weighting on the observations you would do something like:

    # add self.weights as a DataHolder in __init__
    # self.weights is same shape as self.Y i.e. (N,num_latent)
    ...
    @params_as_tensors
    def _build_likelihood(self):
        """
        Construct a tensorflow function to compute the likelihood.
            \log p(Y | theta).
        """
        K = self.kern.K(self.X) + tf.eye(tf.shape(self.X)[0], dtype=settings.float_type) * self.likelihood.variance
        L = tf.cholesky(K)
        m = self.mean_function(self.X)
        logpdf = multivariate_normal(self.Y, m, L)  # (R,) log-likelihoods for each independent dimension of Y

        return tf.reduce_sum(logpdf * self.weights)

Note I've only changed the last line. All else is the same. This actually requires the assumption that the data are independent. If for instance you wanted a more rigorous weighting, say you had an observation variance for each data point, and your `Y` was scalar so that `Y.shape = (N,1)`, then you could do instead,

    # add self.obs_var as a DataHolder in __init__
    # self.obs_var is same shape as self.Y i.e. (N,1)
    ...
    @params_as_tensors
    def _build_likelihood(self):
        """
        Construct a tensorflow function to compute the likelihood.
            \log p(Y | theta).
        """
        K = self.kern.K(self.X) + tf.diag(self.likelihood.variance*self.obs_var[:,0])
        L = tf.cholesky(K)
        m = self.mean_function(self.X)
        logpdf = multivariate_normal(self.Y, m, L)  # (R,) log-likelihoods for each independent dimension of Y

        return tf.reduce_sum(logpdf)

Now the observational uncertainty is in the proper place (but this can only be done when the observations are scalar). In this case likelihood.variance behaves as a scaling factor to your weights which can be turned off by setting in non-trainable.

**Comment by awayt039** [comment]
@Joshuaalbert Thanks for your comment. I was just curious what is the thinking behind multiplying the likelihood variance and the observed variance. Would addition be more appropriate? e.g.
` K = self.kern.K(self.X) + tf.diag(self.likelihood.variance+self.obs_var[:,0])`

**Comment by Joshuaalbert** [comment]
Addition is also a valid operation there however the meaning behind it is slightly different from weighting your data points. The addition would correspond to letting the self.likelihood.variance be a modelization error (uncertainty in the model itself). It is indistinguishable from observational error anyways (if you read my reference below you'll see). If you know your observational uncertainties then you can forget about a learnable self.likelihood.variance altogether.

Example 1.36 in (http://www.ipgp.fr/~tarantola/Files/Professional/Books/InverseProblemTheory.pdf)

**Comment by awayt039** [comment]
So for incorporating observational uncertainty you would recommend something like your `Gaussian1` class in this gist?

https://gist.github.com/Joshuaalbert/431e084cb2cd47da723a4436bc7fceb9

**Comment by Joshuaalbert** [comment]
No, unfortunately I wrote that when I was still learning how gpflow is structured. It works for the GPR model but it's not generalizable to others. Now I would say you should make a subclass the model you are interested in using and modify the `def _build_likelihood(self):` method as I did above to weight the `logpdf` before the `reduce_sum`. That can be in the form of `K = self.kern.K(self.X) + tf.diag(self.likelihood.variance+self.obs_var[:,0])` or as I did above.

**Comment by jacob-roth** [comment]
@Joshuaalbert : thanks for your notes on adding observational variance! I'm having trouble modifying the `_init__` method and was wondering if you could be a bit more explicit in how you input / access `self.obs_var` and work with `DataHolder`s. When I optimize, I'm getting an invalid input error for the Cholesky

**Comment by awayt039** [comment]
@Joshuaalbert I see that you have this notebook https://nbviewer.jupyter.org/github/GPflow/GPflow/blob/develop/doc/source/notebooks/advanced/varying_noise.ipynb that provide a hetero likelihood. Thank you so much for your contribution! In my case, some of my output data may have noise and some of it may not have noise (weird I know) so as described above I use 

```class HetGaussian(gpflow.likelihoods.Likelihood):
    def logp(self, F, Y):
        # logp is used by the quadrature fallback of variational_expectations and predict_density.
        # As variational_expectations is implemented analytically below, this is not actually needed,
        # but included for pedagogical purposes.
        # Note that currently relying on the quadrature would fail due to https://github.com/GPflow/GPflow/issues/966
        Y, NoiseVar = Y[:, 0:1], Y[:, 1:2]
        return gpflow.logdensities.gaussian(Y, F, self.variance+NoiseVar)

    def conditional_mean(self, F):
        raise NotImplementedError

    def conditional_variance(self, F):
        raise NotImplementedError

    def variational_expectations(self, Fmu, Fvar, Y):
        Y, NoiseVar = Y[:, 0:1], Y[:, 1:2]
        return -0.5 * np.log(2 * np.pi) - 0.5 * tf.log((self.variance+NoiseVar)) \
               - 0.5 * (tf.square(Y - Fmu) + Fvar) / (self.variance+NoiseVar)
```

My question though is could this be extended for the student T likelihood?  Would adding the observation noise to the scale parameter work? I can't find any implementation of a hetero student T likelihood. I am not familiar with the student T likelihood  so I am unsure if there is any justification for this nor am I smart enough to figure out the math.

```
def student_t(x, mean, scale +NoiseVar, df):
    df = tf.cast(df, settings.float_type)
    const = tf.lgamma((df + 1.) * 0.5) - tf.lgamma(df * 0.5) \
        - 0.5 * (tf.log(tf.square(scale)) + tf.log(df) + np.log(np.pi))
    const = tf.cast(const, settings.float_type)
    return const - 0.5 * (df + 1.) * \
        tf.log(1. + (1. / df) * (tf.square((x - mean) / scale)))
```
