### ISSUE TITLE
Docker image out of date

### ISSUE THREAD

**Issue by jwvdm** [GPflow/GPflow#620]
Thanks for your great work on this library! I'm using GPflow for a programming assignment in a class that I'm teaching. I was hoping to point students towards your docker image. Unfortunately, it appears the docker image is still running 0.3.5. Is it indeed out of date, or might I have done something silly?

**Comment by alexggmatthews** [comment]
Hi Jan-Willem. Yes it is certainly out of date. My apologies- I will add a ticket to regenerate it.
Alex

**Comment by d-henderson** [comment]
Hello, looking to run the latest version of GPflow with docker. Is this PR ready to be finalised.

**Comment by st--** [comment]
@awav  do we not have a new Docker image now?

**Comment by st--** [comment]
It looks like the Docker image linked to from the documentation (https://gpflow.readthedocs.io/en/develop/intro.html, even for 2.0 version) is massively out of date (still 0.3.5). Should we remove the link, or update the docker image? (Who even has permission to update the docker image, and who knows what would be needed for that?)
