### ISSUE TITLE
Whether GPflow is computing using GPU

### ISSUE THREAD

**Issue by zheng992328** [GPflow/GPflow#625]
I am trying using GPflow to construct regression model and the snippet of the code is below. I also compare it with GPy.  Firstly, the computation of this part is too much slower than GPy. I don't know why is that.  Secondly, when I using GPflow to construct GPR, I check whether GPU is running for computing with entering "nvidia-smi" in cmd, however, it shows "No running process found". So, I wonder whether the GPflow is computing on GPU.
In addition, my tensorflow-gpu(0.12) is OK, and I have tested it with MNIST code and data. I can run on my Tesla K80 normally. Can someone help me about this problem? Thanks a lot! 

**GPR using GPflow**
```
for i in range(output_dim):
    k=gpflow.kernels.Matern52(input_dim,ARD=False)
    scaler=preprocessing.StandardScaler().fit(Y_train[:,i].reshape(-1,1))
    y_train_scaled=scaler.transform(Y_train[:,i].reshape(-1,1))
    model1 = gpflow.models.GPR(X_train, y_train_scaled, kern=k)
    model1.likelihood.variance=0.01
    
    gpflow.train.ScipyOptimizer().minimize(model1)
    
    mu1,var1=model1.predict_y(X_test)
    y_predict[:,i]=scaler.inverse_transform(mu1.ravel())
```

**GPR using GPy**
```
for i in range(output_dim):
    k1=GPy.kern.Matern52(input_dim,ARD=False)
    scaler=preprocessing.StandardScaler().fit(Y_train[:,i].reshape(-1,1))
    y_train_scaled=scaler.transform(Y_train[:,i].reshape(-1,1))
    model1 = GPy.models.GPRegression(X=X_train, Y=y_train_scaled, kernel=k1)
    
    model1[".*Gaussian_noise"] = model1.Y.var()*0.1
    model1[".*Gaussian_noise"].fix()
    
    model1.optimize(max_iters = 1000)
    
    mu1,v1=model1.predict(X_test)
    y_predict[:,i]=scaler.inverse_transform(mu1.ravel())
```

**Comment by hughsalimbeni** [comment]
a few points: 

GPflow builds a computational graph first and then executes afterwards. For very small models, (e.g. the above with <200 points) the execution time can small time compared to the graph building. GPy on the other hand simply executes the python code directly, so does not have to build a graph. For small, models if you compare the total time then you might find that GPy is indeed faster. In my experience, when I'm worrying about performance it is in settings where the execution time is large (O(hours)) and so I don't care too much about the graph building overhead (O(seconds)). Also you might be finding that just the importing of tensorflow-gpu can add a few seconds to the run time.

GPflow can benefit from the GPU acceleration provided by tensorflow, but this does not necessarily speed all computation. As a general guide, if the main bottleneck in the model is matrix multiplication (or matrix solves), then the GPU is likely to improve things considerably. If the bottleneck is a cholesky or has lots of small ops executed in series, then you might find the CPU is faster. 

Regarding whether tensorflow is actually using the GPU, this isn't likely to be an issue related to GPflow. You can see whether the GPU is being used by tensorflow by opening up a notebook and importing tensorflow. If things are working you should see that a process is launched on your GPU that consumes all available memory. NB if you run something in a terminal then process might finish too quickly to be picked up by nvidia-smi. If you want to find out exactly what's going on, then I strongly recommend using the tracing feature of GPflow. You can activate this by setting the options in the gpflowrc file. This will save a json file which you can open by typing `chrome://tracing/` in a chrome browser and loading the file

**Comment by zheng992328** [comment]
@hughsalimbeni Thank you very much for your so detailed reply.
