### ISSUE TITLE
Referring to issue #192. Import error.

### ISSUE THREAD

**Issue by svaibhavsingh** [GPflow/GPflow#628]
I am using GPflow 0.3.5 in which all the changes mentioned in #192 is already being done. tfops dir. is being created but it contains 2 files only. I am using tensorflow 0.12.1, gcc - 5.4.0.
Complete traceback is mentioned below:
from . import likelihoods, kernels, ekernels, param, model, gpmc, sgpmc, priors, gpr, svgp, vgp, sgpr, gplvm, tf_wraps, tf_hacks
     19 from ._version import __version__
     20 from ._settings import settings

/home/vaibhav/p2Doubly/local/lib/python2.7/site-packages/GPflow/likelihoods.py in <module>()
     15 
     16 from __future__ import absolute_import
---> 17 from . import densities, transforms
     18 import tensorflow as tf
     19 import numpy as np

/home/vaibhav/p2Doubly/local/lib/python2.7/site-packages/GPflow/transforms.py in <module>()
     16 import numpy as np
     17 import tensorflow as tf
---> 18 from . import tf_wraps as tfw
     19 from ._settings import settings
     20 

/home/vaibhav/p2Doubly/local/lib/python2.7/site-packages/GPflow/tf_wraps.py in <module>()
     30 
     31 
---> 32 _custom_op_module = tf.load_op_library(os.path.join(os.path.dirname(__file__), 'tfops', 'matpackops.so'))
     33 vec_to_tri = _custom_op_module.vec_to_tri
     34 tri_to_vec = _custom_op_module.tri_to_vec

/home/vaibhav/p2Doubly/local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.pyc in load_op_library(library_filename)
     62       # pylint: disable=protected-access
     63       raise errors_impl._make_specific_exception(
---> 64           None, None, error_msg, error_code)
     65       # pylint: enable=protected-access
     66   finally:

NotFoundError: /home/vaibhav/p2Doubly/local/lib/python2.7/site-packages/GPflow/tfops/matpackops.so: cannot open shared object file: No such file or directory

**Comment by st--** [comment]
Check out the tag '0.3.9' I just made (`git pull; git checkout 0.3.9`). This is the last commit before the rename from `GPflow` to `gpflow`. You will also need tensorflow 1.3. This does not require the matpackops.so anymore, and should work for you without any code changes.

In the long run, you would probably benefit from porting your code to GPflow-1.0 (which requires tensorflow 1.4)

**Comment by svaibhavsingh** [comment]
Thanks for replying on such a short notice. That helped.
