### ISSUE TITLE
Gradient check in GPflow

### ISSUE THREAD

**Issue by anh-tong** [GPflow/GPflow#629]
Hi,
I wonder if there is a way to test gradient error in GPflow as in TF with `tf.test.compute_gradient_error`.
I think it is necessary to justify the correctness of auto-diff in GPflow. 

Thanks in advance.

**Comment by hughsalimbeni** [comment]
Do you have a particular gradient that you are suspicious of? It's unlike to be a problem with gpflow, though, as none of the gradients are overwritten. 

You can still use the `tf.test.compute_gradient_error` function:

```python
model = GPR(np.zeros((1, 1)), np.zeros((1, 1)), RBF(1))
with tf.Session() as sess:
    model.initialize(session=sess)
    e = tf.test.compute_gradient_error(model.kern.variance.constrained_tensor, [],
                             model.likelihood_tensor, [],
                             delta=0.00001)
print(e)
9.57012247227e-13
```

**Comment by anh-tong** [comment]
Thank you very much. Your example code is what I am looking for.
