### ISSUE TITLE
A question about Coregionalization case using Gpflow

### ISSUE THREAD

**Issue by zheng992328** [GPflow/GPflow#639]
I am trying to run the Coregionalization case 
[http://gpflow.readthedocs.io/en/latest/notebooks/coreg_demo.html](url)，
but when i run to the code "gpflow.train.ScipyOptimizer().minimize(m)", it raises en error below
![image](https://user-images.githubusercontent.com/16679647/35724969-84aa1b16-083a-11e8-96ca-7562f2840e76.png)

Could someone help me how to solve it? Thanks a lot!

**Comment by hughsalimbeni** [comment]
Are you running the notebook as is, or changing it? If you're changing it, please provide some more details to help fix the problem.
