### ISSUE TITLE
Sample from model

### ISSUE THREAD

**Issue by PabloLeon** [GPflow/GPflow#64]
What would be the preferred way to sample from a GP with mean function/compositional kernel? I tired the various sample/predict and also the evalK() from #63 but I can't make it work.

**Comment by jameshensman** [comment]
We're going to need a little more information: what doesn't work, exactly? Have you tried:

```python
X, Y = np.random.randn(2, 100, 1)
Xtest = np.random.randn(1000, 1)
m = GPflow.gpr.GPR(X, Y, GPflow.kernels.Matern32(1))
my_sample = m.predict_f_sample(Xtest, 1)
```

**Comment by mathDR** [comment]
@jameshensman running your example I get an error:

AttributeError: 'GPR' object has no attribute 'predict_f_sample'

**Comment by mathDR** [comment]
Also, running the example from #63, I receive:

AttributeError: 'RBF' object has no attribute 'evalK'

**Comment by jameshensman** [comment]
> AttributeError: 'GPR' object has no attribute 'predict_f_sample'

git pull. Works for me on master.

> AttributeError: 'RBF' object has no attribute 'evalK'
#63 has not been merged yet, so you'd need to grab the corresponding branch.

**Comment by PabloLeon** [comment]
That works for me! I guess I had some non updated imports, thanks!

**Comment by mathDR** [comment]
Looking at gpr.py on master, doing a search for predict_f returns no results.

**Comment by mathDR** [comment]
Okay, the relevant code is in models.py and the function call is predict_f_samples, with an s.  It all works now...(with the corresponding addition of the s)

**Comment by jameshensman** [comment]
Edited, thanks @mathDR !

**Comment by PabloLeon** [comment]
I might be missing something, but the example you provided @jameshensman  fails for Linear and Cosine kernels, but works for White/RBF/Exponential/Matern.
```
X, Y = np.random.randn(2, 100, 1)
Xtest = np.random.randn(1000, 1)
m = GPflow.gpr.GPR(X, Y, GPflow.kernels.Cosine(1))
my_sample = m.predict_f_samples(Xtest, 1)
```
The error I get is:

>  InvalidArgumentError: LLT decomposition was not successful. The input might not be valid.  [[Node: Cholesky_56 = Cholesky[T=DT_DOUBLE, _device="/job:localhost/replica:0/task:0/cpu:0"](Squeeze_139)]]

**Comment by jameshensman** [comment]
Ah, you may well be right, those covariances can be singular. 

You could try adding a small amount of jitter to the diagonal of the covariance matrix before taking the Cholesky decomposition: this should help. Send a PR if it works :)
