### ISSUE TITLE
Issue with linear mean function.

### ISSUE THREAD

**Issue by svaibhavsingh** [GPflow/GPflow#640]
When gpflow settings is changed with dtype=float32. 
A,b of mean function should be initialised with mentioning dtype too. (line 59,60) of mean_functions.py .
dtype=settings.float_type

**Comment by markvdw** [comment]
Indeed, we've seen this as well. Originally, this was a design decision. The current fix is to pass numpy arrays of the desired type using `array.as_type('float32')`.

But I do think that this is cumbersome. We will make a PR to change this behaviour.

**Comment by markvdw** [comment]
This issue is fixed with https://github.com/GPflow/GPflow/pull/647
