### ISSUE TITLE
Calculating gradients with respect to input variables using GPFlow

### ISSUE THREAD

**Issue by krm58** [GPflow/GPflow#643]
Hi,
I am attempting to calculate the gradient of the loss function with respect to input variables, using a GPFlow SVGP model. In tensorflow, what I want to do is similar to the following:
```
train_loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=train_logits, labels=tf_y_train))
grad = tf.gradients(train_loss, [tf.input_data], name='gradients')[0]
```
Here is the classification GPFlow example model from the documentation that is very similar to the model I'm using right now:
```
# Setup the experiment and plotting.
Ms = [4, 8, 16, 32, 64]

# Run sparse classification with increasing number of inducing points
models = []
for index, num_inducing in enumerate(Ms):
    # kmeans for selecting Z
    from scipy.cluster.vq import kmeans
    Z = kmeans(Xtrain, num_inducing)[0]

    m = gpflow.models.SVGP(
        Xtrain, Ytrain, kern=gpflow.kernels.RBF(2),
        likelihood=gpflow.likelihoods.Bernoulli(), Z=Z)
    # Initially fix the hyperparameters.
    m.feature.set_trainable(False)
    gpflow.train.ScipyOptimizer().minimize(m, maxiter=20)

    # Unfix the hyperparameters.
    m.feature.set_trainable(True)
    gpflow.train.ScipyOptimizer(options=dict(maxiter=200)).minimize(m)
    models.append(m)
```

Any guidance would be greatly appreciated, thank you!

**Comment by markvdw** [comment]
GPflow only really defines a TensorFlow graph, so I think you can essentially use the same trick as you mentioned. The tensor for the inputs is located in `m.X.unconstrained_tensor`, so you get the gradient by taking the gradients of `m._likelihood_tensor` w.r.t. `m.X.unconstrained_tensor`.

Alternatively, if you want to take gradients w.r.t. predictions, you can create a prediction tensor with `m.build_predict()`, and then perform the same procedure.

**Comment by krm58** [comment]
Thank you for the quick reply! Looking at the trained model, m.X.unconstrained_tensor doesn't seem to be defined. I get the following message:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-17-b4202a9a0dc7> in <module>()
----> 1 m.X.unconstrained_tensor

/home/krm58/anaconda3/lib/python3.6/site-packages/gpflow/params/parameter.py in unconstrained_tensor(self)
    166     @property
    167     def unconstrained_tensor(self):
--> 168         return self._unconstrained_tensor
    169 
    170     @property

AttributeError: 'DataHolder' object has no attribute '_unconstrained_tensor'
```
Would the tensor for the inputs be stored differently as a function of GPFlow version? I am using gpflow 1.1.0.

**Comment by krm58** [comment]
That worked! For everyone who had similar issues, here is how I access the gradients wrt inputs once the model is trained:

```
with tf.Session() as sess:
    m.initialize()
    grads = tf.gradients(m._likelihood_tensor, m.X._dataholder_tensor)[0]
    mygrads = grads.eval()
```
Thank you so much :)

**Comment by pstrz** [comment]
How would one get the gradient at another point? 

This (as I understand) gives the gradient at all available data points. Is there a way to get the gradient at some other point?
