### ISSUE TITLE
Gradient at a point?

### ISSUE THREAD

**Issue by pstrz** [GPflow/GPflow#651]
I found this answer to a previous question 
```
with tf.Session() as sess:
    m.initialize()
    grads = tf.gradients(m._likelihood_tensor, m.X._dataholder_tensor)[0]
    mygrads = grads.eval()
```
Which, I believe, returns the gradient at all known points. I'd like to get the gradient at one specific point, which has not been evaluated. I tried:
```
with tf.Session() as sess:
    m.initialize()
    grads = tf.gradients(m._likelihood_tensor, m._build_predict(c))[0]
    mygrads = grads.eval()
```
where `c` is point I'd like the gradient at. Here, `grads` is returned as `None`. How can I get this gradient?

**Comment by markvdw** [comment]
Can you mathematically describe which gradient you want?

**Comment by pstrz** [comment]
Sorry if I abuse any vocabulary, but (I think) I'm looking for the derivative of the likelihood w.r.t. the inputs.

**Comment by pstrz** [comment]
I'm looking for the gradient of the posterior mean and covariance, w.r.t. the inputs.

**Comment by pstrz** [comment]
So I found this, which looks like what I need:
[(https://github.com/GPflow/GPflow/pull/246/files)]
but, for the life of me, I can't find a `predict_f_gradients` method in GPFlow. I tried the next best thing, using that same code without calling that method
```
Fmu, Fvar = m._build_predict(a)
grad = tf.gradients(Fmu, a) + tf.gradients(Fvar, a)
```
Where `a` is the point I'm interested in. This returns
```
In [508]: grad
Out[508]: [None, None]
```
What am I doing wrong?

**Comment by markvdw** [comment]
Make sure `a` is a Tensor, and that you run the gradient op within a session. Check the TensorFlow documentation for more details.
