### ISSUE TITLE
Re-setting data in a GPModel

### ISSUE THREAD

**Issue by beangoben** [GPflow/GPflow#657]
I am trying to reset the data in a model, looking to do CV without re-defining a new model.
The current [docstring on GPModel](https://github.com/GPflow/GPflow/blob/master/gpflow/models/model.py) says:
>  For handling another data (Xnew, Ynew), set the new value to self.X and self.Y
    >>> m.X = Xnew
    >>> m.Y = Ynew

This no longer works since gpflow 1.0. I am currently doing the following:

```python
        model.X._value = Xnew
        model.Y._value = Ynew
        model.compile()
```
Is this the correct way to reset the data? Assuming model could be any flavor of the models in gpflow (regression, classification, etc).

By the way, really enjoy your work with gpflow!

**Comment by awav** [comment]
Hello @beangoben, 
It does work. What are X and Y?

**Comment by beangoben** [comment]
Tried making a working minimal example, and indeed you are right @awav , it works as documented.

I was getting *'cannot set attribute'* type of messages...but for some weird reason I am no longer getting them.
