### ISSUE TITLE
Make a kernel function

### ISSUE THREAD

**Issue by Bluejung** [GPflow/GPflow#658]
Nice to meet you.

I want to create a kernel function, so I studied all day long. By the way, I do not understand how to create a kernel function that I want to create, so I post a question.

Here is the kernel function I want to create:
X = 3 X N (3-dimention)
Y = 1 X N

K(X_i, X_j) = alpha1 * X_i,1 * X_j,1 + alpha2 * X_i,2 * X_j,2 + alpha3 * X_i,3 * X_j,3

Could I possibly get help?

**Comment by markvdw** [comment]
This kernel is already implemented. You can use as the `Linear` kernel with `ard=True`. 

Also, your X and Y tensors should be transposed.

**Comment by Bluejung** [comment]
Oh really? thank you for letting me know.
One thing I want to know is that I want to use N hyperparameters as I use N dimension data.
such as, alpha1 * X_i,1 * X_j,1 + alpha2 * X_i,2 * X_j,2 + alpha3 * X_i,3 * X_j,3
is it possible by using linear kernel??

**Comment by markvdw** [comment]
https://github.com/GPflow/GPflow/blob/master/gpflow/kernels.py#L277, use the `ARD` parameter.
