### ISSUE TITLE
Using gpflow multithreaded (how to control graphs and sessions)

### ISSUE THREAD

**Issue by Joshuaalbert** [GPflow/GPflow#659]
I'm trying to run prediction in a threaded way. The below example simply tries to do prediction in parallel by having each thread build a model and do `predict_f`. Tensorflow sessions are designed to be thread safe so I would expect anything built on top of it to also be fine. It appears gpflow is capable of threading however one needs to take care of which graph is being used when building a model. 
How should this be done? [I see that autoflow uses the current session's graph as default](https://github.com/GPflow/GPflow/blob/master/gpflow/decors.py#L148), so wrapping `_predict` in `with tf.Graph().as_default()` would not work.

## MCVE

``` python
import gpflow as gp
import tensorflow as tf
import numpy as np
from concurrent import futures

def _predict(x,y,l):
    kern = gp.kernels.RBF(1,active_dims = [0],lengthscales=[l], variance = 1.)
    mean = gp.mean_functions.Zero()

    with gp.defer_build():
        m = gp.models.GPR(x, y, kern, mean_function=mean)
        m.compile()
        ystar,varstar = m.predict_f(x)
    return ystar, varstar

def async(X,Y,ls, max_workers):
    ###
    # Possibly do some GP optimization etc.
    # then run some gpflow operations in threads
    jobs = []
    with futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        for x,y,l in zip(X,Y,ls):
            jobs.append(executor.submit(_predict, x,y,ls))
        futures.wait(jobs)
        results = [j.result() for j in jobs]

if __name__ == '__main__':
    async(np.sort(np.random.normal(size=[2,100,1]),axis=1),
            np.random.normal(size=[2,100,1]),
            [0.1,0.2],
            1)
    ###
    # Works

    async(np.sort(np.random.normal(size=[2,100,1]),axis=1),
            np.random.normal(size=[2,100,1]),
            [0.1,0.2],
            2)

    ###
    # Fails with

#     File "/net/lofar1/data1/albert/miniconda3/envs/kerastf/lib/python3.6/site-packages/gpflow-1.1.0-py3.6.egg/gpflow/core/node.py", line 157, in is_built_coherence
#        raise GPflowError('Tensor "{}" uses different graph.'.format(self.full_name))
#    gpflow.core.errors.GPflowError: Tensor "RBF" uses different graph.
```

**Comment by markvdw** [comment]
I think many people would appreciate a solution to this. It would be great to be able to run testing code separately from training code.

Right now, an easy, but hacky way of doing this, would be to replicate the model multiple different times with multiple different Sessions attached to it.

Actually, come to think of it, doesn't autoflow allow you to pass a session? https://github.com/GPflow/GPflow/blob/30120a183c81cc5d18af0a00ae35e3ec9e06063a/gpflow/decors.py#L147 Does that not solve your issue?

**Comment by Joshuaalbert** [comment]
Here is the solution I have.
Replace `_predict` in the MCVE with the following:
``` python
def _predict(x,y,l):
    ###
    # First create your own graph
    graph = tf.Graph()
    ###
    # Set it as default. 
    # gpfow default session doesn't see tensors in this graph at this point
    with graph.as_default():  
        ###
        # This will reset the default session with proper config settings
        # also passing your new graph
        gp.reset_default_session(graph=graph)  
        ###
        # Get the session object which you'll need to pass later
        sess = gp.get_default_session()
        
        ###
        # You'll need to construct all tensors in a defer_build context
        with gp.defer_build():
            kern = gp.kernels.RBF(1,active_dims = [0],lengthscales=[l], variance = 1.)
            mean = gp.mean_functions.Zero()
            m = gp.models.GPR(x, y, kern, mean_function=mean)
        ###
        # compiling and running ops require that you pass the sess with your
        # graph as keywords.
        m.compile(session=sess)
        ystar,varstar = m.predict_f(x,session=sess)
    return ystar, varstar
```

**Comment by Joshuaalbert** [comment]
Note I've noticed a race condition that occurs if you let the graph be constructed inside the thread job, i.e. inside of `_predict` in the above.
You should use instead something like,
``` python
def _predict(x,y,l,graph=None):
    ###
    # First create your own graph
    graph = graph or tf.Graph()
    ...
```
Then you should pass `graph=tf.Graph()` in as a kwarg in `executor.submit`.

**Comment by Joshuaalbert** [comment]
No that doesn't quite solve it. Still occasionally getting `GPR tensor not in graph` which seems to imply the graph creation naming mechanism isn't randomized unique or something?

**Comment by Joshuaalbert** [comment]
Okay, a I've eliminated the need to create multiple graphs, and the potential race condition, by using name spaces. 

Now simply add a,
```python 
with tf.name_scope("job_{}".format(id)):
    ...
```
around the `gp_defer_build`.
You can pass the same graph object for all threads (or pass a new one per thread, or leave None to let thread make it's own).

**Comment by Joshuaalbert** [comment]
Final code looks like,
``` python 
import gpflow as gp
import tensorflow as tf
import numpy as np
from concurrent import futures

def _predict(x,y,l,id,graph = None):
    ###
    # First create your own graph
    graph = None or tf.Graph()
    ###
    # Set it as default. 
    # gpfow default session doesn't see tensors in this graph at this point
    with graph.as_default():  
        ###
        # This will reset the default session with proper config settings
        # also passing your new graph
        gp.reset_default_session(graph=graph)  
        ###
        # Get the session object which you'll need to pass later
        sess = gp.get_default_session()
        
        ###
        # You'll need to construct all tensors in a defer_build context
        with gp.defer_build():
            with tf.name_scope("job_{}".format(id)):
                kern = gp.kernels.RBF(1,active_dims = [0],lengthscales=[l], variance = 1.)
                mean = gp.mean_functions.Zero()
                m = gp.models.GPR(x, y, kern, mean_function=mean)
        ###
        # compiling and running ops require that you pass the sess with your
        # graph as keywords.
        m.compile(session=sess)
        ystar,varstar = m.predict_f(x,session=sess)
    return ystar, varstar

def async(X,Y,ls, max_workers):
    ###
    # Possibly do some GP optimization etc.
    # then run some gpflow operations in threads
    jobs = []
    graph = tf.Graph()
    with futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        for id,(x,y,l) in enumerate(zip(X,Y,ls)):
            jobs.append(executor.submit(_predict, x,y,ls,id,graph=graph))
        futures.wait(jobs)
        results = [j.result() for j in jobs]

if __name__ == '__main__':

    async(np.sort(np.random.normal(size=[20,100,1]),axis=1),
            np.random.normal(size=[20,100,1]),
            [0.1,0.2],
            8)
```

**Comment by Joshuaalbert** [comment]
There are several reasons why this is not ideal. Firstly, it's not how tensorflow would do it. It that case, the `X`, `Y`, `legnthscales`, etc. would all be placeholders and you would simply run multiple threads on the same graph with different  feed_dicts. This is not possible here due to autoflow functionality (I think). Secondly, there will be one name_scope per job which will grow the graph for each job.
Note you cannot pass the `id % max_workers` in place of `id` (which is just the sequential count of the jobs), because then you could have contention for the thread number.

**Comment by Joshuaalbert** [comment]
The problem returns again. I think I have found out the cause though. The defer_build uses a global variable to indicate whether or not to do auto build. [Here](https://github.com/GPflow/GPflow/blob/master/gpflow/decors.py#L102).

**Comment by awav** [comment]
Hello @Joshuaalbert,

GPflow `compile` uses default graph for TensorFlow graph construction, unless you specified another one using `graph=...` option. Asynchronous execution uses shared resources including default graph. If you ran everything in parallel you wouldn't have that issue.

`with tf.Session(graph=tf.Graph()):` should be enough for running your code.

**Comment by Joshuaalbert** [comment]
Okay, well the simple final solution is to use a Lock on the global variable that defer_build depends on. Final code is here,
``` python
import gpflow as gp
import tensorflow as tf
import numpy as np
from concurrent import futures
from threading import Lock

def _predict(x,y,l,lock,graph = None):
    ###
    # First get or create your own graph
    graph = None or tf.Graph()
    ###
    # This will reset the default session with proper config settings
    # also passing your new graph
    gp.reset_default_session(graph=graph)  
    ###
    # Get the session object which you'll need to pass later
    sess = gp.get_default_session()

    #Lock on the AutoBuild global
    lock.acquire()
    try:
        ###
        # Set it as default. 
        # gpfow default session doesn't see tensors in this graph at this point
        with sess.graph.as_default():
            ###
            # You'll need to construct all tensors in a defer_build context
            with gp.defer_build():
                kern = gp.kernels.RBF(1,active_dims = [0],lengthscales=[l], variance = 1.)
                mean = gp.mean_functions.Zero()
                m = gp.models.GPR(x, y, kern, mean_function=mean)
    finally:
        lock.release()
    ###
    # compiling and running ops require that you pass the sess with your
    # graph as keywords.
    m.compile(session=sess)
    ystar,varstar = m.predict_f(x,session=sess)
    return ystar, varstar

def async(X,Y,ls, max_workers):
    ###
    # Possibly do some GP optimization etc.
    # then run some gpflow operations in threads
    jobs = []
    graph = tf.Graph
    lock = Lock()
    with futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        for id,(x,y,l) in enumerate(zip(X,Y,ls)):
            jobs.append(executor.submit(_predict, x,y,ls,lock, graph=graph))
        futures.wait(jobs)
        results = [j.result() for j in jobs]

if __name__ == '__main__':

    async(np.random.normal(size=[20,100,1]),
            np.random.normal(size=[20,100,1]),
            [0.1]*20,
            8)
```

**Comment by Joshuaalbert** [comment]
@awav I can try out your idea later or perhaps tomorrow. Feel free to take the posted code and see if it works though.

**Comment by awav** [comment]
It will work, if you put _predict body under `with tf.Session(graph=tf.Graph())` and w/o `defer_build` (which is unnecessary here). May I ask you what are trying to achieve with async running?

**Comment by Joshuaalbert** [comment]
Hi @awav I did test this. Indeed, one can replace the parts, 
``` python
gp.reset_default_session(graph=graph)  
sess = gp.get_default_session()
with sess.graph.as_default():
    ...
``` 
With,
``` python
with tf.Session(graph=graph):
    ...
```
and then you do not need to pass  `session` keyword to the compile and other sessions evaluating calls.
Thanks for the tip. I would just add one modification.
I am using the `gp.reset_defaul_session` for posterity, since in that method a session is built with a `ConfigProto` defined in gpflow's settings, and also allows for `TracerSessions`. Therefore, I suggest using,
``` python
gp.reset_default_session(graph=graph)  
sess = gp.get_default_session()
with sess:
    ...
```
Furthermore, this plays well with `defer_build` if you use the `Lock` mechanism from above.

My specific use case is that I have phase screens in 2D space + 1D time + 1D frequency which represent the path length differences for radio waves that come from astronomic sources. The phase screens are discrete calibration solutions solved for discrete directions per antenna per time per channel. I am playing with the idea of using GP's to smooth these solutions and possibly for interpolation. It must run very fast though. I have about 4000 time stamps in an 8 hour observation 500 channels, ~40 directions, and ~60 antennas. I explicitly neglected inter-antenna correlations. To make it somewhat fast, I solve for kernels in a time and frequency chunk per antenna using multiprocessing. Then using multi threading I have each subprocess use those kernels to smooth the rest of the antenna's time/frequency domain. Sorry to be long winded. To finish, I'll just note that I am using a slightly modified version of gpflow that allows vector likelihood variances, i.e. coordinated dependent observation uncertainties.

**Comment by Joshuaalbert** [comment]
I'll close this issue because it is solved.

**Comment by Joshuaalbert** [comment]
Oddly, using @awav's advice I'm back at `RBF tensor not in graph` sometimes. Therefore, I suspect there is another race condition (perhaps another global? But I don't have time to look into it right now). The only method that works so far is the one posted prior with a `Lock` and `defer_build`.

**Comment by BrunoQin** [comment]
Hi @Joshuaalbert , thank you for your code for multi-thread gp, and try the above demo local, and It success. However, when I add `gp.train.ScipyOptimizer().minimize(m, session=sess, disp=True)` under `m.compile(session=sess)` It occurs the error 

`ValueError: Tensor("Reshape:0", shape=(), dtype=float64) must be from the same graph as Tensor("GPR-55220bd4-77/kern/lengthscales/unconstrained:0", shape=(), dtype=float64_ref).`

So I want to ask how to train this multi-thread gp? can you give me some advice? Thank you!

**Comment by Joshuaalbert** [comment]
Could you post what you ran? In general, the easiest way to get multithreaded gpflow, in each thread that you run, make sure you create a new session with it's own default graph, and do everything inside. I.e. in the job,
``` python 
with tf.Session(graph=tf.Graph()) as sess:
    ...
```
Gpflow will always add operations to the default graph and run things in the default session. You don't need to do anything else. The only caveat is that if you use `defer_build`, then you must lock on the graph build part because gpflow uses a global structure for that.

**Comment by Joshuaalbert** [comment]
No problem. Yes it will train your model at the line `gp.train.ScipyOptimizer().minimize(model)`.

**Comment by BrunoQin** [comment]
Thank you for your help!

**Comment by Joshuaalbert** [comment]
Yes it will be the same order.
