### ISSUE TITLE
GPR using Linear Kernel and multi-dimension input

### ISSUE THREAD

**Issue by Bluejung** [GPflow/GPflow#662]
Nice to meet you. 
I am writing to ask for advice on the problems that have occurred to me.

Problems arise in the process of GPR using multi-demension input data. 
I used the ARD option as shown in the code below, and used 5-D data as input.

===========================================================
import gpflow
import numpy as np
import tensorflow as tf
import timeit

#Parameter:
#dim --> dimension of input data
#num_input --> The number of input(row)

dim = 5 
num_input = 100 
rng = np.random.RandomState(1)

x1 = np.linspace(2, 10 ,num_input)
x2 = np.linspace(2, 10, num_input)
x3 = np.linspace(2, 10, num_input)
x4 = np.linspace(2, 10, num_input)
x5 = np.linspace(2, 10, num_input)
XX = (np.array([x1, x2, x3, x4, x5])).T

YY = np.random.uniform(2, 7, XX.shape[0]).reshape(-1, 1)

start_time = timeit.default_timer()

k = gpflow.kernels.Linear(input_dim=dim , ARD=True)
k.as_pandas_table()

m = gpflow.models.GPR(XX, YY, kern=k)
m.compile()
opt = gpflow.train.ScipyOptimizer()
opt.minimize(m)

end_time = timeit.default_timer()

print("Dimension : " + str(dim) + "\t" + "# input : " + str(num_input))
print("--- %s seconds ---" %(end_time - start_time))

===========================================================

My problem is that,
As the number of num_input increases, the execution time exponentially increases. Furthurmeore, If I set it to 5000, it will not work at all. Why is this happening? Is it a matter of heap size?

The execution time according to num_input is as follows.
num_input = 100, time = 1.6 sec
num_input = 500, time = 2.47 sec
num_input = 1000, time = 6.85 sec
num_input = 1500, time = 18.74 sec
num_input = 3000, time = 131.66 sec

Thank you.

**Comment by Bluejung** [comment]
Even with 1D data, the execution time seems to increase tremendously depending on the number of input.

**Comment by markvdw** [comment]
This is expected behaviour for GP regression, which has cost O(N^3). Sparse methods exist which avoid this limitation, see `SVGP`.

I suggest reading a book like http://www.gaussianprocess.org/gpml/ to get up to speed.
