### ISSUE TITLE
Model <-> ... <-> GPModel

### ISSUE THREAD

**Issue by st--** [GPflow/GPflow#667]
GPModel defines a couple useful functions on top of the Model class: predict_f_samples, predict_y, and predict_density. For this, it requires a kernel, a likelihood, and X and Y. However, some models only have an X (e.g. point process models), or require something more complicated than simply setting a likelihood. Yet, they would still benefit from reusing predict_f_samples(). Right now I can subclass from GPModel, but call `Model.__init__` instead, but that seems rather hacky, and maybe it'd be worth to have a class layer between Model and (what is currently) GPModel? @markvdw also had some related thoughts regarding Deep GPs.

**Comment by markvdw** [comment]
Shelved for a later large redesign.

**Comment by st--** [comment]
Are we going to have a large redesign? Do we have a list of items for that where we should add this?
