### ISSUE TITLE
Mean function tests are very slow

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#67]
On my desktop running the tests sequentially takes:

540s

Of this: 324s are spent in the mean functions test.

@jameshensman I don't have much familiarity with this test as it is new. Do you have any ideas about how we could keep coverage and reduce the time?

Obviously this would make a major difference to our build times.

**Comment by PabloLeon** [comment]
The mean function tests right now contain the tests I had added originally (and did not really intend for this version but my own testing) and I think could be considerably shortened without much loss - especially it should be unnecessary to run all models on the mean function combinations. I could delete unnecessary tests if wanted...

**Comment by alexggmatthews** [comment]
Thanks for the info @PabloLeon . I know James H made some changes. @jameshensman can we close this one now?

**Comment by jameshensman** [comment]
Yep, I went through and removed some of the more extensive tests that covered all permutations.
