### ISSUE TITLE
GPFlow with missing values / sparse observation matrix?

### ISSUE THREAD

**Issue by charleshamesse** [GPflow/GPflow#671]
Hi,

I have some X (NxM, dense) and some Y (NxP, sparse, lot of missing values currently as nan). My goal is to recover the missing values in Y. I've been skimming through notebooks and examples here but can't seem to find resources on how to use GPFlow to model this. 

Could anyone let me know the way to go for this? Any help appreciated. Thanks!

**Comment by markvdw** [comment]
First, you will have to write your own likelihood to ensure that missing values do not contribute to the variational lower bound. This ensures that the model trains correctly by leaving the missing values out.

You can then predict all outputs as usual.

**Comment by rsstoyanova** [comment]
I have a similar problem right now. Could you perhaps elaborate on how to write the likelihood function in this case?
