### ISSUE TITLE
Is it possible to embed gpflow models in a TF graph

### ISSUE THREAD

**Issue by Joshuaalbert** [GPflow/GPflow#686]
I'm not sure, but I think this should be possible. More specifically, I'd like to use the SVGP model in a classification task, and instead of specifying model.X and Y as numpy tensors, use tensors that have preceeding ops and variables to train. I would like to group the training ops of gpflow with other training ops, and also use the output of predict_y as a tensor as input to further ops.

**Comment by a5a** [comment]
From the documentation of GPflow.params.DataHolder:

    :param value: Data input value. It can be a float, an integer,
        a float or integer like list, numpy array or TensorFlow variable.

which indicates that defining self.X and self.Y in terms of tf variables should indeed work.

**Comment by hughsalimbeni** [comment]
perhaps of interest: https://github.com/GPflow/GPflow/blob/hugh/advanced_usage_notebook/doc/source/notebooks/advanced_usage.ipynb

I'd be interested in feedback

**Comment by Joshuaalbert** [comment]
That looks really nice and helpful! I could also think of another cool extension to that notebook, to combine gpflow with pymc3 for hierarchical modeling with NUTS. I think gpflow is much faster, and full-featured than pymc3's GP capability, and gpflow lacks the NUTS and hierarchical capabilities.
