### ISSUE TITLE
ModuleNotFoundError: No module named 'gpflow'

### ISSUE THREAD

**Issue by a5a** [GPflow/GPflow#687]
After pulling the latest changes from the master branch, I'm getting "ModuleNotFoundError: No module named 'gpflow'" errors, due to line 20 in natgrad_optimizer.py 

from gpflow.models import Model

Commenting out this line fixes this error for me. Also, GPflow.models.Model is imported a second time on line 24, so I think removing the first line should not have any adverse effect.

**Comment by hughsalimbeni** [comment]
Thanks for the spot
