### ISSUE TITLE
Input matrix is not invertible

### ISSUE THREAD

**Issue by AlejandroCatalina** [GPflow/GPflow#692]
Hi guys,

I'm having some trouble optimising a Sparse Gaussian Process Regressor when setting some priors so I obtain a bayesian model. 

I should note that the code runs fine if I remove the priors, the snippet would be

```
D = X_train.shape[1]
k = GPflow.kernels.Matern12(D, lengthscales=100.) + GPflow.kernels.Matern12(D, lengthscales=1.) + GPflow.kernels.White(D)
M = 50
Z = np.zeros((M, D))
m_ = GPflow.sgpr.SGPR(X_train, y_train[:, np.newaxis], kern=k, Z=Z)
m_.kern.matern12_1.variance.prior = GPflow.priors.Gamma(1., 10.)
m_.kern.matern12_1.lengthscales.prior = GPflow.priors.Gamma(1., 10.)
m_.kern.matern12_2.variance.prior = GPflow.priors.Gamma(1., 10.)
m_.kern.matern12_2.lengthscales.prior = GPflow.priors.Gamma(1., 10.)
m_.kern.white.variance.prior = GPflow.priors.Gamma(1., 10.)
m_.likelihood.variance.prior = GPflow.priors.Gamma(1., 10.)
m_.Z.prior = GPflow.priors.Gamma(1., 10.)
m_.likelihood.variance = 0.01
m_.optimize()
```

The error is

```
InvalidArgumentError (see above for traceback): Input matrix is not invertible.
	 [[Node: model.build_likelihood_35/MatrixTriangularSolve = MatrixTriangularSolve[T=DT_DOUBLE, adjoint=false, lower=true, _device="/job:localhost/replica:0/task:0/cpu:0"](model.build_likelihood_35/Cholesky, model.build_likelihood_35/model.kern.K/Add_1)]]
```

Any pointers?

Thank you!

**Comment by hughsalimbeni** [comment]
A few things
* What is X_train and y_train? The scale of the input data might be causing the problem. 
* The code above uses an old version of gpflow which is no longer supported. Please install the newest version and adapt the code (the only thing you'll need to change is the optimize line) and then we can take a look
* Why do you have a prior for Z? This doesn't make sense as Z is a variational parameter. 
* The prior for the matern12 lengthscale isn't consistent with the initial value. Why do you use the same gamma prior for all hyperparameters?

**Comment by AlejandroCatalina** [comment]
Yeah I know that the priors don't make sense, this snippet is the result of many tryouts, so I just set the same prior to see how the code runs. 

I'll install the latest version. I installed this one through anaconda, I'll install the newest by compiling from source.

With respect to X_train and y_train, X_train is scaled to 0 mean and 1 std and y_train is in [0, 100]. 

I'll update and test again, hope it solves it!

**Comment by AlejandroCatalina** [comment]
Okay now the problem is twofold:

1. With the above snippet the problem is the same, input matrix is not invertible.
2. Removing the priors gives the same error (it did run okay before).
```
In [11]: D = X_train.shape[1]
    ...: k = gpflow.kernels.Matern12(D, lengthscales=100.) + gpflow.kernels.Matern12(D, lengthscales=1.) + gpflow.kern
    ...: els.White(D)
    ...: M = 50
    ...: Z = np.zeros((M, D))
    ...: m_ = gpflow.models.SGPR(X_train, y_train[:, np.newaxis], kern=k, Z=Z)
    ...: m_.compile()
    ...: opt = gpflow.train.ScipyOptimizer()
    ...: opt.minimize(m_)
InvalidArgumentError: Input matrix is not invertible.
	 [[Node: gradients/SGPR-53f8887e-62/Cholesky_grad/MatrixTriangularSolve = MatrixTriangularSolve[T=DT_DOUBLE, adjoint=false, lower=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](SGPR-53f8887e-62/Cholesky, gradients/SGPR-53f8887e-62/Cholesky_1_grad/eye/MatrixDiag)]]
```
3. Trying a GPR (not a Sparse approximation) runs for 1 iteration and return nan.
```
In [12]: D = X_train.shape[1]
    ...: k = gpflow.kernels.Matern12(D, lengthscales=100.) + gpflow.kernels.Matern12(D, lengthscales=1.) + gpflow.kern
    ...: els.White(D)
    ...: M = 50
    ...: Z = np.zeros((M, D))
    ...: m_ = gpflow.models.GPR(X_train, y_train[:, np.newaxis], kern=k)
    ...: m_.compile()
    ...: opt = gpflow.train.ScipyOptimizer()
    ...: opt.minimize(m_)
    ...:
/Users/alex/.anaconda/lib/python3.6/site-packages/gpflow/densities.py:89: UserWarning: Shape of x must be 2D at computation.
  warnings.warn('Shape of x must be 2D at computation.')
INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
  Objective function value: nan
  Number of iterations: 0
  Number of functions evaluations: 1

In [13]: preds, std = m_.predict_y(X_test)

In [14]: preds
Out[14]:
array([[ nan],
       [ nan],
       [ nan],
       ...,
       [ nan],
       [ nan],
       [ nan]])
```

So I guess I should make it work without priors first and then go back to the priors.

Any pointers? am I doing it wrong?

**Comment by markvdw** [comment]
@AlejandroCatalina has this worked out yet? The only thing I can really suggest is to try and debug the code path to see where the nans come from.

**Comment by AlejandroCatalina** [comment]
This same model works in GPy, so I used that for the time being, thanks though, I will try this again this evening and will let you know.

**Comment by mohammadAbdolhosseiniMoghaddam** [comment]
@AlejandroCatalina   Could you solve the problem? I have the same issue as yours.

**Comment by AlejandroCatalina** [comment]
No I could not.

**Comment by mohammadAbdolhosseiniMoghaddam** [comment]
The issue got solved by updating gpflow. Thanks
