### ISSUE TITLE
pytest dependency not specified

### ISSUE THREAD

**Issue by gdkrmr** [GPflow/GPflow#697]
When installing gpflow as suggested (cloning, then `pip install .`), the dependency `pytest` is not installed.

**Comment by awav** [comment]
`pytest` is not required for GPflow usage, therefore it goes into test requirements. Look at:
https://setuptools.readthedocs.io/en/latest/setuptools.html?highlight=tests_require#new-and-changed-setup-keywords

**Comment by st--** [comment]
In a fresh virtualenv with the latest master (commit f5d8cc45aec7e1f5a5c27f49e4ee377a7fbbac83) I cannot reproduce your issues. If you still experience this issue with the latest commit, can you please open a new issue, and also provide more detailed error messages? Thanks!
