### ISSUE TITLE
Params and DataHolders converted to NoneType when using @params_as_tensors decorator

### ISSUE THREAD

**Issue by a5a** [GPflow/GPflow#699]
Hi,

This is a follow-up of a previous issue regarding defining a GP model with multiple datasets, so apologies for opening a new issue, as I cannot reopen the other issue. 

I'm having trouble using Params and DataHolders in my model, as arithmetic operations (specifically multiplication in the example below) are crashing due to the variables being of type "NoneType". I have a simple example below showing how my model is crashing (see the create_data_set() function). 

    class GPWithMultipleDataSets(GPModel):
        def __init__(self, X, Y, kern, my_param, some_constant, name=None):
            super().__init__(X, Y, kern,
                             Gaussian(),
                             None, name=name)
    
            self.some_constant = some_constant
    
            # New hyperparameter that will be optimized
            self.my_param = Param(my_param,
                                  transform=transforms.positive)
    
            # Creating a list of data sets
            self.data_sets = []
            for col in range(X.shape[1]):
                self.data_sets.append(self.create_data_set(col))
    
        @params_as_tensors
        def create_data_set(self, col):
            """
            Create a version of self.X with a value added along
            the col-th column.
    
            I'm only showing the two types of operations that I need in order to
            create my actual model.
            """
            # Adding or multiplying a constant with a Param variable crashes with:
            # TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
            perturbation = self.some_constant * self.my_param
    
            # Adding "perturbation" to X along the ii-th column crashes with:
            # TypeError: 'NoneType' object is not subscriptable
            new_X = self.X[:, col].assign_add(perturbation)
            return new_X
    
        @params_as_tensors
        def _build_likelihood(self):
            """
            Using super class function as a placeholder until
            self.create_data_set() works
            """
            return super()._build_likelihood()
    
        @params_as_tensors
        def _build_predict(self, Xnew: np.ndarray, full_cov: bool = False):
            """
            Using super class function as a placeholder until
            self.create_data_set() works
            """
            return super()._build_predict(Xnew, full_cov)

I used the @params_as_tensors decorator, but I'm getting errors (described in the comments of the function) because the Param and DataHolder objects become NoneTypes when the program enters the function during model initialisation.

The two specific operations I'm interested in doing are:

* arithmetic operations containing Param variables as well as constants and DataHolders
* Slice assignment of DataHolders. tf.assign_add() works fine in unrelated test cases for me, so do I need to define a different context or access the tensor directly somehow?

This may be a basic misunderstanding on my end, as I'm quite new to GPflow, but any help/comments appreciated!

Versions:
Python 3.6.1
TensorFlow 1.7.0
GPflow latest master branch commit at time of writing (16570be787f2d3b0d8c4469a54ea2c6279186d8f)

**Comment by hughsalimbeni** [comment]
I've had problems doing this sort of thing before, too. The problem is using params inside` __init__`. I'd suggest just forming the datasets as you like using X (not model.X), or else use param.unconstrained_tensor and manage the session yourself

**Comment by a5a** [comment]
My requirement is for the DataHolders to be dependent on a Param variable as they will dynamically change when the hyperparameter is optimized, and that the log likelihood (and its gradients) are correctly computed. 

Have I understood you correctly when I say you are suggesting I define them fully in terms of TF operations outside of the model and feed in tensorflow variables for the datasets as well as the hyperparameter to the model?

I'm not sure what you mean with regards to managing the session myself -- is there an example somewhere that I could look at how this works with GPflow? I have only seen examples of the form

    with GPflow.defer_build():
        ...

Is this what you mean?

Thanks!

**Comment by hughsalimbeni** [comment]
That sounds like a very tricky usage for tensorflow, as the graph is static. If you only need to change shape (N,D to N,D+1) then it might be possible, but changing control flow (e.g. an if statement) is going to be harder. You could check out the natural gradients code for an example of performing a variable assign mid-optimization.
