### ISSUE TITLE
MCMC example documentation on readthedocs didn't render

### ISSUE THREAD

**Issue by sadatnfs** [GPflow/GPflow#703]
In the section where we attempt to use MCMC on theta, that block errored out:
https://gpflow.readthedocs.io/en/stable/notebooks/regression.html

**Comment by awav** [comment]
Thx, we will fix it.

**Comment by sadatnfs** [comment]
Thanks! I feel like something might have changed with the API eh? (I'm also getting errors when I'm trying to MCMC)

**Comment by st--** [comment]
This is working for me locally. How does the readthedocs version get updated?

**Comment by st--** [comment]
Related to #582 - same notebook, just latest vs stable...

**Comment by st--** [comment]
@sadatnfs "stable" and "latest" versions of readthedocs are deprecated. We now have "master" for the master branch (latest actual release) and "develop" for the develop branch (bleeding-edge latest version on github). Please check you are looking at the correct version of the docs. If you find any links pointing to "stable" or "latest", please let us know so we can fix them! (Feel free to re-open this issue!)
