### ISSUE TITLE
Error when running AdamOptimizer

### ISSUE THREAD

**Issue by aboustati** [GPflow/GPflow#707]
Hi,

Whenever I try to optimize a model using Adam, I get the following error:

`FailedPreconditionError: Attempting to use uninitialized value beta1_power`

This happens when I run my own models, as well as when I run GPflow tests and notebooks. All other optimizers work perfectly fine. Any ideas on what is causing this?

Thanks!

**Comment by aboustati** [comment]
After further invesitgation, I found that this issue is caused by incompatibility with Tensorflow version 1.6. I am going to keep this issue open for now so that the devs aware of this problem.

Thanks

**Comment by awav** [comment]
Hello @aboustati! We are well aware of this issue, will fix it soon.Thanks!

**Comment by mrksr** [comment]
See #677

**Comment by awav** [comment]
Solved #714
