### ISSUE TITLE
Coregionalization implementation help

### ISSUE THREAD

**Issue by sadatnfs** [GPflow/GPflow#709]
Hi there,

I'm trying to expand on the 2-dimensional coregionalization example into a 3-dimensional output problem, and I'm running into trouble trying to fit the GPRs. I think my biggest issue is that I'm not understanding how exactly the 0 and 1 indicators should be implement to fit the model. 

I've attached my code below, and the output it produces (mean line) are almost exactly overlapping, and nothing as beautiful as the example code. What I'm really hoping to achieve is to fit 3 output variables with GPR such that they draw from the correlation across the 3 variables. It'd be awesome if you guys could give some inputs and thoughts on this!

Thanks!

````
import gpflow as gpflow
import pandas as pd
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
plt.style.use('ggplot')
# %matplotlib inline
import seaborn as sns
np.random.seed(1)


def plot_gp(x, mu, var, color='k'):
    plt.plot(x, mu, color=color, lw=2)
    plt.plot(x, mu + 2*np.sqrt(var), '--', color=color)
    plt.plot(x, mu - 2*np.sqrt(var), '--', color=color)

def plot(m):
    xtest = np.linspace(0, 1, 300)[:,None]
    line, = plt.plot(X1, Y1, 'x', mew=2)
    mu, var = m.predict_f(np.hstack((xtest, np.zeros_like(xtest))))
    plot_gp(xtest, mu, var, line.get_color())

    line, = plt.plot(X2, Y2, 'x', mew=2)
    mu, var = m.predict_f(np.hstack((xtest, np.ones_like(xtest))))
    plot_gp(xtest, mu, var, line.get_color())
    
    line, = plt.plot(X3, Y3, 'x', mew=2)
    mu, var = m.predict_f(np.hstack((xtest, np.ones_like(xtest))))
    plot_gp(xtest, mu, var, line.get_color())



# make a dataset with 3 outputs

X1 = np.random.rand(100, 1)
X2 = np.random.rand(100, 1) 
X3 = np.random.rand(100, 1) 

Y1 = np.sin(6*X1) + np.random.standard_t(3, X1.shape)*0.03
Y2 = np.sin(6*X2+ 0.7) + np.random.standard_t(3, X2.shape)*0.1
Y3 = np.cos(5*X3- 0.3) + np.random.standard_t(3, X3.shape)*0.4

plt.plot(X1, Y1, 'x', mew=2)
plt.plot(X2, Y2, 'x', mew=2)
plt.plot(X3, Y3, 'x', mew=2)
plt.show()


# Base Matern kernel
k1 = gpflow.kernels.Matern32(1, active_dims=[0])

# Build the coreg kernel
coreg = gpflow.kernels.Coregion(1, output_dim=3, rank=3, active_dims=[1])

kern = k1 *  coreg

# Build Likelihood
lik = gpflow.likelihoods.SwitchedLikelihood([gpflow.likelihoods.StudentT(), gpflow.likelihoods.StudentT()])

# Augment the time data with ones or zeros to indicate the required output dimension
X_augmented = np.vstack((np.hstack((X1, np.zeros_like(X1))), np.hstack((X2, np.ones_like(X2))), np.hstack((X3, np.ones_like(X3)))) )

# Augment the Y data to indicate which likeloihood we should use
Y_augmented = np.vstack((np.hstack((Y1, np.ones_like(X1))), np.hstack((Y2, np.ones_like(X2))), np.hstack((Y3, np.ones_like(X3))) ))

# now buld the GP model as normal
m = gpflow.models.VGP(X_augmented, Y_augmented, kern=kern, likelihood=lik, num_latent=1)

# fit the covariance function parameters
gpflow.train.ScipyOptimizer().minimize(m)

## Fit and plot
xtest = np.hstack([np.linspace(0, 1, 100)]*3)[:,None]
mu1, var1 = m.predict_f(np.hstack((xtest, np.zeros_like(xtest))))
mu2, var2 = m.predict_f(np.hstack((xtest, np.ones_like(xtest))))
plt.plot(X1, Y1, 'x', mew=2)
plt.plot(X2, Y2, 'x', mew=2)
plt.plot(X3, Y3, 'x', mew=2)
plt.plot(np.linspace(0, 1, 100), np.reshape(mu2, [100,3]))
```

**Comment by Canas** [comment]
From my understanding, which may or may not be accurate, there are some issues with your code that I will address independently 

**Regarding the 0 and 1 indicators confusion**
The Coregion kernel for 1 input and 3 outputs works with data that has 2 dimensions: the first dimension corresponds to the data itself, and the second dimension indexes the data to indicate the kernel which input corresponds to which output. For example, suppose I have 2 data samples for each of my 3 output dimensions, then:

```
X_1 = [0.2, 0.3], 
Y_1 = [12.5, 15.3]

X_2 = [0.1, 0.5]
Y_2 = [-5.2, -7.7]

X_3 = [0.7, 0.9]
Y_3 = [6.8, 6.9]
```

The augmented data should be like this:
```
X_augmented = [
    [0.2, 0.3, 0.1, 0.5, 0.7, 0.9]
    [  0,   0,   1,   1,   2,   2]
]
Y_augmented = [
    [12.5, 15.3, -5.2, -7.7, 6.8, 6.9],
    [   0,    0,    1,    1,   2,   2]
]
```
This indicates the kernel which data corresponds to which output dimension.

In your code then, you should do the following changes:
```
# Augment the time data with ones or zeros to indicate the required output dimension
X_augmented = np.vstack(
    (np.hstack((X1, np.zeros_like(X1))), np.hstack((X2, np.ones_like(X2))), np.hstack((X3, 2*np.ones_like(X3))))
)

# Augment the Y data to indicate which likeloihood we should use
Y_augmented = np.vstack(
    (np.hstack((Y1, np.zeros_like(X1))), np.hstack((Y2, np.ones_like(X2))), np.hstack((Y3, 2*np.ones_like(X3))))
)
```

Additionally, each output dimension has a likelihood variance:
```
lik = gpflow.likelihoods.SwitchedLikelihood([
    gpflow.likelihoods.StudentT(), gpflow.likelihoods.StudentT(), gpflow.likelihoods.StudentT()
])
```

**Regarding the way you extract the predictions**
Currently, you create 3 different copies of `xtest` and do a reshape of the `predict_f` method, which is not the way this is supposed to be used. You only pass one copy of `xtest` and concat the index of the output dimension you want to predict. This means that if you want to use the same `xtest` for each prediction, then you'll have to use the following:

```
mu1, var1 = m.predict_f(np.hstack((xtest, np.zeros_like(xtest))))
mu2, var2 = m.predict_f(np.hstack((xtest, np.ones_like(xtest))))
mu3, var3 = m.predict_f(np.hstack((xtest, 2*np.ones_like(xtest))))
```

To plot, I recommed to assign a specific color to each output dimension so you don't get lost with the amount of points and lines :)

```
plt.plot(X1, Y1, 'x', mew=2, color='r')
plt.plot(X2, Y2, 'x', mew=2, color='b')
plt.plot(X3, Y3, 'x', mew=2, color='g')

plt.plot(np.linspace(0, 1, 100), mu1, 'r')
plt.plot(np.linspace(0, 1, 100), mu2, 'b')
plt.plot(np.linspace(0, 1, 100), mu3, 'g')
```

Testing this version of the code gave me decent predictions for each output so I hope it works for you too :).

**Comment by sadatnfs** [comment]
Woah this is awesome, thank you so much for writing out a detailed example for me! I will test this out in the next few days when I have time and will let you know!

**Comment by sadatnfs** [comment]
Oh question @Canas : Would the same kernels that I built in my example work with this setup as well?

**Comment by Canas** [comment]
They should. I tested it with the same kernels in your code.

**Comment by sadatnfs** [comment]
Can confirm that I was able to run with simulated data on my end:
[https://gist.github.com/sadatnfs/11f5d8f63ddbabbf41afaff7d1fb39c6](url)

Thanks so much for your help! Your reply has definitely been a great tutorial for understanding the augmenting!

**Comment by sadatnfs** [comment]
Apologies for reopening this @Canas , but I had a follow up question: this works quite well with single dimensional input, but what if we wanted to have multiple columns of input data to try and model our outputs? Simply appending zeroes in the augmented datasets isn't helping so I imagine I'd have to change the kernels as well..?

**Comment by Canas** [comment]
Sorry but I have never worked with the multi-input case so I'm not sure about the optimal approach. Wouldn't it be better to treat them separately in that case?

**Comment by sadatnfs** [comment]
Turns out that I actually could just define a multidimensional base kernel and then apply the coregion on top of that! So if I have 5 inputs where I use a Matern on the first dimension and Linear on the rest 4, this works for me:

`k1 = gpflow.kernels.Matern32(input_dim = 1, active_dims=[0])
k2 = gpflow.kernels.Linear(input_dim = 4, active_dims=[1,2,3,4])
coreg = gpflow.kernels.Coregion(1, output_dim=3, rank=3, active_dims=[5])
kern = (k1+k2) * coreg`
