### ISSUE TITLE
implementing a non-separable kernel in GPflow

### ISSUE THREAD

**Issue by halasadi** [GPflow/GPflow#710]
Hi,

I am trying to implement a new kernel,

theta * exp{ - [ (d/alpha)^2 + (t/beta)^2]^{1/2}}

where d is the spatial distance, and t is the temporal distance. As you can see, it reduces to the exponential kernel when the input dimension is one.

I'm not sure how implement this kernel because it cannot be written as a product (or sum) of existing kernels in GPflow.

I would appreciate any help on this.

Thank you for the great software!

Hussein

**Comment by st--** [comment]
The `Exponential` kernel does implement ARD (different lengthscales for each dimension), so all you need to do is `k = gpflow.kernels.Exponential(2, lengthscales=[alpha, beta], variance=theta)`, assuming your data is (space,time).

In general, you can easily implement a new kernel by subclassing from `gpflow.kernels.Kernel` (or `gpflow.kernels.Stationary` or whatever else is appropriate). Hope this helps, ask again if you've got any further questions.
