### ISSUE TITLE
GPflow model zoo?

### ISSUE THREAD

**Issue by st--** [GPflow/GPflow#711]
I think it'd be really nice to have a place to collect various GPflow models, both general and specific applications, which would then be a good place for models such as the Student's-T-Process (#265), the birthday data decomposition (#491), and other snippets that are currently only hanging around in issues (e.g #619) or people's home directories, but which might be useful to showcase the wide variety of things that can be done with GPflow (and how easy it is to do them). Similar to https://github.com/tensorflow/models ... and maybe similarly a good place to host this could be https://github.com/GPflow/models ? Any comments/approvals/objections?

**Comment by mathDR** [comment]
👍

**Comment by st--** [comment]
Oh, and the MNIST demo in #200.

@alexggmatthews @jameshensman should this be a separate repository (in which case could you please set one up - I can't do it by myself), or just a subdirectory in the GPflow repo?

Pro separate repo: no burden on gpflow-core to keep maintaining a bunch of models. No guarantees that a model will work with latest GPflow version. Pro subdirectory in same repo: easier to keep models up to date with changes to GPflow. Models should only depend on the API so shouldn't break until we move to GPflow 2...

**Comment by st--** [comment]
#735

**Comment by markvdw** [comment]
I think we should not have them in the same repo. The policy in the contributing.md is that we're happy to link to projects that use GPflow. I don't think we want to support a whole zoo of models.

Plus, once we get a better release schedule working with GPflow, it should be easier to keep code working when new versions of GPflow come out.

**Comment by shyamalschandra** [comment]
That would be great because I don't see any value in an arbitrary python package unless it has some applications in python notebooks.
