### ISSUE TITLE
Access a ParamList with tensor index for use with tf.map_fn

### ISSUE THREAD

**Issue by maximilianmordig** [GPflow/GPflow#715]
This is not a bug, but rather a feature request.

Given a ParamList p, is it possible to access it via a tensor index? Here is a trivial use case with tf.map_fn.

tf.map_fn(lambda p: p[i], np.arange(10))

This fails with the exception:
TypeError: list indices must be integers or slices, not Tensor

I have so far done circumvented it doing:
tf.stack([p[i] for i in np.arange(10)])

**Comment by hughsalimbeni** [comment]
A `ParamList` can't be tensor-like as the parms could all be different shapes. For `map_fn` to work the graph inside must be static, so it can't handle different shaped inputs. In situations where all the params are all the same shape then they could be concatenated to a single param which could then be iterated over in a `map_fn`
