### ISSUE TITLE
Predictive mean GP regression model as covariance function

### ISSUE THREAD

**Issue by PabloAlvarado** [GPflow/GPflow#716]
Hello all,

Could you please tell me if it is possible to use the predictive mean of a GP regression model to define the method K in a new kernel class? Hope the following code (using gpflow 0.5.0) explains better this question:

    import numpy as np
    import tensorflow as tf
    import gpflow
    from gpflow.kernels import Stationary

    # Generate samples of Gabor kernel for this example

    N = 101
    X = np.linspace(-1, 1, N).reshape(-1, 1)
    Y = np.cos(3*2.*np.pi*X) * np.exp(-8.*X**2)

    # Define and optimize GP regression model

    k = gpflow.kernels.Matern52(1, lengthscales=0.3)
    model = gpflow.gpr.GPR(X, Y, kern=k)
    model.likelihood.variance = 0.01

    model.optimize(disp=True, maxiter=1000)

    # define new kernel class

    class KernelGP(Stationary):
        """
        The GP kernel
        """
       
        def __init__(self, input_dim, gpmodel, variance=1.0, lengthscales=None, active_dims=None, ARD=False):
           
            Stationary.__init__(self, input_dim, variance=1.0, lengthscales=None, active_dims=None, ARD=False)
           
            self.gpmodel = gpmodel

        def K(self, X, X2=None, presliced=False):
            if not presliced:
                X, X2 = self._slice(X, X2)
            r = self.euclid_dist(X, X2)
            return self.variance * self.gpmodel.predict_f(r)[0]

    # evaluate kernel in xnew
    xnew = np.linspace(0, 1, 100).reshape(-1, 1)
    newkern = KernelGP(input_dim=1, gpmodel=m)-
    newkern.compute_K_symm(xnew)

Thank you so much

**Comment by hughsalimbeni** [comment]
A few points:
* As above, this kernel is not positive definite so not a valid kernel.  
* You can't feed tensors to an autoflow function (you should be calling `_build_predict`) to get the tensors.
* If you put the GP before the euclidian distance you have something quite like a Deep GP. Code based on GPflow for this model is available [here](https://github.com/ICL-SML/Doubly-Stochastic-DGP)
* I strongly suggest getting the most recent gpflow, as the old version is not supported

**Comment by PabloAlvarado** [comment]
Thank you for your reply.
