### ISSUE TITLE
Student T Prior?

### ISSUE THREAD

**Issue by sar2160** [GPflow/GPflow#718]
Are there technical reasons why a Student-T prior hasn't been implemented? From glancing at the code it seems like it would be relatively easy to add with the existing Student T density, so the fact it hasn't been done makes me suspect there's something more complicated lurking.

Thanks for your work on this project. I just migrated over from GPy and am still learning GPs in general, digging into the code here has been helpful.

**Comment by st--** [comment]
I don't think there's anything special about the Student-T distribution that would prevent it from being used as a prior. Probably, no-one needed one so far. You are welcome to make a Pull Request to GPflow to add one (please follow https://github.com/GPflow/GPflow/blob/master/contributing.md and https://github.com/GPflow/GPflow/blob/master/.github/PULL_REQUEST_TEMPLATE.md)! I just updated someone else's PR to add an Exponential distribution as a prior (#717).
