### ISSUE TITLE
How to reset the self.X and self.Y in the model

### ISSUE THREAD

**Issue by Jarrome** [GPflow/GPflow#720]
The issue is I want to change the self.X and self.Y after estimation of the hyper parameter. And then use the new X,Y to predict on the Xtest. 

So, how to do this without bug?

**Comment by st--** [comment]
Hi, the DataHolder should support reassignment, so `self.X = newX` and `self.Y = newY` should work just fine. If that doesn't work for you, please provide a Minimal Working (or Failing) Example that reproduces the bug. Thanks!

**Comment by awav** [comment]
@Jarrome, https://github.com/GPflow/GPflow/blob/master/.github/ISSUE_TEMPLATE.md
