### ISSUE TITLE
Implementing slice on feature matrix X for mean function

### ISSUE THREAD

**Issue by gsVAM** [GPflow/GPflow#722]
As a preface, I am a complete newb to GPflow -- so apologies if this question just seems so completely obvious that you may wonder if I suffer from some form of congenital mental defect -- I probably do.

That said, I want to implement a model with a non-zero mean function as follows:
X = N x D feature matrix
D can be partitioned into d1 and d2 where I want to use d1 for the mean function and d2 for the GP

y = X_d1 * B + GP(X_d2)

I can easily slice the feature matrix into different partitions when creating my kernel, can I do the same when creating the mean function?  If so, how?

Thanks!

-Gau

**Comment by imsrgadich** [comment]
I request you to watch this [video](https://www.youtube.com/watch?v=4vGiHC35j9s), I feel your concepts about GP are still inchoate . I would also suggest you to study the first two chapters of this fantastic [book](http://www.gaussianprocess.org/gpml/chapters/RW.pdf). I guess after that you would be able to formulate the model properly.

**Comment by hughsalimbeni** [comment]
I think it would be quite just to add a slice to an existing mean function. E.g. something like

```python
class SlicedLinear(Linear):
    def __init__(self, slice, A=None, b=None):
        Linear.__init__(self, A=A, b=b)
        self._slice = slice

    @params_as_tensors
    def __call__(self, X):
        return Linear(self, X[self._slice])
```
