### ISSUE TITLE
`gauss_kl` error when mean has non-static shape

### ISSUE THREAD

**Issue by rhaps0dy** [GPflow/GPflow#725]
When running `gpflow.kullback_leiblers.gauss_kl` on something with shape undefined at graph-building time, such as a `tf.placeholder`, the following happens:
```
TypeError: Value passed to parameter 'out_type' has DataType float64 not in list of allowed values: int32, int64
```
And [this GPflow line](https://github.com/GPflow/GPflow/blob/master/gpflow/kullback_leiblers.py#L73) is the one that causes the error. It seems that tensorflow has different code paths for fully defined and partially defined shapes, see [this Tensorflow snippet](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/array_ops.py#L399-L404).

Minimum failing example:
```python
import gpflow
import tensorflow as tf
import numpy as np

mu = tf.ones([1, 4], dtype=gpflow.settings.float_type)
sig = tf.ones([4, 1, 1], dtype=gpflow.settings.float_type)
mu_ph = tf.placeholder(gpflow.settings.float_type, [1, None])

with tf.Session() as sess:
    print(sess.run(gpflow.kullback_leiblers.gauss_kl(mu, sig)))  # works
    print(sess.run(gpflow.kullback_leiblers.gauss_kl(mu_ph, sig),
                   feed_dict={mu_ph: np.ones([1, 4])}))  # doesn't work
```

Suggested fix:

```python
tf.cast(-tf.size(q_mu, out_type=settings.float_type), dtype=gpflow.settings.float_type)
```

Should I make a pull request?

**Comment by markvdw** [comment]
@hughsalimbeni, you looked at #734, do you think this would solve it?

**Comment by hughsalimbeni** [comment]
Looks like a good fix to me. @rhaps0dy are you happy to do this?
