### ISSUE TITLE
Same code gives Cholesky error on a different machine with CPU

### ISSUE THREAD

**Issue by Joshuaalbert** [GPflow/GPflow#732]
A model runs perfectly fine on my laptop, but when I run it on the same data on a cluster I get failed matrix inversion every time. Both cases its CPU only TF, same version of TF 1.7, identical python environments actually.

I'll describe the model, and if requested I can post it though it's lengthy.
It is SVGP with a custom likelihood that uses a GP to model the noise instead of a scalar variance parameter. The noise GP is constant mean and RBF kernel. I use the reparametrization trick to learn the hyperparrameters of this GP simultaneously. I.e. I draw a sample of the noise GP as minibatching occurs during likelihood calculation. During the sampling of the noise GP, Cholesky decomposition fails on one computer but not the other. 

All input data is scaled to centered unit variance. 
I have tried increasing jitter to 1e-5, 1e-4, 1e-3, and 1. A jitter of 1 must make it posdef!?
On the one computer everything is stable and I can run the same code on all the different datasets I apply it to. 

Computer where is works: Laptop, Fedora 64, i7 Xeon, CPU TF 1.7, python 3.6, gpflow HEAD

Computer where is fails: Cluster, Redhat 7, I think Xeon cores, CPU TF 1.7, python 3.6, gpflow HEAD

**Comment by nrontsis** [comment]
I am just curious - instead of Cholesky you could use `tf.matrix_solve` and `tf.matrix_determinant`. Do they exhibit the same challenges w.r.t. conditioning?

**Comment by Joshuaalbert** [comment]
In my experience those are equally sensitive to conditioning (though usually the log of determinant is numerically less stable compared to sum(log(Tr(L))) ). There are known issues that appear between using GPU and CPU versions of TF, because of the indeterminacy of FLOP order on the GPU, but in this case I'm surprised to find a difference arising between two different CPU's all else the same.

**Comment by markvdw** [comment]
Wow this seems like a bizarre and really frustrating problem. No idea why / how 2 different computers would give such different answers. Could you print out the matrix on both computers and then compare? Perhaps then use bumpy to do the cholesky to investigate whether it's the input or the tf routine that's causing the problem?

This is the approach I used in the past, and I found a bug in tensorflow with it.

**Comment by markvdw** [comment]
Hi @Joshuaalbert, did you manage to figure out the bug? If this can not be reproduced with a model inside the GPflow repo, I'll have to close this, as this is a bug outside our code.

However, do get in touch if it's a more general error.
