### ISSUE TITLE
Matrix multiplication and kernels

### ISSUE THREAD

**Issue by lerkoah** [GPflow/GPflow#737]
Hello,

I'm trying to implement a GP regression with the following kernel:

`K = W^T K_{base} W
`
where `W` is a `nxn` matrix.
I have stored `W` in a numpy array. Is it some way to implement this using gpflow?

Thanks

**Comment by markvdw** [comment]
Yes, you will have to create your own kernel. You can either make `W` a `gpflow.Param` object, and pre and post multiply the resulting K by overriding `kern.K` from the class you want to inherit from, or keep it as a numpy array and then pass it to TensorFlow directly or through `tf.Identity()`.

**Comment by lerkoah** [comment]
Sorry, but I don't understand how to create this kernel in this case. Maybe I abused of notation. In my case the element `i,j` of my covariance matrix `K` have the form:

`K(i,j) = sum_k sum_l W(k,i) K_{base}(k,l) W(l,j)`

```python
class cov_imag_real(gpflow.kernels.Kernel):
    def __init__(self, input_dim, active_dims, W = W.real):
        super().__init__(input_dim=input_dim, active_dims=active_dims)
        self.W = gpflow.Param(W, trainable=False)
        self.Wtranspose = gpflow.Param(W.T, trainable=False)

        
        self.k = gpflow.kernels.RBF(input_dim=input_dim, active_dims=[0])
        self.kern = tf.multiply(tf.multiply(tf.multiply(self.Wtranspose,self.k1),self.k2),self.W)
        
    def K(self, X, X2=None):
        if X2 is None:
            X2 = X
        return

    def Kdiag(self, X):
        return
```

I obtained this error:

```
TypeError: Failed to convert object of type <class 'gpflow.params.parameter.Parameter'> to Tensor. Contents:                               class prior transform  trainable         shape  \
cov_imag_real/Wtranspose  Parameter  None    (none)      False  (2500, 2500)   

                          fixed_shape  \
cov_imag_real/Wtranspose         True   

                                                                      value  
cov_imag_real/Wtranspose  [[0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0....  . Consider casting elements to a supported type.
```
