### ISSUE TITLE
Relating the spectral mixture kernel parameters to their GPflow counterparts

### ISSUE THREAD

**Issue by Brunarspunar** [GPflow/GPflow#739]
I am currently trying to plot the power spectrum of the spectral mixture kernel. I know that the kernel can be constructed in GPflow by a sum of RBF * Cosine kernels, but I am unsure how the four parameters specified in GPflow (Cosine lengthscale and variance, RBF lengthscale and variance) relates to the three parameters ``\mu_q``, ``v_q`` and ``w_q``in the Spectral Mixture kernel definition ([Equation 5 here](http://www.cs.cmu.edu/~andrewgw/typo.pdf) with P=1). Knowing this would help me to put sensible priors on the parameters and also plot the spectrum of the resulting covariance.

**Comment by markvdw** [comment]
You can find this by taking the Fourier transform of the mathematical equation of the squared exponential multiplied by the cosine kernel, and then equating coefficients.

Is there anything specific that you are struggling with?

**Comment by Brunarspunar** [comment]
Hmm, not sure if i got that... But thank you for answering. 

To clearify, my issue is that when I run a scale mixture implementation using a sum of (gpflow.RBF * gpflow.Cosine), I am not sure how to physically interpret the parameters of these kernels. If you have a look at [this paper](https://arxiv.org/pdf/1302.4245.pdf), last paragraph in section 3, you see that the parameters there have a nice physical intuition, but I am not able to relate this to the parameters of the GPflow RBF*Cos kernel product (4 parameters in total vs. 3 parameters in the article). 

It would help a lot if I knew the exact mathematical formulas used in the GPflow implementation of the RBF and Cosine kernels. It varies a lot throughout different libraries.

**Comment by st--** [comment]
You can find the exact formula in the `kernels.py` module, e.g. for RBF: `K(X, X2) = self.variance * tf.exp(-self.scaled_square_dist(X, X2) / 2)`, where `scaled_square_dist(X, X2) = ((X - X2ᵀ)/lengthscales)²`.

**Comment by Brunarspunar** [comment]
I'll have a look at that, thank's for the answer!

**Comment by imsrgadich** [comment]
@st-- isn't those absolute distance rather than scaled square?
