### ISSUE TITLE
update m.X, m.Y become slower

### ISSUE THREAD

**Issue by Jarrome** [GPflow/GPflow#743]
Q: When frequently reset m.X and m.Y by m.X=X and m.Y=Y, this step will takes more time as time goes by. For example, the 500th takes 0.03s, the 1400th takes 0.07s and 1900th takes 0.13s

PS: the number of sample is almost the same.

Why could this happen? How to avoid it?  I will really appreciate the help:)

**Comment by awav** [comment]
@Jarrome ^^^

**Comment by Jarrome** [comment]
Ehhh, sorry, because the project is in urgent, I just change the code to GPy that day though I really appreciate the GPflow. 

Maybe I will post the more detailed test case later. :)

**Comment by markvdw** [comment]
This sounds like the graph is growing. One way to work around this is just to re-create the entire model in a new graph each time. You can make sure you don't lose the parameters by using `assign()` and `read_values()`

**Comment by Brunarspunar** [comment]
@markvdw 
Do you know of an example where assign() and read_values() has been used?

**Comment by markvdw** [comment]
:)

Hope it works. If this is still an issue, feel free to re-open.

**Comment by awav** [comment]
@Jarrome I'm pretty sure, it is not about assignment or reading. Are you using Minibatch or DataHolders inside the model? That's a reason, why MWE is crucial for you and us, we could just check the problem instantly and give you feedback instantly.
