### ISSUE TITLE
Cannot pip install from requirements containing numpy and gpy

### ISSUE THREAD

**Issue by peay** [GPflow/GPflow#744]
`setup.py` starts with `import numpy` (in order to get the paths), and then goes on to express the dependency on `numpy >= 1.7`.

On my clean system with a `requirements.txt` file of the form

```
numpy
gpy
```

running `pip install -r requirements.txt` fails because `numpy` is not yet installed, and thus gpy's `setup.py` cannot be imported: it fails with `ImportError`. I am not familiar enough with `setuptools` and friends to suggest a fix, unfortunately.

This is of course trivially resolved by installing `numpy` before, but this kind of breaks the standard install-from-full-requirements-list workflow, which is pretty useful to populate virtual envs or images.

**Comment by st--** [comment]
Hi @peay, this is the GPflow project, which is independent of GPy. If you've got any GPflow questions, please ask, but I'm afraid we cannot help you with GPy issues!

**Comment by peay** [comment]
Oops, not sure how I missed that -- sorry for the noise!
