### ISSUE TITLE
Implementing Beta-binomial likelihood

### ISSUE THREAD

**Issue by gsVAM** [GPflow/GPflow#750]
First -- I want to sincerely thank @imsrgadich and @hughsalimbeni and the rest of the community for being so generous with the quandaries of newbs like myself.

That said -- I'd like to implement a Beta-Binomial likelihood. I was curious as to how would one get started. I could not find any documentation as to how to create customized likelihoods in GPFlow. 

Any help here will be greatly appreciated.

Cheers!

**Comment by markvdw** [comment]
I think the best way to go about this, is to look at `likelihoods.py`. There, many likelihoods are implemented by subclassing `Likelihood`. Following this template and implementing the correct densities will get you a likelihood which will at least work with numerical quadrature to compute the variational expectations.

Making the documentation better is something which will happen in the near term. Feel free to re-open if you have any more specific questions.
