### ISSUE TITLE
Constraining a parameter using the value of another parameter

### ISSUE THREAD

**Issue by Canas** [GPflow/GPflow#755]
Suppose I have a custom kernel with trainable parameters a and b, which may or may not be scalar:

```
a = 1.0
b = 2.0
param_a = gpflow.params.Parameter(a)
param_b = gpflow.params.Parameter(b)
```

Is there any way I can constrain the value of parameter b to never be lower than the value of parameter a during optimization? I tried using some of the default transforms that allow a lower bound, but it doesn't seem to work as intended, at least not using Powell (I think this idea doesn't talk well with line search, but it's just a guess since I'm not well versed in numerical optimization).

Any ideas would be appreciated :)

**Comment by hughsalimbeni** [comment]
You could define a variable to be the difference, and constrain it to be positive. You mention that it may or not be a scalar, but in the non-scalar care in what sense do you mean less?

**Comment by markvdw** [comment]
Currently transforms can only depend on the value of the parameter they're associated to. We have no immediate plans to implement this, but it is a feature that we bump into occasionally, so it may be implemented in the longer term.
