### ISSUE TITLE
Optimization slows down when redone many times

### ISSUE THREAD

**Issue by tomaskrehlik** [GPflow/GPflow#756]
1. When you rerun optimisation over the same model many times it becomes slower and slower.
2. MWE:
```
opt = gpflow.train.ScipyOptimizer()
mean = gpflow.mean_functions.Constant()
k = gpflow.kernels.Matern52(1) 

x = np.atleast_2d(np.random.rand(100))
y = np.atleast_2d(np.random.rand(100))

m = gpflow.models.GPR(x, y, kern=k, mean_function=mean)

for i in range(100):
    %time opt.minimize(m)
```
3.
    * GPflow 1.1.1
    * Tensorflow version tensorflow==1.7.0
    * No GPU
    * Python 3.6.4
    * macOS

Is there a way how to clean the tf graph easily, it seems to be growing with every iteration.

**Comment by markvdw** [comment]
That is strange. I don't immediately see why the graph should grow with this code.

**Comment by hughsalimbeni** [comment]
I think this is inevitable as the scipy optimizer build a graph each time (https://github.com/GPflow/GPflow/blob/bac97289f9c3194f13729eb6b8531b4c6afcaec8/gpflow/training/external_optimizer.py#L221). If you use the actions framework you can call the optimize operation directly, and not have to rebuild the graph each time

**Comment by Brunarspunar** [comment]
I had a quite similar problem. It was fixed by resetting the graph in each iteration, see the last comment in #719. In your case you will have to reassign the trained parameters from the previous iteration, but I guess that is possible too.

**Comment by markvdw** [comment]
I like @hughsalimbeni's solution. Did you have a one-liner example in mind?

**Comment by awav** [comment]
@tomaskrehlik , Hello! Are you sure that you are using scipy optimizer correctly, maybe you need: `opt.minimize(m, **maxiter=1000**)`? In any case,  you can use `session.run(optimizer.optimize_tensor)`.

**Comment by sanket-kamthe** [comment]
@awav  is the actions framework that @hughsalimbeni  is mentioning documented somewhere ?  I need to actually do the optimisation in the issue where `opt.minimize` needs to be called within a loop (RL loop)

**Comment by kozisek** [comment]
@hughsalimbeni Can the Action framework be used with ScipyOptimizer?

Using it with other optimizers (like AdamOptimizer) does work as a workaround for this problem.

**Comment by awav** [comment]
@kozisek, 
> Can the Action framework be used with ScipyOptimizer?
No.

@sanket-kamthe, @tomaskrehlik 
You have different ways to optimize model:

```
import numpy as np
import numpy.random as rnd
import gpflow

X = rnd.randn(100, 1)
Y = np.sin(X) + np.sin(1.5*X) + 0.3 * rnd.randn(*X.shape)
m = gpflow.models.SGPR(X, Y, gpflow.kernels.RBF(1), Z=X.copy())
```

1. ```gpflow.train.ScipyOptimizer().minimize(m, maxiter=1000)```
2. 
```
import gpflow.actions as actions
adam = gpflow.train.AdamOptimizer(0.01).make_optimize_action(m)
actions.Loop(adam, stop=100)
# or
adam.run(actions.ActionContext(adam))
# or
actions.Loop(actions.Condition(lambda ctx: ctx.iteration % 2, adam), stop=100)
# any many many more examples
```

Caveat: doesn't work with scipyoptimizer, but use trick in next item.

3.  
```
o = gpflow.train.ScipyOptimizer()
o.minimize(m, maxiter=1)
scipyopt_tensor = o.optimizer

for i in range(100):
    gpflow.get_default_session().run(scipyopt_tensor)
```

**Comment by awav** [comment]
More answers in #761. I'm about to close this issue, any objections? @tomaskrehlik, @kozisek, @markvdw, @Brunarspunar?

**Comment by awav** [comment]
@tomaskrehlik, okay, now I got it. In such cases, you are forced to use shared optimizer with one model (as you said it is 3 approach in the list). I'm not sure though, that it is going to work when shape of your data changes.
