### ISSUE TITLE
Implementation Hidden Physics Models

### ISSUE THREAD

**Issue by GJBoth** [GPflow/GPflow#758]
Hi,

I'm working on implementing so-called hidden physics models (see for example https://arxiv.org/abs/1708.00588) in GPflow. I think that this could be implemented as an LMC model, but from what I read this has not been implemented yet in GPFlow. Looking at the code I think I can build my own model to accommodate HPM, but I have a couple questions:

1) To modify the likelihood and predict function, does it really only depend on _build_predict and _build_likelihood functions of the GPR model?
2) Why does _build_likelihood return the reduce_sum? Doesn't multivariate_normal return a scalar?

Separately: can I combine mean functions, e.g. combining a linear with a constant mean function? Or is it more preferable to prescale the data to zero mean?

Thanks in advance!

**Comment by hughsalimbeni** [comment]
The `_build_likelihood ` function is where you put the optimization objective, and if the model gives a Gaussian prediction then `_build_predict functions` is where that should go. If you model gives non-gaussian marginals for the latent function then you'll need to override the autoflow functions, but you can still use `_build_likelihood `.

`_build_likelihood` must returns a scalar. The spurious sum is probably for the sum over the output dimensions.

Mean functions can be combined, but there is no point combining linear with constant as the linear contains the constant part.

**Comment by st--** [comment]
For future such questions please use stackoverflow instead, there's a gpflow tag: https://stackoverflow.com/questions/tagged/gpflow !
