### ISSUE TITLE
how to predict x_* given y_* using GPLVM?

### ISSUE THREAD

**Issue by LuckyTiger** [GPflow/GPflow#762]
I know that GPLVM is a dimension reduction model, but I can't find how to get p(x_{\*}|y_{\*},Y)

**Comment by hughsalimbeni** [comment]
This question doesn't have a very easy answer as it depends on how you want to treat the variational distribution at additional points. The easy way is just to add the new observations and re-optimize everything together. Possibly instead though you want to freeze the existing distribution and optimize just the new point to find q(x_*). Alternatively, you could use a sampling method, which for low dimensional latent spaces might be feasible. This is an inherent difficulty of the model itself, not an issue with GPflow.

**Comment by Willmr** [comment]
As LuckyTiger mentioned, I try to do a similar thing:
Currently, I am using the GPLVM for dimensional reduction. Actually, the modeling was pretty straight forward... No I have the problem, that I would like to apply the trained model (so the training dataset is fixed) to a new sample. 
@hughsalimbeni 
Is this done by the _build_predict function? 
If not, how can I do my prediction?
Thanks for your help
