### ISSUE TITLE
Possible to implement MCMC in VGP models?

### ISSUE THREAD

**Issue by sadatnfs** [GPflow/GPflow#763]
Out of curiosity, will MCMC be implemented in models using VGP (for example, for coregion models)?

**Comment by hughsalimbeni** [comment]
MCMC and VI are different methods and cannot be combined in a straightforward way. See http://papers.nips.cc/paper/5875-mcmc-for-variationally-sparse-gaussian-processes.pdf for one hybrid scheme with a sparse VI approximation. 

MCMC for hyperparameters with a Gaussian VI approximation for the latent function would not be valid unless the global optimum for the VI part was found in an inner loop, and this would be impractically slow (and would not give gradients so couldn't be used with HMC)
