### ISSUE TITLE
Making kernel list for separate GPs in case of multi-output GPs.

### ISSUE THREAD

**Issue by svaibhavsingh** [GPflow/GPflow#765]
I was trying to use separate GPs for a multi-output GP regression case. I was getting the error "ValueError : self references are not allowed".

self.kern = kern
self.kern_list = ParamList([kern]*num_outputs) 
on the third line. 

But when I changed my code to 

self.kern = kern
self.kern_list = [kern]*num_outputs

the error is not there but i was wondering whether both the approach are correct as my model is not learning anything after using the second method of doing things. If not can anyone please suggest to correct the 1st method of doing things.

**Comment by vdutor** [comment]
Hi @svaibhavsingh 
We've been working on supporting multi-output GPs in GPflow.  You can find the branch, which is currently under review, here: https://github.com/GPflow/GPflow/tree/multidispatch_featureconditionals.
Especially the class `gpflow.multioutput.kernels.SeparateIndependentMok` implements the functionality you are trying to achieve. 

I suggest you try to use this branch with the new multi-output classes as lots of work has already been done. As a starting point, check out the explanatory notebook: https://github.com/GPflow/GPflow/blob/multidispatch_featureconditionals/doc/source/notebooks/multioutput.ipynb.

**Comment by sanket-kamthe** [comment]
@svaibhavsingh  the way you are creating list is itself troublesome in python. 

```python
>>> test_list = ['3'] * 5
>>> test_list
['3', '3', '3', '3', '3']
```
All list items are not only identical they are exactly same items repeated 5 times. Just to confirm

```python
[id(item) for item in test_list]
[4459868880, 4459868880, 4459868880, 4459868880, 4459868880]
```

Please correct your code or better use the multi-output code @vdutor mentioned. This now in main.

**Comment by svaibhavsingh** [comment]
@sanket-kamthe thanks for the help. I too did the same thing after checking the multi-output code and it worked. So closing the issue now.
