### ISSUE TITLE
Naming of kernels to change parameters

### ISSUE THREAD

**Issue by fshamout** [GPflow/GPflow#766]
Hi, I'm using GPflow version 1.1.1 with tensorflow 1.8.0.

I am trying to run the basic [tutorial ](http://gpflow.readthedocs.io/en/latest/notebooks/models.html) but I get the following error when I try to change the values of the parameters: 
AttributeError: 'Sum' object has no attribute 'matern32'

the 'sum' object refers to k3, where:

_k1 = gpflow.kernels.Matern12(input_dim=1)
k2 = gpflow.kernels.Linear(input_dim=1)
k3 = k1+k2_

_k3.as_pandas_table()_ shows the following parameters:

**Sum/kernels/0/lengthscales
Sum/kernels/0/variance
Sum/kernels/1/variance**

i.e. the kernels are not automatically named matern12  or linear, and are instead numbered.

I tried changing the name parameter when initiating the kernels, k1 = gpflow.kernels.Matern12(input_dim=1, name='kern_name') but this doesn't change the name of the kernel. 

Has anyone faced similar issues?

**Comment by st--** [comment]
In this case the documentation is out of date, unfortunately... the named access to sub-kernels got removed; you'll now have to do `m.kern.kern_list[0].lengthscales = 0.5` instead -- or `k1.lengthscales = 0.5` if you still have the reference.

**Comment by awav** [comment]
@st-- , as far as I remember in `m.kern.kern_list` kern_list was replaced with `kernels`.

**Comment by st--** [comment]
Yes you are right ... sorry just typing from memory!

**Comment by fshamout** [comment]
I just tested and you need to call **m.kernels[0].**lengthscales=0.5, without the 'kern'.

Thank you both!

**Comment by hjzh4** [comment]
In my case, m.kern.kernels[0].lengthscales = 0.5 works instead of m.kernels[0].

My GPflow version is 1.3.0
