### ISSUE TITLE
Question: Tfdbg with GPFlow

### ISSUE THREAD

**Issue by maximilianmordig** [GPflow/GPflow#769]
Is it possible to use Tfdbg with GPFlow models? I have tried overwriting the enquire_session(), but I am getting problems because the parameterized class checks in the anchor method:
`if not isinstance(session, tf.Session)`.

```
from tensorflow.python import debug as tf_debug
from gpflow import get_default_session
def enquire_session(self, session=None):
    if session is None:
        session = get_default_session()
        session = tf_debug.LocalCLIDebugWrapperSession(session)
    return super().enquire_session(session)
```

**Comment by awav** [comment]
Hello @maximilianmordig, you don't need to override `enquire_session`, you can do:
```
session = get_default_session()
with tf_debug.LocalCLIDebugWrapperSession(session) as sess:
    pass
```

**Comment by maximilianmordig** [comment]
Thanks a lot, that solved it. I finally do:
```
with tf_debug.LocalCLIDebugWrapperSession(model.enquire_session()) as sess:
     opt_method.minimize(maxiter=iterations)
```
It is important to put it after
`model.enquire_session().run(global_step.initializer)` (global_step is associated to the optimizer).
