### ISSUE TITLE
Add **unused_kwargs to likelihood methods now that ndiagquad is used

### ISSUE THREAD

**Issue by Joshuaalbert** [GPflow/GPflow#770]
Given that argument passing is built in to the likelihood quadrature (thanks to #736 ) it makes sense, for posterity, that the method declarations explicitly have keyword placeholders (even if they are unused).

**Comment by st--** [comment]
Hi Joshua, I'm not quite sure what you mean - what method declaration are you referring to, and what is the point of having keyword placeholders if they are unused? I think that is more likely to lead to hard-to-spot bugs - I'd prefer a method to give an error if I give it keyword arguments that it does not know how to handle.

**Comment by Joshuaalbert** [comment]
My thought was that since (https://github.com/GPflow/GPflow/blob/master/gpflow/quadrature.py#L142) passes kwargs `Ys` it might be good in the original  Likelihood method declarations to explicitly state that they are accepted. Not super required. Your right, let the error indicated missing params.
