### ISSUE TITLE
mean functions per output dimension

### ISSUE THREAD

**Issue by kkmann** [GPflow/GPflow#772]
Hi, 
is there currently a way to have different mean functions for different output dimensions (similar to the active_dims feature for kernels?).

**Comment by vdutor** [comment]
Hi @kkmann 
GPflow does not support different mean functions for different output dimensions. 
In case you need it, it should be pretty straightforward to add this:
```python
class MultiOutputMeanFunction(gpflow.mean_functions.MeanFunction):

  def __init__(self, mean_list):
    super(self).__init__()
    self.mean_list = mean_list

  def __call__(self, X):
    return [mean(X) for mean in self.mean_list]
```
The SVGP model should work out of the box with this mean function. Other models will require some tweaking.

**Comment by kkmann** [comment]
Hey, thanks. Good to know that it might work in principle. 

Doesn't work for me quite yet though, `MultiOutputMeanFunction([gpflow.mean_functions.Constant(), gpflow.mean_functions.Constant()])` produces a type error:

```
--------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-39-6cf18c80b183> in <module>()
----> 1 MultiOutputMeanFunction([gpflow.mean_functions.Constant(), gpflow.mean_functions.Constant()])

c:\python\python35\lib\site-packages\gpflow\core\compilable.py in __init__(self, *args, **kwargs)
     84                     break
     85                 frame = frame.f_back
---> 86             origin_init(self, *args, **kwargs)
     87             autobuild_on = __execute_autobuild__ == AutoBuildStatus.BUILD
     88             global_autobuild_on = AutoBuildStatus.__autobuild_enabled_global__

<ipython-input-35-67f3c9ff4bda> in __init__(self, mean_list)
      2 
      3   def __init__(self, mean_list):
----> 4     super(self).__init__()
      5     self.mean_list = mean_list
      6 

TypeError: must be type, not MultiOutputMeanFunction
```

**Comment by vdutor** [comment]
Hi,
you should drop the `self` in the first line of the `__init__`. Be aware that the code snippet above was written out the top of my head and was mainly given to explain the concept. It probably needs some more tweaking. For example, you'll need to use a `stack` operation: 
```python
  def __call__(self, X):
    return tf.stack([mean(X) for mean in self.mean_list], axis=0)
```

In your example, I see that you want to use a `MultiOutputMeanFunction` for two constant mean functions. This is not necessary, you can get the same behaviour using a single one `m = gpflow.mean_functions.Constant(c=np.array([1, 2]))`.

**Comment by kkmann** [comment]
Thx, for sticking with me! 

```
class MultiOutputMeanFunction(gpflow.mean_functions.MeanFunction):

  def __init__(self, mean_list):
    super(MultiOutputMeanFunction, self).__init__()
    self.mean_list = mean_list

  def __call__(self, X):
    return tf.stack([mean(X) for mean in self.mean_list], axis=0)
```

seems to work. However, if I get it right, this will only work for balanced multi output processes, i.e., situations where all outputs are available at the same input locations. I am trying to implement a linear model of co-regularization based on the excellent [example](http://gpflow.readthedocs.io/en/latest/notebooks/coreg_demo.html). The data structure is different (long format with 'augmented X, Y'). So I fear that both methods won't be applicable (`m = gpflow.mean_functions.Constant(c=np.array([1, 2]))`). 
Is that correct?

I need output-specific means to get sensible predictions over large gaps in the respective output dimensions.

**Comment by martiningram** [comment]
Hi,

For anyone trying to get things to work with the [new multi-output framework](https://github.com/GPflow/GPflow/tree/develop/gpflow/multioutput):

I had to change Kevin's code just a little bit, to the following, to get the dimensions to work out:

```python
import tensorflow as tf

class MultiOutputMeanFunction(gpf.mean_functions.MeanFunction):

  def __init__(self, mean_list):
    super(MultiOutputMeanFunction, self).__init__()
    self.mean_list = mean_list

  def __call__(self, X):
    return tf.squeeze(tf.stack([mean(X) for mean in self.mean_list], axis=1))

mean_fun = MultiOutputMeanFunction(mean_functions)
``` 

This appears to optimise OK. I am still working on a version where you can learn the values of the mean functions, too.
