### ISSUE TITLE
UserWarning: Shape of x must be 2D at computation

### ISSUE THREAD

**Issue by ceceha** [GPflow/GPflow#774]
Even if I run the easiest example:
```
N = 12
X = np.random.rand(N,1)
Y = np.sin(12*X) + 0.66*np.cos(25*X) + np.random.randn(N,1)*0.1 + 3
k = gpflow.kernels.Matern52(1, lengthscales=0.3)
m = gpflow.models.GPR(X, Y, kern=k)
```

there is always a warning:
/usr/local/lib/python3.5/dist-packages/gpflow-1.1.1-py3.5.egg/gpflow/logdensities.py:89: UserWarning: Shape of x must be 2D at computation.
  warnings.warn('Shape of x must be 2D at computation.')

tensorflow version:1.8.0
gpflow version:1.1.1
only cpu
python version 3.5
ubuntu 16.04

Could anyone help me?

**Comment by awav** [comment]
@ceceha Hello.
But it works, right?! If you want to turn warning off, just ignore warnings with https://docs.python.org/3.6/library/warnings.html.

Thanks!

**Comment by ceceha** [comment]
It works ~, Thanks! I will close the problem ~

**Comment by farahshamout** [comment]
I tried ignoring the warnings as in the python documentation but it didn't work for me. @ceceha can you show me what you've used? thanks!

**Comment by st--** [comment]
Hi @farahshamout, the warning was a bit stupid really, but it should be removed now in the latest develop branch, and will be replaced by a more useful warning (that only goes off when it's actually relevant!) in #964. We'll publish a new release that includes these fixes soon (@awav). Hope that helps!
