### ISSUE TITLE
notebooks/multiclass.ipynb uses kernels instead of kern_list

### ISSUE THREAD

**Issue by lotka** [GPflow/GPflow#775]
In this notebook, whenever a kernel is being made trainable e.g:
```
m2 = gpflow.models.SVGP(
    X, Y, kern=gpflow.kernels.Matern32(1) + gpflow.kernels.White(1, variance=0.01),
    likelihood=gpflow.likelihoods.MultiClass(3),
    Z=X[::5].copy(), num_latent=3, whiten=True, q_diag=True)

m2.kern.kernels[1].variance.trainable = False
m2.feature.trainable = False
```

`kernels` is not a thing, it should be `kern_list`

**Comment by st--** [comment]
Readthedocs should now be up to date (use "master" or "develop" versions; "latest" is deprecated).
@lotka if you've got any further questions feel free to reopen.
