### ISSUE TITLE
Asymmetric multi-task GP kernel 

### ISSUE THREAD

**Issue by krturnbull** [GPflow/GPflow#782]
Hello,

I am trying to use GPflow to implement a kernel for multi-task GPs. It has the form k(x,y) x B[i,j] with the kernel k(x,y) acting on a single task (ie data indexed only by index i). This is almost what is implemented in the coregionalization example in the docs, however I cannot see how to impose that the kernel k(x,y) does not act on all of the data. 

Is it possible to implement this is GPflow?

Many thanks in advance!

**Comment by hughsalimbeni** [comment]
You can use `active_dims` for this and the kernel will only see the dimensions that you specify.

**Comment by krturnbull** [comment]
Thanks for the quick response.

If I understand correctly, active_dims allows me to change which of the input dimensions my kernel acts on. So if x is d-dimensional I can put different kernels on different dimensions. Is that correct?

If so, I think I want to do something slightly different to this. I am considering fitting a coregionalized GP, say on data (X1, Y1) and (X2, Y2), and I want to specify a kernel which acts only on (X1, Y1). Is this possible?

Once again, thanks for your help!

**Comment by hughsalimbeni** [comment]
Yes you're correct about active_dims. 

GPflow doesn't handle multiple inputs, however (they must always be concatenated into a single X), and I'm not completely clear what the model is here. Could you be more specific?

**Comment by krturnbull** [comment]
Thanks. The kernel I am trying to fit is specified in equation (5) of https://link.springer.com/content/pdf/10.1007%2Fs10994-012-5302-y.pdf . 

The kernel is of the form k^T(t,t') k^p(x,x'), which is just like coregionalisation. However the kernel denoted as k^p(x,x') acts only on a single set of data. For example, if I am fitting a model to jointly model (X1, Y1) and (X2, Y2) then this kernel is only trained on the data (X1, Y1). 

I understand for coregionalisation all the X's and Y's should be concatenated and a column added which indicates which set of data each point belongs to. Instead what I want is to train a kernel on, say, all the data points labelled with an indicator 0.

I hope that is clearer!

**Comment by hughsalimbeni** [comment]
I think you'll need a custom model implementation for this, as if the inputs for each kernel are x, x', and x is shape N,D and x' is shape M,D, then k(x, x') must be shape N,M, but you will have missing entries if you only want certain N and M. Do you have a reference paper for your model? The vanilla coregionalization model assumes all inputs are known for each output. The missing covariate problem is not straightforward as far I am aware (e.g. https://arxiv.org/pdf/1509.01168.pdf)

**Comment by krturnbull** [comment]
The reference paper for this model is 'Focused multi-task learning in a Gaussian process framework', Leen et al 2012 (https://link.springer.com/content/pdf/10.1007%2Fs10994-012-5302-y.pdf) . The kernel I am trying to describe is detailed in section 2.3.1 in equation (5). 

I have that all inputs are known for each output, but I want to train a kernel on a subset of the inputs.

**Comment by aboustati** [comment]
Hello @krturnbull , 

Not sure if you were able to find a solution to your problem, but I have implemented something similar to what you were describing a while ago here: https://github.com/aboustati/dgplib/blob/master/dgplib/specialized_kernels.py

As far I understand, you want a kernel that generates a covariance matrix of the form:

![image](https://user-images.githubusercontent.com/7793553/44057135-292664e4-9f42-11e8-9e31-7d8ab0ad8e19.png)

You can achieve this by specifying the kernels for each dataset and wrapping them around the `SwitchedKernel` object. Here is a simple examples:

```{python}
k1 = gpflow.kernel.RBF(1)
k2 = gpflow.kernels.Constant(1)
k = SwitchedKernel([k1,k2], output_dim=2)
```
Note that your inputs need to be augmented with an index to select the appropriate kernel, in the same way it is implemented for the `Coregion` kernel. This implementation is similar to the `SwitchedLikelihood` object in `GPflow`, hence the name.

**Comment by st--** [comment]
For future such questions please use stackoverflow instead, there's a gpflow tag: https://stackoverflow.com/questions/tagged/gpflow !
