### ISSUE TITLE
multi output sparse GP with different kernels but same inducing points

### ISSUE THREAD

**Issue by gabrielnan** [GPflow/GPflow#783]
I have only recently started working with GPFlow, so my knowledge is limited.

I read that instantiating a GP with a multidimensional output will yield an independent GP for each output dimension, but with the same kernel across the GPs. Also, I could define a completely new GP for each output dimension, and that would allow me to have different kernels with different parameters. But this wouldn't allow me to have the same trainable inducing points (if using SGPR for instance) across all GPs (to my understanding).

So, is there any way I can have independent GPs (one for each output dim) with different kernel parameters but the same inducing points?

**Comment by vdutor** [comment]
Hi @gabrielnan 

You are describing one of the use-cases of the new multi-output GP framework we have been working on lately. You can find the code in the "multidispatch_featureconditionals" branch and an explanatory notebook in `doc/source/notebooks/multioutput.ipynb`.

I assume you will need to do something very similar to this:
```python
import gpflow
import gpflow.multioutput.kernels as mk
import gpflow.multioutput.features as mf

D = 1  # input dimension
P = 2  # output dimension
M = 20  # number of inducing inputs
X, Y = data()   # input and output data

kern_list = [gpflow.kernels.RBF(D) + gpflow.kernels.Linear(D) for _ in range(P)]
kernel = mk.SeparateIndependentMok(kern_list)
feature = mf.SharedIndependentMof(gpf.features.InducingPoints(X[:M,...].copy()))

model = gpflow.models.SVGP(X, Y, kernel, gpflow.likelihoods.Gaussian(), feat=feature)
```
The `mk.SeparateIndependentMok` is a multi-output kernel class which accepts a different kernel for each output (Separate). The `mf.SharedIndependentMof` class is a multi-output feature class that will use the same inducing inputs for every output dimension (Shared). 

Hope this helps,
Vincent

**Comment by gabrielnan** [comment]
This is exactly what I was looking for. Thanks a lot @vdutor!

**Comment by gabrielnan** [comment]
Hi @vdutor,

I checked out the branch, but I think it's broken. When I import gpflow I get the following:
```
Traceback (most recent call last):
  File "/home/gan9/src/packages/GPflow/gpflow/_settings.py", line 32, in __getattr__
    return self._cur_settings[name]
KeyError: 'logger'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gan9/src/packages/GPflow/gpflow/__init__.py", line 27, in <module>
    from . import conditionals
  File "/home/gan9/src/packages/GPflow/gpflow/conditionals.py", line 26, in <module>
    logger = settings.logger()
  File "/home/gan9/src/packages/GPflow/gpflow/_settings.py", line 34, in __getattr__
    raise AttributeError("Unknown setting.")
AttributeError: Unknown setting.
```

**Comment by vdutor** [comment]
Yes, the "multidispatch_featureconditionals" branch is currently under development and not very stable, my apologies. The missing `Logger` class is already in master, so merging in master will solve the issue.

**Comment by gabrielnan** [comment]
Perfect. Thanks again!

**Comment by gabrielnan** [comment]
Okay, so I got it to work with SVGP, but I've been getting the following error when I run `opt.minimize(m)` on an SGPR model:
```
InvalidArgumentError (see above for traceback): In[0] and In[1] has different ndims: [3,20,100] vs. [100,3]
	 [[Node: SGPR-569f204a-18/MatMul_7 = BatchMatMul[T=DT_DOUBLE, adj_x=false, adj_y=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](SGPR-569f204a-18/truediv_9, SGPR-569f204a-18/sub)]]
``` 
here are some relevant dimensions of the data I ran:
X is 100x2
y is 100x3
M = 20 (number of inducing points)

**Comment by vdutor** [comment]
Hi, at this point we only support multi-output features and kernels for the SVGP class. Feel free to make SGPR compatible with the multi-output framework, happy to review your code.
