### ISSUE TITLE
Is there a missing sqrt(2)/2**(d/2) in quadrature?

### ISSUE THREAD

**Issue by Joshuaalbert** [GPflow/GPflow#784]
[In this line](https://github.com/GPflow/GPflow/blob/master/gpflow/quadrature.py#L133) I think there is a missing factor of `sqrt(2)/2**(D/2)`. I'll post some latex snippet to show where.
![screenshot from 2018-06-12 01-34-57](https://user-images.githubusercontent.com/14807032/41262392-dcb95aae-6de0-11e8-8bdf-a9d44c5e72de.png)
In 1D Gauss-Hermite the `sqrt(2)/2**(D/2)` cancel, which might be the source of this error?

**Comment by st--** [comment]
`ndiagquad()` only does 1D quadrature (but for many points simultaneously). That's why it has `diag` in the name...

**Comment by st--** [comment]
Does this apply for diagonal covariances as well? In that case the integrals are all independent 1D. There's a test that checks 2D integration is correct... If you still think the code is wrong, it'd be great if you could write a test that shows that!

**Comment by markvdw** [comment]
It should be easy to do a numerical test for this. We know that the mvnquad should be correct, since it's tested against all kernel expectations, which work :)

**Comment by Joshuaalbert** [comment]
@st-- Yes it holds for diagonal also, the diagonal is just a special case of lower triangular form which is used to make the Gaussian independent. I agree there should be a way to test this. I'll quickly check.

**Comment by Joshuaalbert** [comment]
There is the correct normalization in [the definition of mvnormal](https://github.com/GPflow/GPflow/blob/master/gpflow/logdensities.py#L101) i.e. there is the `(2 pi)**(-D/2)` so numerical checks would be testing against the correct thing if they use `logdensities` definitions.

**Comment by Joshuaalbert** [comment]
Ah, I found my error. I forgot the $sqrt(2)$ in the jacobian gets a power as well. It all cancels out. Numerical test confirms.

![screenshot from 2018-06-12 11-43-36](https://user-images.githubusercontent.com/14807032/41283052-df48be04-6e35-11e8-86a8-ecfb9acc12e6.png)
