### ISSUE TITLE
Adding Changepoint and/or Changewindow kernels

### ISSUE THREAD

**Issue by BracketJohn** [GPflow/GPflow#786]
Hi guys,

I was wondering whether issue #453 might deserve reconsideration.

CPs and CWs add a structural shift/operation to a composited kernel model, that cannot easily be achieved by combining standard kernels. They seem to be non-trivial (an important factor as mentioned by @jameshensman) and see many applications ([>300 results on scholar this year alone](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&as_ylo=2018&q=changepoint+kernel+gaussian+processes&btnG=)).

This also touches https://github.com/GPflow/GPflow/issues/755 as changewindows depend on two offsets `o_1`, `o_2`, and `o_1 < o_2` has to hold, so the parameter `o_1` depends on `o_2` (or the other way around.

Thanks for taking this into consideration and for your awesome project guys!

(also this is more of a(n) suggestion/enhancement/discussion, not an issue)

**Comment by markvdw** [comment]
@BracketJohn Sorry for late response! I think that given the non-trivial nature of combinations of kernels, the best way for this to be considered is for a contribution to be placed in a separate repo for now. We can link to this repo from the GPflow front page, and if it fits within GPflow, we can always merge the repos.

This way the feature can still be developed and shared within the GPflow community, while keeping the codebase lean as discussed in the PR you mention.
