### ISSUE TITLE
Multi-task/outputs GPs

### ISSUE THREAD

**Issue by alexisboukouvalas** [GPflow/GPflow#79]
Hi team,

I am considering implementing in GPflow the following paper as a start to multi-output GPs:
https://papers.nips.cc/paper/3189-multi-task-gaussian-process-prediction.pdf

It's a kronecker product kernel where the between-output correlation is estimated using maximum likelihood.
I had implemented this a while back in Matlab and with autodifferentiation it should be a breeze to implement in GPflow.

Do you think this is worth doing or there are much better approaches out there we should implement instead? I like the kronecker approach because it's so simple and interpretable.

**Comment by jameshensman** [comment]
Hi Alexis,

That paper is exactly a linear model of coregionalization. Essentially it's
a product kernel between k(x, x') and what GPy calls a 'Coregionalization'
kernel. If the tasks are all aligned (i.e. for each input we observe all
tasks), the the kronecker structure can be used for inference.

So, you'd need two separate features to make this work.

1) a coregionalization kernel.
2) a kronecker-structured model object

I would love to see an implementation of 1.

For 2, the structure should be able to handle any separable kernel. I think
it would be great to have a think about what's possible for both GPR and
for MCMC. Here are some useful references:

http://papers.nips.cc/paper/5089-it-is-all-in-the-noise-efficient-multi-task-gaussian-process-inference-with-structured-residuals.pdf
http://jmlr.org/proceedings/papers/v37/flaxman15.pdf

For completeness, I'd also want a variational version, calling @c0g

James.

**Comment by alexisboukouvalas** [comment]
Thanks James,  I will go over the papers and we can discuss the best code design.
