### ISSUE TITLE
Gradients of predictive mean and variance w.r.t. GP hyperparameters

### ISSUE THREAD

**Issue by a5a** [GPflow/GPflow#790]
Hi,

I have seen Issue #527 and PR #247 regarding gradients of the predictive mean and variance w.r.t. the test points X and I am trying to write a function that can evaluate the gradient of the posterior mean and variance w.r.t. the GP's hyperparameters. So far I'm coming across issues that may be relating to how I collect/deal with the GP's hyperparameters I think. I'd appreciate any pointers to get this working! A lot of this is re-using PR #247's code.

I've tried the following:

    def columnwise_gradients(Y, X):
        """
        Copied out of PR #247 
        """
        num_cols = tf.shape(Y)[1]

        def body(old_grads, col):
            g = tf.gradients(Y[:, col], X)[0]
            new_grads = tf.concat([old_grads, tf.expand_dims(g, 2)], axis=2)
            return new_grads, col + 1

        def cond(_, col):
            return tf.less(col, num_cols)

        shape_invariants = [tf.TensorShape([None, None, None]), tf.TensorShape([])]
        grads, _ = tf.while_loop(cond, body, [
            tf.zeros([tf.shape(X)[0], tf.shape(X)[1], 0], settings.float_type),
            tf.constant(0)], shape_invariants=shape_invariants)

        return grads

    class GP_with_gradients(GPR):
        def __init__(self, X, Y, kern, mean_function=None, **kwargs):
            GPR.__init__(self, X, Y, kern, mean_function=mean_function, **kwargs)

        @autoflow((settings.float_type, [None, None]))
        def posterior_df_dx(self, Xnew):
            """
            From PR #247
            """
            pred_f_mean, pred_f_var = self._build_predict(Xnew)
            return columnwise_gradients(pred_f_mean, Xnew), columnwise_gradients(pred_f_var, Xnew)

        @autoflow((settings.float_type, [None, None]))
        @params_as_tensors
        def posterior_df_dtheta(self, Xnew):
            """
            This doesn't work
            """
            fmean, fvar = self._build_predict(Xnew)
            params = tf.reshape(tf.stack(self.trainable_tensors), [-1, 1])
            return columnwise_gradients(fmean, params), columnwise_gradients(fvar, params)

A minimal example showing the code failing is as follows:

    import numpy as np

    x = np.linspace(0, 6, 10)[:, None]
    x_dense = np.linspace(0, 6, 100)[:, None]
    y = np.sin(x) + 1e-5 * np.random.randn(*x.shape)
    y -= np.mean(y)

    kernel = gpflow.kernels.RBF(1)
    m = GP_with_gradients(x, y, kernel)
    m.compile()

    m.posterior_df_dx(x_dense)  # This works
    m.posterior_df_dtheta(x_dense)  # This crashes

And the error message is 

    File "<..>/gp_with_gradients.py", line 122, in posterior_df_dtheta
        return columnwise_gradients(fmean, params), columnwise_gradients(fvar, params)
    File "<..>/gp_with_gradients.py", line 144, in columnwise_gradients
        tf.constant(0)], shape_invariants=shape_invariants)
    File "<..>/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3224, in while_loop
        result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
    File "<..>/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2956, in BuildLoop
        pred, body, original_loop_vars, loop_vars, shape_invariants)
    File "<..>/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2893, in _BuildLoop
        body_result = body(*packed_vars_for_body)
    File "<..>/gp_with_gradients.py", line 135, in body
        new_grads = tf.concat([old_grads, tf.expand_dims(g, 2)], axis=2)
    File "<..>/site-packages/tensorflow/python/ops/array_ops.py", line 201, in expand_dims
        return gen_array_ops.expand_dims(input, axis, name)
    File "<..>/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1943, in expand_dims
        "ExpandDims", input=input, dim=axis, name=name)
    File "<..>/site-packages/tensorflow/python/framework/op_def_library.py", line 528, in _apply_op_helper
        (input_name, err))
    ValueError: Tried to convert 'input' to a tensor and failed. Error: None values not supported.

**Comment by a5a** [comment]
Any thoughts on this issue? Would be great to get some advice on this!

**Comment by hughsalimbeni** [comment]
The problem is that you have done an op (the stack and reshape) to the tensors you want to take the grad of, and so the outputs don't depend on this tensor. I've made this mistake before too. Here's a simple example of the problem 
```python
a = tf.Variable(1.)
b = a
c = tf.identity(a)
print(tf.gradients(b, a))  # what you would expect
print(tf.gradients(c, a))  # None
```

To make the above code work you need to get rid of the stack and reshape. Incidentally, that code will break if the parameters aren't all scalars.

**Comment by st--** [comment]
@hugh I don't see how your example is applicable - both tf.gradients(b, a) and tf.gradients(c, a) evaluate to 1.?

**Comment by hughsalimbeni** [comment]
Ooops: sorry it should be the other way around. I've edited to make more clear. Than @st-- !

**Comment by a5a** [comment]
I see, so the concatenation of the parameters is dropping the dependencies, and so the gradient will be None.

What is the best way going forward to get all the free parameters of a GP model in a single tensor for gradient computations? 

From looking in the code base, I've found multiple options, so I would like to know what the recommended method is:

    Parameterized.params
    Parameterized.non_empty_params
    Parameterized.parameters
    Parameterized.trainable_parameters
    Parameterized.trainable_tensors  # is it this one?
    Parameterized.read_trainables()
    Parameterized.read_values()

**Comment by hughsalimbeni** [comment]
The easiest thing (though not directly compatible with your column-wise code) is to simply get the gradients from `tf.gradients(loss, model.trainable_tensors)` then reshape/stack them afterwards. Alternatively you could make a single parameter and slice out the parameters where you need them, but this would mostly lose all the functionality that gpflow provides.

**Comment by a5a** [comment]
I may have misunderstood your suggestion, so please correct me if I'm wrong:

I'm trying to find dmu/dtheta at locations x_star, where mu is the posterior mean. Does the `loss` term in your response correspond to looping over each mu(x), evaluating the gradient w.r.t. model.trainable_tensors and stacking them into a single vector afterwards? I guess that could work, so I just wanted to be sure that's what you meant.

Cheers!

**Comment by hughsalimbeni** [comment]
Or actually why not something like:
```python
fmean, fvar = self._build_predict(Xnew)  # this is a function of self.trainable_tensors
[np.stack([columnwise_gradients(f, t) for t in self.trainable_tensors]) for f in [fmean, fvar]]
```
This is doing a python loop (i.e. graph building) of the hyperparameters, but there are only three in the above so that's not too bad

**Comment by a5a** [comment]
So I have managed to come up with a solution that doesn't crash, so I thought I'd post my version here in case it is useful for people viewing this thread at a later date. If something obvious needs to be corrected, I'd be happy to know your opinions. 

I ended up looping over hyperparameters, as @hughsalimbeni suggested, and had to make some changes to the gradient computation function to allow for scalar as well as multi-D tensors:


    def elementwise_gradients_theta(Y, theta):
        """
        For a (Nx1) Tensor Y, compute the derivative of each element
        w.r.t  a hyperparameter tensor theta.
        """
        num = tf.shape(Y)[0]

        def body(old_grads, ii):
            g = tf.gradients(Y[ii, :], theta)[0]
            new_grads = tf.concat([old_grads, tf.reshape(g, [1, -1])], axis=0)
            return new_grads, ii + 1

        def cond(_, col):
            return tf.less(col, num)

        shape_invariants = [tf.TensorShape([None, None]), tf.TensorShape([])]
        grads, _ = tf.while_loop(cond, body, [
            tf.zeros([0, tf.size(theta)], settings.float_type),
            tf.constant(0)], shape_invariants=shape_invariants,
                                parallel_iterations=1)

        return grads



    class GP_with_gradients(GPR):
        def __init__(self, X, Y, kern, mean_function=None, **kwargs):
            GPR.__init__(self, X, Y, kern, mean_function=mean_function, **kwargs)

        @autoflow((settings.float_type, [None, None]))
        @params_as_tensors
        def posterior_df_dtheta(self, Xnew):
            """
            Evaluate dfmean_dtheta, dfvar_dtheta at location(s) Xnew
            """
            fmean, fvar = self._build_predict(Xnew)
            dmu = tf.concat([elementwise_gradients_theta(fmean, t)
                            for t in self.trainable_tensors], 1)
            dvar = tf.concat([elementwise_gradients_theta(fvar, t)
                            for t in self.trainable_tensors], 1)

            return dmu, dvar

And the minimum working example from above:

    import numpy as np

    x = np.linspace(0, 6, 10)[:, None]
    x_dense = np.linspace(0, 6, 100)[:, None]
    y = np.sin(x) + 1e-5 * np.random.randn(*x.shape)
    y -= np.mean(y)

    kernel = gpflow.kernels.RBF(1)
    m = GP_with_gradients(x, y, kernel)
    m.compile()

    print([s.shape for s in m.posterior_df_dtheta(x_dense)])  # [(100, 3), (100, 3)]


I'll close the issue once I'm certain the numbers are correct, but thanks everyone for your suggestions up until this point!

**Comment by st--** [comment]
@a5a have you solves this issue in the end ? would be great if you could make a stackoverflow.com question (and answer it yourself, if you want!) so other people can benefit from your learnings: https://stackoverflow.com/questions/tagged/gpflow - thank you :)
