### ISSUE TITLE
Interpretation of Multi-Class

### ISSUE THREAD

**Issue by theogf** [GPflow/GPflow#796]
Hello,

I would like to use the Multi-Class likelihood on the SVGP model. However I noticed that neither in the notebooks or the docs you precise how to recover the mapping from the different classes in the model to the labels of the data. The results of the prediction are therefore completely non interpretable for test data. Or did I miss something?

**Comment by hughsalimbeni** [comment]
It's the robust max likelihood, and  more details can be found in the following:

[31] M. Girolami and S. Rogers. Variational Bayesian multinomial probit regression with Gaussian process
priors. Neural Comp., 18:2006, 2005.

[32] H. Kim and Z. Ghahramani. Bayesian Gaussian Process Classification with the EM-EP Algorithm. IEEE
TPAMI, 28(12):1948–1959, 2006.

[33] D. Hernandez-Lobato, J. M. Hern ´ andez-Lobato, and P. Dupont. Robust multi-class Gaussian process ´
classification. In NIPS, pages 280–288, 2011.

These references were copied from http://papers.nips.cc/paper/5875-mcmc-for-variationally-sparse-gaussian-processes.pdf, which is the basis for much of the gpflow code.

**Comment by hughsalimbeni** [comment]
I should add that it's easy to interpret the probabilities, conditioned on the latent function: the probabilities are just 1-esp (for the largest) or e/(K-1) (all the others). Perhaps this doesn't seem all that nice compared to the softmax, where the probabilities are just the sortmax of the function values. When the integral is taken over the latent functions it's not so clear, however, as it depends on the mean and the variance of each function (as is also the case for the softmax: though in that case just using the mean for each function might give something sensible, whereas for the robustmax it certainly doesn't)

**Comment by theogf** [comment]
Thanks for the fast answer. My question is actually a lot more practical ^^. When using predict_y(X_test).
I will get arrays of probability (here computed through RobustMax). But how do I know which index of the array is attributed to which class? I tried to investigate the code, but I could not find this mapping anywhere.
For example, for a problem with 3 classes (let's say A B and C), when I compute `p, _ = predict_y(x)` a single test point. To which class refers p[0] ?

**Comment by hughsalimbeni** [comment]
Oh I see: Sorry I totally misunderstood your question!

For the multiclass likelihood the classes must be labelled as 0, 1, ...K-1, which correspond to the indices of the output (i.e. p(y=k) = p(y)_k).  In a previous version of the code there was check to make sure that users didn't accidentally use 1, ..., K indexing, but the current code doesn't do this. If you pass A, B, C for the Y values it won't work properly (though might fail silently. I haven't tried)

Also, for Bernoulli the positive class must be labelled 1 and everything else is the other class.

**Comment by theogf** [comment]
Ah now I get it, the example is indeed doing it, but I did not understand it was a rule, thanks for the clarification.

Cheers,
