### ISSUE TITLE
ScipyOptimizer initial values

### ISSUE THREAD

**Issue by chdamianos** [GPflow/GPflow#797]
I would like some help on changing the default initial values of the ScipyOptimizer

In the example below I'm optimizing a GP regression model using ScipyOptimizer where I can set the method used by the optimizer as 'L-BFGS-B'.
```python
import gpflow
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(1)

x=np.linspace(5,10,num=100)[:,None]
y=10*np.sin(x)+np.random.normal(loc=0.0,scale=1.0,size=x.shape)

modelGPflow=gpflow.models.GPR(x,y,kern=gpflow.kernels.RBF(1))
optimizer=gpflow.train.ScipyOptimizer(method='L-BFGS-B')
optimizer.minimize(modelGPflow) 
```
If I try to pass initial values for the hyperparameters (kernel lengthscale, kernel variance and likelihood variance) I get the error  "TypeError: minimize() got multiple values for argument 'x0'" 
```python
optimizer=gpflow.train.ScipyOptimizer(method='L-BFGS-B',x0=[1.,2.,3.])
optimizer.minimize(modelGPflow)
```
From what I understand this is because GPflow is already passing initial values to ScipyOptimizer. These values are visible using the initializable_feeds attribute of the GPflow model. 
```python
print(modelGPflow.initializable_feeds)
{<tf.Tensor 'RBF-731bd712-30/variance/initial_unconstrained_value:0' shape=() dtype=float64>: 0.5413232726357509, <tf.Tensor 'RBF-731bd712-30/lengthscales/initial_unconstrained_value:0' shape=() dtype=float64>: 0.5413232726357509, <tf.Tensor 'GPR-4c669434-37/likelihood/variance/initial_unconstrained_value:0' shape=() dtype=float64>: 0.5413232726357509,...}
```
I'm not sure how to modify these initial parameter values. Is possible to set these initial optimization values before optimizing the GPflow model? 

Thanks

GPflow 1.1.1
Tensorflow 1.8.0
Python 3.6.5 
No GPU
Windows 10

**Comment by hughsalimbeni** [comment]
You can set the values on the model directly. I.e. you can do `model.kern.lengthscale = 2`

**Comment by chdamianos** [comment]
@hughsalimbeni thanks changing the parameters as you suggested results in changes of the initial parameters passed to the optimizer, but they are not exactly the same as the ones I'm setting. 
For example if I change the parameters to:
```python
modelGPflow=gpflow.models.GPR(x,y,kern=gpflow.kernels.RBF(1))
modelGPflow.kern.lengthscales=2.5
modelGPflow.kern.variance=11.2
modelGPflow.likelihood.variance=100.0
```
when I run the optimiser I noticed that the values passed to the optimiser at .\training\external_optimizer.py lines 162-163 
```python
    # Get initial value from TF session.
    initial_packed_var_val = session.run(self._packed_var)
```
are slightly different 
```python
array([99.999999  ,  2.41434843, 11.19998533])
```
Is this just a rounding error?

**Comment by hughsalimbeni** [comment]
This is the difference between the `_unconstrained_tensor` (which is what actually get optimized and can take any value) and the `_constrained_tensor` (which is the value after gpflow applies the transform, e.g. positive, and in this case it's the softplus which tends to the identity, so the larger values the closer the two become). 

NB you're printing an underscored variable, which is not intended to be accessed by users. In this case the underlying parameter values are deliberately kept hidden as it can be very confusing.

**Comment by chdamianos** [comment]
@hughsalimbeni  thanks for the clarification
