### ISSUE TITLE
Treating fixed values as placeholder rather than constants

### ISSUE THREAD

**Issue by alexisboukouvalas** [GPflow/GPflow#80]
This is something that has been bugging me with GPflow, namely how fixed parameters are treated.

if you have a param.fixed = True then during 
_compile-> make_tf_array
it is added in the graph as a tf.constant (see Param:make_tf_array)
However if we want to do somethings like
m.kern.param.fixed=True
m.kern.param = 2
m.optimize() -> this will trigger a compile that adds a constant
if we now do
m.kern.param = 3 this will also trigger a compile during the next optimize (see Param.setattr)
m.optimize()

However tensorflow offers another mechanism that will save some computation, namely placeholders.
As we have the free state, we could have a fixed state.
When _compile gets called it creates tf.Variables for the former and tf.PlaceHolders for the latter.

Then in our above scenario, recompilation would not be needed.
Note that this would apply to transforms and priors as well (for example we want to return the optimization with different limits on the logistic transform).

This will be only important when cost of recompilation is high, that is in complex models with large graphs.
Also note that by avoiding recompilation we do not pollute the default graph space in tensorflow with  redundant graphs.

Perhaps this is not that important at this point but wanted to bring it to your attention for comments.

**Comment by alexisboukouvalas** [comment]
@jameshensman, @alexggmatthews  let me know if I should close. 
My thinking here is why we are not use the tensorflow placeholders in GPflow but perhaps as compile time is not such a big issue, we can forget about it. This is also related to the serialisation work #56

**Comment by alexisboukouvalas** [comment]
Okay I have been thinking about this a bit more, and I will try the following experiment in the near future:
GPflow, construct fixed_state in additiont to free_state. 
Then pass in fixed_state to graph via placeholders (feed_dict).

Compare performance to current approach on tests as well as scripts that update fixed state variables, for e.g. for i in range(1000)
	m.kern.bias = i
	m.predict()

Note this is scenario may be important when doing Bayesian optimisation to learn some of the model parameters and the others are learned by gradient optimisation.
This is exactly the case for the branching model I am developing with @jameshensman 

Let me know if you think this is not a sensible or worthwhile approach.

**Comment by jameshensman** [comment]
I think this is a sensible plan, happy to accept it if the solution turns out to be clean.

**Comment by jameshensman** [comment]
We're working on a fix for this over in #105 with @fujiisoup .

**Comment by alexisboukouvalas** [comment]
Fixed in #105.
