### ISSUE TITLE
Adding numerical stability to low triangular transform

### ISSUE THREAD

**Issue by Joshuaalbert** [GPflow/GPflow#800]
@markvdw Currently, the default [LowerTriangular](https://github.com/GPflow/GPflow/blob/master/gpflow/transforms.py#L315) transform does no scaling of the rows of L.
This has an impact on the numerical stability.
To see this, imagine you have lower triangular matrix of `[N,N]`. 
If the elements of `L` are zero mean, unit variance, then the n-th diagonal of `C=L.L^T` will scale as `n`.
This is not good for numerical performance if you have for example N=1000, as lower row elements will need to be made very small to cope with this scaling factor.
See the MVCE

# MVCE
``` python
import numpy as np
import pylab as plt
N=100
triu = np.triu_indices(N,1)
L = np.random.normal(size=[N,N])
L[triu] = 0.
plt.imshow(L)
plt.show()
C = L.dot(L.T)
plt.imshow(C)
plt.show()
var = np.diag(C)
# This variance scales as sum_i L_ii^2 \propto row^2
plt.plot(var)
plt.show()

scale = np.diag(1./np.sqrt(np.arange(1,N+1)))
L = scale.dot(L)
plt.imshow(L)
plt.show()
C = L.dot(L.T)
plt.imshow(C)
plt.show()
var = np.diag(C)
# This variance is uniformly 1
plt.plot(var)
plt.show()
```
As you can see the simple fix is to introduce a scaling:
``` python
scale = np.diag(1./np.sqrt(np.arange(1,N+1)))
L = scale.dot(L)
```

# Some helpful code
Here are some tensorflow equivalents to the current numpy based LowerTriangular:
``` python
def tri(N, M=None, k=0, dtype=tf.int32):
    """
    An array with ones at and below the given diagonal and zeros elsewhere.
    Parameters
    ----------
    N : int
        Number of rows and cols in the array.
    dtype : dtype, optional
        Data type of the returned array.  The default is float.
    Returns
    -------
    tri : ndarray of shape (N, M)
        Array with its lower triangle filled with ones and zero elsewhere;
        in other words ``T[i,j] == 1`` for ``i <= j + k``, 0 otherwise.
    """

    arange = tf.range(N,dtype=tf.int32)
    m = tf.greater_equal(arange[:,None],arange[None,:])
    
    return tf.cast(m,dtype)

def nonzero(idx):
    return tf.where(tf.not_equal(idx,False))

def tril_indices(n):
    """
    Return the indices for the lower-triangle of an (n, n) array.
    Parameters
    ----------
    n : int
        The row dimension of the arrays for which the returned
        indices will be valid.
    Returns
    -------
    inds : tuple of arrays
        The indices for the triangle. The returned tuple contains two arrays,
        each with the indices along one dimension of the array.
    """
    return nonzero(tri(n, dtype=tf.bool))

def vec_to_tri(vectors, N):
    """
    vectors: Tensor [batch, (N*2 + N)/2.]
    Returns lower triangular form:
    Tensor [batch, N, N]
    """
    indices = tril_indices(N)

    def vec_to_tri_vector(vector):
        return tf.scatter_nd(indices=indices, shape=[N, N], updates=vector)

    return tf.map_fn(vec_to_tri_vector, vectors)

def tri_to_vec(tri, N):
    """
    tri: [batch, N, N]
    N: int
    Return the packed version of tri
    """
    indices = tril_indices(N)
    def tri_to_vec_vector(tri):
        return tf.reshape(tf.gather_nd(tri,indices), ((N**2 + N) // 2, ))
    return tf.map_fn(tri_to_vec_vector, tri)

def scale_L(L, N):
    """
    Scale L such so that the row space uniformly square sums
    L: [batch, N, N]
    N: int
    """
    scale = tf.diag(1./tf.sqrt(tf.range(1,N+1,dtype=tf.float32)))[None,:,:]
    return tf.einsum("knm,kml->knl",scale,L)

def test_tri():
    with tf.Session(graph=tf.Graph()) as sess:
        assert np.all(sess.run( vec_to_tri(tf.range(10)[None,:],4)) == np.array([[0,0,0,0],[1,2,0,0],[3,4,5,0],[6,7,8,9]]))
       
```

**Comment by markvdw** [comment]
Hi @Joshuaalbert 

It looks like there are 2 contributions here. Firstly the question of initialising L, and secondly, a TF version of `LowerTriangular`.

For the first one, the code perfectly illustrates the point, but I'm not sure that changing the default behaviour is the answer. Considerations:
- In GPflow, we usually initialise L to be an identity matrix, since (at least when whitened) this corresponds to initialising at the prior. Why are you initialising with N(0, 1)?
- Even with the scaling you suggest, the statistics of the diagonal do still change with the position along the diagonal (the variance seems to decrease?)
- This is more of a question than a consideration, but I wonder how the diagonal of an optimised L behaves. Does the scale also increase / drop off? Not sure. Maybe an initialisation should follow this?

Currently, I'm not convinced that the behaviour you describe would work well for the common use-cases in GPflow (but I'd be happy to consider this more!).

As for the TensorFlow-ification of `LowerTriangular`, this would be super useful! Maybe your ideas could help improve #794? Feel free to get involved with the discussion :)

**Comment by Joshuaalbert** [comment]
Thanks for feedback, I'll answer in order.

1) Let me first say the moment where I had this thought. The situation I was imagining was that of a function approximator like a neural network providing the L matrix, in the case where the output is  random and approximately unit variance normal. In the diagonal initialization case this phenomenon is not immediately noticeable because all off diagonals are zero, but if they gain non-zero value then it seems plausible that at least some scaling may occur. `L_ij~N[0,1]` is probably not a good assumption though.

2) The average shouldn't change. It simply comes from the definition after carrying out the matrix multiplication,
```
C_ii = sum_j=1^i L_ij^2
for L_ij~N[0,sigma^2]
E[C_ii] = i sigma^2
```

3) I think it's worth looking into the optimal solution of `q_sqrt` as an empirical investigation might right away say if there is any reason looking further into this.

At least when you look at the `L` diagonal for a simple 1D covariance you see it decreases from by index. The offdiagonal terms are small compared to the diagonal though so the scaling is not as drastic as `1/sqrt(row)`.

``` python
from scipy.spatial.distance import cdist
import numpy as np
import pylab as plt

def K (X,X2):
    return np.exp(-0.5*cdist(X,X2,metric='seuclidean'))

X = np.random.normal(size=1000)[:,None]#np.linspace(-1,1,100)[:,None]

C = K(X,X)
L = np.linalg.cholesky(C)

plt.plot(np.diag(L))
plt.show()
```
I looked into #794 and it seems that my use of map_fn would be less optimal and also not work with TF-distributed (I'm not sure why map_fn shouldn't work in this case unless it calls py_func ops).

**Comment by st--** [comment]
@Joshuaalbert did you actually look into this further? If so, I'd be very curious to hear your findings - and please re-open this issue if you think it is something that WOULD actually be worth changing! Thanks :)
