### ISSUE TITLE
GPFlow_Monitor in Action interface

### ISSUE THREAD

**Issue by maximilianmordig** [GPflow/GPflow#805]
Is all of GPFlow_Monitor already integrated into the action interface? 
I cannot find any implementations in the action interface of the classes like "StoreSession" or "ModelTensorBoard" that are implemented in gpflow_monitor.

**Comment by vdutor** [comment]
Have a look in here: https://github.com/GPflow/GPflow/blob/master/gpflow/training/monitor.py.
Most (probably all) functionality of gpflow_monitor is ported to the new monitoring framework. A couple of classes got renamed in the process.
`ModelTensorBoard` -> `ModelToTensorBoardTask`
`StoreSession` -> `CheckpointTask`
