### ISSUE TITLE
How is it possible to get *positive* log_likelihoods? [discussion]

### ISSUE THREAD

**Issue by dgilford** [GPflow/GPflow#808]
Hi there,

New to GPflow and Gaussian-process modeling in general. I've noticed something with my training where I can sometimes optimize my hyperparameters and find *positive* log_likelihoods. I haven't noticed this for many models, but for some fits I find it.

e.g. I get the message.

`INFO:tensorflow:Optimization terminated with:`
  `Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'`
  `Objective function value: -17.656434`
  `Number of iterations: 7`
 ` Number of functions evaluations: 12`

And then with:

`m.compute_log_likelihood()`
I get the return
`17.6564349273`

Maybe its something I'm fundamentally misunderstanding about what the optimizer is doing, but I thought if you are taking the log of a probability the return should always be less than 1? Then I checked Rasmussen and Williams (2006) and find that the green line in their Fig. 5.3b actually does seem to go above 1.0... but under what conditions is this possible?

I've looked elsewhere and there are some online discussions that sometimes a constant is added to the log-likelihood which can push it over 1. Is this the case in GPflow? I've scoured the code and can't seem to find the relevant lines.

Thank you for any insight you can provide. Sorry if this is a simplistic question, all of this is quite new to me.

**Comment by hughsalimbeni** [comment]
The key distinction here is between continuous and discrete probability distributions. To use the scipy nomenclature: for continuous distributions we say probability density, which can be any positive value but must integrate to one, and for discrete variables we say probability mass, which must be between 0 and 1. For models with continuous outputs the log likelihood can be any real number. 

Gpflow does not add a constant to the log likelihood.
