### ISSUE TITLE
VGP model cannot cope with updating training data

### ISSUE THREAD

**Issue by beangoben** [GPflow/GPflow#809]
# VGP data update crashing

## Bug case

1. One a VGP model has been fitted with data, changing the data will give a "Matrix size-incompatible:" error. This is related to #617, but I tried that patch and it still does not work. The behavior is inconsistent since GPR, SGPR and SVGP do work correctly. Here is an example that shows it working for SVGP and VGP.
2. Code example:. 
```
import gpflow
from sklearn.datasets import  make_classification
from sklearn.model_selection import train_test_split
from scipy.cluster.vq import kmeans

# make dataset
X, Y = make_classification(n_features=2, n_redundant=0, n_informative=2, n_clusters_per_class=1)
Y = Y.reshape(-1,1)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=.5)
Z = kmeans(X_train, 10)[0]
# make models
model1 = gpflow.models.SVGP(X, Y, kern=gpflow.kernels.RBF(2),likelihood=gpflow.likelihoods.Bernoulli(), Z=Z)
model2 = gpflow.models.VGP(X, Y, kern=gpflow.kernels.RBF(2),likelihood=gpflow.likelihoods.Bernoulli())
# opt
gpflow.train.ScipyOptimizer().minimize(model1, maxiter=20)
gpflow.train.ScipyOptimizer().minimize(model2, maxiter=20)
#change data
model1.X = X_train
model1.Y = Y_train
model1.predict_y(X_test)
#change data
model2.X = X_train
model2.Y = Y_train
model2.predict_y(X_test)
```

**Comment by st--** [comment]
@beangoben the VGP behaviour is inconsistent, but hard to change as it is. In contrast to GPR, SGPR, and SVGP, the VGP model contains *parameters* that directly correspond to the training data - for N data points, q_mu and q_sqrt must have shape [N, L] and [L, N, N], respectively (where L = num_latent, usually 1). If you change X and Y to have a different number of data points, then the shapes of the matrices becomes inconsistent as you noticed. We cannot automatically change the size of q_mu and q_sqrt as they are tensorflow variables that are tied down in the tensorflow graph (this will become easier with tensorflow eager mode and gpflow2). However, you can reuse the same model if you call `model.clear()` to reset all parameters, followed by `model.compile()` to build the tensorflow graph afresh.
