### ISSUE TITLE
Parallelization of the training of multiple GP models. 

### ISSUE THREAD

**Issue by mehdiserfoufou** [GPflow/GPflow#815]
Hello,
I just recently discovered GPflow and now i'm using it in the context of simple regression problems. So firstly i would like to thank you for the hardwork to develop this implementation of gaussian processes. 

I want to know if it is possible to parallelize multiple training of different GP models. For example, i want to make a cross validation with 5 folders which creates 5 GPs each with its own training dataset. So it will be efficient to launch the training of the 5 different models in parallel since they are independent. So, i used an embarrassingly parallelization with joblib for the optimization of the 5 models that returns the RMSE of each one:

`Parallel(n_jobs=num_cores)(delayed(CV_train)(X,Y,train_index,test_index) for train_index, test_index in kf.split(X))`
Where CV_train is the function that instantiates and optimize the models.

```
def CV_train(X,Y,train_index,test_index,layers,q):
    X_train, X_test = X[train_index], X[test_index]
    Y_train, Y_test = Y[train_index], Y[test_index]
    model = make_model(X_train,Y_train)
    gpflow.train.ScipyOptimizer().minimize(model)
    return compute_MSE(model,X_test,Y_test,layers)
```

So, sometimes i get the cross validations while sometimes an error is raised : _BrokenProcessPool: A process in the executor was terminated abruptly while the future was running or pending._

I am sure that it is not the best way to parallelize since each training uses the same gpu and that joblib parallelizes on the cpu. Is there a better way to parallelize the training of these different model using tensorflow? 

Thank you
Sincerly

**Comment by hughsalimbeni** [comment]
If your jobs really are parallel then the easiest thing is just to fire them all off in separate processes. You can then set the gpu memory limit to 20% so all 5 will fit (though be aware that this does reduced the speed of each one quite substantially, at least in my experience). I tend to make use of the monitoring framework to setup a tensorboard, which makes running many experiments in parallel much more manageable.

If you want to run 5 experiments in parallel in the _same tensorflow session_ then this is less straightforward. I've never done this myself, but one thing I guess you could do is call the ops of several optimizers at once:

```python
op1 = Optimizer().make_optimize_tensor(model1, session=sess)
op2 = Optimizer().make_optimize_tensor(model2, session=sess)

op = tf.group([op1, op2])

for _ in iterations:
    sess.run(op)
```

The above wouldn't work for a scipy optimizer, however.

I doubt that using a multithreading lib with tensorflow is straightforward, but the place to look for such things is on the tensorflow repo, not here. If it can be done in tensorflow, it can almost certainly be done in gpflow, too.

**Comment by Joshuaalbert** [comment]
Because the OP is interested in CV, I'll post here how I like to do my CV.
Personally, I like to do my cross validation by subclassing `sklearn.base.BaseEstimator` and using `sklearn.model_selection.cross_val_score`. `cross_val_score` will automatically parallelize the process. 

``` python
from sklearn.base import BaseEstimator

class Estimator(BaseEstimator):
    def fit(self, X, y=None, **params):
        """
        Traina this model.
        X : array (N, ...) the input data, float32 
        y: array (N, ...) the prediction data, float32 or int32
        **parms passed at training
        """
        self.sess = tf.Session(graph=tf.Graph())
        with self.sess.as_default(), self.sess.graph.as_default():
            self._build_train_graph()
            self._exectute_training() # -> saves the model perhaps using a callback

    def score(self,X,y=None):
        """
        Score the model.
        X: array-like (N,...) the test input data, float32
        y: array-like (N, ..) the test predictions, float32, int32
        Returns:
            Score, float32
        """
        with self.sess.as_default(), self.sess.graph.as_default():
            #self._build_eval_graph() # not needed here unless you saved model and want to reload, or something. Usually, self.sess still contains all the things required to make the evaluation
            return self._execute_score()

    def _build_train_graph(self):
        """
        Build the train graph.
        Returns:
            TF graph
        """
        raise NotImplementedError("Must subclass")
    def _build_eval_graph(self):
        """
        Build the eval graph.
        Returns:
            TF graph
        """
        raise NotImplementedError("Must subclass")
    def _execute_training(self):
        """
        Train
        """
        raise NotImplementedError("Must subclass")
    def _execute_score(self):
        """
        Score
        Returns: float32
        """
        raise NotImplementedError("Must subclass")
```
I then make a benchmark class that you can feed estimators and a data generation method,
``` python
from ..estimators.estimator import Estimator
from sklearn.model_selection import cross_val_score
import os
import numpy as np
import logging
logging.basicConfig(format='%(asctime)s %(message)s')

class Benchmark(object):
    def __init__(self,run_dir,models,model_names):
        self.run_dir = os.path.abspath(run_dir)
        os.makedirs(self.run_dir,exist_ok=True)
        if not isinstance(models,(tuple,list)):
            models = [models]
        if not isinstance(model_names,(tuple,list)):
            model_names = [model_names]
        for m in models:
            assert isinstance(m,Estimator)
        self.models = models
        self.model_names = model_names
        assert len(self.models) == len(self.model_names)
        
    def data_gen(self):
        """
        Generates all data.
        Returns:
            X, y of full dataset
        """
        raise NotImplementedError("Must subclass")

    def run(self,folds=3,n_jobs=1,fit_params={}):
        """
        Train each model on the same data, then save the results.
        """
        X, y = self.data_gen()
        scores = []
        for model, model_name in zip(self.models,self.model_names):
            model_dir = os.path.join(self.run_dir,"models",model_name)
            fit_params.update(
                {"model_dir":model_dir,
                       "model_name":model_name})
            logging.warning("=== New Model ===")
            logging.warning("Running {} {}-fold CV in {}".format(model_name, folds, model_dir))
            scores.append(cross_val_score(model,X, y,fit_params=fit_params,cv=folds,n_jobs=n_jobs,))
            logging.warning("{} {}-fold results: {} +/- {}\n\t{}".format(model_name, folds, np.mean(scores[-1]), np.std(scores[-1]), scores[-1]))
        logging.warning("=== Benchmark results ===")
        logging.warning("=========================")
        for score, model_name in zip(scores, self.model_names):
            logging.warning("{} {}-fold results: {} +/- {}\n\t{}".format(model_name, folds, np.mean(score), np.std(score), score))
```

**Comment by st--** [comment]
@mehdiserfoufou this type of question is more suitable to stackoverflow than github issues, as posting on stackoverflow means other users in the future are more likely to find the answers as well! see https://stackoverflow.com/questions/tagged/gpflow
