### ISSUE TITLE
Request for zero inflated Gaussian process regression

### ISSUE THREAD

**Issue by chdamianos** [GPflow/GPflow#817]
Apologies for not keeping with the issues template but this is a feature request. 

I was wondering whether you could include zero inflated Gaussian process regression in GPflow. 
Pashupati Hegde has already written code for implementing these models in GPflow version 0.4.0 (https://github.com/hegdepashupati/zero-inflated-gp). There is also a recent publication going over the models P. Hegde, M. Heinonen, and S. Kaski, “Variational zero-inflated Gaussian processes with sparse kernels,” ArXiv180305036 Stat, Mar. 2018. (https://arxiv.org/pdf/1803.05036.pdf).

**Comment by hughsalimbeni** [comment]
This is beyond the scope of gpflow, but there could be a link to an external project at https://github.com/GPflow/GPflow#projects-using-gpflow if there is an up-to-date implementation using gpflow>1.

**Comment by chdamianos** [comment]
thanks for the quick reply. 
I hope the project gets updated and added to your external projects list.
