### ISSUE TITLE
Shape issues with multioutput kernels

### ISSUE THREAD

**Issue by kekeblom** [GPflow/GPflow#818]
I have some questions regarding the `independent_interdomain_conditional` function in the multioutput module. 

I'm dealing with a case where I have a multiple output kernel and several independent GPs with separate inducing points. In this case the variables will have the following shapes:

`Kmn: M x L x N x P`
`Kmm: L x M x M`
`Knn: N x P (or P x N x N for full_cov case)`
`f: M x L`
`q_sqrt: L x M x M`

If `full_cov = False` and `full_ouput_cov = False` and `white = False`, `Ar` will have shape `(L, M, N, P)` as explicitly reshaped on line 311. Now on line 327 (link below) the code will crash as `Lm` will have rank 3 and `Ar` rank 4. The comment seems to be wrong as well. 

https://github.com/GPflow/GPflow/blob/54a276ab92ead568e969c7f073694b12bd8124e1/gpflow/multioutput/conditionals.py#L327

The problem might be fixed by replacing `Ar` with `A` on that line. However, then the output will have shape `(N * L, P)`. Shouldn't the mean and variance have shape `(N, L * P)` in this case?

Am I thinking about this the wrong way?

**Comment by awav** [comment]
@kekeblom, could you post MWE?

**Comment by kekeblom** [comment]
```
import gpflow
import tensorflow as tf
import numpy as np
import observations
from gpflow.multioutput.conditionals import independent_interdomain_conditional

(Xtrain, Ytrain), _ = observations.mnist('/tmp/mnist')
Xtrain -= Xtrain.mean(axis=0)

Zs = [np.random.randn(32, 392) for _ in range(2)]
rbf = gpflow.kernels.RBF(392)

def compute_Kmn(Z, X):
    X1 = X[:, 0:392]
    X2 = X[:, 392:]
    return tf.stack([
        rbf.K(Z, X1),
        rbf.K(Z, X2)
    ])

def compute_Knn(X):
    X1 = X[:, 0:392]
    X2 = X[:, 392:]
    return tf.stack([
        rbf.Kdiag(X1),
        rbf.Kdiag(X2)
    ])

batch = Xtrain[0:10]
# L = 2, P = 2, N = 10, M = 32
Kmm = tf.stack([rbf.K(Z) for Z in Zs]) # L x M x M
Kmn = tf.stack([compute_Kmn(Z, batch) for Z in Zs]) # L x P x M x N
Kmn = tf.transpose(Kmn, [2, 0, 3, 1]) # -> M x L x N x P
Knn = tf.transpose(compute_Knn(batch)) # N x P
q_mu = np.zeros((32, 2))
q_sqrt = np.stack([np.eye(32) for _ in range(2)])

mean, var = independent_interdomain_conditional(Kmn, Kmm, Knn, q_mu, q_sqrt=q_sqrt, full_cov=False, full_output_cov=False)
```

So in this case we have two independent gps with separate inducing points. Two kernels which use different subsets of the input.

**Comment by Joshuaalbert** [comment]
This is a repeat (or very similar to) of #819

**Comment by st--** [comment]
@kekeblom thanks for bringing this to our attention, and apologies for the long delay - it turned out to be a bug in our code indeed! I had to slightly edit your example to make it "work" (fail for the right reason), and fixed it in #818.

**Comment by st--** [comment]
@kekeblom thanks again for the bug report, late but better late than never, it's finally fixed!

**Comment by kekeblom** [comment]
Kudos on having a watertight process! Most other projects would have probably dropped the ball at some point during those couple years.
