### ISSUE TITLE
TensorFlow 2.0 implications for GPflow

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#824]
There has been some details released about the forthcoming TensorFlow 2.0

https://groups.google.com/a/tensorflow.org/forum/#!msg/announce/qXfsxr2sF-0/jHQ77dr3DAAJ

Note particularly that it will allow breaking changes to the API and that tf.contrib will be no more.

@awav @markvw @jameshensman @hughsalimbeni

**Comment by markvdw** [comment]
If anything, I'm excited about the changes, although it may require a new major version bump of GPflow if we need to make some big changes to support it.

**Comment by alexggmatthews** [comment]
tf eager might replace aspects of autoflow in time?

**Comment by markvdw** [comment]
I have been in touch with some Google insiders who have been very helpful in pointing out changes that GPflow may have to make in the future. To cut a long story short, I believe that graph mode will not disappear, but that our code will be made to allow easy use with both eager and graph mode. It is likely that autoflow will indeed not be necessary anymore.

**Comment by mrksr** [comment]
Is the `gpflow-2.0` the correct branch to look at for future plans? Is there a plan when it will be merged?

**Comment by awav** [comment]
https://github.com/GPflow/GPflow/pull/871
