### ISSUE TITLE
Could not find signature for _expectation: <Gaussian, Periodic, NoneType, NoneType, NoneType>

### ISSUE THREAD

**Issue by jannine92** [GPflow/GPflow#832]
Hi,

is there a reason why there is no function to compute the expectation with a Periodic kernel? 

This error message appeared while I tried to build a Bayesian GPLVM with a Periodic kernel:

```
Could not find signature for _expectation: <Gaussian, Periodic, NoneType, NoneType, NoneType>
WARNING:gpflow.expectations:Quadrature is used to calculate the expectation. This means that an analytical implementations is not available for the given combination.
Killed
```
Using then quadrature to calculate the expectation leads to a dead kernel everytime.

And that's the code (copy-paste from the tutorial except the kernels):
```
k = kernels.Sum(kernels.RBF(input_dim=Q,ARD=True),kernels.Periodic(input_dim=Q)) 
m = gpflow.models.BayesianGPLVM(X_mean=X_mean, X_var=0.1*np.ones((N, Q)), Y=Y, kern=k, M=M, Z=Z)
m.likelihood.variance = 0.01
opt = gpflow.train.AdadeltaOptimizer(0.01)
m.compile()
opt.minimize(m)
```

Any tipps what I could do instead to be able to use the Periodic kernel for a Bayesian GPLVM?

I'm using:
- GPflow 1.2.0
- Python 3.5
- GPU: Tesla V100 16 GB RAM

**Comment by hughsalimbeni** [comment]
Unless `input_dim` is small (<3) you're likely to run out of memory , which may be why you're getting a `Killed` message. The quadrature uses `H**Q` points, where `H=100` by default. If you want that kernel then you either need to turn the quadrature points down to a manageable number (incurring bias) or else use a stochastic method (NB but then you can't use the 'collapsed' GPLVM, and the uncollapsed model isn't in gpflow at the moment)

**Comment by st--** [comment]
@jannine92 did @hughsalimbeni answer your question? If you want to implement the analytic expectation for the Periodic() kernel, we'd be very happy about a pull request to provide that in GPflow!
