### ISSUE TITLE
Hessian matrix

### ISSUE THREAD

**Issue by ionut199418** [GPflow/GPflow#833]
Hello,
Can you please tell me how to get the Hessian matrix or second derivative in GPflow?

**Comment by hughsalimbeni** [comment]
You can use `tf.hessians`. Which hessian are you after? If you want the objective wrt to the  model parameters this is a bit fiddly as the parameters aren't packed into a single vector. If you want the hessian wrt e.g. test inputs then this is much easier. If you actually want a hessian-vector product then directly calculating the hessian and doing the multiplication is extremely inefficient and much better ways exist

**Comment by ionut199418** [comment]
Thanks a lot. I want the Hessian matrix that allows me to calculate the Cramer Rao lower bound.

**Comment by markvdw** [comment]
For the hyperparameters? For GPR this should just be the Hessian of the objective function.

**Comment by hughsalimbeni** [comment]
The fiddlyness here is that you'll need to be careful with the packing of the tensors and taking the gradients. As encountered in #790, if you pack the hyperparameters into a single tensor and then get the gradients of the objective wrt that tensor you'll get a `None` gradient. Of course, if you only want the diagonals of the Hessian then that's really easy and can be done in a couple of lines.

**Comment by st--** [comment]
Dear @ionut199418, it would be great if you could post this as a question on stackoverflow (tagged gpflow: https://stackoverflow.com/questions/tagged/gpflow), whether you're still looking for an answer or found it by now (in which case I would encourage you to answer it yourself) so that future users can also benefit. Hope this makes sense!
