### ISSUE TITLE
Likelihood of new dataset given an optimized GP

### ISSUE THREAD

**Issue by panchoqv** [GPflow/GPflow#835]
Hello,

I am using GPFlow to obtain the log marginal likelihood of an optimized GP, given a dataset. After the optimization, I would like to "test" the aforementioned GP with a **_new_** dataset, and know what is the probability of this GP "producing" this new dataset.

Is this possible in GPFlow? I have searched the documentation and have not found results.

Thank you very much for the great tool.

Regards,
Francisco.

**Comment by hughsalimbeni** [comment]
You can either set `model.X` and `model.Y` to new values, or you can use a feed dict (this is likely to be faster, especially if you want to do this many times):

```python
fd = {model.X.parameter_tensor:Xnew, model.Y.parameter_tensor:Ynew}
print(model.compute_log_likelihood(feed_dict=fd))
```

**Comment by panchoqv** [comment]
@hughsalimbeni Thank you so much! It worked perfectly well.
