### ISSUE TITLE
high dimnesional data regression IndexError: tuple index out of range

### ISSUE THREAD

**Issue by pullanagari** [GPflow/GPflow#837]
when i tried to apply gpflow on high dimensional data i getting the following problem 
IndexError: tuple index out of range

 import gpflow
import numpy as np
import matplotlib as plt
N = 12
X = np.random.rand(N,100)
Y = np.sin(12*X[:,1]) 
k = gpflow.kernels.Matern52(1, lengthscales=0.9)
m = gpflow.models.GPR(X, Y, kern=k)
m.likelihood.variance = 0.01

**Comment by vdutor** [comment]
Hi,

This issue is not related to `X` being high dimensional.
GPflow simply requires `X` and `Y` to be rank 2 matrices.
`Y = np.sin(12*X[:,1]).reshape(-1, 1)` solves your issue.
