### ISSUE TITLE
Using while-loops in custom kernel

### ISSUE THREAD

**Issue by gideonite** [GPflow/GPflow#843]
# Problem

We are trying to use a TF while-loop to define a custom kernel function but we are getting an error
```
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value autoflow/MyRBF/compute_K/kernel_matrix
```
We believe that this is due to the fact that we are building up a kernel dynamically which must be done with a `tf.Variable`, but GPflow assumes that the kernel is a `tf.Tensor`. So, it doesn't get initialized at the right time. We tried putting it into the `initializables` property but these are initialized before the kernel function is called.

How can we use `tf.while_loop` to define a custom kernel function?

# Example
Here is a minimal example for the RBF kernel. Obviously, we want to use while-loops for a different kernel.

```python
D = 10

class MyRBF(gpflow.kernels.Kernel):
    def __init__(self):
        super().__init__(input_dim=D)
        self.variance = gpflow.Param(1.0, transform=gpflow.transforms.positive)
        self.kernel_matrix = None

    def K(self, X, X2=None):
        if X2 is None:
            X2 = X

        N = tf.shape(X)[0]
        M = tf.shape(X2)[0]
        self.kernel_matrix = tf.Variable(tf.zeros([N,M], dtype=tf.float64),
                trainable=False,
                validate_shape=False, # prevent TF from validating shapes (N and M) at compile time
                dtype=tf.float64,
                name="kernel_matrix")

        i = tf.constant(0)
        j = tf.constant(0)

        while_condition_i = lambda i: tf.less(i, N)
        while_condition_j = lambda j: tf.less(j, M)

        def body_i(x):
            r_j = tf.while_loop(while_condition_j, body_j, [j])
            return [tf.add(x, 1)]

        def body_j(x):
            dist = tf.exp(tf.square(X[i] - X2[j]))
            tf.assign(self.kernel_matrix[i, j], dist)
            return [tf.add(x, 1)]

        result = tf.while_loop(while_condition_i, body_i, [i])

        # Fails with a type error:
        # TypeError: unsupported operand type(s) for *: 'float' and 'Parameter'
        # self.kernel_matrix *= tf.exp(-1/2*self.variance)

        # Fails with an uninitialized value error:
        # tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value autoflow/MyRBF/compute_K/kernel_matrix
        return self.kernel_matrix

    def Kdiag(self, X):
        return tf.diag_part(self.K(X))

data_train = np.random.randn(42, D)
rbf = MyRBF()
rbf.compute_K(data_train, data_train)
```
# Setup
```
gpflow.__version__ == '1.1.1'
tensorflow.__version__ == '1.11.0-dev20180822'
No GPU, CPU only
Python 3.6.6
OS X 10.13.6
Macbook Pro 2016
```

**Comment by hughsalimbeni** [comment]
If you introduce a `tf.Variable` yourself then you need to initialize it. In this case you can either call the initializer manually, or else (perhaps better) you can add it to the `initializables` and gpflow will sort out the initialization for you. Why do you want a variable here, however? Also, `result` doesn't appear to be used in the above code. I would expect that you want to return `result*tf.exp(-1/2*self.variance)`, which should work if you add the `params_as_tensors` decorator

**Comment by fortuin** [comment]
I think the problem is that the `initializables` don't get initialized in time for this to work. At least we tried to put it in there and still get the `FailedPreconditionError`.

We need a variable here, because the elements of the kernel matrix are computed sequentially and TensorFlow only supports dynamic assignment of tensor elements for variables.

**Comment by amaris-i-is** [comment]
Hi @gideonite, 

Were you able to solve this problem or find a way around it? I am also using a TF while loop for a custom kernel and running into the same initialisation error!

**Comment by st--** [comment]
@gideonite, @amaris-i-is if you think this is still a relevant question, it would be great if you could repost this on stackoverflow (tagged gpflow: https://stackoverflow.com/questions/tagged/gpflow), whether you're still looking for an answer or found it (in which case I would encourage you to answer it yourself) so that future users can also benefit. Hope this makes sense!
