### ISSUE TITLE
Why are self-references not allowed in ParamList's

### ISSUE THREAD

**Issue by Joshuaalbert** [GPflow/GPflow#844]
This is more of a implementation question. Why are self-references not allowed in ParamList's?
E.g. a kernel_list with repeated elements referencing the same kern.

``` python
mk.SeparateMixedMok([gp.kernels.RBF(1)]*2, np.eye(2))
```

Throws an assertion error `Self references are not allowed.`.

**Comment by st--** [comment]
@awav might have some more detailed explanation, but if param objects allowed self-references, then they wouldn't form a tree anymore which would make it much more complicated iterating over all trainable parameters and things like that (would have to manually keep track of duplicates etc). Does that answer your question?

**Comment by Joshuaalbert** [comment]
Answered
