### ISSUE TITLE
GP Regression with Poisson likelihood for 300 observation took  a 65 minutes on Desktop

### ISSUE THREAD

**Issue by NuhaSaud** [GPflow/GPflow#848]
%pylab inline
import numpy as np
import gpflow
import tensorflow as tf
import time
import matplotlib.pyplot as plt

# Sampling from Poisson distribution
np.random.seed(100)
plt.figure(figsize=(8, 8))
samples =300
x = np.linspace(1, 300, samples)[:, None]
noise= np.random.normal(0,1,samples)
f_true = np.random.multivariate_normal(np.zeros([samples]), gpflow.kernels.RBF(1,lengthscales=30., variance = 1.0).compute_K_symm(x))
y = np.array([np.random.poisson(np.exp(f)) for f in f_true])[:,None]   + np.eye(samples) * 1e-10  # nugget needed
plt.plot(x,y,'kx')
plt.plot(x, np.exp(f_true), '--k', linewidth=2)
 # fitting a GP
t0 = time.time()
with gpflow.defer_build():
    kern = gpflow.kernels.RBF(1, variance= 1.,lengthscales =3.,ARD=False)
    lik = gpflow.likelihoods.Poisson()
    m = gpflow.models.VGP(x, y, kern , lik)
m.compile()
gpflow.train.ScipyOptimizer().minimize(m,maxiter=20000.0)
Time=time.time() - t0
print('Time:',Time/60.)   
#output:

INFO:tensorflow:Optimization terminated with:
  Message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
  Objective function value: 115665.469385
  Number of iterations: 556
  Number of functions evaluations: 639
Time: 65.59093526999156 minutes

How can I make it faster ?

**Comment by hughsalimbeni** [comment]
Your y is the wrong shape, unless you really want 300 outputs. It's the `np.eye(samples)` that's doing it.

**Comment by NuhaSaud** [comment]
Thank you.
