### ISSUE TITLE
Autoflow fails when making predictions with different models

### ISSUE THREAD

**Issue by markvdw** [GPflow/GPflow#85]
Another failure case of Autoflow:

```
import numpy as np
import GPflow
import tensorflow as tf

X = rnd.rand(10, 1)
Y = rnd.rand(10, 1)
mv = GPflow.sgpr.SGPR(X.copy(), Y.copy(), GPflow.kernels.RBF(1), Z=np.random.rand(4, 1)*np.max(X))
mf = GPflow.sgpr.GPRFITC(X.copy(), Y.copy(), GPflow.kernels.RBF(1), Z=np.random.rand(4, 1)*np.max(X))

mv.predict_y([[3]])
mf.predict_y([[3]])
mv.predict_y([[3]])
```

The cause: When running several models in parallel, AutoFlow shares its `self.tf_args` variable between models. So after `mf.predict_y` has been called, the AutoFlow object will now contain the tensorflow arguments for mf. These are the wrong placeholders when `mv.predict_y` is called again. The root of problems here, is that the decorator is called when the `GPModel` class is created, so the decorator is shared between all objects that inherit from it.

A quick fix would be to remove the caching mechanism. A different fix would be to store `tf_args` in `instance` instead of `self`.

I think the latter solution is preferable, so I'll submit a pull request for it.

**Comment by markvdw** [comment]
Pull request: https://github.com/GPflow/GPflow/pull/86

**Comment by jameshensman** [comment]
Thanks again for fixing this @markvdw .
