### ISSUE TITLE
Relationship between new Multi-Output GP and LMC / ICM

### ISSUE THREAD

**Issue by martiningram** [GPflow/GPflow#851]
Hi everyone,

This isn't so much a bug as an ask for pointers!

I have been trying out the multi-output functionality illustrated in [the notebook](https://github.com/GPflow/GPflow/blob/develop/doc/source/notebooks/multioutput.ipynb). It seems to work quite well, but I would like to read more about the theory behind it. Are there any papers to read to understand what exactly is going on? I am familiar with [this review](https://arxiv.org/abs/1106.6251), but I can't quite tell whether the "mixed" kernel is a form of LMC, or something different.

Thanks!

**Comment by markvdw** [comment]
We're planning to write some kind of (white)paper about it, relating the existing models to what is possible in our framework. For now (unfortunately) the best I advise is to carefully compare the maths in the review to what is implemented in the code. Hopefully we can have more helpful papers / docs soon!

**Comment by martiningram** [comment]
I see, no problem. Thanks for the response!
