### ISSUE TITLE
Importing gpflow failing, throwing ValueError - "gpflow/_settings.py", line 135, ValueError: Config value "WARNING" expected to be string

### ISSUE THREAD

**Issue by syedrizvi** [GPflow/GPflow#855]
Hello, I got the following issue while trying to update gpflow, now it's just not importing
(sorry for the formatting)

______ In bash terminal _________
Python 2.7.13 |Anaconda 4.3.1 (64-bit)| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
: import gpflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gpflow/__init__.py", line 19, in <module>
    from ._settings import SETTINGS as settings
  File "gpflow/_settings.py", line 198, in <module>
    __LOADED_SETTINGS = _namedtuplify(__CONFIG._sections)
  File "gpflow/_settings.py", line 162, in _namedtuplify
    mapping[key] = _namedtuplify(value)
  File "gpflow/_settings.py", line 162, in _namedtuplify
    mapping[key] = _namedtuplify(value)
  File "gpflow/_settings.py", line 169, in _namedtuplify
    return _parse(mapping)
  File "gpflow/_settings.py", line 135, in _parse
    .format(string))
ValueError: Config value "WARNING" expected to be string.
______________________

Subset of my pip freeze results:
anaconda-client==1.6.0
anaconda-navigator==1.5
anaconda-project==0.4.1
gpflow==1.2.0
GPUtil==1.2.3
GPy==1.6.1
ipykernel==4.5.2
ipython==5.1.0
ipython-genutils==0.1.0
ipywidgets==5.2.2
numpy==1.14.5
pandas==0.23.4
psutil==5.0.1
pycuda==2016.1.2
scikit-image==0.12.3
scikit-learn==0.18.1
scipy==0.19.0
tensorboard==1.10.0
tensorflow==1.10.1
tensorflow-gpu==1.10.1
tensorflow-tensorboard==0.4.0
Theano==0.9.0

**Comment by syedrizvi** [comment]
@hughsalimbeni: thank you for the comment
a. What version of python < 3 can I safely use here with this version
b. Can I use some older version of GP flow safely with 2.7?

I am worried that updating from 2.7 onwards might break the rest of my code base, and will need a major re-write.

**Comment by st--** [comment]
@syedrizvi 
GPflow > 1.0 only supports python 3. Python 2 will stop being maintained in just over a year, so if you at all expect to use your code beyond 2020, I would strongly suggest trying to migrate (you'll need to touch a lot of code, but it won't actually be a big re-write, and there's a helper module 'six' to help ease the transition). You'll be glad about it once you've done it. (GPflow supported both python2 AND python3 for a while, you can do it as a step-by-step process towards python3 compatibility without having your code being broken in the meantime)

If moving your code to python 3 is not an option, you could try out GPflow 1.0.0 (https://github.com/GPflow/GPflow/releases/tag/1.0.0), 0.5 or 0.4 - I'm afraid I don't remember exactly when we gave up on python 2, but it was one of those.
