### ISSUE TITLE
Implementation of a two sided error term

### ISSUE THREAD

**Issue by markmoses** [GPflow/GPflow#862]
Hello all,

I am not reporting a bug.; I have a question about implementation of a custom likelihood function. If this is not a good forum to ask the question, then please feel free to point me in the correct direction. (GPflow does not have a strong presence on stackoverflow)

The specific likelihood that I am trying to implement is a two sided error term with one side being normally distributed and the other side with an assumed truncated normal distribution. This type of likelihood is common in stochastic frontier analyses (see this paper for the original implementation. could not find a better document https://ac.els-cdn.com/0304407680900421/1-s2.0-0304407680900421-main.pdf?_tid=f0e0ac0d-eef7-4f02-8386-fd93d6edd927&acdnat=1538246979_c25210597f80b5cf68aaf06cbdd5b41e). This likelihood is useful because the returned residuals can be converted into an estimate of "efficiency" of each observation given a set of covaraites. (the efficiency part is measured on a scale of zero to one and can be thought of like Carnot's theorem and heat engines etc... for those of you with some physics). The main limitation with stochastic frontier analysis is the assumption of a function form (linear, quadratic etc..). I am trying to address this limitation by implementing a GPR with this two sided likelihood.

Using an R package as I guide https://github.com/cran/sfa/blob/bd47878ee213bcdedbd15dc13c01782fdf7689fd/R/sfa.R#L27 I copied the likelihood and implemented a custom GPflow likelihood. I'll grant you that right now it is a bit bulky

```
import gpflow as gpflow
from gpflow.decors import params_as_tensors
import tensorflow as tf
import numpy as np
def gaussian_trunc_normal(obs, y_hat, variance, variance_2, mu, N):
    epsilon = obs - y_hat
    sigmau2 = variance
    sigmav2 = variance_2
    mu = mu
    dist = tf.distributions.Normal(tf.constant(0.,tf.float64), tf.constant(1., tf.float64))  ## better way for cdf?
    sc = 1.
  
    ret = -(N / 2. * -1.8378770664093453 + N * tf.log(1. / (tf.sqrt(sigmau2 + sigmav2))) \
            - tf.log(dist.cdf(tf.divide(mu, tf.cast(tf.sqrt(sigmau2), tf.float64)))) \
             + tf.reduce_sum(tf.log(dist.cdf(((1. - (sigmau2 / (sigmau2 + sigmav2))) \
             - sc * (sigmau2 / (sigmau2 + sigmav2)) * epsilon) / (tf.sqrt(sigmau2 * (1. - sigmau2 / (sigmau2 + sigmav2))))))) \
             - 1. / (2. * (sigmau2 + sigmav2)) * tf.reduce_sum(tf.square((epsilon + sc * mu))))
    return ret 

           
class SFA_trunc_normal(gpflow.likelihoods.Likelihood):
    def __init__(self,N, variance=1.0, variance_2=1.0, mu=.1, **kwargs):
        super().__init__(**kwargs)
        self.variance = gpflow.params.Parameter(
            variance, transform=gpflow.transforms.positive, dtype=gpflow.settings.float_type)
        self.variance_2 = gpflow.params.Parameter(
            variance_2, transform=gpflow.transforms.positive, dtype=gpflow.settings.float_type)
        self.mu = gpflow.params.Parameter(
            mu, transform=gpflow.transforms.positive, dtype=gpflow.settings.float_type)
        self.N= N

    @params_as_tensors
    def logp(self, F, Y):
        return gaussian_trunc_normal(Y, F, self.variance, self.variance_2, self.mu, self.N)

    @params_as_tensors
    def conditional_mean(self, F):  # pylint: disable=R0201
        return tf.identity(F)

    @params_as_tensors
    def conditional_variance(self, F):
        return tf.fill(tf.shape(F), tf.squeeze(self.variance))

    @params_as_tensors
    def predict_mean_and_var(self, Fmu, Fvar):
        return tf.identity(Fmu), Fvar + self.variance

    @params_as_tensors
    def predict_density(self, Fmu, Fvar, Y):
        return gaussian_trunc_normal(Y, Fmu, Fvar + self.variance, self.variance_2, self.mu, self.N)

    @params_as_tensors
    def variational_expectations(self, Fmu, Fvar, Y):
        ## I won't be doing any variational GPs... so I don't think I need this part
        return -0.5 * np.log(2 * np.pi) - 0.5 * tf.log(self.variance) \
               - 0.5 * (tf.square(Y - Fmu) + Fvar) / self.variance
```

When I test this out on any synthetic data it throws an error and the traceback says the input matrix is not invertable. Below is an example
```
import numpy as np
import pandas as pd
import gpflow as gpflow

x1 = (np.random.normal(5, 2, 100))
x2 = (np.random.normal(2, 1, 100))

efficiency = np.random.uniform(0, 1, 100)

noise = np.random.normal(0, .3, 100)

y = 3+ 2*(x1) + -3*(x2)  +noise + np.log(efficiency)

kern = gpflow.kernels.RBF(2, active_dims=[0,1])*gpflow.kernels.Linear(2, active_dims=[0,1])*gpflow.kernels.Constant(1)

df =pd.DataFrame(np.vstack((x1, x2, y)).T)
df.columns =['x1', 'x2', 'y']

model =gpflow.models.GPMC(df[['x1', 'x2']].values, df.y.values[:,None], kern, SFA_trunc_normal(df.shape[0]))

gpflow.train.AdamOptimizer().minimize(model, maxiter=1000)
```
It do not get the error when I use a simple Gaussian likelihood. 

I am curious, from a gpflow standpoint, if there is anything immediately wrong with my implementation that would cause the matrix to not be invertable. Secondly, a friend mentioned that the truncated normal part of the likelihood could be implemented as a kernel. I agree that it would be cleaner, but I don't know how to do that and I wouldn't want to go down a rabbit hole if it fundamentally would not work. 

Any helpful tips or tricks you could provide would be most appreciated. Thanks!

**Comment by hughsalimbeni** [comment]
A few pointers:

* If you're using the GPMC model you need to use HMC, and either fix or put priors on all the hyperparameters. Otherwise this is the MAP estimate. 

* I suspect you only want to sum over certain axes. For example in the term, `tf.reduce_sum(tf.square((epsilon + sc * mu))))` looks like it might be only intended to sum of the columns, not rows. A good idea might be to check that the operation really is happening elementwise over the first index of Y. 

* It's a good idea to check that there aren't any nans in the density before debugging anything else

* Does the optimization fail on the first iteration, or does it only fail after some point?

* Not that is matters for the optimization, but are you sure you have the right conditional mean etc? If the likelihood is assymetric it doesn't seem like it should have the same result as the Gaussian.

* Why do you include the constant kernel? The RBF already includes a variance term, so this won't be having any effect. (also, I wonder if the multiplication by the linear kernel is really what you want, as this seems an odd model to me)

**Comment by st--** [comment]
@markmoses we'd like to move towards using stackoverflow for more generic questions and keeping this for actual issues; this seems to be an example of something reasonably suited to stackoverflow: would you be willing to repost your question there?

**Comment by st--** [comment]
@markmoses there's a gpflow tag: https://stackoverflow.com/questions/tagged/gpflow - would be great if you could populate it with your question (and any partial or full answer you may have gotten already)!
