### ISSUE TITLE
How to config GPU options?

### ISSUE THREAD

**Issue by HeroKillerEver** [GPflow/GPflow#865]
I would like to config the gpu options as

gpu_options['allow_growth'] = True 

in gpflowrc under [session],  it seems not working

**Comment by rhaps0dy** [comment]
At the moment you can't. You have to edit [the file `session_manager.py`](https://github.com/GPflow/GPflow/blob/develop/gpflow/session_manager.py#L111) and add `gpu_options.allow_growth` to the ConfigProto.

You could also hack it and add the recursive option to the settings _before doing anything else_ with GPflow:
```python
import gpflow
settings_obj = gpflow.settings.get_settings()
settings_obj.session.gpu_options = gpflow._settings._MutableNamedTuple()
settings_obj.session.gpu_options.allow_growth = True
gpflow.settings.push(settings_obj)
```

**Comment by awav** [comment]
Hello @HeroKillerEver,

This is not a bug or performance issue, and probably you've created the issue via `How-to and other issues` option, which has this description: *Please, post other questions on StackOverflow with `gpflow` tag.* Could you please next time create a StackOverflow question instead? Thanks!

And, you can tweak GPU parameters using:

1. 
```python
import gpflow
import tensorflow as tf

config = tf.ConfigProto(gpu_options=tf.GPUOptions(allow_growth=True))
gpflow.reset_default_session(config=config)

... your gpflow code
```

2.
```python
import gpflow
import tensorflow as tf

config = tf.ConfigProto(gpu_options=tf.GPUOptions(allow_growth=True))
with tf.Session(config=config).as_default():
    ... your gpflow code
```
