### ISSUE TITLE
the large dataset problem

### ISSUE THREAD

**Issue by 311dada** [GPflow/GPflow#867]
I want to finish a muli-classification problem. The dataset is so large!!! It includes 200 thousand samples which have high dimension about 2,000,000. However, it's a binary sparse matrix.So i want to use sparse matrix as input.What can i do to solve the input problem? Thanks!

**Comment by hughsalimbeni** [comment]
This is beyond the scope of gpflow. It would be probably be possible to make a custom model using SVGP and tensorflow sparse matrix operations.

**Comment by 311dada** [comment]
Thanks a lot!I reduce the dimension but when i use the SVGP to make muli-class(22) classification,i get the OOM error.Could you please tell me what to do?

**Comment by awav** [comment]
It is very hard to give an advice not seeing what you actually do and error output, is that gpu oom or standard one and so on.

**Comment by st--** [comment]
@311dada please feel free to reopen this issue if you've got further questions and further details to help us answer your questions!
