### ISSUE TITLE
How to update trained model?

### ISSUE THREAD

**Issue by BingqingLiu** [GPflow/GPflow#872]
I want to update my trained model's input data without retrain the hyperparameters

that is - I want to save my hyperparameters from `gpflow.train.ScipyOptimizer().minimize(m)` and assign them to the model with updated input x and y ranges:  `m = gpflow.models.GPR(x_rolling, y_rolling, kern=gpflow.kernels.Matern32(1) + gpflow.kernels.White(1))`, where x_rolling and y_rolling moves to the next data point in each loop.

Thank you so much

**Comment by markvdw** [comment]
Hi, this can be done by using `d = m.read_values()` to get a dictionary containing the hyperparameters and their corresponding values. The dictionary can then be assigned to a new model using `m.assign(d)`.
