### ISSUE TITLE
How are the inducing points computed?

### ISSUE THREAD

**Issue by wizmik12** [GPflow/GPflow#874]
Hi All, I want to know how the inducing points are computed. Looking the code I see that they are trainables but I don't know how and I don't find anything at the documentation. I am very new to code so it is quite hard to me seeing and understanding the code.

Thank you, Mik.

**Comment by hughsalimbeni** [comment]
Do you have anything specific about the inducing points you'd like to compute? NB gpflow is not designed with tutorial purposes in mind and other gp libraries may be better suited for introductory purposes.

**Comment by wizmik12** [comment]
What I want to know it is what approximation is done in the code for the optimization of the inducing points. I know that GPflow seems hard to learn but I needed for my research. Sorry, if the question is very basic. My background it is purely mathematical so dealing with python and especially with tensorflow is a battle for me.

**Comment by hughsalimbeni** [comment]
There is no approximation the code regarding optimization of inducing points. The code precisely implements the results of the relevant papers (these are generally included in the doc strings). The actual optimizer used depends on the user.
