### ISSUE TITLE
inter-domain GPs in 1.2.0?

### ISSUE THREAD

**Issue by ambrishrawat** [GPflow/GPflow#875]
I was wondering if there is sample code available for inter-domain GPs in 1.2.0 or 1.3.0?
The [convgp](https://github.com/markvdw/convgp) code, as I understand is based on [this](https://github.com/markvdw/GPflow-inter-domain).

However, I am unable to get it to work with 1.2.0. The rest of my code is built with the updated gpflow. Any pointers on this would greatly help

**Comment by markvdw** [comment]
Indeed there is. The old inter-domain fork of GPflow is now obsolete now that there's a more elegant solution in GPflow. We use multiple dispatch to automatically choose the right code for computing Kuu and Kuf. See https://github.com/GPflow/GPflow/blob/develop/gpflow/features.py.

Are you interested in extending the convolutional GP at all?
