### ISSUE TITLE
estimate noise level at each covariate

### ISSUE THREAD

**Issue by jacob-roth** [GPflow/GPflow#881]
Similar to the discussion here #402, is there a simple way of estimating the noise level at each covariate in GP regression? It seems that adding a `White` kernel populates the diagonal with a single model variance parameter, and I was wondering if it's possible to adjust this to allow for different parameters for each entry of the diagonal?

Specifically, I have a dataset <a href="https://www.codecogs.com/eqnedit.php?latex=$\{X_i,&space;Y_i^{(j)}\}_{i,j=1,1}^{n_i,&space;n_j}$" target="_blank"><img src="https://latex.codecogs.com/gif.latex?$\{X_i,&space;Y_i^{(j)}\}_{i,j=1,1}^{n_i,&space;n_j}$" title="$\{X_i, Y_i^{(j)}\}_{i,j=1,1}^{n_i, n_j}$" /></a> where `i` indexes my covariates and `j` indexes the "trial" number. So, at each covariate, I have multiple dependent responses, and I'd like to account for the variance in response at each `X_i`. Thanks!

**Comment by hughsalimbeni** [comment]
The multioutput framework will do this for you, or if you have a Gaussian likelihood you could subclass the likelihood to have a vector valued variance (I think should broadcast without any work, but it would be worth checking this)

**Comment by jacob-roth** [comment]
Thanks for the suggestion @hughsalimbeni! I looked into `multioutput` but think my setup is slightly different. I didn't explain this clearly originally, but we might not know which trial a particular `Y`-response is from for a given `X`. My understanding is that `multioutput` fits multiple GPs with some sort of correlation between trials, but heuristically, I'm just seeking a way to say that if I have a lot of `Y`-observations at a particular `X` value, then the `sigma_X` will reflect the noise at this `X`. So, I think I'm more interested in your second suggestion.

On broadcasting variance, I worked from the [`models.ipynb`](https://github.com/GPflow/GPflow/blob/develop/doc/source/notebooks/models.ipynb) example and adjusted the data to repeat 5 times to give 100 points. I then manually compiled `gpflow` with a new `Gaussian_` likelihood which fixed the variance as `variance = np.ones(100)` before initialization. Running this model didn't seem to give prediction bands that accounted for the variance as much as I thought, and my guess was because each point was treated separately. Is there a way to restrict the variance to only 10 parameters at the known `X`-values? Or am I thinking about this wrong? Thanks!

**Comment by st--** [comment]
Dear @jacob-roth, it would be great if you could post this as a question on stackoverflow (tagged gpflow: https://stackoverflow.com/questions/tagged/gpflow), whether you're still looking for an answer or found it (in which case I would encourage you to answer it yourself) so that future users can also benefit. Hope that makes sense!
