### ISSUE TITLE
Unable to clear kernel parameters

### ISSUE THREAD

**Issue by tadejkrivec** [GPflow/GPflow#889]
I am trying to run some regression examples in Jupyter Notebook. I am unable to clear the kernel parameters. If I comment out m.clear() I get the following error: `GPflowError: Parameter "GPR/kern/lengthscales" has already been compiled.`, which is expected. And if I try to clear the model parameters I get the some Tensorflow error. Here is the example i am running:
```
import gpflow
import numpy as np
import matplotlib
%matplotlib inline
matplotlib.rcParams['figure.figsize'] = (12, 6)
plt = matplotlib.pyplot

N = 12
X = np.random.rand(N,1)
Y = np.sin(12*X) + 0.66*np.cos(25*X) + np.random.randn(N,1)*0.1 + 3

k = gpflow.kernels.Matern52(1, lengthscales=0.3)
m = gpflow.models.GPR(X, Y, kern=k) 

m.clear()
m.kern.lengthscales.prior = gpflow.priors.Gamma(1., 1.)
m.kern.variance.prior = gpflow.priors.Gamma(1., 1.)
m.likelihood.variance.prior = gpflow.priors.Gamma(1., 1.)
m.compile()
m.as_pandas_table()
```
Some additional information:
    - GPflow version 1.3.0
    - Tensorflow 1.12.0
    - CPU
    - Python 3.5.2
    - Ubuntu 18.04

**Comment by markvdw** [comment]
I'm uncertain what you're trying to do with `m.clear()`. Are you trying to reset them to default? If so, it's better to use `vals = m.read_values()` at the start, and then use `m.assign(vals)` when you want to reset the values.

**Comment by tadejkrivec** [comment]
I am just trying to run an example. It is `regression.ipynb`. If i run all of the cells consequently everything works as expected. But if i just omit the cell 8 (plot and predict) i get the following error on cell 14 (assigning priors):
```
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Tensor'>):
<tf.Tensor 'Matern52-44a47b66-0/lengthscales/IsVariableInitialized:0' shape=() dtype=bool>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 3287, in run_code
    return outflag  File "<ipython-input-3-3836f454caba>", line 1, in <module>
    k = gpflow.kernels.Matern52(1, lengthscales=0.3)  File "/home/GPflow/gpflow/core/compilable.py", line 91, in __init__
    self.initialize(force=True)  File "/home/GPflow/gpflow/core/node.py", line 156, in build
    self._build()  File "/home/GPflow/gpflow/params/parameterized.py", line 302, in _build
    self._prior_tensor = self._build_prior(priors)  File "/home/GPflow/gpflow/core/node.py", line 156, in build
    self._build()  File "/home/GPflow/gpflow/params/parameter.py", line 372, in _build
    self._prior_tensor = prior  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/tf_should_use.py", line 189, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
==================================
```

**Comment by tadejkrivec** [comment]
I am trying to assign priors to the model after i already assigned some parameters. This was said on some previous issue: "with a prior, the computational graph will be different. Tensorflow only has a static graph - so you can't change it. Hence, you will need to reset the graph: call model.clear(), then add the priors, then call model.compile() to re-build the graph". But this only seems to work if you first define the parameters, then run some prediction and then clear the graph and assign priors. To be precise i am running an example - `regression.ipynb`. If i run all of the cells consequently everything works as expected. But if i just omit the cell 8 (plot and predict) i get the following error on cell 14 (when assigning priors):
```
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Tensor'>):
<tf.Tensor 'Matern52-44a47b66-0/lengthscales/IsVariableInitialized:0' shape=() dtype=bool>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 3287, in run_code
    return outflag  File "<ipython-input-3-3836f454caba>", line 1, in <module>
    k = gpflow.kernels.Matern52(1, lengthscales=0.3)  File "/home/GPflow/gpflow/core/compilable.py", line 91, in __init__
    self.initialize(force=True)  File "/home/GPflow/gpflow/core/node.py", line 156, in build
    self._build()  File "/home/GPflow/gpflow/params/parameterized.py", line 302, in _build
    self._prior_tensor = self._build_prior(priors)  File "/home/GPflow/gpflow/core/node.py", line 156, in build
    self._build()  File "/home/GPflow/gpflow/params/parameter.py", line 372, in _build
    self._prior_tensor = prior  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/tf_should_use.py", line 189, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))

**Comment by tadejkrivec** [comment]
I am trying to assign priors to the model after i already assigned some parameters to it. This was said on some previous issue: "with a prior, the computational graph will be different. Tensorflow only has a static graph - so you can't change it. Hence, you will need to reset the graph: call model.clear(), then add the priors, then call model.compile() to re-build the graph". But this only seems to work if you first define the parameters, then run some prediction and then clear the graph and assign priors. To be precise i am running an example - `regression.ipynb`. If i run all of the cells consequently everything works as expected. But if i just omit the cell 8 (plot and predict) i get the following error on cell 14 (when assigning priors):
```
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Tensor'>):
<tf.Tensor 'Matern52-44a47b66-0/lengthscales/IsVariableInitialized:0' shape=() dtype=bool>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 3287, in run_code
    return outflag  File "<ipython-input-3-3836f454caba>", line 1, in <module>
    k = gpflow.kernels.Matern52(1, lengthscales=0.3)  File "/home/GPflow/gpflow/core/compilable.py", line 91, in __init__
    self.initialize(force=True)  File "/home/GPflow/gpflow/core/node.py", line 156, in build
    self._build()  File "/home/GPflow/gpflow/params/parameterized.py", line 302, in _build
    self._prior_tensor = self._build_prior(priors)  File "/home/GPflow/gpflow/core/node.py", line 156, in build
    self._build()  File "/home/GPflow/gpflow/params/parameter.py", line 372, in _build
    self._prior_tensor = prior  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/tf_should_use.py", line 189, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
```

**Comment by markvdw** [comment]
The best course of action here would be to recreate the GPflow object (possibly by wrapping the model generating code into a function and calling it again), and then assign the values of the parameters from the previous model to it. There's no real reason to re-use a previously created model object.

**Comment by st--** [comment]
@tadejkrivec are you still struggling with this or is this resolved now ?

**Comment by st--** [comment]
@tadejkrivec please, re-open this issue if you still encounter any issues - as it is, your example works for me ...

**Comment by farahshamout** [comment]
@tadejkrivec I was facing the same problem with tensorflow 1.12.0
However, when downgraded to 1.5.0 it works just fine.
