### ISSUE TITLE
multi-dimensional input hyperparameter optimization search boundaries 

### ISSUE THREAD

**Issue by Guest2789** [GPflow/GPflow#890]
Hi, 
I'm just starting out with GPflow, and not sure if I'm attempting this in the correct way at all... 

For 2D input I'd like 2 different lengthscales, and I'd like to constrain the the search space for each of these to potentially different intervals during optimization. Using logistic transform I can limit both to the same interval, but can't work out how to set different intervals. 

```
inDim=2
X = np.random.rand(10, inDim)
Y = np.random.rand(10, 1)

Vf = np.array([1])
length = np.array([0.5, 1.5])

lowerBounds = np.array([0.,1.])
upperBounds = np.array([1., 2.])

with gpflow.defer_build():
    k = gpflow.kernels.Matern32(input_dim=inDim, variance=Vf, lengthscales=length, ARD=True)
    m = gpflow.models.GPR(X, Y, kern=k)
    #m.kern.lengthscales.transform = gpflow.transforms.Logistic(np.min(lowerBounds), np.max(upperBounds))
    m.kern.lengthscales.transform = gpflow.transforms.Logistic(lowerBounds, upperBounds)

m.compile()
gpflow.train.ScipyOptimizer().minimize(m)
```

`m.kern.lengthscales.transform = gpflow.transforms.Logistic(np.min(lowerBounds), np.max(upperBounds))` runs without error, but `m.kern.lengthscales.transform = gpflow.transforms.Logistic(lowerBounds, upperBounds)` results in errors at line 206 of gpflow/transforms.py. 

Is there a proper way to pass a vector of boundaries, or a more correct way of achieving the same result?

**Comment by markvdw** [comment]
You will have to implement your own version of the `Logistic` transform. Using `Logistic` as an example, this should be straightforward.

**Comment by koneshgit** [comment]
For beginner like me, it is important to learn how assign parameter to a kernel or a combination of kernels (assign initial lengthscales, variance and their bounding limits), and how read the optimized parameters from the model. It would be really helpful if you add a sub-section [here](https://gpflow.readthedocs.io/en/latest/notebooks/models.html#) 

I still has problem to replicate the above-mentioned example.
