### ISSUE TITLE
How to set an upper bound on the parameters?

### ISSUE THREAD

**Issue by bavent** [GPflow/GPflow#891]
I'm trying to figure out if there is a way to set an upper bound on parameters of a model. In GPy, the constrain_bounded method does the trick, and I'm curious whether there is an analogous method in GPFlow?

**Comment by hughsalimbeni** [comment]
You can use `transforms.Logistic(a=2., b=3.)`, which will bound the parameter between 2 and 3

**Comment by koneshgit** [comment]
```
> k1 = gpflow.kernels.RBF(input_dim=2, active_dims = [0,1], ARD=False)
> k1.lengthscales = 100
> k1.lengthscales.transform = gpflow.transforms.Logistic(lowerBounds, upperBounds
```

  File "C:\Users\mo.koneshloo\Continuum\miniconda3\envs\py36\lib\site-packages\gpflow\params\parameter.py", line 473, in _set_parameter_attribute
    raise GPflowError('Parameter "{}" has already been compiled.'.format(self.pathname))

_GPflowError: Parameter "SquaredExponential/lengthscales" has already been compiled._
