### ISSUE TITLE
Specifying per-observation noise

### ISSUE THREAD

**Issue by bavent** [GPflow/GPflow#896]
I was looking to do heteroscedastic regression on a set of points that each have their own (known) variances, but it isn't clear to me from the documentation how to make that work in GPFlow (or if it's possible in GPFlow).

The GPy equivalent is detailed here: https://github.com/SheffieldML/notebook/blob/master/GPy/heteroscedastic_regression.ipynb

**Comment by hughsalimbeni** [comment]
That model is quite straightforward to implement in gpflow for training points only (just make a likelihood with a variance parameter that is the same shape as the data), but to me it doesn't seem a very sensible model as it doesn't place a prior on the per-observation noise and so doesn't provide a natural way to predict at test points.

**Comment by bavent** [comment]
I see, thanks!
