### ISSUE TITLE
GPflow for the TF library use case 

### ISSUE THREAD

**Issue by bodin-e** [GPflow/GPflow#897]
Want to raise a discussion / question around GPflow that I believe makes a difference for further increasing the applicability of it for people making use of as well as researching Gaussian Process models.

I find the GPflow community vibrant and an excellent path to consolidate efforts around GPs for TensorFlow. Both using and extending GPflow is easy, which to me indicates an useful framework. However, what I think could be better are GPflow's capabilities as a library within the larger context of using TensorFlow. With this I mean for users not writing code from "within" GPflow, adopting its larger abstractions, but want to with little effort make use of functionality implemented in GPflow, such as covariance functions, likelihoods and other subgraphs when building larger composite computational graphs.

I guess my main question is the following: Is ease of such usage intended to be one of the targets for GPflow looking forward?

Had to pleasure to talk to a couple of people involved and behind GPflow at this year's NeurIPS and heard about some of the upcoming changes in GPflow 2.0 relating to this, but thought I post this here for completeness. I do recognize the GPflow development towards using more composable abstractions throughout the year (such as conditionals.py) and the reason I'm reaching out now is simply because its almost there and GPflow really starts to look interesting from my point of view.

**Comment by jameshensman** [comment]
Hi @bodin-e 

Thanks for your comments. 

You're right, we do need to make some effort to make sure that GPflow becomes more extensible in the future for those working outside the GPflow/model framework. 

The conditionals.py effort is a good start, and we have plans to do some more of this. Off the top of my head:
 - make more functionality be tensor-in-tensor-out
 - make better use of tf.distributions
 - go with eager-mode as default as soon as tf does

There are probably more, and @st-- and @awav probably have some things that I've missed. 

If you have any concrete suggestions of things that you think would help, please let us know on here.

**Comment by markvdw** [comment]
@bodin-e I'm curious to hear your opinion on what is currently lacking when it comes to incorporating things in larger sub-graphs. All `Parameterized` objects allow tensors to be passed in. This allows, for example, kernels to be used fully within a non-GPflow graph, by passing in tensors for the hyperparameters and `X`. GPflow models can also interoperate with the output of a NN by passing the output of the NN in as the input data.

This being said, I can anticipate a complaint that this approach requires a large amount of GPflow code being used, for a simple task. Additionally, we don't play particularly well with larger frameworks like Keras.

Do you have any specific use cases which are currently difficult?

**Comment by bodin-e** [comment]
@jameshensman @markvdw Thank you for your responses.

That sounds to me like excellent steps. Especially making functionality be tensor-in-tensor-out is a large part of what I am alluding to.

@markvdw Yes, I do see your argument (and you were right in your anticipation). It is very possible to plugin arbitrary subgraphs into GPflow constructs, although I think it could be further simplified.  But plugging in GPflow declared subgraphs into arbitrary subgraphs is more difficult (although still possible) - such as the difficulty in playing well with Keras, as you mentioned, is a symptom of. This latter thing, as I am sure you know, has to do with the inversion of control respective framework expects.

I think I can summarize my main suggestions/concerns in one example, comprised of two aspects. 

The approach I've tested successfully to use e.g. a kernel (for the case of using GPflow constructs as a part of arbitrary graphs, possibly with third-party/own initialization) is the following below. Do point me in the right direction if this could be further simplified already. 

1. open a scope using gpflow.defer_build()
2. call the constructor (e.g. gpflow.kernels.RBF(...) - where the constructor expects numpy arrays or python primitives, that now will not be used)
3. override the parameter members (e.g. kernel.variance = some_tensor_node) after deleting the members from the namespace (e.g. del kernel.variance)
4. call kernel.build()
5. return from the defer_build scope
7. repeat for other constructs used

Following that, for all constructs where variables to be initialized by GPflow still remain, I gather all associated initializable_feeds in a dict to be passed as feed_dict to the global initializer, in order to break the cyclic dependencies upon variable initialization.

The first concrete thing I suggest is avoiding/reducing the amount of variable declarations and placeholder declarations done inside of e.g. GPflow class constructors. This reduces the flexibility of usage since that makes the assumption that the corresponding tensor is not coming from outside, such as being the output from another subgraph. This would make GPflow usage such as this straightforward:

```python
# Nodes from other graphs / variables / placeholders. Could e.g. be MCMC samples 
variance = some_node_a  
lengthscales = some_node_b
x = some_node_c

kernel = gpflow.kernels.RBF(variance=variance, lengthscales=lengthscales)

x_covar = kernel.K(X=x)
```

The second thing I suggest is to not make the inversion of control, i.e. take care of variable initialization without any explicit calls to do so. Letting the caller/context of usage dictate when variables are initialized makes it easier to combine with things like Keras as well as give more control and transparency in setting up graphs and managing its state.

I do see the benefit of the automatic variable initialization and similar mechanisms GPflow provides, effectively hiding some of the aspects of the tensorflow graph and runtime from the user for ease of usage of models (a separate target/goal from that of ease of arbitrary tensorflow graph composability), but I do believe these ease-of-use mechanisms can be provided as opt-in utilities/wrappers rather than an integral part of the expressions declaring subgraphs. The same, in my opinion, go for variable declaration inside of e.g. constructors, where I am in favor of instead passing them in as parameters to the constructors/functions as default and for the ease-of-use use case provide mechanisms to generate such variable declarations in order to reduce verbosity.

**Comment by st--** [comment]
@bodin-e can you confirm whether (most of) your issues have gone away with gpflow-2.0 (now in the `develop` branch and as a 2.0rc1 on pypi!) or whether this is still an issue - and if so, how ? Thanks!

**Comment by bodin-e** [comment]
> @bodin-e can you confirm whether (most of) your issues have gone away with gpflow-2.0 (now in the `develop` branch and as a 2.0rc1 on pypi!) or whether this is still an issue - and if so, how ? Thanks!

Yes, the issues described above have been addressed. Excellent work with gpflow-2.0

**Comment by st--** [comment]
@bodin-e great! glad you like it. Please don't be shy and leave us feedback - feel free to open new issues even if it isn't exactly a bug - on what you think could be even better about gpflow2. Thanks!
