### ISSUE TITLE
Mutliclass likelihood in GPflow 

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#9]
It would be good to have the multi class likelihood sucessfully used in this paper

https://papers.nips.cc/paper/5875-mcmc-for-variationally-sparse-gaussian-processes.pdf

in GPflow . Ideally this would be done using fast ops written in TensorFlow .

**Comment by jameshensman** [comment]
I started working on this in this branch: https://github.com/GPflow/GPflow/tree/multiclass

**Comment by alexggmatthews** [comment]
@jameshensman I had a look at the branch and it looks good so far. What do you think    still needs doing? Would you like some help getting it in?

**Comment by jameshensman** [comment]
Mostly needs testing! Would appreciate some help, yes.

I suspect it could suffer from numerical overflow easily, especially in the gradient computation.

**Comment by alexggmatthews** [comment]
The overflow sounds potentially problematic. Could you say a bit more about why?

**Comment by jameshensman** [comment]
Hi @alexggmatthews 

I revisited this over the weekend, see the new notebook I added for a demo. the stability seems to have improved a lot since I first looked at this: I suspect improvements elsewhere in GPflow and tensorflow are responsible. 

It might be a good moment to have a look at pressure testing the code a little more with a real-world dataset?

**Comment by alexggmatthews** [comment]
Hi @jameshensman I just had a look and I couldn't see the new notebook you talked about. Are you sure you pushed it?

**Comment by jameshensman** [comment]
Just pushed, sorry. 

https://github.com/GPflow/GPflow/blob/multiclass/notebooks/multiclass.ipynb

**Comment by alexggmatthews** [comment]
@jameshensman Not to worry. Why only 4 Gauss-Hermite points in the demo?

**Comment by jameshensman** [comment]
Ah, that will be a hangover from when I was trying to stabilize the code a
bit. The idea being that fewer GH points means less 'extreme' evaluations
of the log-likelihood, so hopefully less overflow. I wonder what happens if
you change it?
J.

**Comment by alexggmatthews** [comment]
@jameshensman Ok I see. Does that explain away the improved numerical stability do you think? Or do you have independent evidence for that?

**Comment by jameshensman** [comment]
unsure. It seems to work quite well in the notebook, even without that
line.

**Comment by alexisboukouvalas** [comment]
@alexggmatthews  can we close this now?

**Comment by alexggmatthews** [comment]
@alexisboukouvalas Yes. Good point.
