### ISSUE TITLE
Simple example of Cholesky decomposition Issue on kernel matrix

### ISSUE THREAD

**Issue by lexxx233** [GPflow/GPflow#900]
Simple example of cholesky decomposition issue on kernel matrix.

```
import numpy as np
import gpflow.kernels as kernels
import tensorflow as tf

sess = tf.InteractiveSession()

T = np.linspace(0, 4*np.pi, 100)
kern = kernels.RBF(1)
kern.variance = 3.19
kern.lengthscales = 1.47

T = np.transpose(T[np.newaxis])
km = kern.K(T)

sess.run(tf.cholesky(km))
```
produce error

> InvalidArgumentError (see above for traceback): Cholesky decomposition was not successful. The input might not be valid.
	 [[node Cholesky_3 (defined at <ipython-input-27-af2e0b6d9e35>:1)  = Cholesky[T=DT_DOUBLE, _device="/job:localhost/replica:0/task:0/device:CPU:0"](mul_9)]]

Is there something wrong with the kernel evaluation or did I do something funky with the kernel parameters? This problem is solved by adding c*I to the kernel matrix but shouldn't this matrix already positive definite? I am veyr confused.

**Comment by lexxx233** [comment]
This produces output just fine
`sess.run(tf.cholesky(cov + tf.eye(100, dtype=tf.float64)))`

> Out[37]: 
array([[2.04694895e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.55261790e+00, 1.33393315e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.53534982e+00, 5.95470597e-01, 1.21577782e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [9.09360757e-16, 1.80700384e-15, 4.37447980e-15, ...,
        1.14198487e+00, 0.00000000e+00, 0.00000000e+00],
       [4.39556915e-16, 8.83815737e-16, 2.15594672e-15, ...,
        3.00750670e-01, 1.14198487e+00, 0.00000000e+00],
       [2.10889938e-16, 4.29046291e-16, 1.05458476e-15, ...,
        3.32987536e-01, 3.00750669e-01, 1.14198487e+00]])

**Comment by lexxx233** [comment]
Hi. I hope this would be helpful to others

After digging, I found that some eigenvalues of the kernel matrix are slightly negative

> sess.run(tf.linalg.eigh(km))
Out[52]: 
(array([-9.34265966e-14, -5.93276678e-14, -4.92322595e-14, -4.25945076e-14,
        -3.43520683e-14, -3.01023651e-14, -2.61893286e-14, -2.36002671e-14,
        -2.28381810e-14, -1.92585743e-14, -1.82610848e-14, -1.72266322e-14,
        -1.49326840e-14, -1.15581962e-14, -1.10357596e-14, -9.66280261e-15,
        -8.31902625e-15, -8.03553399e-15, -7.09629006e-15, -6.22543236e-15,
        -5.71370939e-15, -5.08978001e-15, -4.59461157e-15, -4.42874576e-15,
        -3.92375182e-15, -2.93750018e-15, -2.39737572e-15, -2.36143510e-15,
        -1.71935578e-15, -1.35291586e-15, -1.19853136e-15, -9.79926567e-16,
        -7.38869430e-16, -6.67880163e-16, -2.44431571e-16, -1.05157548e-16,
         2.99117158e-16,  4.30144491e-16,  6.87550693e-16,  8.69578108e-16,
         1.30266384e-15,  1.42976396e-15,  1.61392558e-15,  1.70999527e-15,
         2.70321487e-15,  3.00644969e-15,  4.06778032e-15,  4.55159597e-15,
         5.45770741e-15,  6.27253842e-15,  6.98420654e-15,  7.54031655e-15,
         8.25007622e-15,  9.31295530e-15,  1.12198286e-14,  1.18374912e-14,
         1.30975614e-14,  1.34497746e-14,  1.56038877e-14,  1.75228819e-14,
         1.98079252e-14,  2.06238581e-14,  2.19719640e-14,  2.84354404e-14,
         2.97755649e-14,  3.18836327e-14,  3.56998144e-14,  3.86421372e-14,
         4.47810571e-14,  8.47071498e-14,  1.22097404e-13,  7.90412225e-13,
         5.08075951e-12,  3.13768657e-11,  1.86172788e-10,  1.06123298e-09,
         5.80572129e-09,  3.04484984e-08,  1.52903499e-07,  7.34257611e-07,
         3.36705733e-06,  1.47219237e-05,  6.12739934e-05,  2.42331585e-04,
         9.08915189e-04,  3.22625359e-03,  1.08126856e-02,  3.41296046e-02,
         1.01177745e-01,  2.80842658e-01,  7.27432756e-01,  1.75166697e+00,
         3.90547958e+00,  8.02772838e+00,  1.51463328e+01,  2.61209877e+01,
         4.10187484e+01,  5.84633286e+01,  7.54383869e+01,  8.79684875e+01]),

Setting these to small positive value solve the cholesky decomposition issue. It can be done as follow

```
e,v = tf.linalg.eigh(km)
eps = 1e-5
e = tf.maximum(e, eps)
km = tf.matmul(tf.matmul(v,tf.diag(e)),tf.transpose(v))
km_chol = tf.cholesky(km) ----> this works now
```

**Comment by hughsalimbeni** [comment]
It is usual to add a small amount of 'jitter' to positive definite matrices, exactly for the reasons you are seeing. Gpflow uses 1e-6 times the identity for this as default, though larger values might be necessary for very ill conditioned matrices
