### ISSUE TITLE
Is gpflow's scaled_euclid_dist as stable as tensorflow_probabilities?

### ISSUE THREAD

**Issue by Joshuaalbert** [GPflow/GPflow#917]
Basically, for kernels that depend on ```r``` the L2 norm is calculated [here](https://github.com/GPflow/GPflow/blob/master/gpflow/kernels.py#L288) and one sees we first clip the value. In [tensorflow probability](https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/positive_semidefinite_kernels/internal/util.py#L88) they use a ```sqrt``` with a modified gradient that replaces ```grad(|x - x'|)``` with a large but finite number when ```x=x'```. 
My question is whether they are equivalent, or if one is better?

**Comment by awav** [comment]
Hello Josh, 

We are trying to move all non-related to bugs and features questions to StackOverflow and make questions like yours searchable. Could you post this question on stackoverflow with gpflow tag, as it was described in issue template :)

Kind regards

**Comment by awav** [comment]
@Joshuaalbert ^^^

**Comment by awav** [comment]
Yep :)
