### ISSUE TITLE
AttributeError: module 'gpflow' has no attribute 'kernels'

### ISSUE THREAD

**Issue by madudata61** [GPflow/GPflow#932]
**For questions on how to work with GPflow, or support for problems that are not verified bugs in GPflow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) and use [gpflow](https://stackoverflow.com/questions/tagged/gpflow) tag for your question.**

Hi I installed gpflow package. When I tried to run a small code suggested in the document, code throws an error:
AttributeError: module 'gpflow' has no attribute 'kernels'

import gpflow
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')
import tensorflow as tf
%matplotlib inline

k1 = gpflow.kernels.Matern12(input_dim=1)
k2 = gpflow.kernels.Linear(input_dim=1)

k3 = k1 + k2
k4 = k1 * k2

Does anyone know the reason for this?
When I go to the gpflow package folder, I can see kernels.py file. 
Any help would be much appreciated.
Thanks

**Comment by hughsalimbeni** [comment]
Sounds like a path issue. How did you install gpflow?

**Comment by st--** [comment]
@madudata61 this looks like an installation issue, not a bug in gpflow - if you still require some help, you'll need to provide a bit more information on what you tried to do to install gpflow. This may be more appropriate as a stackoverflow question (https://stackoverflow.com/questions/tagged/gpflow).
