### ISSUE TITLE
Non-invertable input matrix for coregionalization

### ISSUE THREAD

**Issue by thatmushroom** [GPflow/GPflow#934]
I am getting the "Input matrix is not invertible" error when attempting to implement coregionalization for a 3-output-dimension time series.
I have gotten it to work for 2 output dimensions, but not for 3.

I'm using GPFlow 1.3.0. 
I've tried following the examples from #542 and #709 as best I can. 

The CSV is here: 
https://github.com/thatmushroom/SNOTEL_prediction/blob/master/Initial_multiyear_prototype_data.csv 
The code that is below can also be grabbed from here: 
https://github.com/thatmushroom/SNOTEL_prediction/blob/master/PGM/07a_coregionalization_testcase.py 

```
import gpflow
import pandas as pd
import os
import numpy as np

os.chdir('Z:\SNOTEL\SNOTEL_prediction\PGM')






relpath = '../DATA/Initial_multiyear_prototype_data.csv'
#relpath_pickle = '../DATA/Initial_multiyear_prototype_data.pkl'
multiyear_df = pd.read_csv(relpath ,sep=",", engine='python')
#multiyear_df = pd.read_pickle(relpath_pickle,  compression=None)




multiyear_df['stationtriplet_codes'] = pd.Categorical(multiyear_df.stationtriplet).codes


#weekmask = multiyear_df.index % 7 == 0  
# Do based on day of week
multiyear_df.date = pd.to_datetime(multiyear_df.date)

weekmask = multiyear_df.date.dt.dayofweek == 0
multiyear_week_df = multiyear_df[weekmask]



# Convert "date" to "days since mindate"
datemin = min(multiyear_week_df.date)
multiyear_week_df['dayssincemindate'] = ( (multiyear_week_df.date - datemin).dt.days ) / 365.


# For coregionalization, form 2-column input/output with data in col1 and "dimension" (label) in col2
X = multiyear_week_df[['dayssincemindate','stationtriplet_codes']]
Y = multiyear_week_df[['value','stationtriplet_codes']]



X = X[X.stationtriplet_codes.isin([0,1,2])]
Y = Y[Y.stationtriplet_codes.isin([0,1,2])]

X = X.values
Y = Y.values

# Model build: 
with gpflow.defer_build():
    k_0 = gpflow.kernels.Periodic(1)
    k_0.period.prior = gpflow.priors.Gaussian(1,0.05) 
    k1 = gpflow.kernels.Matern32(1, active_dims=[0])
    input_dim=1

    coreg = gpflow.kernels.Coregion(input_dim = input_dim, output_dim = 3, 
                                    rank=1, active_dims = [1]) # Should have rank 2?
    # 2 output dims work just fine. 3 is when it starts to break down


    kern = k_0 * k1 * coreg + gpflow.kernels.White(1) #+ k_0 * k1 * coregions[1]
    
    lik = gpflow.likelihoods.SwitchedLikelihood([gpflow.likelihoods.Gaussian(),
                                                 gpflow.likelihoods.Gaussian(),
                                                 gpflow.likelihoods.Gaussian()]) # One likelihood per output dim
    # TODO: 2 gives some sort of partition error. 3 gives non-invertable matrix
    m = gpflow.models.VGP(X, Y, kern=kern, likelihood=lik, num_latent=1)


m.compile()
print(kern)

m.kern.kernels[0].kernels[2].W = np.random.randn(3, 1) # (output_dim, rank) # IF not adding the white noise kernel, drop the kernels[0].


#%%


o = gpflow.train.AdamOptimizer(0.01)
o.minimize(m, maxiter=150) 
```

**Comment by st--** [comment]
Hi @thatmushroom, I've had a look at your code but failed to get it to work with 2 output dims, and it's hard to get to the bottom of it in its current state. Please could you turn your issue into an actual Minimal Working (/Failing) Example: a single script, with any required data defined inside the script so that I can simply copy&paste it (and not have to worry about paths etc.), and no code that isn't required to reproduce the issue. If you can get it to work for 2 output dims, please include a flag at the start of the script so that changing its value from 2 to 3 or back to reproduce both it working and it failing and narrowing down what might be the issue. If you've got any further questions for how to construct the MWE, feel free to get in touch!

**Comment by thatmushroom** [comment]
Thank you for your answer. While cleaning it up and attempting to trim down the data to get it to be a minimally failing example without external data dependencies, I reduced the size of the input data further and no longer receive the non-invertable matrix error. I'm not entirely sure where this leaves me, but I think I am in a place to continue exploring on my own before taking up someone else's time.
