### ISSUE TITLE
Fixing a set of parameters e.g in kernel

### ISSUE THREAD

**Issue by alexggmatthews** [GPflow/GPflow#94]
Unless I've missed a thread we don't currently have the ability to fix a set of parameters all at once.

For instance it would be nice to say

`model.kern.fixed=True`

which would fix all the hyper parameters in the kernel, rather than going through fixing each one in turn which is what we currently have to do.

**Comment by jameshensman** [comment]
That would be a nice feature, and easily implemented.

**Comment by jameshensman** [comment]
Another thing: if we do this for fixed, we should perhaps do it for all transforms. And maybe priors too.

Also, I wonder if we should keep the `fixed` attribute on the kernel? Calling `m.kern.fixed = True` would set the fixed state of the variance and lengthscale, but the kernel actually doesn't have a fixed attribute, so presumably we'd not set one? Would it be odd to do

```python
m.kern.fixed = True
hasattr(m.kern, 'fixed')
>>> False
```

**Comment by alexggmatthews** [comment]
Fixed in #98
