### ISSUE TITLE
GPR implementation; is it log(p(Y|X)) or p(y|X) which is maximised?

### ISSUE THREAD

**Issue by mosen-sadr** [GPflow/GPflow#949]
Dear all,

Firstly, I apologise if the question is too trivial for the pros here. I'm pretty new to the topic. So, here is my question:

In the GPR implementation, 
https://gpflow.readthedocs.io/en/stable/_modules/gpflow/models/gpr.html
it is mentioned that log of likelihood is being maximised. However, the return of the function call (def _build_likelihood(self)) is the multivariate distribution on the output given the data, which is not exactly log(p(y|X))? Can anyone please clarify this for me.

Thanks for your time.

Regards,
Mohsen

**Comment by st--** [comment]
Hi @mosen-sadr, I'm afraid you're looking at a very out-of-date version of the documentation (as indicated by the red bar in the bottom left of the screen where it says "stable"). If you look at the up-to-date documentation as linked from github, e.g. https://gpflow.readthedocs.io/en/develop/_modules/gpflow/models/gpr.html, you'll find that we renamed the module to `logdensities` to make it clearer - it is indeed the _log_-likelihood that is being maximised. Could you let us know where you found the link to the documentation so we can update the link? Thanks!

**Comment by mosen-sadr** [comment]
Hi @st--,

Thanks a lot for your response. Actually, I just googled "GPflow GPR" and indeed you will find two links for it. Ok, I wasn't sure of the difference between stable and develop versions.

Regarding log-likelihood, I was expecting to see an expression like
logpdf = -\frac12 \ln(|k( x, x^\prime)|) + (y-m)^T k(x, x^\prime)^{-1} (y-m) -\frac{M}{2} \ln(2\pi)
Sorry for the ugliness of latex format. I understand that the likelihood function is multivariate gaussian distribution, but not its log. I'm really confused :)

I hope you could point me in the right direction.

Again, thanks for your replies.

Regards, Mohsen

**Comment by st--** [comment]
The log-likelihood (defined in `_build_likelihood`) calls logdensities.multivariate_normal(), which computes exactly the expression you wrote. Hope that answers your question? If you need more clarification/explanation, please ask your question on stackoverflow and tag it with "gpflow"; you can then post the link to your stackoverflow question here.

**Comment by mosen-sadr** [comment]
Thanks a lot. Now I understand what is going on.

Cheers,
Mohsen
