### ISSUE TITLE
Use GPFlow as part of a larger graph

### ISSUE THREAD

**Issue by c0g** [GPflow/GPflow#95]
Do the authors have any advice on integrating a GP from GPflow as part of a large graph? My two applications are: optimising a loss function with respect to predictive locations, and warping the inputs to the GP. 

For the former, this seems to work:

```
    k = GPflow.kernels.Matern32(1)
    m = GPflow.gpr.GPR(X, Y, k)
    m.likelihood.variance = 0.01
    m.optimize(AdamOptimizer(0.1))
    init  = np.random.rand(3,)
    with m.tf_mode():
        xp = tf.Variable(init.reshape(-1,1))
        nu = np.min(Y)
        mean, cov = m.build_predict(xp, full_cov=True)
        m._session.run(tf.initialize_variables([p]))
```

but it requires me to call ```m.optimize()``` before constructing my further loss functions with build_predict, and I have to be careful about when and which variables I initialise since it seems to decouple the tf.Variables from the model, and give me garbage output after training.

For me, the ideal system would be a way to keep everything symbolic and inside whatever graph/session I am already using.

```
Xwarp = complex_function(X)
Xpwarp = complex_funciton(Xp)
k = GPflow.kernels.Matern32(2)
m = GPflow.gpr(Xwarp, Y, k)
mu, cov = m.predict(Xpwarp)
lik = m.likelihood()
loss = loss_function(mu, cov)
step = tf.train.AdamOptimizer(0.1).minimize(loss, [Xp])
```

Is there a way to do this in current GPflow?

**Comment by jameshensman** [comment]
Yep, you can do this. GPflow has a convention that the version of the function that returns a symbolic graph is called `build_foo`. You'll also have to handle the parameters (e.g. lengthscales etc). Something like:

```python
theta = tf.variable(m.get_free_state()) # something to keep GPflow paramters in
m._make_tf_array(theta)
Xwarp = complex_function(X)
Xpwarp = complex_funciton(Xp)
k = GPflow.kernels.Matern32(2)
m = GPflow.gpr(Xwarp, Y, k)
mu, cov = m.build_predict(Xpwarp)
lik = m.build_likelihood()
loss = loss_function(mu, cov)
step = tf.train.AdamOptimizer(0.1).minimize(loss, [Xp])
```

**Comment by jameshensman** [comment]
edited code to ensure `tf_mode`.

**Comment by c0g** [comment]
So it seems like GPflow doesn't like having a symbolic expression as an input:

```
X = np.random.randn(10,1)
Y = np.sin(X)
Xwarp = tf.exp(X)
k = GPflow.kernels.Matern32(1)
m = GPflow.gpr.GPR(Xwarp, Y, k)
m.optimize()
```
the error is:
```AttributeError: 'Tensor' object has no attribute 'shape'```.

Do you think this will be an easy fix? I'll hack around with it a bit later, I think parameterised input warps could be quite useful.

**Comment by jameshensman** [comment]
Allowing GPflow to have symbolic expressions might not be too straightforward without failry invasive changes I suspect. 

On the other hand, I've wanted to do exactly this before, and my solution was to change the kernel as follows. I hope this is useful. 

My warping is effectively `Xwarp = log(X + \alpha)`

```python
class TransKernel(GPflow.kernels.Kern):
    def __init__(self, kern):
        GPflow.kernels.Kern.__init__(self, kern.input_dim)
        self.kern = kern
        self.alpha = GPflow.param.Param(0.1, transform=GPflow.transforms.positive)
    def K(self, X, X2=None):
        X = tf.log(X + self.alpha)
        if X2 is not None:
            X2 = tf.log(X2 + self.alpha)
        return self.kern.K(X, X2)
    def Kdiag(self, X):
        return self.kern.Kdiag(tf.log(X + self.alpha))
```

**Comment by c0g** [comment]
Thanks James, closing this.
