### ISSUE TITLE
Time Series with Multi-input and Multi-output 

### ISSUE THREAD

**Issue by JimAva** [GPflow/GPflow#956]
Are there any examples for GP with multiple input and output? I have a project that has input_shape=8 (maybe even up to 11) and out_shape must be the same (8 or 11) for regression. Any help would be greatly appreciated

**Comment by st--** [comment]
Hi JimAva, this is not an "issue" in the sense that it's anything wrong with GPflow, I believe: could you please post this as a question on stackoverflow, tagged with the "gpflow" tag (https://stackoverflow.com/questions/tagged/gpflow). That a) allows anyone to answer & improve both the answers and your question, and b) means that the question&answer will be around and more easily found for someone else who might have the same or a similar question. We have notebooks on multioutput GPs in the documentation: https://nbviewer.jupyter.org/github/GPflow/GPflow/blob/develop/doc/source/notebooks/intro.ipynb - if that doesn't answer your question already, it's probably going to make it easier for you to get an answer if you explain your setting in more depth (on stackoverflow).
