### ISSUE TITLE
Intermediate Gradients from Optimizer

### ISSUE THREAD

**Issue by ibrahimkakbar** [GPflow/GPflow#958]
Is there any way to observe the gradients given per iteration to the ScipyOptimizer when optimizing the model? I am interested in cross-checking several different GP models and their gradients but am unsure of how to access the gradients that are passed to the optimizer.

**Comment by st--** [comment]
Dear @ibrahimkakbar, as this is a "how-to" question and not an issue with the actual GPflow code, could you please ask this on stackoverflow (there is a gpflow tag: https://stackoverflow.com/questions/tagged/gpflow) as this will mean answers will be more visible to people who have similar questions in the future than being hidden away as a closed "issue". Hope that makes sense!

**Comment by ibrahimkakbar** [comment]
Thank you shall do!
