### ISSUE TITLE
Links to out-of-date documentation on readthedocs

### ISSUE THREAD

**Issue by koneshgit** [GPflow/GPflow#961]
https://gpflow.readthedocs.io/en/latest/notebooks/regression.html?highlight=densities%20gaussian

**Comment by markvdw** [comment]
Thanks for highlighting this issue. We'll look into it. In the meantime, you can find the notebook here: https://github.com/GPflow/GPflow/blob/develop/doc/source/notebooks/basics/regression.ipynb

All the notebooks in general are included in /doc/source/notebooks.

**Comment by st--** [comment]
@koneshgit the link you posted is outdated (note the red highlighting of the "v:latest" in the bottom left - we deprecated the `latest` tag on readthedocs; you should only use either `master` or `develop`). Could you please let us know where you found this link so we can fix it at the source ? Thanks!

**Comment by st--** [comment]
@koneshgit if you can tell us where to find the link pointing to this out-of-date version of readthedocs, please let us know and reopen this issue!
