### ISSUE TITLE
Haversine Kernel for Kriging

### ISSUE THREAD

**Issue by FabricioArendTorres** [GPflow/GPflow#970]
Since Kriging is a really popular application of GPs, I'd suggest adding a Kernel that supports the Haversine distance to the default Kernels for directly working with latitude/longitude data.

I implemented one, but unfortunately it is not fully working yet (https://github.com/GPflow/GPflow/issues/969),
and I'm rather new to Tensorflow, so I don't know if I my version is the most efficient one.

I'd suggest maybe also changing the stationary Kernels in a way that allows non-euclidean distances.

**Comment by markvdw** [comment]
Hi! These are good suggestions, but slightly outside the scope of what we want to include in the package. Given that you're implementing these, if you're interested in open-sourcing the code, you could publish them in a separate repository that extends GPflow. We would be happy to link your project.

**Comment by rafaelalmeida** [comment]
@FabricioArendTorres you're probably aware of this, but commenting for reference of others: a way to work with Euclidean distances in geographic data would be to use the UTM projection, which is common if your area of interest is no larger than a couple hundred kilometers.
