### ISSUE TITLE
Getting basic periodic model to fit

### ISSUE THREAD

**Issue by michael-ziedalski** [GPflow/GPflow#971]
(I had opened previously a question on cross-validated, but received no answers, probably since there is no `gpflow` tag yet)

Having read about Gaussian Processes, I wanted to get into a library dealing with them, and I am now encountering difficulty fitting (what I imagine to be) a standard model. 

My code is as follows:
```
## Data generation
x = np.linspace(0,20, num=150)
noise = np.random.normal(0,0.3,150)
y = np.sin(x) + noise

plt.scatter(x, y)

## Some pre-processing
X_sin = np.expand_dims(x, axis=1)
Y_sin = np.expand_dims(y, axis=1)

test_X_sin_1dim = np.linspace(-20,40,500)
test_X_sin_2dim = np.expand_dims(test_X_sin_1dim, axis=1)

## Model
with gpflow.defer_build():

        m = gpflow.models.GPR(X_sin, Y_sin, kern = gpflow.kernels.Periodic(1))
                              
m.as_pandas_table()

m.compile()

opt = gpflow.train.ScipyOptimizer(options=dict(maxiter=1000))
opt.minimize(m)

## Plotting
f = m.predict_y(test_X_sin_2dim)
upper = f[0] + f[1]/2
lower = f[0] - f[1]/2
lower = lower.squeeze()
upper = upper.squeeze()

fig, ax = plt.subplots()

ax.fill_between(test_X_sin_1dim, lower, upper)

ax.scatter(x_sin, y_sin, color='r', marker='x', s=9, label='Data')
ax.plot(test_X_sin_1dim, f[0], color='#FFA500', linewidth=0.5, label='Forecast Mean')

ax.set_xlim([-20, 40])
ax.set_ylim([-3, 3])
```

No matter which optimization settings I use, I cannot get either the simple `gpflow.kernels.Periodic` or `gpflow.kernels.Periodic + gpflow.kernels.Constant` kernels to fit my basic data. 

This is the best I have been able to achieve, with `opt = gpflow.train.ScipyOptimizer(options=dict(maxiter=10000, ftol=0.000000001, gtol=0.000000001, maxfun=10000, maxls=50))`:

<img width="669" alt="Screen Shot 2019-05-07 at 1 41 38 PM" src="https://user-images.githubusercontent.com/43689829/57328409-5b1a9f00-70df-11e9-9ffe-e0bad5973d89.png">

Could someone give me advice on how to fit this data using only the periodic kernel, or some basic combination thereof? I went through all the guides and example notebooks, but they tend to focus on more difficult models.

**Comment by hughsalimbeni** [comment]
The default period is 1, which is too small for your data. Try: 

`m = gpflow.models.GPR(X_sin, Y_sin, kern=gpflow.kernels.Periodic(1, period=5.))
`

The plotting code above doesn't make sense as `x_sin, y_sin` are not defined, but with a small modification I got the following image 
![image](https://user-images.githubusercontent.com/4891485/57768068-b9a8d400-7702-11e9-973b-6a0781bfee36.png)

**Comment by michael-ziedalski** [comment]
So a period of `5` is what makes sense for this data? Visually that makes sense. However, is there any way to prod the model/fitting algorithm to find that out by itself?

**Comment by hughsalimbeni** [comment]
The period is optimized along with other hyperparameters, but there can be issues of local optima. If the period is initialised to 1 then it turns out for this data the model finds the trivial solution (that the data is all noise), but tweaking other hyperparameters / changing the optimizer might fix this.

**Comment by st--** [comment]
@michael-ziedalski we have a gpflow tag on stackoverflow: https://stackoverflow.com/tags/gpflow
Your question doesn't really relate to gpflow itself - it is a model issue, not an implementation issue - but if you'd like more responses / give other people with the same problem a better chance of finding the answers, please repost there !
