### ISSUE TITLE
I am trying to train a GPR model and a tensorflow model together. The training part has no issue. But for prediction using the trained model I receive a type error in a tf.placeholder op .  pred, uncp=sess.run([my, yv], feed_dict={X:xtr}) I have posted the whole code at stackoverflow https://stackoverflow.com/questions/56069296/gp-tensorflow-training, can you pls let me know why this is happening? 

### ISSUE THREAD

**Issue by SimaDidari** [GPflow/GPflow#972]
### Please fill out the template below.
___

System information:

* Python version:
* TensorFlow installed from (source or binary):
* TensorFlow version (use command below):
* GPflow installed from (source or binary):
* GPflow version:

> You can collect some of this information using our environment capture script You can also obtain the TensorFlow version with python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

... _Describe the current behavior_

... _Describe the expected behavior_

... _Code to reproduce the issue Provide a reproducible test case that is the bare minimum necessary to generate the problem._

.. _Other info / logs, include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached._

**Comment by awav** [comment]
@SimaDidari, I will answer on StackOverflow.
