### ISSUE TITLE
link_parameter of GPy equivalent in GPflow kernels?

### ISSUE THREAD

**Issue by JSP21** [GPflow/GPflow#977]
The kernel parameters with Kern as base class in GPy are added by using self.link_parameter(param_name). What is its equivalent in gpflow.kernels.kernel?

**Comment by st--** [comment]
Hi @JSP21, your question is not about a bug or a feature, so would be much more suited to stackoverflow: could you please repost it there and tag it "gpflow"? (see https://stackoverflow.com/tags/gpflow). Thanks!
