### ISSUE TITLE
How to predict latent function values in Multioutput framework?

### ISSUE THREAD

**Issue by martiningram** [GPflow/GPflow#978]
Hi there,

I am using the [multi-output framework](https://github.com/GPflow/GPflow/blob/master/doc/source/notebooks/multioutput.ipynb), which is really great! However, I just ran into something I couldn't resolve.

I am using the model for classification together with SVGP. My model line is:

```python
m = gpf.models.SVGP(X, y, kernel, gpf.likelihoods.Bernoulli(), 
                    feat=feature, q_mu=q_mu, q_sqrt=q_sqrt)
```

I can get mean and variance of the latent function values at `n` test points using

```python
mean, var = m.predict_f(x_test)
```

That all seems to be working fine. However, in the multi-output case, the way things work is that while there are `n_c` classes, there may only be `n_l` latent functions. `predict_f` gives me a matrix of shape `n x n_c`, but I would also like to take a look at the latent values before they are mapped by the weights `W` from `n x n_l` to `n x n_c`, and I haven't yet found a way to do that.

`predict_f_samples` seems to produce an array of the shape I would like (`n_samples x n x n_l`) , but when I multiply it with `W.T`, I get results that don't seem to agree with the mean reported by `predict_f`.

Is there some way I can get to these values? That would be really useful. Thanks!

**Comment by vdutor** [comment]
Hi Martin,
Great to hear that you are using the multi-output framework!
The `predict_f` function of a model calls the model's `build_predict` function under the hood, which eventually calls the multi-dispatch function `conditional`, which deals with all the different multi-output cases depending on the kernel and feature used. As the `conditional` function returns the function evaluations in the observed space (in your case `n_c` dimensional) it is not straightforward to get the latent values out of GPflow. 

A general solution for this is currently not supported and would require quite a bit of work -- feel free to make a PR if you're up for it. However, it is not too difficult to overwrite `predict_f` for your specific need. Given that you are referring to the `W` mixing matrix, I assume you are using the `SeparateMixedMok` kernel and `MixedKernelSharedMof/MixedKernelSeparateMof` feature. You should be able to call the independent conditional for these types, which will return you the latent GP values (referred to as `g` in GPflow source code). Have a look here: https://github.com/GPflow/GPflow/blob/develop/gpflow/multioutput/conditionals.py#L212, you will have to do something similar to this: 
```
independent_cond = conditional.dispatch(object, SeparateIndependentMof, SeparateIndependentMok, object)
g_mu, g_var = independent_cond(Xnew, feat, kern, f, white=white, q_sqrt=q_sqrt,
                                   full_output_cov=False, full_cov=False)  # [..., N, L], [..., N, L]
``` 

Hope this helps,
Vincent

BTW: We are currently writing a technical report explaining the maths and technical details of the interdomain and multi-output framework. It should help you to use and extend the framework to your needs. So, watch this space :)

**Comment by martiningram** [comment]
Hi Vincent,

Thanks so much for replying so quickly!

That all sounds great, I'll give this a go and will let you know if I run into any trouble, and I'll definitely have a look if I can find a general solution. And I'm really looking forward to the technical report!

That makes me think of another question, sorry if it's a little off topic (feel free to tell me to wait for the technical report or open another issue or something!): is there a way / are you planning to provide functionality to also do variational inference on the weights matrix W? My dataset has so many classes that I think I'm actually running into overfitting issues with `W`, so it would be great to integrate it out too!

Thanks again,
Martin

**Comment by vdutor** [comment]
Funny you ask, we've actually worked on this before. If you want, you can take a look at this paper: https://papers.nips.cc/paper/7506-gaussian-process-conditional-density-estimation.pdf (section 3.3: Probabilistic Linear Transformations). In short: you can define a Gaussian prior and approximate posterior over `W`, which keeps the conjugacy, and optimise the posterior using VI. You'll also need to add an extra KL term in the elbo `KL[q(W) || p(W)]`. All of this, however, falls outside the scope of GPflow.

Cheer,
Vincent

**Comment by martiningram** [comment]
Oh fantastic, I'll take a look! Thanks so much for responding so quickly again.

**Comment by st--** [comment]
The report that Vincent was referring to is now online: https://arxiv.org/abs/2003.01115 !
