### ISSUE TITLE
Does whitening have an impact on SVGP fitting?

### ISSUE THREAD

**Issue by martiningram** [GPflow/GPflow#979]
Hi there,

I was recently tripped up by the same issue mentioned here: https://github.com/GPflow/GPflow/issues/230 . I refit my model with `whiten=False` because I am a more used to the non-whitened representation. However, the first model I fit appears to perform slightly worse than the whitened version. I'm not sure whether to read anything into that, or whether it is just the result of a different initialisation. So my question is really whether the whitening helps the optimisation in some way, or it is just a matter of which representation you prefer and I can safely set it to False.

Thanks a lot!

**Comment by hughsalimbeni** [comment]
Whether whitening is good or not is an open question, and depends very much on the data and model. This question would be better suited to the https://stackoverflow.com/questions/tagged/gpflow format, so I'm closing for now.

**Comment by martiningram** [comment]
That's interesting, thanks! It being an open question is all I really needed to know.

**Comment by st--** [comment]
To clarify, whitening is just a variable transformation - so you may end up with a different result in empirical optimisation (the optimisation is non-convex) or take a different number of iterations to get there, but it does not change the model at all (and with natural gradient updates it makes no difference whether you whiten or not).
