### ISSUE TITLE
NatGrad placeholder issue can be solved

### ISSUE THREAD

**Issue by Joshuaalbert** [GPflow/GPflow#980]
@hughsalimbeni The place holder issue with the forward differentiation seems to be solved here: https://github.com/renmengye/tensorflow-forward-ad/blob/master/tensorflow_forward_ad/fwgrad.py#L993

**Comment by hughsalimbeni** [comment]
Great thanks for spotting. This should certainly simplify some of the code. @awav does this help with getting nat grads into gpflow2?

**Comment by st--** [comment]
@awav I'm assuming this is sorted now? please re-open if needed
