### ISSUE TITLE
Variational Expectation of Poisson 

### ISSUE THREAD

**Issue by FabricioArendTorres** [GPflow/GPflow#981]
Hi,

I was wondering where the analytical form of the variational Expectation
\int q(f)logp(y|f) df for the Poisson Likelihood comes from (when using a log link).

In the documentation it is only mentioned that one can approximate the intractable likelihood,
however I'm not familiar enough with the topic to know what exactly is used.

```
    let g(.) be the inverse-link function, then this likelihood represents

    p(y_i | f_i) = Poisson(y_i | g(f_i) * binsize)

    Note:binsize
    For use in a Log Gaussian Cox process (doubly stochastic model) where the
    rate function of an inhomogeneous Poisson process is given by a GP.  The
    intractable likelihood can be approximated by gridding the space (into bins
    of size 'binsize') and using this Poisson likelihood.
```

Could you maybe point me to that approximation method?

**Comment by st--** [comment]
@FabricioArendTorres this is a question more suited to stackoverflow, please repost it there under the gpflow tag (https://stackoverflow.com/tags/gpflow) and I'll be happy to answer there.

**Comment by FabricioArendTorres** [comment]
For future reference, answer is at:
https://stackoverflow.com/questions/56423927/variational-expectation-of-poisson
