### ISSUE TITLE
set prior for mean

### ISSUE THREAD

**Issue by Fangwq** [GPflow/GPflow#982]
The package can set prior for variance, I want to know if I can set prior for the mean and how to do it ? thank you very much!

**Comment by st--** [comment]
@Fangwq I'm assuming you mean "set prior for variance of the likelihood"? The prior on the function is defined by the GP covariance and mean function, the covariance is set by the kernel and you can set an explicit mean function using the `mean_function` argument to a model constructor). For a more complex example see https://nbviewer.jupyter.org/github/GPflow/GPflow/blob/develop/doc/source/notebooks/tailor/external-mean-function.ipynb - if you've got any further questions please repost this as a stackoverflow question, see https://stackoverflow.com/tags/gpflow.
