### ISSUE TITLE
InvalidArgumentError in 2D GP with Coregionalization

### ISSUE THREAD

**Issue by fonnesbeck** [GPflow/GPflow#985]
I'm trying to fit a set of coregionalized 2-dimensional GPs with verison 1.3.0, but am running into an input error (apparently) that I cannot diagnose. My `X` inputs have 2 columns (x and y coordinates) plus a coregion index column (currently trying to fit 3 components to test things):

```
>>> X[:5]

array([[-0.255,  1.666,  1.   ],
       [-0.488,  1.251,  1.   ],
       [-0.573,  0.749,  1.   ],
       [-1.041,  2.127,  1.   ],
       [-0.535,  1.327,  1.   ]])
```

and my `y` response is univariate (plus the coregion column as well). `Z` is a grid of values chosen using k-nearest-neighbor. Based on the existing examples, the model is:

```python
k1 = gf.kernels.Matern32(input_dim=2, active_dims=[0, 1], lengthscales=0.1)
coreg = gf.kernels.Coregion(input_dim=1, output_dim=3, rank=2, active_dims=[2])
k = k1*coreg

lik = gf.likelihoods.SwitchedLikelihood([gf.likelihoods.StudentT(), gf.likelihoods.StudentT(),
                                     gf.likelihoods.StudentT()])

mu = gf.mean_functions.Constant(y.max())
m = gf.models.SVGP(X, y, kern=k, likelihood=lik, mean_function=mu, num_latent=1, Z=Z)

opt = gf.train.ScipyOptimizer()
opt.minimize(m)
```

However, I'm getting the following:

```
InvalidArgumentError: indices[0] = 2 is not in [0, 2)
	 [[node SVGP-0016d7ab-321/conditional/GatherV2_6 (defined at /home/fonnesbeck_gmail_com/anaconda3/envs/dev/lib/python3.7/site-packages/gpflow/kernels.py:129) ]]
```

I assume this has to do with the `active_dims` on the `Coregion` kernel, but I don't see what I've done wrong if this is the case.

**Comment by fonnesbeck** [comment]
Can anyone confirm whether its possible to build a coregionalized model with 2D inputs? I've not been able to get any model running (even trying to generalize from the example notebook) without triggering an error like the one above.

**Comment by vabor112** [comment]
@fonnesbeck did you solve the problem? How?

**Comment by LCanas** [comment]
@fonnesbeck did you manage to solve the issue? I have the same problem, but my kernel has the right active dims.

**Comment by Atulsingh92** [comment]
@fonnesbeck Could you please share more detail on how did you solved it?

**Comment by fonnesbeck** [comment]
This was 2 years ago, so I don't recall how it was solved, and I ended up using a different approach altogether for my analysis. Sorry I can't be more helpful.
