### ISSUE TITLE
Variational Bound on BayesianGPLVM seems to have some issues?

### ISSUE THREAD

**Issue by lexxx233** [GPflow/GPflow#986]
The implemented Bayesian GPLVM seems to work fine on the oilflow data. Though when applied to digit data, a few strange things happen, I include the report here along with a request for documentation of the derivation in the original implementation

**Dataset**
```
from sklearn import datasets, preprocessing

digits = datasets.load_digits(n_class=5) #Only get 5 classes of digits
X = preprocessing.normalize(digits.data)
y = digits.target
```
**Initialize some params**
```
latent_dim = 20  
num_data = X.shape[0]  
X_mean_init = gpflow.models.PCA_reduce(X, latent_dim)
X_var_init = 0.1*np.ones((num_data, latent_dim))
```
**Using packaged Bayesian GPLVM**
```
from gpflow.models import BayesianGPLVM

kernel_org = gpflow.kernels.RBF(latent_dim, ARD=True)
m_org = BayesianGPLVM(
    X_mean=X_mean_init,
    X_var=X_var_init,
    Y=X,
    kern=kernel_org,
    M=20
)
m_org.likelihood.variance = 0.1
opt = gpflow.train.ScipyOptimizer()
opt.minimize(m_org, maxiter=500)
```
The sensitivity plot after the optimization for the ARD kernel is the following
![Screen Shot 2019-06-05 at 12 29 21 PM](https://user-images.githubusercontent.com/646456/58973310-a501ae00-878d-11e9-966e-dd2a8e73b1ba.png)

This looks kind of bad and looks almost like % variance in PCA . Comparison of visualization of the reduced dimention data is at the end.

**Reimplementation of Variational bound**

Suspected that this was because of some issue with the bound used, I just roughly reimplemented the bound described in Titsias 2009

```
        # reimplemented var bound for _build_likelihood
        sigma2 = self.likelihood.variance
        sigma = tf.sqrt(sigma2)
        beta = 1/sigma
        beta2 = 1/sigma2

        N = self.num_data
        D = self.output_dim

        bound = 0
        pi = tf.constant(np.pi, dtype=settings.float_type)

        bound += D * N * tf.log(beta)
        bound += D * tf.log(tf.linalg.det(Kuu))
        bound += - D * N * tf.log(2 * pi)
        bound += - D * tf.log(tf.linalg.det(beta * psi2 + Kuu))
        bound += - D * beta * psi0
        bound += D * beta * tf.trace(tf.matmul(iKuu, psi2))
        W = beta * tf.eye(self.num_data, dtype=settings.float_type) - beta2 * tf.matmul(psi1, tf.matmul(
            tf.linalg.inv(beta * psi2 + Kuu), tf.transpose(psi1)))

        bound += - tf.reduce_sum(tf.diag_part(tf.matmul(tf.matmul(tf.transpose(self.Y), W), self.Y)))

        return 0.5 * bound - gauss_kl(self.X_mean, self.X_var)
```
Which after optimize leading to the following sensitivity plot for the ARD kern
![Screen Shot 2019-06-05 at 12 29 25 PM](https://user-images.githubusercontent.com/646456/58973755-bc8d6680-878e-11e9-8cf7-adb21884149e.png)
This looks a lot more like what I would have expected

**Result comparison**
The visualization of these 
![Screen Shot 2019-06-05 at 12 33 13 PM](https://user-images.githubusercontent.com/646456/58973825-ec3c6e80-878e-11e9-8f4c-f486f695a27d.png)
The reimplemented bound does seem to work better here

**The Issue**
The problem is with the reimplemented bound is that when the number of inducing points increases to, says, 40 for this data set, the quantity 'beta * psi2 + Kuu' is somehow not invertible even after toiling with adding diagonal entries to this matrix.

My question is then, is there any documentation for the implemented bound in the package BGPLVM? It looks somewhat different from the bound described in Titsias 2009. And from the visualization of result didn't look great either. a notebook page would be useful. Maybe I did something wrong when using the packaged B-GPLVM?

Also, how should I resolve the problem of the described matrix not being invertible?

**Comment by markvdw** [comment]
Hi, thanks for bringing this to our attention, particularly with so much useful detail. We're looking into it.

**Comment by markvdw** [comment]
Ok, so let me summarise your points. Your observations are:
1. `gpflow.models.BayesianGPLVM` does not perform as expected on the digits data.
2. your reimplemented bound suffers from inversion errors of `beta * psi2 + Kuu`

I believe that the `BayesianGPLVM` does follow Titsias & Lawrence (2010) closely. You are correct that the implementation *looks* different. This is because the expressions in Titsias & Lawrence were written for ease of mathematical understanding, not for numerically stable implementation. For numerical stability reasons direct inversions should be avoided and replaced with Cholesky decompositions and solves. It should be the intention that the maths in `BayesianGPLVM` should reduce to Titsias & Lawrence (2010).

Is there any behaviour in particular that occurs with the GPflow version? E.g. does it stop optimising? What hyperparameters does it obtain? I have always found the `BayesianGPLVM` to be difficult to train, with it requiring a bit of thought and debugging to get it to work.

**Comment by lexxx233** [comment]
Hi. Thanks for responding. 

I did notice all the inversion were found by chol then solve. I also attempted the same procedure on the B*Psi2+Kuu quantity to no avail which was kind of frustrating given that this quantity should always be invertible, I could in theory, approximate this quantity using power series expansion since iKuu was already computed in a previous step like so
![image](https://user-images.githubusercontent.com/646456/61138010-a614b200-a494-11e9-9889-461f102f71b6.png)

, though I am not entirely certain what effect this approximation will have on the implementation.

The optimization does conclude without any error or warning, all the params look inconspicuous after the optimization. (however, there still seems to be numerical instability issue in a few datasets which I guess might be a separate issue?). I include a print out of model params here for inspection

Original Implementation 
![image](https://user-images.githubusercontent.com/646456/61138172-ee33d480-a494-11e9-8583-66173ad3fbe1.png)

Reimplementation
![image](https://user-images.githubusercontent.com/646456/61138172-ee33d480-a494-11e9-8583-66173ad3fbe1.png)

Please let me know if I can provide any other details that would help

**Comment by lexxx233** [comment]
After some more testing. It seems that the package B-GPLVM behave just fine in term of performance when I increase the number of inducing points (double in the digit dataset).

As for the approximation. I tried that and it works out fine for solving the instability issue, though each iteration does take longer dependent on the truncation, and probably is not worth it. 

I don't really see a reason for it to not work as well at fewer inducing points in comparison to the reimplemented bound; but at this point, it seems redundant to try to solve this issue. I will take note of this for using the package BGPLVM. 

Please close the issue as you see fit.
