### ISSUE TITLE
Cannot use TensorFlow optimizer (e.g. AdamOptimizer) with TF v1.14

### ISSUE THREAD

**Issue by wiseodd** [GPflow/GPflow#995]
System information:

* Python version: 3.7.3
* TensorFlow installed from: binary
* TensorFlow version: 1.14
* GPflow installed from: binary
* GPflow version: 1.4.1

Just do `gpflow.train.AdamOptimizer()`, it will throw an error saying that it's not found. Downgrading to TF version 1.13.1 fixes this.

**Comment by awav** [comment]
https://stackoverflow.com/questions/56741160/importerror-cannot-import-name-adamoptimizer-in-gpflow
