### ISSUE TITLE
Restoring Model with Mean Function doesn't work (tensorflow naming convention problem?)

### ISSUE THREAD

**Issue by dgilford** [GPflow/GPflow#998]
* Python version: 3.5.2
* TensorFlow installed from (source or binary): source
* TensorFlow version (use command below): v1.8.0-0-g93bc2e2072 1.8.0
* GPflow installed from (source or binary): source
* GPflow version: 1.3.0

I have been following the methodology of #852 for some time now, successfully saving out and restoring GPflow models. But now I've run into a snag which I think is a bug, or maybe there is an easy fix I'm not considering?

When I try to restore a model with a Linear mean function, the restore crashes with the error:

> NotFoundError (see above for traceback): Key Linear-44dbadbb-0/A/unconstrained not found in checkpoint...

I spent a few hours tracking this down yesterday, and realized that the issue comes in the naming convention of the tensorflow Linear mean function object. The above **"-44dbadbb-0"** is random and changes every time the model is rebuilt, so if I check the tensor names when I saved the model with

`from tensorflow.python.tools.inspect_checkpoint import print_tensors_in_checkpoint_file
print_tensors_in_checkpoint_file(file_name='./model.ckpt', tensor_name='', all_tensors=False)`

I get the return:

> Linear-eeb5f9f3-0/A/unconstrained (DT_DOUBLE) [1,1]
> Linear-eeb5f9f3-0/b/unconstrained (DT_DOUBLE) [1]
> model/X/dataholder (DT_DOUBLE) [15,1]
> model/Y/dataholder (DT_DOUBLE) [15,1]
> model/kern/kernels/0/lengthscales/unconstrained (DT_DOUBLE) []
> model/kern/kernels/0/variance/unconstrained (DT_DOUBLE) []
> model/kern/kernels/1/lengthscales/unconstrained (DT_DOUBLE) []
> model/kern/kernels/1/variance/unconstrained (DT_DOUBLE) []
> model/likelihood/variance/unconstrained (DT_DOUBLE) []

Where the Linear function clearly has a different name from the model which is trying to be restored.
Here is the simple code to recreate the problem.

**Saving the Model**
```
import gpflow
import numpy as np
import random
import tensorflow as tf

# define data
rng = np.random.RandomState(4)
X = rng.uniform(0, 5.0, 15)[:, np.newaxis]
Y = np.sin((X[:, 0] - 2.5) ** 2).reshape(len(X),1)

# define the mean function
mf = gpflow.mean_functions.Linear(np.ones((1,1)),np.zeros((1,)))
    
# create the GP model
with gpflow.defer_build():
    k = gpflow.kernels.Matern32(1)+gpflow.kernels.RBF(1)
    m = gpflow.models.GPR(X, Y, kern=k,name='model',mean_function=mf)
    m.likelihood.variance = 1e-03
    m.likelihood.trainable = False
    
tf.global_variables_initializer()

tf_session = m.enquire_session()
m.compile( tf_session )

gpflow.train.ScipyOptimizer().minimize(m)

saver = tf.train.Saver()
save_path = saver.save(tf_session, "./model.ckpt")
print("Model saved in path: %s" % save_path)
```

**Restoring the Model**
```
import gpflow
import numpy as np
import random
import tensorflow as tf

# define data
rng = np.random.RandomState(4)
X = rng.uniform(0, 5.0, 15)[:, np.newaxis]
Y = np.sin((X[:, 0] - 2.5) ** 2).reshape(len(X),1)

# define the mean function
mf = gpflow.mean_functions.Linear(np.ones((1,1)),np.zeros((1,)))
    
with gpflow.defer_build():
    k = gpflow.kernels.Matern32(1)+gpflow.kernels.RBF(1)
    m = gpflow.models.GPR(X, Y, kern=k,name='model',mean_function=mf)
    m.likelihood.variance = 1e-03
    m.likelihood.trainable = False
    
# construct and compile the tensorflow session
tf.global_variables_initializer()
tf_session = m.enquire_session()
m.compile( tf_session )

saver = tf.train.Saver()

save_path = saver.restore(tf_session, "./model.ckpt")
print("Model loaded from path: %s" % save_path)

m.anchor(tf_session)
```
The code crashes at `save_path = saver.restore(tf_session, "./model.ckpt")`.

I have tried to fix this by renaming the variables before the restore, but this doesn't work with tensorflow. Thanks in advance for any input you can provide!

**Comment by st--** [comment]
Hi @dgilford, this is not a bug in GPflow, but an error in how it is used. Could you please open this as a question on stackoverflow (https://stackoverflow.com/tags/gpflow), so that others will be able to find question & answer in the future? Please post the link to your stackoverflow question here, and I will answer over there!

**Comment by dgilford** [comment]
Thanks @st-- ! Here is the link: https://stackoverflow.com/questions/56991656/restoring-gpflow-model-with-mean-function-doesnt-work

**Comment by st--** [comment]
Answered on stackoverflow.
